using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;

namespace PulseRPC.Generator.Generators;

/// <summary>
/// 生成增强的EventListenerExtensions，支持批量处理和智能处理器
/// </summary>
public static class EnhancedEventListenerExtensions
{
    /// <summary>
    /// 生成增强的事件监听器扩展方法
    /// </summary>
    public static string GenerateEnhancedExtensions(ImmutableArray<INamedTypeSymbol> eventTypes)
    {
        var sb = new StringBuilder();

        GenerateFileHeader(sb);
        GenerateExtensionsClass(sb, eventTypes);

        return sb.ToString();
    }

    private static void GenerateFileHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Enhanced PulseRPC Event Listener Extensions with Smart Handlers and Batch Processing");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using PulseRPC;");
        sb.AppendLine("using PulseRPC.Client;");
        sb.AppendLine("using PulseRPC.Client.Events;");
        sb.AppendLine();
    }

    private static void GenerateExtensionsClass(StringBuilder sb, ImmutableArray<INamedTypeSymbol> eventTypes)
    {
        sb.AppendLine("namespace PulseRPC.Client");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 增强的事件监听器扩展 - 支持智能处理器、批量处理、高级配置");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static partial class EnhancedEventListenerExtensions");
        sb.AppendLine("    {");

        // 生成智能处理器工厂方法
        GenerateSmartHandlerFactories(sb, eventTypes);

        // 生成批量订阅方法
        GenerateBatchSubscriptionMethods(sb, eventTypes);

        // 生成预设配置方法
        GeneratePresetConfigurationMethods(sb, eventTypes);

        // 生成性能监控方法
        GeneratePerformanceMonitoringMethods(sb, eventTypes);

        // 生成条件订阅方法
        GenerateConditionalSubscriptionMethods(sb, eventTypes);

        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void GenerateSmartHandlerFactories(StringBuilder sb, ImmutableArray<INamedTypeSymbol> eventTypes)
    {
        sb.AppendLine("        #region Smart Handler Factory Methods");
        sb.AppendLine();

        foreach (var eventType in eventTypes)
        {
            if (eventType == null) continue;

            var interfaceName = eventType.Name;
            var handlerClassName = GetSmartHandlerClassName(interfaceName);
            var namespaceName = eventType.ContainingNamespace.ToDisplayString();

            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 创建 {interfaceName} 的智能事件处理器");
            sb.AppendLine($"        /// 包含性能监控、批量处理、错误恢复等高级功能");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        public static {namespaceName}.Smart{handlerClassName} CreateSmart{GetCleanTypeName(interfaceName)}Handler(this IPulseClient client)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (client == null) throw new ArgumentNullException(nameof(client));");
            sb.AppendLine($"            return new {namespaceName}.Smart{handlerClassName}();");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine("        #endregion");
        sb.AppendLine();
    }

    private static void GenerateBatchSubscriptionMethods(StringBuilder sb, ImmutableArray<INamedTypeSymbol> eventTypes)
    {
        sb.AppendLine("        #region Batch Subscription Methods");
        sb.AppendLine();

        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 批量订阅多个事件监听器 - 优化大量订阅的性能");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static Task<ISubscriptionToken[]> BatchSubscribeAsync<T>(");
        sb.AppendLine("            this IPulseClient client,");
        sb.AppendLine("            IEnumerable<T> listeners,");
        sb.AppendLine("            SmartSubscriptionOptions? options = null) where T : class, IPulseReceiver");
        sb.AppendLine("        {");
        sb.AppendLine("            if (client == null) throw new ArgumentNullException(nameof(client));");
        sb.AppendLine("            if (listeners == null) throw new ArgumentNullException(nameof(listeners));");
        sb.AppendLine();
        sb.AppendLine("            var listenerList = listeners.ToList();");
        sb.AppendLine("            if (listenerList.Count == 0) return Task.FromResult(Array.Empty<ISubscriptionToken>());");
        sb.AppendLine();
        sb.AppendLine("            // 并行订阅以提高性能");
        sb.AppendLine("            var tasks = listenerList.Select(listener => client.RegisterSmartEventListenerAsync(listener, options));");
        sb.AppendLine("            return Task.WhenAll(tasks);");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 生成按类型分组的批量订阅
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 按事件类型分组批量订阅 - 自动选择最佳的智能处理器");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static async Task<IDictionary<Type, IList<ISubscriptionToken>>> BatchSubscribeByTypeAsync(");
        sb.AppendLine("            this IPulseClient client,");
        sb.AppendLine("            IEnumerable<IPulseReceiver> listeners,");
        sb.AppendLine("            SmartSubscriptionOptions? options = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (client == null) throw new ArgumentNullException(nameof(client));");
        sb.AppendLine("            if (listeners == null) throw new ArgumentNullException(nameof(listeners));");
        sb.AppendLine();
        sb.AppendLine("            var result = new Dictionary<Type, IList<ISubscriptionToken>>();");
        sb.AppendLine("            var groupedListeners = listeners.GroupBy(l => l.GetType());");
        sb.AppendLine();
        sb.AppendLine("            var tasks = groupedListeners.Select(async group =>");
        sb.AppendLine("            {");
        sb.AppendLine("                var tokens = await client.BatchSubscribeAsync(group, options);");
        sb.AppendLine("                return new { Type = group.Key, Tokens = tokens };");
        sb.AppendLine("            });");
        sb.AppendLine();
        sb.AppendLine("            var results = await Task.WhenAll(tasks);");
        sb.AppendLine("            foreach (var item in results)");
        sb.AppendLine("            {");
        sb.AppendLine("                result[item.Type] = item.Tokens;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return result;");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        #endregion");
        sb.AppendLine();
    }

    private static void GeneratePresetConfigurationMethods(StringBuilder sb, ImmutableArray<INamedTypeSymbol> eventTypes)
    {
        sb.AppendLine("        #region Preset Configuration Methods");
        sb.AppendLine();

        // 游戏场景预设
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 注册游戏事件监听器 - 低延迟、高频处理优化");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static Task<ISubscriptionToken> RegisterGameEventListenerAsync<T>(");
        sb.AppendLine("            this IPulseClient client, T listener) where T : class, IPulseReceiver");
        sb.AppendLine("        {");
        sb.AppendLine("            return client.RegisterSmartEventListenerAsync(listener, SmartSubscriptionOptions.Game);");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 关键业务场景预设
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 注册关键业务事件监听器 - 高可靠性、强一致性");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static Task<ISubscriptionToken> RegisterCriticalEventListenerAsync<T>(");
        sb.AppendLine("            this IPulseClient client, T listener) where T : class, IPulseReceiver");
        sb.AppendLine("        {");
        sb.AppendLine("            return client.RegisterSmartEventListenerAsync(listener, SmartSubscriptionOptions.Critical);");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 调试场景预设
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 注册调试事件监听器 - 详细监控、性能分析");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static Task<ISubscriptionToken> RegisterDebugEventListenerAsync<T>(");
        sb.AppendLine("            this IPulseClient client, T listener) where T : class, IPulseReceiver");
        sb.AppendLine("        {");
        sb.AppendLine("            var options = new SmartSubscriptionOptions");
        sb.AppendLine("            {");
        sb.AppendLine("                EnablePerformanceMonitoring = true,");
        sb.AppendLine("                EnableBatchProcessing = false, // 调试时不使用批量处理");
        sb.AppendLine("                MaxRetries = 0, // 调试时不重试");
        sb.AppendLine("                Timeout = TimeSpan.FromMinutes(5), // 调试时允许较长时间");
        sb.AppendLine("                ErrorHandler = (ex, eventName) =>");
        sb.AppendLine("                {");
        sb.AppendLine("                    System.Diagnostics.Debug.WriteLine($\"[DEBUG] Event {eventName} failed: {ex}\");");
        sb.AppendLine("                    Console.WriteLine($\"[DEBUG] Event {eventName} failed: {ex}\");");
        sb.AppendLine("                }");
        sb.AppendLine("            };");
        sb.AppendLine("            return client.RegisterSmartEventListenerAsync(listener, options);");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        #endregion");
        sb.AppendLine();
    }

    private static void GeneratePerformanceMonitoringMethods(StringBuilder sb, ImmutableArray<INamedTypeSymbol> eventTypes)
    {
        sb.AppendLine("        #region Performance Monitoring Methods");
        sb.AppendLine();

        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 获取客户端的全局事件处理性能指标");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static EventHandlerMetrics GetGlobalEventMetrics(this IPulseClient client)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 这里需要客户端提供全局指标收集功能");
        sb.AppendLine("            // 目前返回一个空的指标对象");
        sb.AppendLine("            return new EventHandlerMetrics();");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 注册带性能监控的事件监听器");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static Task<ISubscriptionToken> RegisterEventListenerWithMonitoringAsync<T>(");
        sb.AppendLine("            this IPulseClient client,");
        sb.AppendLine("            T listener,");
        sb.AppendLine("            Action<EventHandlerMetrics>? metricsCallback = null) where T : class, IPulseReceiver");
        sb.AppendLine("        {");
        sb.AppendLine("            var options = new SmartSubscriptionOptions");
        sb.AppendLine("            {");
        sb.AppendLine("                EnablePerformanceMonitoring = true");
        sb.AppendLine("            };");
        sb.AppendLine();
        sb.AppendLine("            // 如果提供了回调，可以定期调用它");
        sb.AppendLine("            if (metricsCallback != null)");
        sb.AppendLine("            {");
        sb.AppendLine("                // 这里可以启动一个定时器来定期报告指标");
        sb.AppendLine("                // 暂时先跳过实现");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return client.RegisterSmartEventListenerAsync(listener, options);");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        #endregion");
        sb.AppendLine();
    }

    private static void GenerateConditionalSubscriptionMethods(StringBuilder sb, ImmutableArray<INamedTypeSymbol> eventTypes)
    {
        sb.AppendLine("        #region Conditional Subscription Methods");
        sb.AppendLine();

        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 条件性注册事件监听器 - 只有当条件满足时才订阅");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static async Task<ISubscriptionToken?> RegisterEventListenerIfAsync<T>(");
        sb.AppendLine("            this IPulseClient client,");
        sb.AppendLine("            T listener,");
        sb.AppendLine("            Func<bool> condition,");
        sb.AppendLine("            SmartSubscriptionOptions? options = null) where T : class, IPulseReceiver");
        sb.AppendLine("        {");
        sb.AppendLine("            if (condition())");
        sb.AppendLine("            {");
        sb.AppendLine("                return await client.RegisterSmartEventListenerAsync(listener, options);");
        sb.AppendLine("            }");
        sb.AppendLine("            return null;");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 延迟注册事件监听器 - 在指定延迟后订阅");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static async Task<ISubscriptionToken> RegisterEventListenerDelayedAsync<T>(");
        sb.AppendLine("            this IPulseClient client,");
        sb.AppendLine("            T listener,");
        sb.AppendLine("            TimeSpan delay,");
        sb.AppendLine("            SmartSubscriptionOptions? options = null) where T : class, IPulseReceiver");
        sb.AppendLine("        {");
        sb.AppendLine("            await Task.Delay(delay);");
        sb.AppendLine("            return await client.RegisterSmartEventListenerAsync(listener, options);");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 临时注册事件监听器 - 在指定时间后自动取消订阅");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static async Task<ISubscriptionToken> RegisterEventListenerTemporaryAsync<T>(");
        sb.AppendLine("            this IPulseClient client,");
        sb.AppendLine("            T listener,");
        sb.AppendLine("            TimeSpan duration,");
        sb.AppendLine("            SmartSubscriptionOptions? options = null) where T : class, IPulseReceiver");
        sb.AppendLine("        {");
        sb.AppendLine("            var token = await client.RegisterSmartEventListenerAsync(listener, options);");
        sb.AppendLine();
        sb.AppendLine("            // 启动定时器在指定时间后取消订阅");
        sb.AppendLine("            _ = Task.Run(async () =>");
        sb.AppendLine("            {");
        sb.AppendLine("                await Task.Delay(duration);");
        sb.AppendLine("                token.Unsubscribe();");
        sb.AppendLine("            });");
        sb.AppendLine();
        sb.AppendLine("            return token;");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        #endregion");
        sb.AppendLine();

        // 生成核心的智能注册方法
        GenerateCoreSmartRegistrationMethod(sb, eventTypes);
    }

    private static void GenerateCoreSmartRegistrationMethod(StringBuilder sb, ImmutableArray<INamedTypeSymbol> eventTypes)
    {
        sb.AppendLine("        #region Core Smart Registration");
        sb.AppendLine();

        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 核心智能事件监听器注册方法 - 支持所有高级功能");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static async Task<ISubscriptionToken> RegisterSmartEventListenerAsync<T>(");
        sb.AppendLine("            this IPulseClient client,");
        sb.AppendLine("            T listener,");
        sb.AppendLine("            SmartSubscriptionOptions? options = null) where T : class, IPulseReceiver");
        sb.AppendLine("        {");
        sb.AppendLine("            if (client == null) throw new ArgumentNullException(nameof(client));");
        sb.AppendLine("            if (listener == null) throw new ArgumentNullException(nameof(listener));");
        sb.AppendLine();
        sb.AppendLine("            options ??= SmartSubscriptionOptions.Default;");
        sb.AppendLine();

        // 为每个事件类型生成智能分发逻辑
        sb.AppendLine("            // 智能分发到对应的处理器");
        foreach (var eventType in eventTypes)
        {
            if (eventType == null) continue;

            var interfaceName = eventType.Name;
            var handlerClassName = GetSmartHandlerClassName(interfaceName);
            var namespaceName = eventType.ContainingNamespace.ToDisplayString();

            sb.AppendLine($"            if (listener is {GetFullTypeName(eventType)} {interfaceName.ToLower()}Listener)");
            sb.AppendLine("            {");
            sb.AppendLine($"                var handler = new {namespaceName}.Smart{handlerClassName}();");
            sb.AppendLine($"                return await handler.SubscribeAsync({interfaceName.ToLower()}Listener, options);");
            sb.AppendLine("            }");
            sb.AppendLine();
        }

        // 回退到传统方法
        sb.AppendLine("            // 回退到传统注册方法");
        sb.AppendLine("            return await client.RegisterEventListenerAsync(listener);");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        #endregion");
    }

    // 辅助方法
    private static string GetSmartHandlerClassName(string interfaceName)
    {
        return interfaceName.StartsWith("I")
            ? interfaceName.Substring(1) + "Handler"
            : interfaceName + "Handler";
    }

    private static string GetCleanTypeName(string interfaceName)
    {
        return interfaceName.StartsWith("I") ? interfaceName.Substring(1) : interfaceName;
    }

    private static string GetFullTypeName(INamedTypeSymbol typeSymbol)
    {
        if (typeSymbol.ContainingNamespace.IsGlobalNamespace)
        {
            return typeSymbol.Name;
        }
        return $"{typeSymbol.ContainingNamespace.ToDisplayString()}.{typeSymbol.Name}";
    }
}
