using System.Text;
using Microsoft.CodeAnalysis;


namespace PulseRPC.Generator.Generators;

/// <summary>
/// 生成事件处理器支持类型的代码
/// </summary>
public static class EventHandlerSupportTypes
{
    /// <summary>
    /// 生成所有支持类型的代码
    /// </summary>
    public static string GenerateSupportTypes()
    {
        var sb = new StringBuilder();

        GenerateFileHeader(sb);

        // 生成支持类型
        GenerateSubscriptionOptions(sb);
        GenerateSubscriptionContext(sb);
        GenerateSubscriptionToken(sb);
        GenerateEventMetrics(sb);
        GenerateEventHandlerMetrics(sb);
        GenerateBatchEventItem(sb);
        GenerateBatchProcessor(sb);
        GenerateMonitoredEventReceiver(sb);
        GenerateCircuitBreakerState(sb);
        GenerateAsyncHelpers(sb);

        return sb.ToString();
    }

    private static void GenerateFileHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// PulseRPC Event Handler Support Types");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Concurrent;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Diagnostics;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using PulseRPC;");
        sb.AppendLine("using PulseRPC.Client;");
        sb.AppendLine();
        sb.AppendLine("namespace PulseRPC.Client.Events");
        sb.AppendLine("{");
    }

    private static void GenerateSubscriptionOptions(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 订阅选项 - 配置高级事件处理特性");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public sealed class SubscriptionOptions");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 默认配置 - 适用于大多数场景");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static SubscriptionOptions Default { get; } = new();");
        sb.AppendLine();

        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 游戏优化配置 - 低延迟、高频处理");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static SubscriptionOptions Game { get; } = new()");
        sb.AppendLine("        {");
        sb.AppendLine("            EnableBatchProcessing = true,");
        sb.AppendLine("            BatchSize = 100,");
        sb.AppendLine("            BatchTimeout = TimeSpan.FromMilliseconds(10),");
        sb.AppendLine("            EnablePerformanceMonitoring = true,");
        sb.AppendLine("            MaxRetries = 0, // 游戏事件不重试");
        sb.AppendLine("            Timeout = TimeSpan.FromMilliseconds(100)");
        sb.AppendLine("        };");
        sb.AppendLine();

        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 关键业务配置 - 高可靠性、强一致性");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static SubscriptionOptions Critical { get; } = new()");
        sb.AppendLine("        {");
        sb.AppendLine("            EnableBatchProcessing = false,");
        sb.AppendLine("            EnablePerformanceMonitoring = true,");
        sb.AppendLine("            MaxRetries = 5,");
        sb.AppendLine("            RetryDelay = TimeSpan.FromSeconds(1),");
        sb.AppendLine("            Timeout = TimeSpan.FromSeconds(30),");
        sb.AppendLine("            EnableCircuitBreaker = true");
        sb.AppendLine("        };");
        sb.AppendLine();

        // 配置属性
        sb.AppendLine("        /// <summary>启用批量处理</summary>");
        sb.AppendLine("        public bool EnableBatchProcessing { get; set; } = false;");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>批量大小</summary>");
        sb.AppendLine("        public int BatchSize { get; set; } = 50;");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>批量超时时间</summary>");
        sb.AppendLine("        public TimeSpan BatchTimeout { get; set; } = TimeSpan.FromMilliseconds(100);");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>启用性能监控</summary>");
        sb.AppendLine("        public bool EnablePerformanceMonitoring { get; set; } = true;");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>最大重试次数</summary>");
        sb.AppendLine("        public int MaxRetries { get; set; } = 3;");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>重试延迟</summary>");
        sb.AppendLine("        public TimeSpan RetryDelay { get; set; } = TimeSpan.FromMilliseconds(500);");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>事件处理超时时间</summary>");
        sb.AppendLine("        public TimeSpan Timeout { get; set; } = TimeSpan.FromSeconds(10);");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>启用断路器模式</summary>");
        sb.AppendLine("        public bool EnableCircuitBreaker { get; set; } = false;");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>自定义错误处理器</summary>");
        sb.AppendLine("        public Action<Exception, string>? ErrorHandler { get; set; }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>事件优先级</summary>");
        sb.AppendLine("        public EventPriority Priority { get; set; } = EventPriority.Normal;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // 生成枚举
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 事件优先级");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public enum EventPriority");
        sb.AppendLine("    {");
        sb.AppendLine("        Low = 0,");
        sb.AppendLine("        Normal = 1,");
        sb.AppendLine("        High = 2,");
        sb.AppendLine("        Critical = 3");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateSubscriptionContext(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 订阅上下文 - 管理单个订阅的状态和指标");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal sealed class SubscriptionContext : IDisposable");
        sb.AppendLine("    {");
        sb.AppendLine("        public object Subscriber { get; }");
        sb.AppendLine("        public SubscriptionOptions Options { get; }");
        sb.AppendLine("        public EventMetrics Metrics { get; }");
        sb.AppendLine("        public DateTime CreatedAt { get; }");
        sb.AppendLine("        public CircuitBreakerState? CircuitBreaker { get; }");
        sb.AppendLine();

        sb.AppendLine("        public SubscriptionContext(object subscriber, SubscriptionOptions options, EventMetrics metrics)");
        sb.AppendLine("        {");
        sb.AppendLine("            Subscriber = subscriber;");
        sb.AppendLine("            Options = options;");
        sb.AppendLine("            Metrics = metrics;");
        sb.AppendLine("            CreatedAt = DateTime.UtcNow;");
        sb.AppendLine("            ");
        sb.AppendLine("            if (options.EnableCircuitBreaker)");
        sb.AppendLine("            {");
        sb.AppendLine("                CircuitBreaker = new CircuitBreakerState();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        public void Dispose()");
        sb.AppendLine("        {");
        sb.AppendLine("            CircuitBreaker?.Dispose();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateSubscriptionToken(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 订阅令牌 - 增强的订阅管理");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal sealed class SubscriptionToken : ISubscriptionToken");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly ISubscriptionToken _innerToken;");
        sb.AppendLine("        private readonly SubscriptionContext _context;");
        sb.AppendLine("        private readonly Action _onDispose;");
        sb.AppendLine("        private bool _disposed;");
        sb.AppendLine();

        sb.AppendLine("        public Guid Id => _innerToken.Id;");
        sb.AppendLine("        public bool IsActive => !_disposed && _innerToken.IsActive;");
        sb.AppendLine("        public bool IsUnsubscribed => _disposed || _innerToken.IsUnsubscribed;");
        sb.AppendLine();

        sb.AppendLine("        public SubscriptionToken(ISubscriptionToken innerToken, SubscriptionContext context, Action onDispose)");
        sb.AppendLine("        {");
        sb.AppendLine("            _innerToken = innerToken;");
        sb.AppendLine("            _context = context;");
        sb.AppendLine("            _onDispose = onDispose;");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        public void Unsubscribe()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_disposed) return;");
        sb.AppendLine("            ");
        sb.AppendLine("            _innerToken.Unsubscribe();");
        sb.AppendLine("            _onDispose();");
        sb.AppendLine("            _context.Dispose();");
        sb.AppendLine("            _disposed = true;");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        public void Dispose()");
        sb.AppendLine("        {");
        sb.AppendLine("            Unsubscribe();");
        sb.AppendLine("            GC.SuppressFinalize(this);");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 获取订阅的性能指标");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public EventHandlerMetrics GetMetrics()");
        sb.AppendLine("        {");
        sb.AppendLine("            return _context.Metrics.GetSnapshot();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateEventMetrics(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 事件指标收集器 - 线程安全的性能监控");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal sealed class EventMetrics");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly ConcurrentDictionary<string, EventMethodMetrics> _methodMetrics = new();");
        sb.AppendLine("        private long _totalEventsReceived;");
        sb.AppendLine("        private long _totalEventsProcessed;");
        sb.AppendLine("        private long _totalErrors;");
        sb.AppendLine("        private long _totalBatchesProcessed;");
        sb.AppendLine("        private long _totalBatchErrors;");
        sb.AppendLine();

        sb.AppendLine("        public void RecordEventReceived(string methodName)");
        sb.AppendLine("        {");
        sb.AppendLine("            Interlocked.Increment(ref _totalEventsReceived);");
        sb.AppendLine("            var metrics = _methodMetrics.GetOrAdd(methodName, _ => new EventMethodMetrics());");
        sb.AppendLine("            Interlocked.Increment(ref metrics.CallCount);");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        public void RecordEventProcessed(string methodName, TimeSpan duration)");
        sb.AppendLine("        {");
        sb.AppendLine("            Interlocked.Increment(ref _totalEventsProcessed);");
        sb.AppendLine("            var metrics = _methodMetrics.GetOrAdd(methodName, _ => new EventMethodMetrics());");
        sb.AppendLine("            Interlocked.Increment(ref metrics.SuccessCount);");
        sb.AppendLine("            ");
        sb.AppendLine("            // 更新延迟统计");
        sb.AppendLine("            var durationMs = duration.TotalMilliseconds;");
        sb.AppendLine("            lock (metrics)");
        sb.AppendLine("            {");
        sb.AppendLine("                metrics.TotalDuration += durationMs;");
        sb.AppendLine("                metrics.MaxDuration = Math.Max(metrics.MaxDuration, durationMs);");
        sb.AppendLine("                metrics.MinDuration = metrics.MinDuration == 0 ? durationMs : Math.Min(metrics.MinDuration, durationMs);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        public void RecordEventError(string methodName, Exception exception, TimeSpan duration)");
        sb.AppendLine("        {");
        sb.AppendLine("            Interlocked.Increment(ref _totalErrors);");
        sb.AppendLine("            var metrics = _methodMetrics.GetOrAdd(methodName, _ => new EventMethodMetrics());");
        sb.AppendLine("            Interlocked.Increment(ref metrics.ErrorCount);");
        sb.AppendLine("            ");
        sb.AppendLine("            lock (metrics)");
        sb.AppendLine("            {");
        sb.AppendLine("                metrics.LastError = exception;");
        sb.AppendLine("                metrics.LastErrorTime = DateTime.UtcNow;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        public void RecordBatchProcessed(int batchSize, int successCount, TimeSpan duration)");
        sb.AppendLine("        {");
        sb.AppendLine("            Interlocked.Increment(ref _totalBatchesProcessed);");
        sb.AppendLine("            Interlocked.Add(ref _totalEventsProcessed, successCount);");
        sb.AppendLine("            ");
        sb.AppendLine("            if (successCount < batchSize)");
        sb.AppendLine("            {");
        sb.AppendLine("                Interlocked.Add(ref _totalErrors, batchSize - successCount);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        public void RecordBatchProcessingError(Exception exception)");
        sb.AppendLine("        {");
        sb.AppendLine("            Interlocked.Increment(ref _totalBatchErrors);");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        public void RecordSubscriptionError(Exception exception)");
        sb.AppendLine("        {");
        sb.AppendLine("            Interlocked.Increment(ref _totalErrors);");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        public EventHandlerMetrics GetSnapshot()");
        sb.AppendLine("        {");
        sb.AppendLine("            var methodSnapshots = new Dictionary<string, MethodMetrics>();");
        sb.AppendLine("            ");
        sb.AppendLine("            foreach (var kvp in _methodMetrics)");
        sb.AppendLine("            {");
        sb.AppendLine("                var method = kvp.Value;");
        sb.AppendLine("                lock (method)");
        sb.AppendLine("                {");
        sb.AppendLine("                    methodSnapshots[kvp.Key] = new MethodMetrics");
        sb.AppendLine("                    {");
        sb.AppendLine("                        CallCount = method.CallCount,");
        sb.AppendLine("                        SuccessCount = method.SuccessCount,");
        sb.AppendLine("                        ErrorCount = method.ErrorCount,");
        sb.AppendLine("                        AverageDuration = method.SuccessCount > 0 ? method.TotalDuration / method.SuccessCount : 0,");
        sb.AppendLine("                        MaxDuration = method.MaxDuration,");
        sb.AppendLine("                        MinDuration = method.MinDuration,");
        sb.AppendLine("                        LastError = method.LastError,");
        sb.AppendLine("                        LastErrorTime = method.LastErrorTime");
        sb.AppendLine("                    };");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return new EventHandlerMetrics");
        sb.AppendLine("            {");
        sb.AppendLine("                TotalEventsReceived = _totalEventsReceived,");
        sb.AppendLine("                TotalEventsProcessed = _totalEventsProcessed,");
        sb.AppendLine("                TotalErrors = _totalErrors,");
        sb.AppendLine("                TotalBatchesProcessed = _totalBatchesProcessed,");
        sb.AppendLine("                TotalBatchErrors = _totalBatchErrors,");
        sb.AppendLine("                MethodMetrics = methodSnapshots");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private sealed class EventMethodMetrics");
        sb.AppendLine("        {");
        sb.AppendLine("            public long CallCount;");
        sb.AppendLine("            public long SuccessCount;");
        sb.AppendLine("            public long ErrorCount;");
        sb.AppendLine("            public double TotalDuration;");
        sb.AppendLine("            public double MaxDuration;");
        sb.AppendLine("            public double MinDuration;");
        sb.AppendLine("            public Exception? LastError;");
        sb.AppendLine("            public DateTime LastErrorTime;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateEventHandlerMetrics(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 事件处理器性能指标快照");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public sealed class EventHandlerMetrics");
        sb.AppendLine("    {");
        sb.AppendLine("        public long TotalEventsReceived { get; set; }");
        sb.AppendLine("        public long TotalEventsProcessed { get; set; }");
        sb.AppendLine("        public long TotalErrors { get; set; }");
        sb.AppendLine("        public long TotalBatchesProcessed { get; set; }");
        sb.AppendLine("        public long TotalBatchErrors { get; set; }");
        sb.AppendLine("        public Dictionary<string, MethodMetrics> MethodMetrics { get; set; } = new();");
        sb.AppendLine();

        sb.AppendLine("        public double SuccessRate => TotalEventsReceived > 0 ? (double)TotalEventsProcessed / TotalEventsReceived : 0;");
        sb.AppendLine("        public double ErrorRate => TotalEventsReceived > 0 ? (double)TotalErrors / TotalEventsReceived : 0;");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 方法级性能指标");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public sealed class MethodMetrics");
        sb.AppendLine("    {");
        sb.AppendLine("        public long CallCount { get; set; }");
        sb.AppendLine("        public long SuccessCount { get; set; }");
        sb.AppendLine("        public long ErrorCount { get; set; }");
        sb.AppendLine("        public double AverageDuration { get; set; }");
        sb.AppendLine("        public double MaxDuration { get; set; }");
        sb.AppendLine("        public double MinDuration { get; set; }");
        sb.AppendLine("        public Exception? LastError { get; set; }");
        sb.AppendLine("        public DateTime LastErrorTime { get; set; }");
        sb.AppendLine();

        sb.AppendLine("        public double SuccessRate => CallCount > 0 ? (double)SuccessCount / CallCount : 0;");
        sb.AppendLine("        public double ErrorRate => CallCount > 0 ? (double)ErrorCount / CallCount : 0;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateBatchEventItem(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 批量事件项");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal readonly struct BatchEventItem");
        sb.AppendLine("    {");
        sb.AppendLine("        public string EventName { get; }");
        sb.AppendLine("        public object EventData { get; }");
        sb.AppendLine("        public Func<object, Task> Handler { get; }");
        sb.AppendLine();

        sb.AppendLine("        public BatchEventItem(string eventName, object eventData, Func<object, Task> handler)");
        sb.AppendLine("        {");
        sb.AppendLine("            EventName = eventName;");
        sb.AppendLine("            EventData = eventData;");
        sb.AppendLine("            Handler = handler;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateBatchProcessor(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 客户端批量事件处理器 - 优化高频事件处理性能");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal sealed class BatchProcessor : IDisposable");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly EventMetrics _metrics;");
        sb.AppendLine("        private readonly System.Threading.Channels.Channel<BatchEventItem> _eventQueue;");
        sb.AppendLine("        private readonly Task _processingTask;");
        sb.AppendLine("        private readonly CancellationTokenSource _cancellationTokenSource = new();");
        sb.AppendLine("        private volatile bool _disposed;");
        sb.AppendLine();

        sb.AppendLine("        public BatchProcessor(EventMetrics metrics)");
        sb.AppendLine("        {");
        sb.AppendLine("            _metrics = metrics ?? throw new ArgumentNullException(nameof(metrics));");
        sb.AppendLine("            var options = new System.Threading.Channels.BoundedChannelOptions(1000)");
        sb.AppendLine("            {");
        sb.AppendLine("                FullMode = System.Threading.Channels.BoundedChannelFullMode.Wait,");
        sb.AppendLine("                SingleReader = true,");
        sb.AppendLine("                SingleWriter = false");
        sb.AppendLine("            };");
        sb.AppendLine("            _eventQueue = System.Threading.Channels.Channel.CreateBounded<BatchEventItem>(options);");
        sb.AppendLine("            _processingTask = ProcessBatchEventsAsync(_cancellationTokenSource.Token);");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        public async ValueTask QueueEventAsync<T>(string eventName, T eventData, Func<T, Task> handler)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_disposed) return;");
        sb.AppendLine("            ");
        sb.AppendLine("            var item = new BatchEventItem(eventName, eventData!, async data =>");
        sb.AppendLine("            {");
        sb.AppendLine("                if (data is T typedData)");
        sb.AppendLine("                {");
        sb.AppendLine("                    await handler(typedData).ConfigureAwait(false);");
        sb.AppendLine("                }");
        sb.AppendLine("            });");
        sb.AppendLine("            ");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                await _eventQueue.Writer.WriteAsync(item, _cancellationTokenSource.Token).ConfigureAwait(false);");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (OperationCanceledException)");
        sb.AppendLine("            {");
        sb.AppendLine("                // 已取消，忽略");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private async Task ProcessBatchEventsAsync(CancellationToken cancellationToken)");
        sb.AppendLine("        {");
        sb.AppendLine("            var batch = new List<BatchEventItem>(50);");
        sb.AppendLine("            ");
        sb.AppendLine("            while (!cancellationToken.IsCancellationRequested)");
        sb.AppendLine("            {");
        sb.AppendLine("                try");
        sb.AppendLine("                {");
        sb.AppendLine("                    // 收集事件到批次中");
        sb.AppendLine("                    while (batch.Count < 50 && _eventQueue.Reader.TryRead(out var item))");
        sb.AppendLine("                    {");
        sb.AppendLine("                        batch.Add(item);");
        sb.AppendLine("                    }");
        sb.AppendLine();
        sb.AppendLine("                    if (batch.Count > 0)");
        sb.AppendLine("                    {");
        sb.AppendLine("                        await ProcessBatch(batch).ConfigureAwait(false);");
        sb.AppendLine("                        batch.Clear();");
        sb.AppendLine("                    }");
        sb.AppendLine("                    else");
        sb.AppendLine("                    {");
        sb.AppendLine("                        // 等待新事件");
        sb.AppendLine("                        await Task.Delay(10, cancellationToken).ConfigureAwait(false);");
        sb.AppendLine("                    }");
        sb.AppendLine("                }");
        sb.AppendLine("                catch (OperationCanceledException)");
        sb.AppendLine("                {");
        sb.AppendLine("                    break;");
        sb.AppendLine("                }");
        sb.AppendLine("                catch (Exception ex)");
        sb.AppendLine("                {");
        sb.AppendLine("                    _metrics.RecordBatchProcessingError(ex);");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private async Task ProcessBatch(List<BatchEventItem> batch)");
        sb.AppendLine("        {");
        sb.AppendLine("            var stopwatch = Stopwatch.StartNew();");
        sb.AppendLine("            ");
        sb.AppendLine("            var tasks = batch.Select(async item =>");
        sb.AppendLine("            {");
        sb.AppendLine("                try");
        sb.AppendLine("                {");
        sb.AppendLine("                    await item.Handler(item.EventData).ConfigureAwait(false);");
        sb.AppendLine("                    return true;");
        sb.AppendLine("                }");
        sb.AppendLine("                catch (Exception ex)");
        sb.AppendLine("                {");
        sb.AppendLine("                    _metrics.RecordEventError(item.EventName, ex, TimeSpan.Zero);");
        sb.AppendLine("                    return false;");
        sb.AppendLine("                }");
        sb.AppendLine("            }).ToArray();");
        sb.AppendLine("            ");
        sb.AppendLine("            var results = await Task.WhenAll(tasks).ConfigureAwait(false);");
        sb.AppendLine("            var successCount = results.Count(r => r);");
        sb.AppendLine("            ");
        sb.AppendLine("            _metrics.RecordBatchProcessed(batch.Count, successCount, stopwatch.Elapsed);");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        public void Dispose()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_disposed) return;");
        sb.AppendLine("            _disposed = true;");
        sb.AppendLine("            ");
        sb.AppendLine("            _cancellationTokenSource.Cancel();");
        sb.AppendLine("            _eventQueue.Writer.Complete();");
        sb.AppendLine("            ");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                _processingTask.Wait(TimeSpan.FromSeconds(5));");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (AggregateException)");
        sb.AppendLine("            {");
        sb.AppendLine("                // 忽略超时异常");
        sb.AppendLine("            }");
        sb.AppendLine("            ");
        sb.AppendLine("            _cancellationTokenSource.Dispose();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateMonitoredEventReceiver(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 性能监控包装器 - 为事件接收器添加监控功能");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal sealed class MonitoredEventReceiver<T> where T : class");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly T _inner;");
        sb.AppendLine("        private readonly SubscriptionContext _context;");
        sb.AppendLine();

        sb.AppendLine("        public MonitoredEventReceiver(T inner, SubscriptionContext context)");
        sb.AppendLine("        {");
        sb.AppendLine("            _inner = inner ?? throw new ArgumentNullException(nameof(inner));");
        sb.AppendLine("            _context = context ?? throw new ArgumentNullException(nameof(context));");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        public T Inner => _inner;");
        sb.AppendLine("        public SubscriptionContext Context => _context;");
        sb.AppendLine();

        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 创建监控方法调用");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public async Task InvokeMethodAsync(string methodName, Func<T, Task> method)");
        sb.AppendLine("        {");
        sb.AppendLine("            var stopwatch = Stopwatch.StartNew();");
        sb.AppendLine("            _context.Metrics.RecordEventReceived(methodName);");
        sb.AppendLine();
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                await method(_inner).ConfigureAwait(false);");
        sb.AppendLine("                _context.Metrics.RecordEventProcessed(methodName, stopwatch.Elapsed);");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine("                _context.Metrics.RecordEventError(methodName, ex, stopwatch.Elapsed);");
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 创建监控方法调用（同步版本）");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public void InvokeMethod(string methodName, Action<T> method)");
        sb.AppendLine("        {");
        sb.AppendLine("            var stopwatch = Stopwatch.StartNew();");
        sb.AppendLine("            _context.Metrics.RecordEventReceived(methodName);");
        sb.AppendLine();
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                method(_inner);");
        sb.AppendLine("                _context.Metrics.RecordEventProcessed(methodName, stopwatch.Elapsed);");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine("                _context.Metrics.RecordEventError(methodName, ex, stopwatch.Elapsed);");
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateCircuitBreakerState(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 断路器状态");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal sealed class CircuitBreakerState : IDisposable");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly object _lock = new();");
        sb.AppendLine("        private int _failureCount;");
        sb.AppendLine("        private DateTime _lastFailureTime;");
        sb.AppendLine("        private bool _isOpen;");
        sb.AppendLine();

        sb.AppendLine("        public bool IsOpen");
        sb.AppendLine("        {");
        sb.AppendLine("            get");
        sb.AppendLine("            {");
        sb.AppendLine("                lock (_lock)");
        sb.AppendLine("                {");
        sb.AppendLine("                    if (_isOpen && DateTime.UtcNow - _lastFailureTime > TimeSpan.FromMinutes(1))");
        sb.AppendLine("                    {");
        sb.AppendLine("                        _isOpen = false;");
        sb.AppendLine("                        _failureCount = 0;");
        sb.AppendLine("                    }");
        sb.AppendLine("                    return _isOpen;");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        public void RecordSuccess()");
        sb.AppendLine("        {");
        sb.AppendLine("            lock (_lock)");
        sb.AppendLine("            {");
        sb.AppendLine("                _failureCount = 0;");
        sb.AppendLine("                _isOpen = false;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        public void RecordFailure()");
        sb.AppendLine("        {");
        sb.AppendLine("            lock (_lock)");
        sb.AppendLine("            {");
        sb.AppendLine("                _failureCount++;");
        sb.AppendLine("                _lastFailureTime = DateTime.UtcNow;");
        sb.AppendLine("                if (_failureCount >= 5)");
        sb.AppendLine("                {");
        sb.AppendLine("                    _isOpen = true;");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        public void Dispose()");
        sb.AppendLine("        {");
        sb.AppendLine("            // 清理资源");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateAsyncHelpers(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 异步方法辅助扩展 - 为监控包装器提供异步支持");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal static class AsyncMethodHelpers");
        sb.AppendLine("    {");

        // Task 包装方法
        sb.AppendLine("        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        public static async Task CompleteTaskWithMetrics(Task task, string methodName, System.Diagnostics.Stopwatch stopwatch)");
        sb.AppendLine("        {");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                await task.ConfigureAwait(false);");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                stopwatch.Stop();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // ValueTask 包装方法
        sb.AppendLine("        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        public static async System.Threading.Tasks.ValueTask CompleteValueTaskWithMetrics(System.Threading.Tasks.ValueTask valueTask, string methodName, System.Diagnostics.Stopwatch stopwatch)");
        sb.AppendLine("        {");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                await valueTask.ConfigureAwait(false);");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                stopwatch.Stop();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 重试逻辑
        sb.AppendLine("        public static async Task<T> WithRetryAsync<T>(Func<Task<T>> operation, int maxRetries, TimeSpan delay)");
        sb.AppendLine("        {");
        sb.AppendLine("            Exception? lastException = null;");
        sb.AppendLine("            ");
        sb.AppendLine("            for (int attempt = 0; attempt <= maxRetries; attempt++)");
        sb.AppendLine("            {");
        sb.AppendLine("                try");
        sb.AppendLine("                {");
        sb.AppendLine("                    return await operation().ConfigureAwait(false);");
        sb.AppendLine("                }");
        sb.AppendLine("                catch (Exception ex)");
        sb.AppendLine("                {");
        sb.AppendLine("                    lastException = ex;");
        sb.AppendLine("                    if (attempt == maxRetries)");
        sb.AppendLine("                        break;");
        sb.AppendLine("                    await Task.Delay(delay).ConfigureAwait(false);");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("            throw lastException!;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("    }");

        // 结束命名空间
        sb.AppendLine("}");
    }
}
