using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;

namespace PulseRPC.Generator.Generators;

/// <summary>
/// 智能事件处理器生成器 - 生成高性能、智能的事件处理代码
/// </summary>
public static class EventHandlerGenerator
{
    /// <summary>
    /// 生成智能事件处理器
    /// </summary>
    public static string GenerateEventHandler(INamedTypeSymbol interfaceSymbol, SourceProductionContext context, Dictionary<string, ushort> protocolIds)
    {
        var interfaceName = interfaceSymbol.Name;
        var isGlobalNamespace = interfaceSymbol.ContainingNamespace.IsGlobalNamespace;
        var namespaceName = isGlobalNamespace ? null : interfaceSymbol.ContainingNamespace.ToDisplayString();
        var handlerClassName = GetHandlerClassName(interfaceName);
        var channelName = GetChannelAttributeValue(interfaceSymbol) ?? "default";

        var sb = new StringBuilder();

        // 生成文件头
        GenerateFileHeader(sb);

        // 全局命名空间时不生成 namespace 块
        if (!isGlobalNamespace)
        {
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
        }

        // 生成智能事件处理器类（只生成特定于此接口的处理器）
        GenerateSmartHandlerClass(sb, interfaceSymbol, handlerClassName, channelName, protocolIds, isGlobalNamespace);

        // CompositeSubscriptionToken 已在 PulseRPC.Abstractions 中定义，无需重复生成

        // 结束命名空间
        if (!isGlobalNamespace)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static void GenerateFileHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// PulseRPC Smart Event Handler Generator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Concurrent;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Diagnostics;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Channels;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using PulseRPC.Client.Events;");
        sb.AppendLine("using PulseRPC.Client;");
        sb.AppendLine("using PulseRPC;");
        sb.AppendLine();
    }

    private static void GenerateSmartHandlerClass(StringBuilder sb, INamedTypeSymbol interfaceSymbol, string handlerClassName, string channelName, Dictionary<string, ushort> protocolIds, bool isGlobalNamespace)
    {
        var interfaceName = interfaceSymbol.Name;
        // 缩进：全局命名空间时无缩进，否则有4空格缩进
        var indent = isGlobalNamespace ? "" : "    ";
        var memberIndent = indent + "    ";
        var bodyIndent = memberIndent + "    ";

        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}/// 智能事件处理器 - 为 {interfaceName} 提供高性能事件处理功能");
        sb.AppendLine($"{indent}/// 使用协议号进行高性能事件路由");
        sb.AppendLine($"{indent}/// </summary>");
        var smartClassName = interfaceSymbol.Name.StartsWith("I")
            ? $"{interfaceSymbol.Name.Substring(1)}SmartHandler"
            : $"{interfaceSymbol.Name}SmartHandler";
        sb.AppendLine($"{indent}public sealed class {smartClassName} : IDisposable");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{memberIndent}private readonly ConcurrentDictionary<{interfaceName}, SubscriptionContext> _subscriptions = new();");
        sb.AppendLine($"{memberIndent}private readonly EventMetrics _metrics = new();");
        sb.AppendLine($"{memberIndent}private readonly BatchProcessor _batchProcessor;");
        sb.AppendLine($"{memberIndent}private readonly CancellationTokenSource _cancellationTokenSource = new();");
        sb.AppendLine($"{memberIndent}private volatile bool _disposed;");
        sb.AppendLine();

        // 生成协议号常量
        GenerateProtocolIdConstants(sb, interfaceSymbol, protocolIds, memberIndent);
        sb.AppendLine();

        sb.AppendLine($"{memberIndent}public {smartClassName}()");
        sb.AppendLine($"{memberIndent}{{");
        sb.AppendLine($"{bodyIndent}_batchProcessor = new BatchProcessor(_metrics);");
        sb.AppendLine($"{memberIndent}}}");
        sb.AppendLine();

        sb.AppendLine($"{memberIndent}internal {smartClassName}(EventMetrics? customMetrics)");
        sb.AppendLine($"{memberIndent}{{");
        sb.AppendLine($"{bodyIndent}if (customMetrics != null)");
        sb.AppendLine($"{bodyIndent}{{");
        sb.AppendLine($"{bodyIndent}    _metrics = customMetrics;");
        sb.AppendLine($"{bodyIndent}}}");
        sb.AppendLine($"{bodyIndent}_batchProcessor = new BatchProcessor(_metrics);");
        sb.AppendLine($"{memberIndent}}}");
        sb.AppendLine();

        // 生成订阅方法
        GenerateSubscriptionMethods(sb, interfaceSymbol, memberIndent, bodyIndent);

        // 生成通道集成方法
        GenerateChannelIntegrationMethods(sb, interfaceSymbol, memberIndent, bodyIndent);

        // 生成监控方法
        GenerateMonitoringMethods(sb, memberIndent, bodyIndent);

        // 生成配置方法
        GenerateConfigurationMethods(sb, interfaceSymbol, memberIndent);

        // 生成释放方法
        GenerateDisposeMethod(sb, memberIndent, bodyIndent);

        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    private static void GenerateSubscriptionMethods(StringBuilder sb, INamedTypeSymbol interfaceSymbol, string memberIndent, string bodyIndent)
    {
        var interfaceName = interfaceSymbol.Name;
        var innerIndent = bodyIndent + "    ";

        sb.AppendLine($"{memberIndent}/// <summary>");
        sb.AppendLine($"{memberIndent}/// 订阅事件接收器");
        sb.AppendLine($"{memberIndent}/// </summary>");
        sb.AppendLine($"{memberIndent}public void Subscribe({interfaceName} receiver, SmartSubscriptionOptions? options = null)");
        sb.AppendLine($"{memberIndent}{{");
        sb.AppendLine($"{bodyIndent}ThrowIfDisposed();");
        sb.AppendLine($"{bodyIndent}options ??= SmartSubscriptionOptions.Default;");
        sb.AppendLine();
        sb.AppendLine($"{bodyIndent}var context = new SubscriptionContext(receiver, options, _metrics);");
        sb.AppendLine($"{bodyIndent}_subscriptions.TryAdd(receiver, context);");
        sb.AppendLine($"{memberIndent}}}");
        sb.AppendLine();

        sb.AppendLine($"{memberIndent}/// <summary>");
        sb.AppendLine($"{memberIndent}/// 取消订阅事件接收器");
        sb.AppendLine($"{memberIndent}/// </summary>");
        sb.AppendLine($"{memberIndent}public bool Unsubscribe({interfaceName} receiver)");
        sb.AppendLine($"{memberIndent}{{");
        sb.AppendLine($"{bodyIndent}if (_subscriptions.TryRemove(receiver, out var context))");
        sb.AppendLine($"{bodyIndent}{{");
        sb.AppendLine($"{innerIndent}context.Dispose();");
        sb.AppendLine($"{innerIndent}return true;");
        sb.AppendLine($"{bodyIndent}}}");
        sb.AppendLine($"{bodyIndent}return false;");
        sb.AppendLine($"{memberIndent}}}");
        sb.AppendLine();

        sb.AppendLine($"{memberIndent}/// <summary>");
        sb.AppendLine($"{memberIndent}/// 异步订阅事件接收器");
        sb.AppendLine($"{memberIndent}/// </summary>");
        sb.AppendLine($"{memberIndent}public Task<ISubscriptionToken> SubscribeAsync({interfaceName} receiver, SmartSubscriptionOptions? options = null)");
        sb.AppendLine($"{memberIndent}{{");
        sb.AppendLine($"{bodyIndent}Subscribe(receiver, options);");
        sb.AppendLine($"{bodyIndent}var context = _subscriptions.GetValueOrDefault(receiver);");
        sb.AppendLine($"{bodyIndent}var token = new SmartSubscriptionToken(null!, context!, () => Unsubscribe(receiver));");
        sb.AppendLine($"{bodyIndent}return Task.FromResult<ISubscriptionToken>(token);");
        sb.AppendLine($"{memberIndent}}}");
        sb.AppendLine();

        // 为每个接口方法生成智能分发方法
        foreach (var member in interfaceSymbol.GetMembers())
        {
            if (member is IMethodSymbol methodSymbol && methodSymbol.DeclaredAccessibility == Accessibility.Public)
            {
                GenerateSmartDispatchMethod(sb, methodSymbol, interfaceName, memberIndent, bodyIndent);
            }
        }
    }

    private static void GenerateSmartDispatchMethod(StringBuilder sb, IMethodSymbol methodSymbol, string interfaceName, string memberIndent, string bodyIndent)
    {
        var methodName = methodSymbol.Name;
        var returnType = methodSymbol.ReturnType.ToDisplayString();
        var isAsync = IsAsyncMethod(methodSymbol);
        var parameters = methodSymbol.Parameters;
        var innerIndent = bodyIndent + "    ";
        var deepIndent = innerIndent + "    ";

        sb.AppendLine($"{memberIndent}/// <summary>");
        sb.AppendLine($"{memberIndent}/// 智能分发 {methodName} 事件");
        sb.AppendLine($"{memberIndent}/// </summary>");
        sb.Append($"{memberIndent}public async Task Dispatch{methodName}Async(");

        // 生成参数列表
        for (var i = 0; i < parameters.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append($"{parameters[i].Type.ToDisplayString()} {parameters[i].Name}");
        }

        sb.AppendLine(")");
        sb.AppendLine($"{memberIndent}{{");
        sb.AppendLine($"{bodyIndent}ThrowIfDisposed();");
        sb.AppendLine($"{bodyIndent}_metrics.RecordEventReceived(\"{methodName}\");");
        sb.AppendLine();

        sb.AppendLine($"{bodyIndent}var tasks = new List<Task>();");
        sb.AppendLine($"{bodyIndent}");
        sb.AppendLine($"{bodyIndent}foreach (var kvp in _subscriptions)");
        sb.AppendLine($"{bodyIndent}{{");
        sb.AppendLine($"{innerIndent}var receiver = kvp.Key;");
        sb.AppendLine($"{innerIndent}var context = kvp.Value;");
        sb.AppendLine();

        var parameterNames = string.Join(", ", parameters.Select(p => p.Name));

        if (isAsync)
        {
            sb.AppendLine($"{innerIndent}if (context.Options.EnableBatchProcessing)");
            sb.AppendLine($"{innerIndent}{{");
            sb.AppendLine($"{deepIndent}await _batchProcessor.QueueEventAsync(\"{methodName}\", new object[] {{ {parameterNames} }}, ");
            sb.AppendLine($"{deepIndent}    async data => ");
            sb.AppendLine($"{deepIndent}    {{");
            sb.AppendLine($"{deepIndent}        var args = (object[])data;");
            for (int i = 0; i < parameters.Length; i++)
            {
                sb.AppendLine($"{deepIndent}        var param{i} = ({parameters[i].Type.ToDisplayString()})args[{i}];");
            }
            var typedParams = string.Join(", ", Enumerable.Range(0, parameters.Length).Select(i => $"param{i}"));
            sb.AppendLine($"{deepIndent}        var monitoredReceiver = new MonitoredEventReceiver<{interfaceName}>(receiver, context);");
            sb.AppendLine($"{deepIndent}        await monitoredReceiver.InvokeMethodAsync(\"{methodName}\", r => r.{methodName}({typedParams}));");
            sb.AppendLine($"{deepIndent}    }});");
            sb.AppendLine($"{innerIndent}}}");
            sb.AppendLine($"{innerIndent}else");
            sb.AppendLine($"{innerIndent}{{");
            sb.AppendLine($"{deepIndent}var monitoredReceiver = new MonitoredEventReceiver<{interfaceName}>(receiver, context);");
            sb.AppendLine($"{deepIndent}tasks.Add(monitoredReceiver.InvokeMethodAsync(\"{methodName}\", r => r.{methodName}({parameterNames})));");
            sb.AppendLine($"{innerIndent}}}");
        }
        else
        {
            sb.AppendLine($"{innerIndent}var monitoredReceiver = new MonitoredEventReceiver<{interfaceName}>(receiver, context);");
            sb.AppendLine($"{innerIndent}tasks.Add(Task.Run(async () => await monitoredReceiver.InvokeMethodAsync(\"{methodName}\", r => Task.Run(() => r.{methodName}({parameterNames})))));");
        }

        sb.AppendLine($"{bodyIndent}}}");
        sb.AppendLine();
        sb.AppendLine($"{bodyIndent}if (tasks.Count > 0)");
        sb.AppendLine($"{bodyIndent}{{");
        sb.AppendLine($"{innerIndent}await Task.WhenAll(tasks);");
        sb.AppendLine($"{bodyIndent}}}");
        sb.AppendLine($"{memberIndent}}}");
        sb.AppendLine();
    }

    private static void GenerateChannelIntegrationMethods(StringBuilder sb, INamedTypeSymbol interfaceSymbol, string memberIndent, string bodyIndent)
    {
        var interfaceName = interfaceSymbol.Name;
        var innerIndent = bodyIndent + "    ";
        var deepIndent = innerIndent + "    ";

        sb.AppendLine($"{memberIndent}/// <summary>");
        sb.AppendLine($"{memberIndent}/// 连接到 IClientChannel 并订阅所有事件");
        sb.AppendLine($"{memberIndent}/// </summary>");
        sb.AppendLine($"{memberIndent}public async Task<ISubscriptionToken> ConnectToChannelAsync(PulseRPC.Client.IClientChannel channel)");
        sb.AppendLine($"{memberIndent}{{");
        sb.AppendLine($"{bodyIndent}ThrowIfDisposed();");
        sb.AppendLine($"{bodyIndent}var tokens = new List<ISubscriptionToken>();");
        sb.AppendLine();

        // 为每个接口方法生成通道订阅
        foreach (var member in interfaceSymbol.GetMembers())
        {
            if (member is IMethodSymbol methodSymbol && methodSymbol.DeclaredAccessibility == Accessibility.Public)
            {
                GenerateChannelEventSubscription(sb, methodSymbol, interfaceName, bodyIndent, innerIndent, deepIndent);
            }
        }

        sb.AppendLine($"{bodyIndent}// 返回复合订阅令牌");
        sb.AppendLine($"{bodyIndent}return new CompositeSubscriptionToken(tokens);");
        sb.AppendLine($"{memberIndent}}}");
        sb.AppendLine();

        // 为每个接口方法生成智能分发方法（用于从通道事件调用）
        foreach (var member in interfaceSymbol.GetMembers())
        {
            if (member is IMethodSymbol methodSymbol && methodSymbol.DeclaredAccessibility == Accessibility.Public)
            {
                GenerateChannelDispatchMethod(sb, methodSymbol, interfaceName, memberIndent, bodyIndent);
            }
        }
    }

    private static void GenerateChannelEventSubscription(StringBuilder sb, IMethodSymbol methodSymbol, string interfaceName, string bodyIndent, string innerIndent, string deepIndent)
    {
        var methodName = methodSymbol.Name;
        var parameters = methodSymbol.Parameters;
        var constName = ProtocolIdGenerator.GetProtocolIdConstantName(methodSymbol);

        // 确定事件数据类型
        string eventDataType;
        if (parameters.Length == 0)
        {
            eventDataType = "object";
        }
        else if (parameters.Length == 1)
        {
            eventDataType = parameters[0].Type.ToDisplayString();
        }
        else
        {
            // 多个参数时创建一个包装类型名称 (元组)
            eventDataType = "(" + string.Join(", ", parameters.Select(p => p.Type.ToDisplayString())) + ")";
        }

        sb.AppendLine($"{bodyIndent}// ========== 零拷贝优化路径：Server Sent Event ==========");
        sb.AppendLine($"{bodyIndent}// 订阅 {methodName} 事件（使用协议号，零拷贝反序列化）");
        sb.AppendLine($"{bodyIndent}// Protocol ID: {constName}");
        sb.AppendLine($"{bodyIndent}tokens.Add(channel.RegisterEventHandler(");
        sb.AppendLine($"{innerIndent}protocolId: {constName},");
        sb.AppendLine($"{innerIndent}deserializeAndInvoke: (System.ReadOnlyMemory<byte> __rawEventData__) =>");
        sb.AppendLine($"{innerIndent}{{");
        sb.AppendLine($"{deepIndent}// 显式反序列化（编译时已知类型）");
        sb.AppendLine($"{deepIndent}var __eventData__ = MemoryPack.MemoryPackSerializer.Deserialize<{eventDataType}>(__rawEventData__.Span)!;");
        sb.AppendLine($"{deepIndent}// 调用分发方法");
        sb.AppendLine($"{deepIndent}_ = Dispatch{methodName}FromChannelAsync(__eventData__);");
        sb.AppendLine($"{innerIndent}}}));");
        sb.AppendLine();
    }

    private static void GenerateChannelDispatchMethod(StringBuilder sb, IMethodSymbol methodSymbol, string interfaceName, string memberIndent, string bodyIndent)
    {
        var methodName = methodSymbol.Name;
        var parameters = methodSymbol.Parameters;

        sb.AppendLine($"{memberIndent}/// <summary>");
        sb.AppendLine($"{memberIndent}/// 从通道分发 {methodName} 事件到智能处理器（零拷贝优化）");
        sb.AppendLine($"{memberIndent}/// </summary>");

        // 确定参数类型和处理方式
        if (parameters.Length == 0)
        {
            sb.AppendLine($"{memberIndent}private async Task Dispatch{methodName}FromChannelAsync(object eventData)");
            sb.AppendLine($"{memberIndent}{{");
            sb.AppendLine($"{bodyIndent}await Dispatch{methodName}Async();");
            sb.AppendLine($"{memberIndent}}}");
        }
        else if (parameters.Length == 1)
        {
            var paramType = parameters[0].Type.ToDisplayString();
            var paramName = parameters[0].Name;
            sb.AppendLine($"{memberIndent}private async Task Dispatch{methodName}FromChannelAsync({paramType} {paramName})");
            sb.AppendLine($"{memberIndent}{{");
            sb.AppendLine($"{bodyIndent}await Dispatch{methodName}Async({paramName});");
            sb.AppendLine($"{memberIndent}}}");
        }
        else
        {
            // 多个参数的情况下，使用元组解构
            var tupleType = "(" + string.Join(", ", parameters.Select(p => p.Type.ToDisplayString())) + ")";
            sb.AppendLine($"{memberIndent}private async Task Dispatch{methodName}FromChannelAsync({tupleType} eventData)");
            sb.AppendLine($"{memberIndent}{{");
            sb.Append($"{bodyIndent}await Dispatch{methodName}Async(");

            // 生成参数列表（从元组解构）
            for (var i = 0; i < parameters.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append($"eventData.Item{i + 1}");
            }

            sb.AppendLine(");");
            sb.AppendLine($"{memberIndent}}}");
        }
        sb.AppendLine();
    }

    private static void GenerateMonitoringMethods(StringBuilder sb, string memberIndent, string bodyIndent)
    {
        sb.AppendLine($"{memberIndent}/// <summary>");
        sb.AppendLine($"{memberIndent}/// 获取性能监控指标");
        sb.AppendLine($"{memberIndent}/// </summary>");
        sb.AppendLine($"{memberIndent}public EventHandlerMetrics GetMetrics()");
        sb.AppendLine($"{memberIndent}{{");
        sb.AppendLine($"{bodyIndent}return _metrics.GetSnapshot();");
        sb.AppendLine($"{memberIndent}}}");
        sb.AppendLine();
    }

    private static void GenerateConfigurationMethods(StringBuilder sb, INamedTypeSymbol interfaceSymbol, string memberIndent)
    {
        var interfaceName = interfaceSymbol.Name;

        sb.AppendLine($"{memberIndent}/// <summary>");
        sb.AppendLine($"{memberIndent}/// 获取活跃订阅数量");
        sb.AppendLine($"{memberIndent}/// </summary>");
        sb.AppendLine($"{memberIndent}public int ActiveSubscriptionCount => _subscriptions.Count;");
        sb.AppendLine();

        sb.AppendLine($"{memberIndent}/// <summary>");
        sb.AppendLine($"{memberIndent}/// 获取所有活跃的订阅者");
        sb.AppendLine($"{memberIndent}/// </summary>");
        sb.AppendLine($"{memberIndent}public IReadOnlyList<{interfaceName}> GetActiveSubscribers()");
        sb.AppendLine($"{memberIndent}{{");
        sb.AppendLine($"{memberIndent}    return _subscriptions.Keys.ToList();");
        sb.AppendLine($"{memberIndent}}}");
        sb.AppendLine();
    }

    private static void GenerateDisposeMethod(StringBuilder sb, string memberIndent, string bodyIndent)
    {
        var innerIndent = bodyIndent + "    ";

        sb.AppendLine($"{memberIndent}/// <summary>");
        sb.AppendLine($"{memberIndent}/// 释放资源");
        sb.AppendLine($"{memberIndent}/// </summary>");
        sb.AppendLine($"{memberIndent}public void Dispose()");
        sb.AppendLine($"{memberIndent}{{");
        sb.AppendLine($"{bodyIndent}if (_disposed) return;");
        sb.AppendLine($"{bodyIndent}");
        sb.AppendLine($"{bodyIndent}_cancellationTokenSource.Cancel();");
        sb.AppendLine($"{bodyIndent}");
        sb.AppendLine($"{bodyIndent}// 取消所有订阅");
        sb.AppendLine($"{bodyIndent}foreach (var context in _subscriptions.Values)");
        sb.AppendLine($"{bodyIndent}{{");
        sb.AppendLine($"{innerIndent}context.Dispose();");
        sb.AppendLine($"{bodyIndent}}}");
        sb.AppendLine($"{bodyIndent}_subscriptions.Clear();");
        sb.AppendLine($"{bodyIndent}");
        sb.AppendLine($"{bodyIndent}_batchProcessor.Dispose();");
        sb.AppendLine($"{bodyIndent}_cancellationTokenSource.Dispose();");
        sb.AppendLine($"{bodyIndent}_disposed = true;");
        sb.AppendLine($"{memberIndent}}}");
        sb.AppendLine();

        sb.AppendLine($"{memberIndent}private void ThrowIfDisposed()");
        sb.AppendLine($"{memberIndent}{{");
        sb.AppendLine($"{bodyIndent}if (_disposed)");
        sb.AppendLine($"{bodyIndent}    throw new ObjectDisposedException(GetType().Name);");
        sb.AppendLine($"{memberIndent}}}");
        sb.AppendLine();
    }


    // 辅助方法
    private static string GetHandlerClassName(string interfaceName)
    {
        return interfaceName.StartsWith("I")
            ? interfaceName.Substring(1) + "Handler"
            : interfaceName + "Handler";
    }

    /// <summary>
    /// 生成协议号常量
    /// </summary>
    private static void GenerateProtocolIdConstants(StringBuilder sb, INamedTypeSymbol interfaceSymbol, Dictionary<string, ushort> protocolIds, string indent)
    {
        sb.AppendLine($"{indent}// ==================== 事件协议号常量 ====================");
        sb.AppendLine($"{indent}// 使用 FNV-1a 哈希算法生成，确保客户端和服务端一致");

        foreach (var member in interfaceSymbol.GetMembers())
        {
            if (member is not IMethodSymbol methodSymbol)
                continue;

            if (methodSymbol.DeclaredAccessibility != Accessibility.Public)
                continue;

            // 使用完整键格式: {InterfaceFullName}.{MethodName}
            var methodKey = $"{methodSymbol.ContainingType.ToDisplayString()}.{methodSymbol.Name}";
            if (protocolIds.TryGetValue(methodKey, out var protocolId))
            {
                var methodSignature = ProtocolIdGenerator.BuildMethodSignature(methodSymbol);
                var constName = ProtocolIdGenerator.GetProtocolIdConstantName(methodSymbol);

                sb.AppendLine($"{indent}/// <summary>");
                sb.AppendLine($"{indent}/// 协议号: {methodSymbol.Name}");
                sb.AppendLine($"{indent}/// 方法签名: {methodSignature}");
                sb.AppendLine($"{indent}/// </summary>");
                sb.AppendLine($"{indent}private const ushort {constName} = 0x{protocolId:X4}; // {protocolId}");
            }
        }
    }

    private static string? GetChannelAttributeValue(ISymbol symbol)
    {
        foreach (var attribute in symbol.GetAttributes())
        {
            if (attribute.AttributeClass?.Name is "ChannelAttribute" or "Channel")
            {
                if (attribute.ConstructorArguments.Length > 0 &&
                    attribute.ConstructorArguments[0].Value is string channelName)
                {
                    return channelName;
                }
            }
        }
        return null;
    }

    private static bool IsAsyncMethod(IMethodSymbol methodSymbol)
    {
        var returnTypeName = methodSymbol.ReturnType.ToDisplayString();
        return returnTypeName.StartsWith("System.Threading.Tasks.Task") ||
               returnTypeName.StartsWith("Task") ||
               returnTypeName.StartsWith("System.Threading.Tasks.ValueTask") ||
               returnTypeName.StartsWith("ValueTask");
    }
}
