using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace PulseRPC.Generator.Generators;

/// <summary>
/// 生成 HubProxyFactory 类，提供编译时类型安全的代理创建方法
/// 避免运行时反射
/// </summary>
public static class HubProxyFactoryGenerator
{
    /// <summary>
    /// 生成 HubProxyFactory 类
    /// </summary>
    public static string GenerateHubProxyFactory(ImmutableArray<INamedTypeSymbol> hubTypes)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// HubProxyFactory - 编译时类型安全的代理创建");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using PulseRPC;");
        sb.AppendLine("using PulseRPC.Client;");
        sb.AppendLine();

        // 收集所有 Hub 类型的命名空间
        var namespaces = hubTypes
            .Where(h => h != null && !h.ContainingNamespace.IsGlobalNamespace)
            .Select(h => h.ContainingNamespace.ToDisplayString())
            .Distinct()
            .OrderBy(n => n);

        foreach (var ns in namespaces)
        {
            sb.AppendLine($"using {ns};");
        }

        sb.AppendLine();
        sb.AppendLine("namespace PulseRPC.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Hub 代理工厂 - 提供编译时类型安全的代理创建");
        sb.AppendLine("    /// 无需运行时反射");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public sealed class HubProxyFactory");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 单例实例");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static HubProxyFactory Instance { get; } = new HubProxyFactory();");
        sb.AppendLine();
        sb.AppendLine("        private HubProxyFactory() { }");
        sb.AppendLine();

        // 生成泛型 Create 方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 创建 Hub 代理实例");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <typeparam name=\"THub\">Hub 接口类型</typeparam>");
        sb.AppendLine("        /// <param name=\"channel\">客户端通道</param>");
        sb.AppendLine("        /// <returns>代理实例，如果类型不支持则返回 null</returns>");
        sb.AppendLine("        public static THub? Create<THub>(IClientChannel channel) where THub : class, IPulseHub");
        sb.AppendLine("        {");
        sb.AppendLine("            if (channel == null) throw new ArgumentNullException(nameof(channel));");
        sb.AppendLine();
        sb.AppendLine("            var hubType = typeof(THub);");
        sb.AppendLine();

        // 为每个 Hub 类型生成类型检查
        foreach (var hubType in hubTypes)
        {
            if (hubType == null) continue;

            var fullTypeName = GetFullTypeName(hubType);
            if (string.IsNullOrEmpty(fullTypeName)) continue;

            var proxyTypeName = $"{fullTypeName}Proxy";

            sb.AppendLine($"            if (hubType == typeof({fullTypeName}))");
            sb.AppendLine($"                return (THub)(object)new {proxyTypeName}(channel);");
            sb.AppendLine();
        }

        sb.AppendLine("            // 不支持的类型");
        sb.AppendLine("            return null;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 生成非泛型 Create 方法（用于委托调用）
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 创建 Hub 代理实例（非泛型版本，用于委托调用）");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <param name=\"hubType\">Hub 接口类型</param>");
        sb.AppendLine("        /// <param name=\"channel\">客户端通道</param>");
        sb.AppendLine("        /// <returns>代理实例，如果类型不支持则返回 null</returns>");
        sb.AppendLine("        public object? Create(Type hubType, IClientChannel channel)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (hubType == null) throw new ArgumentNullException(nameof(hubType));");
        sb.AppendLine("            if (channel == null) throw new ArgumentNullException(nameof(channel));");
        sb.AppendLine();

        // 为每个 Hub 类型生成类型检查
        foreach (var hubType in hubTypes)
        {
            if (hubType == null) continue;

            var fullTypeName = GetFullTypeName(hubType);
            if (string.IsNullOrEmpty(fullTypeName)) continue;

            var proxyTypeName = $"{fullTypeName}Proxy";

            sb.AppendLine($"            if (hubType == typeof({fullTypeName}))");
            sb.AppendLine($"                return new {proxyTypeName}(channel);");
            sb.AppendLine();
        }

        sb.AppendLine("            // 不支持的类型");
        sb.AppendLine("            return null;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 生成 TryCreate 方法（带 out 参数）
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 尝试创建 Hub 代理实例");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static bool TryCreate<THub>(IClientChannel channel, out THub? proxy) where THub : class, IPulseHub");
        sb.AppendLine("        {");
        sb.AppendLine("            proxy = Create<THub>(channel);");
        sb.AppendLine("            return proxy != null;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 生成 IsSupported 方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 检查是否支持指定的 Hub 类型");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static bool IsSupported<THub>() where THub : class, IPulseHub");
        sb.AppendLine("        {");
        sb.AppendLine("            var hubType = typeof(THub);");

        foreach (var hubType in hubTypes)
        {
            if (hubType == null) continue;
            var fullTypeName = GetFullTypeName(hubType);
            if (string.IsNullOrEmpty(fullTypeName)) continue;

            sb.AppendLine($"            if (hubType == typeof({fullTypeName})) return true;");
        }

        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 生成支持的类型列表
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 获取所有支持的 Hub 类型");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static Type[] SupportedTypes { get; } = new Type[]");
        sb.AppendLine("        {");

        foreach (var hubType in hubTypes)
        {
            if (hubType == null) continue;
            var fullTypeName = GetFullTypeName(hubType);
            if (string.IsNullOrEmpty(fullTypeName)) continue;

            sb.AppendLine($"            typeof({fullTypeName}),");
        }

        sb.AppendLine("        };");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GetFullTypeName(INamedTypeSymbol typeSymbol)
    {
        if (typeSymbol.ContainingNamespace.IsGlobalNamespace)
        {
            return typeSymbol.Name;
        }

        return $"{typeSymbol.ContainingNamespace.ToDisplayString()}.{typeSymbol.Name}";
    }
}

