using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace PulseRPC.Generator.Generators;

/// <summary>
/// 接收器调度器生成器 - 为 IPulseReceiver 接口生成客户端反序列化和调度代码
/// </summary>
/// <remarks>
/// 生成内容：
/// - XxxReceiverDispatcher: 处理反序列化和调度到用户实现
/// - RegisterReceiver 扩展方法
/// </remarks>
public static class ReceiverDispatcherGenerator
{
    /// <summary>
    /// 生成接收器调度器代码
    /// </summary>
    public static string GenerateReceiverDispatcher(INamedTypeSymbol interfaceSymbol, SourceProductionContext context)
    {
        var interfaceName = interfaceSymbol.Name;
        var namespaceName = interfaceSymbol.ContainingNamespace.ToDisplayString();
        var dispatcherClassName = GetDispatcherClassName(interfaceName);

        // 为所有方法生成协议号
        var protocolIds = ProtocolIdGenerator.AssignProtocolIds(interfaceSymbol, context);

        var sb = new StringBuilder();

        GenerateFileHeader(sb, interfaceSymbol);
        GenerateUsingStatements(sb, namespaceName);

        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");

        // 生成调度器类
        GenerateDispatcherClass(sb, interfaceSymbol, dispatcherClassName, protocolIds);

        // 生成扩展方法
        GenerateExtensionMethods(sb, interfaceSymbol, dispatcherClassName);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GetDispatcherClassName(string interfaceName)
    {
        return interfaceName.StartsWith("I")
            ? interfaceName.Substring(1) + "Dispatcher"
            : interfaceName + "Dispatcher";
    }

    private static void GenerateFileHeader(StringBuilder sb, INamedTypeSymbol interfaceSymbol)
    {
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This code was generated by PulseRPC.Client.SourceGenerator");
        sb.AppendLine($"// Receiver dispatcher for {interfaceSymbol.ToDisplayString()}");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
    }

    private static void GenerateUsingStatements(StringBuilder sb, string namespaceName)
    {
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using MemoryPack;");
        sb.AppendLine("using PulseRPC;");
        sb.AppendLine("using PulseRPC.Client;");
        sb.AppendLine();
    }

    /// <summary>
    /// 生成调度器类
    /// </summary>
    private static void GenerateDispatcherClass(
        StringBuilder sb,
        INamedTypeSymbol interfaceSymbol,
        string dispatcherClassName,
        Dictionary<string, ushort> protocolIds)
    {
        var interfaceName = interfaceSymbol.Name;
        var interfaceFullName = interfaceSymbol.ToDisplayString();

        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// {interfaceName} 的客户端调度器");
        sb.AppendLine($"    /// 处理反序列化和调度到用户实现");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public sealed class {dispatcherClassName} : IDisposable");
        sb.AppendLine("    {");

        // 字段
        sb.AppendLine($"        private readonly {interfaceFullName} _implementation;");
        sb.AppendLine("        private readonly List<ISubscriptionToken> _subscriptions = new();");
        sb.AppendLine("        private bool _disposed;");
        sb.AppendLine();

        // 协议号常量
        GenerateProtocolIdConstants(sb, interfaceSymbol, protocolIds);

        // 构造函数
        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// 创建调度器实例");
        sb.AppendLine($"        /// </summary>");
        sb.AppendLine($"        public {dispatcherClassName}({interfaceFullName} implementation)");
        sb.AppendLine("        {");
        sb.AppendLine("            _implementation = implementation ?? throw new ArgumentNullException(nameof(implementation));");
        sb.AppendLine("        }");
        sb.AppendLine();

        // RegisterTo 方法
        GenerateRegisterToMethod(sb, interfaceSymbol, protocolIds);

        // Dispose 方法
        GenerateDisposeMethod(sb);

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateProtocolIdConstants(
        StringBuilder sb,
        INamedTypeSymbol interfaceSymbol,
        Dictionary<string, ushort> protocolIds)
    {
        sb.AppendLine("        // ==================== 协议号常量 ====================");
        sb.AppendLine("        // 使用 FNV-1a 哈希算法生成，确保客户端和服务端一致");
        sb.AppendLine();

        foreach (var member in interfaceSymbol.GetMembers())
        {
            if (member is IMethodSymbol methodSymbol &&
                methodSymbol.DeclaredAccessibility == Accessibility.Public &&
                methodSymbol.MethodKind == MethodKind.Ordinary)
            {
                if (protocolIds.TryGetValue(methodSymbol.Name, out var protocolId))
                {
                    var constName = $"Protocol_{methodSymbol.Name}";
                    sb.AppendLine($"        private const ushort {constName} = 0x{protocolId:X4};");
                }
            }
        }
        sb.AppendLine();
    }

    private static void GenerateRegisterToMethod(
        StringBuilder sb,
        INamedTypeSymbol interfaceSymbol,
        Dictionary<string, ushort> protocolIds)
    {
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 注册到通道");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <param name=\"channel\">客户端通道</param>");
        sb.AppendLine("        /// <returns>复合订阅令牌</returns>");
        sb.AppendLine("        public ISubscriptionToken RegisterTo(IClientChannel channel)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (channel == null) throw new ArgumentNullException(nameof(channel));");
        sb.AppendLine("            if (_disposed) throw new ObjectDisposedException(nameof(" + GetDispatcherClassName(interfaceSymbol.Name) + "));");
        sb.AppendLine();

        // 为每个方法注册处理器
        foreach (var member in interfaceSymbol.GetMembers())
        {
            if (member is IMethodSymbol methodSymbol &&
                methodSymbol.DeclaredAccessibility == Accessibility.Public &&
                methodSymbol.MethodKind == MethodKind.Ordinary)
            {
                GenerateEventHandlerRegistration(sb, methodSymbol, protocolIds);
            }
        }

        sb.AppendLine();
        sb.AppendLine("            // 返回复合订阅令牌");
        sb.AppendLine("            return new CompositeSubscriptionToken(_subscriptions);");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GenerateEventHandlerRegistration(
        StringBuilder sb,
        IMethodSymbol methodSymbol,
        Dictionary<string, ushort> protocolIds)
    {
        var methodName = methodSymbol.Name;
        var constName = $"Protocol_{methodName}";
        var parameters = methodSymbol.Parameters;

        sb.AppendLine($"            // 注册 {methodName} 事件处理器");
        sb.AppendLine($"            _subscriptions.Add(channel.RegisterEventHandler(");
        sb.AppendLine($"                protocolId: {constName},");
        sb.AppendLine($"                deserializeAndInvoke: (ReadOnlyMemory<byte> __data__) =>");
        sb.AppendLine("                {");

        if (parameters.Length == 0)
        {
            // 无参数方法
            sb.AppendLine($"                    _ = _implementation.{methodName}();");
        }
        else if (parameters.Length == 1)
        {
            // 单参数方法
            var param = parameters[0];
            sb.AppendLine($"                    var __arg__ = MemoryPackSerializer.Deserialize<{param.Type.ToDisplayString()}>(__data__.Span)!;");
            sb.AppendLine($"                    _ = _implementation.{methodName}(__arg__);");
        }
        else
        {
            // 多参数方法 - 使用元组
            var tupleType = "(" + string.Join(", ", parameters.Select(p => p.Type.ToDisplayString())) + ")";
            sb.AppendLine($"                    var __args__ = MemoryPackSerializer.Deserialize<{tupleType}>(__data__.Span)!;");

            var argList = string.Join(", ", Enumerable.Range(0, parameters.Length).Select(i => $"__args__.Item{i + 1}"));
            sb.AppendLine($"                    _ = _implementation.{methodName}({argList});");
        }

        sb.AppendLine("                }));");
        sb.AppendLine();
    }

    private static void GenerateDisposeMethod(StringBuilder sb)
    {
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 释放资源");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public void Dispose()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_disposed) return;");
        sb.AppendLine("            _disposed = true;");
        sb.AppendLine();
        sb.AppendLine("            foreach (var subscription in _subscriptions)");
        sb.AppendLine("            {");
        sb.AppendLine("                subscription.Dispose();");
        sb.AppendLine("            }");
        sb.AppendLine("            _subscriptions.Clear();");
        sb.AppendLine("        }");
    }

    /// <summary>
    /// 生成扩展方法
    /// </summary>
    private static void GenerateExtensionMethods(
        StringBuilder sb,
        INamedTypeSymbol interfaceSymbol,
        string dispatcherClassName)
    {
        var interfaceName = interfaceSymbol.Name;
        var interfaceFullName = interfaceSymbol.ToDisplayString();
        var extensionClassName = interfaceName.StartsWith("I")
            ? interfaceName.Substring(1) + "ReceiverExtensions"
            : interfaceName + "ReceiverExtensions";

        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// {interfaceName} 的 IClientChannel 扩展方法");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public static class {extensionClassName}");
        sb.AppendLine("    {");

        // RegisterReceiver 扩展方法
        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// 注册 {interfaceName} 接收器");
        sb.AppendLine($"        /// </summary>");
        sb.AppendLine($"        /// <param name=\"channel\">客户端通道</param>");
        sb.AppendLine($"        /// <param name=\"receiver\">接收器实现</param>");
        sb.AppendLine($"        /// <returns>订阅令牌，用于取消注册</returns>");
        sb.AppendLine($"        public static ISubscriptionToken RegisterReceiver(");
        sb.AppendLine($"            this IClientChannel channel,");
        sb.AppendLine($"            {interfaceFullName} receiver)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var dispatcher = new {dispatcherClassName}(receiver);");
        sb.AppendLine("            return dispatcher.RegisterTo(channel);");
        sb.AppendLine("        }");

        sb.AppendLine("    }");
    }
}

