using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace PulseRPC.Generator.Generators;

/// <summary>
/// 接收器调度器生成器 - 为 [Channel("CLIENT")] : IPulseHub 推送接收器接口生成客户端反序列化和调度代码
/// </summary>
/// <remarks>
/// 生成内容：
/// - XxxReceiverDispatcher: 处理反序列化和调度到用户实现
/// - RegisterReceiver 扩展方法
/// </remarks>
public static class ReceiverDispatcherGenerator
{
    /// <summary>
    /// 生成接收器调度器代码
    /// </summary>
    public static string GenerateReceiverDispatcher(INamedTypeSymbol interfaceSymbol, SourceProductionContext context, Dictionary<string, ushort> protocolIds)
    {
        var interfaceName = interfaceSymbol.Name;
        var isGlobalNamespace = interfaceSymbol.ContainingNamespace.IsGlobalNamespace;
        var namespaceName = isGlobalNamespace ? null : interfaceSymbol.ContainingNamespace.ToDisplayString();
        var dispatcherClassName = GetDispatcherClassName(interfaceName);

        var sb = new StringBuilder();

        GenerateFileHeader(sb, interfaceSymbol);
        GenerateUsingStatements(sb, namespaceName);

        // 缩进：全局命名空间时无缩进，否则有4空格缩进
        var indent = isGlobalNamespace ? "" : "    ";

        // 全局命名空间时不生成 namespace 块
        if (!isGlobalNamespace)
        {
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
        }

        // 生成调度器类
        GenerateDispatcherClass(sb, interfaceSymbol, dispatcherClassName, protocolIds, indent);

        // 生成扩展方法
        GenerateExtensionMethods(sb, interfaceSymbol, dispatcherClassName, indent);

        if (!isGlobalNamespace)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static string GetDispatcherClassName(string interfaceName)
    {
        return interfaceName.StartsWith("I")
            ? interfaceName.Substring(1) + "Dispatcher"
            : interfaceName + "Dispatcher";
    }

    private static void GenerateFileHeader(StringBuilder sb, INamedTypeSymbol interfaceSymbol)
    {
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This code was generated by PulseRPC.Client.SourceGenerator");
        sb.AppendLine($"// Receiver dispatcher for {interfaceSymbol.ToDisplayString()}");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
    }

    private static void GenerateUsingStatements(StringBuilder sb, string? namespaceName)
    {
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using MemoryPack;");
        sb.AppendLine("using PulseRPC;");
        sb.AppendLine("using PulseRPC.Client;");
        sb.AppendLine();
    }

    /// <summary>
    /// 生成调度器类
    /// </summary>
    private static void GenerateDispatcherClass(
        StringBuilder sb,
        INamedTypeSymbol interfaceSymbol,
        string dispatcherClassName,
        Dictionary<string, ushort> protocolIds,
        string indent)
    {
        var interfaceName = interfaceSymbol.Name;
        var interfaceFullName = interfaceSymbol.ToDisplayString();
        var memberIndent = indent + "    ";
        var bodyIndent = memberIndent + "    ";

        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}/// {interfaceName} 的客户端调度器");
        sb.AppendLine($"{indent}/// 处理反序列化和调度到用户实现");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine($"{indent}public sealed class {dispatcherClassName} : IDisposable");
        sb.AppendLine($"{indent}{{");

        // 字段
        sb.AppendLine($"{memberIndent}private readonly {interfaceFullName} _implementation;");
        sb.AppendLine($"{memberIndent}private readonly List<ISubscriptionToken> _subscriptions = new();");
        sb.AppendLine($"{memberIndent}private bool _disposed;");
        sb.AppendLine();

        // 协议号常量
        GenerateProtocolIdConstants(sb, interfaceSymbol, protocolIds, memberIndent);

        // 构造函数
        sb.AppendLine($"{memberIndent}/// <summary>");
        sb.AppendLine($"{memberIndent}/// 创建调度器实例");
        sb.AppendLine($"{memberIndent}/// </summary>");
        sb.AppendLine($"{memberIndent}public {dispatcherClassName}({interfaceFullName} implementation)");
        sb.AppendLine($"{memberIndent}{{");
        sb.AppendLine($"{bodyIndent}_implementation = implementation ?? throw new ArgumentNullException(nameof(implementation));");
        sb.AppendLine($"{memberIndent}}}");
        sb.AppendLine();

        // RegisterTo 方法
        GenerateRegisterToMethod(sb, interfaceSymbol, protocolIds, memberIndent, bodyIndent);

        // Dispose 方法
        GenerateDisposeMethod(sb, memberIndent, bodyIndent);

        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    private static void GenerateProtocolIdConstants(
        StringBuilder sb,
        INamedTypeSymbol interfaceSymbol,
        Dictionary<string, ushort> protocolIds,
        string indent)
    {
        sb.AppendLine($"{indent}// ==================== 协议号常量 ====================");
        sb.AppendLine($"{indent}// 使用 FNV-1a 哈希算法生成，确保客户端和服务端一致");
        sb.AppendLine();

        foreach (var methodSymbol in GetReceiverMethods(interfaceSymbol))
        {
            var methodKey = MethodIdentity.CreateLookupKey(methodSymbol);
            if (protocolIds.TryGetValue(methodKey, out var protocolId))
            {
                var constName = ProtocolIdGenerator.GetProtocolIdConstantName(methodSymbol);
                sb.AppendLine($"{indent}private const ushort {constName} = 0x{protocolId:X4};");
            }
        }
        sb.AppendLine();
    }

    private static void GenerateRegisterToMethod(
        StringBuilder sb,
        INamedTypeSymbol interfaceSymbol,
        Dictionary<string, ushort> protocolIds,
        string memberIndent,
        string bodyIndent)
    {
        var innerIndent = bodyIndent + "    ";
        var deepIndent = innerIndent + "    ";

        sb.AppendLine($"{memberIndent}/// <summary>");
        sb.AppendLine($"{memberIndent}/// 注册到通道");
        sb.AppendLine($"{memberIndent}/// </summary>");
        sb.AppendLine($"{memberIndent}/// <param name=\"channel\">客户端通道</param>");
        sb.AppendLine($"{memberIndent}/// <returns>复合订阅令牌</returns>");
        sb.AppendLine($"{memberIndent}public ISubscriptionToken RegisterTo(IClientChannel channel)");
        sb.AppendLine($"{memberIndent}{{");
        sb.AppendLine($"{bodyIndent}if (channel == null) throw new ArgumentNullException(nameof(channel));");
        sb.AppendLine($"{bodyIndent}if (_disposed) throw new ObjectDisposedException(nameof({GetDispatcherClassName(interfaceSymbol.Name)}));");
        sb.AppendLine();

        // 为每个方法注册处理器
        foreach (var methodSymbol in GetReceiverMethods(interfaceSymbol))
        {
            GenerateEventHandlerRegistration(sb, methodSymbol, protocolIds, bodyIndent, innerIndent, deepIndent);
        }

        sb.AppendLine();
        sb.AppendLine($"{bodyIndent}// 返回复合订阅令牌");
        sb.AppendLine($"{bodyIndent}return new CompositeSubscriptionToken(_subscriptions);");
        sb.AppendLine($"{memberIndent}}}");
        sb.AppendLine();
    }

    private static void GenerateEventHandlerRegistration(
        StringBuilder sb,
        IMethodSymbol methodSymbol,
        Dictionary<string, ushort> protocolIds,
        string bodyIndent,
        string innerIndent,
        string deepIndent)
    {
        var methodName = methodSymbol.Name;
        var constName = ProtocolIdGenerator.GetProtocolIdConstantName(methodSymbol);
        var parameters = methodSymbol.Parameters;
        var wireParameters = parameters.Where(parameter => !IsCancellationToken(parameter)).ToArray();

        // [P-4] 返回 Task<T>/ValueTask<T> 的方法 => 反向 Ask，注册请求处理器（RegisterRequestHandler）
        if (TryGetReverseAskResponseType(methodSymbol, out var responseType))
        {
            GenerateRequestHandlerRegistration(sb, methodSymbol, responseType, constName, bodyIndent, innerIndent, deepIndent);
            return;
        }

        // 判断返回类型是否为 void - void 不能赋值给 discard
        var isVoidReturn = methodSymbol.ReturnsVoid;
        var callPrefix = isVoidReturn ? "" : "_ = ";

        sb.AppendLine($"{bodyIndent}// 注册 {methodName} 事件处理器");
        sb.AppendLine($"{bodyIndent}_subscriptions.Add(channel.RegisterEventHandler(");
        sb.AppendLine($"{innerIndent}protocolId: {constName},");
        sb.AppendLine($"{innerIndent}deserializeAndInvoke: (ReadOnlyMemory<byte> __data__) =>");
        sb.AppendLine($"{innerIndent}{{");

        if (wireParameters.Length == 0)
        {
            var argList = BuildInvocationArgumentList(parameters, "System.Threading.CancellationToken.None", useTuple: false);
            sb.AppendLine($"{deepIndent}{callPrefix}_implementation.{methodName}({argList});");
        }
        else if (wireParameters.Length == 1)
        {
            // 单参数方法
            var param = wireParameters[0];
            sb.AppendLine($"{deepIndent}var __arg__ = MemoryPackSerializer.Deserialize<{param.Type.ToDisplayString()}>(__data__.Span)!;");
            var argList = BuildInvocationArgumentList(parameters, "System.Threading.CancellationToken.None", useTuple: false);
            sb.AppendLine($"{deepIndent}{callPrefix}_implementation.{methodName}({argList});");
        }
        else
        {
            // 多参数方法 - 使用元组
            var tupleType = "(" + string.Join(", ", wireParameters.Select(p => p.Type.ToDisplayString())) + ")";
            sb.AppendLine($"{deepIndent}var __args__ = MemoryPackSerializer.Deserialize<{tupleType}>(__data__.Span)!;");

            var argList = BuildInvocationArgumentList(parameters, "System.Threading.CancellationToken.None", useTuple: true);
            sb.AppendLine($"{deepIndent}{callPrefix}_implementation.{methodName}({argList});");
        }

        sb.AppendLine($"{innerIndent}}}));");
        sb.AppendLine();
    }

    private static IEnumerable<IMethodSymbol> GetReceiverMethods(INamedTypeSymbol interfaceSymbol)
    {
        var seen = new HashSet<string>();
        foreach (var type in new[] { interfaceSymbol }.Concat(interfaceSymbol.AllInterfaces))
        {
            foreach (var method in type.GetMembers().OfType<IMethodSymbol>())
            {
                if (method.DeclaredAccessibility == Accessibility.Public &&
                    method.MethodKind == MethodKind.Ordinary &&
                    seen.Add(MethodIdentity.CreateClrSignatureKey(method)))
                {
                    yield return method;
                }
            }
        }
    }

    /// <summary>
    /// [P-4] 判断方法是否为反向 Ask（返回 <c>Task&lt;T&gt;</c> / <c>ValueTask&lt;T&gt;</c>），并取出响应类型 <c>T</c>。
    /// </summary>
    private static bool TryGetReverseAskResponseType(IMethodSymbol methodSymbol, out ITypeSymbol responseType)
    {
        responseType = null!;

        if (methodSymbol.ReturnType is INamedTypeSymbol named &&
            named.IsGenericType &&
            named.TypeArguments.Length == 1)
        {
            var ns = named.ContainingNamespace?.ToDisplayString();
            if (ns == "System.Threading.Tasks" && (named.Name == "Task" || named.Name == "ValueTask"))
            {
                responseType = named.TypeArguments[0];
                return true;
            }
        }

        return false;
    }

    /// <summary>
    /// [P-4] 生成反向请求处理器注册：反序列化请求参数 -> await 用户实现 -> 序列化响应结果。
    /// </summary>
    private static void GenerateRequestHandlerRegistration(
        StringBuilder sb,
        IMethodSymbol methodSymbol,
        ITypeSymbol responseType,
        string constName,
        string bodyIndent,
        string innerIndent,
        string deepIndent)
    {
        var methodName = methodSymbol.Name;
        var parameters = methodSymbol.Parameters;
        var wireParameters = parameters.Where(parameter => !IsCancellationToken(parameter)).ToArray();

        sb.AppendLine($"{bodyIndent}// 注册 {methodName} 反向请求处理器（Server→Client Reverse Ask）");
        sb.AppendLine($"{bodyIndent}_subscriptions.Add(channel.RegisterRequestHandler(");
        sb.AppendLine($"{innerIndent}protocolId: {constName},");
        sb.AppendLine($"{innerIndent}handler: async (ReadOnlyMemory<byte> __data__, System.Threading.CancellationToken __ct__) =>");
        sb.AppendLine($"{innerIndent}{{");

        if (wireParameters.Length == 0)
        {
            var argList = BuildInvocationArgumentList(parameters, "__ct__", useTuple: false);
            sb.AppendLine($"{deepIndent}var __result__ = await _implementation.{methodName}({argList});");
        }
        else if (wireParameters.Length == 1)
        {
            var param = wireParameters[0];
            sb.AppendLine($"{deepIndent}var __arg__ = MemoryPackSerializer.Deserialize<{param.Type.ToDisplayString()}>(__data__.Span)!;");
            var argList = BuildInvocationArgumentList(parameters, "__ct__", useTuple: false);
            sb.AppendLine($"{deepIndent}var __result__ = await _implementation.{methodName}({argList});");
        }
        else
        {
            var tupleType = "(" + string.Join(", ", wireParameters.Select(p => p.Type.ToDisplayString())) + ")";
            sb.AppendLine($"{deepIndent}var __args__ = MemoryPackSerializer.Deserialize<{tupleType}>(__data__.Span)!;");
            var argList = BuildInvocationArgumentList(parameters, "__ct__", useTuple: true);
            sb.AppendLine($"{deepIndent}var __result__ = await _implementation.{methodName}({argList});");
        }

        sb.AppendLine($"{deepIndent}return MemoryPackSerializer.Serialize<{responseType.ToDisplayString()}>(__result__);");
        sb.AppendLine($"{innerIndent}}}));");
        sb.AppendLine();
    }

    private static bool IsCancellationToken(IParameterSymbol parameter)
    {
        var typeName = parameter.Type.ToDisplayString();
        return typeName is "System.Threading.CancellationToken" or "CancellationToken";
    }

    private static string BuildInvocationArgumentList(
        IEnumerable<IParameterSymbol> parameters,
        string cancellationTokenExpression,
        bool useTuple)
    {
        var wireParameterIndex = 0;
        var arguments = new List<string>();

        foreach (var parameter in parameters)
        {
            if (IsCancellationToken(parameter))
            {
                arguments.Add(cancellationTokenExpression);
                continue;
            }

            wireParameterIndex++;
            arguments.Add(useTuple ? $"__args__.Item{wireParameterIndex}" : "__arg__");
        }

        return string.Join(", ", arguments);
    }

    private static void GenerateDisposeMethod(StringBuilder sb, string memberIndent, string bodyIndent)
    {
        var innerIndent = bodyIndent + "    ";

        sb.AppendLine($"{memberIndent}/// <summary>");
        sb.AppendLine($"{memberIndent}/// 释放资源");
        sb.AppendLine($"{memberIndent}/// </summary>");
        sb.AppendLine($"{memberIndent}public void Dispose()");
        sb.AppendLine($"{memberIndent}{{");
        sb.AppendLine($"{bodyIndent}if (_disposed) return;");
        sb.AppendLine($"{bodyIndent}_disposed = true;");
        sb.AppendLine();
        sb.AppendLine($"{bodyIndent}foreach (var subscription in _subscriptions)");
        sb.AppendLine($"{bodyIndent}{{");
        sb.AppendLine($"{innerIndent}subscription.Dispose();");
        sb.AppendLine($"{bodyIndent}}}");
        sb.AppendLine($"{bodyIndent}_subscriptions.Clear();");
        sb.AppendLine($"{memberIndent}}}");
    }

    /// <summary>
    /// 生成扩展方法
    /// </summary>
    private static void GenerateExtensionMethods(
        StringBuilder sb,
        INamedTypeSymbol interfaceSymbol,
        string dispatcherClassName,
        string indent)
    {
        var interfaceName = interfaceSymbol.Name;
        var interfaceFullName = interfaceSymbol.ToDisplayString();
        var extensionClassName = interfaceName.StartsWith("I")
            ? interfaceName.Substring(1) + "ReceiverExtensions"
            : interfaceName + "ReceiverExtensions";

        var memberIndent = indent + "    ";
        var bodyIndent = memberIndent + "    ";

        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}/// {interfaceName} 的 IClientChannel 扩展方法");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine($"{indent}public static class {extensionClassName}");
        sb.AppendLine($"{indent}{{");

        // RegisterReceiver 扩展方法
        sb.AppendLine($"{memberIndent}/// <summary>");
        sb.AppendLine($"{memberIndent}/// 注册 {interfaceName} 接收器");
        sb.AppendLine($"{memberIndent}/// </summary>");
        sb.AppendLine($"{memberIndent}/// <param name=\"channel\">客户端通道</param>");
        sb.AppendLine($"{memberIndent}/// <param name=\"receiver\">接收器实现</param>");
        sb.AppendLine($"{memberIndent}/// <returns>订阅令牌，用于取消注册</returns>");
        sb.AppendLine($"{memberIndent}public static ISubscriptionToken RegisterReceiver(");
        sb.AppendLine($"{bodyIndent}this IClientChannel channel,");
        sb.AppendLine($"{bodyIndent}{interfaceFullName} receiver)");
        sb.AppendLine($"{memberIndent}{{");
        sb.AppendLine($"{bodyIndent}var dispatcher = new {dispatcherClassName}(receiver);");
        sb.AppendLine($"{bodyIndent}return dispatcher.RegisterTo(channel);");
        sb.AppendLine($"{memberIndent}}}");

        sb.AppendLine($"{indent}}}");
    }
}
