using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;

namespace PulseRPC.Generator.Generators;

/// <summary>
/// 智能事件处理器生成器 - 生成高性能、智能的事件处理代码
/// </summary>
public static class SmartEventHandlerGenerator
{
    /// <summary>
    /// 生成智能事件处理器
    /// </summary>
    public static string GenerateSmartEventHandler(INamedTypeSymbol interfaceSymbol, SourceProductionContext context)
    {
        var interfaceName = interfaceSymbol.Name;
        var namespaceName = interfaceSymbol.ContainingNamespace.ToDisplayString();
        var handlerClassName = GetHandlerClassName(interfaceName);
        var channelName = GetChannelAttributeValue(interfaceSymbol) ?? "default";

        // 为所有方法生成协议号
        var protocolIds = ProtocolIdGenerator.AssignProtocolIds(interfaceSymbol, context);

        var sb = new StringBuilder();

        // 生成文件头
        GenerateFileHeader(sb);

        // 生成命名空间
        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");

        // 生成智能事件处理器类（只生成特定于此接口的处理器）
        GenerateSmartHandlerClass(sb, interfaceSymbol, handlerClassName, channelName, protocolIds);

        // CompositeSubscriptionToken 已在 PulseRPC.Abstractions 中定义，无需重复生成

        // 结束命名空间
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateFileHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// PulseRPC Smart Event Handler Generator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Concurrent;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Diagnostics;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Channels;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using PulseRPC.Client.Events;");
        sb.AppendLine("using PulseRPC.Client;");
        sb.AppendLine("using PulseRPC;");
        sb.AppendLine();
    }

    private static void GenerateSmartHandlerClass(StringBuilder sb, INamedTypeSymbol interfaceSymbol, string handlerClassName, string channelName, Dictionary<string, ushort> protocolIds)
    {
        var interfaceName = interfaceSymbol.Name;

        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// 智能事件处理器 - 为 {interfaceName} 提供高性能事件处理功能");
        sb.AppendLine($"    /// 使用协议号进行高性能事件路由");
        sb.AppendLine($"    /// </summary>");
        var smartClassName = interfaceSymbol.Name.StartsWith("I")
            ? $"{interfaceSymbol.Name.Substring(1)}SmartHandler"
            : $"{interfaceSymbol.Name}SmartHandler";
        sb.AppendLine($"    public sealed class {smartClassName} : IDisposable");
        sb.AppendLine("    {");
        sb.AppendLine($"        private readonly ConcurrentDictionary<{interfaceName}, SubscriptionContext> _subscriptions = new();");
        sb.AppendLine("        private readonly EventMetrics _metrics = new();");
        sb.AppendLine("        private readonly BatchProcessor _batchProcessor;");
        sb.AppendLine("        private readonly CancellationTokenSource _cancellationTokenSource = new();");
        sb.AppendLine("        private volatile bool _disposed;");
        sb.AppendLine();

        // 生成协议号常量
        GenerateProtocolIdConstants(sb, interfaceSymbol, protocolIds);
        sb.AppendLine();

        sb.AppendLine($"        public {smartClassName}()");
        sb.AppendLine("        {");
        sb.AppendLine("            _batchProcessor = new BatchProcessor(_metrics);");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine($"        internal {smartClassName}(EventMetrics? customMetrics)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (customMetrics != null)");
        sb.AppendLine("            {");
        sb.AppendLine("                _metrics = customMetrics;");
        sb.AppendLine("            }");
        sb.AppendLine("            _batchProcessor = new BatchProcessor(_metrics);");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 生成订阅方法
        GenerateSubscriptionMethods(sb, interfaceSymbol);

        // 生成通道集成方法
        GenerateChannelIntegrationMethods(sb, interfaceSymbol);

        // 生成监控方法
        GenerateMonitoringMethods(sb);

        // 生成配置方法
        GenerateConfigurationMethods(sb, interfaceSymbol);

        // 生成释放方法
        GenerateDisposeMethod(sb);

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateSubscriptionMethods(StringBuilder sb, INamedTypeSymbol interfaceSymbol)
    {
        var interfaceName = interfaceSymbol.Name;

        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// 订阅事件接收器");
        sb.AppendLine($"        /// </summary>");
        sb.AppendLine($"        public void Subscribe({interfaceName} receiver, SmartSubscriptionOptions? options = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            ThrowIfDisposed();");
        sb.AppendLine("            options ??= SmartSubscriptionOptions.Default;");
        sb.AppendLine();
        sb.AppendLine("            var context = new SubscriptionContext(receiver, options, _metrics);");
        sb.AppendLine("            _subscriptions.TryAdd(receiver, context);");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// 取消订阅事件接收器");
        sb.AppendLine($"        /// </summary>");
        sb.AppendLine($"        public bool Unsubscribe({interfaceName} receiver)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_subscriptions.TryRemove(receiver, out var context))");
        sb.AppendLine("            {");
        sb.AppendLine("                context.Dispose();");
        sb.AppendLine("                return true;");
        sb.AppendLine("            }");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// 异步订阅事件接收器");
        sb.AppendLine($"        /// </summary>");
        sb.AppendLine($"        public Task<ISubscriptionToken> SubscribeAsync({interfaceName} receiver, SmartSubscriptionOptions? options = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            Subscribe(receiver, options);");
        sb.AppendLine("            var context = _subscriptions.GetValueOrDefault(receiver);");
        sb.AppendLine("            var token = new SmartSubscriptionToken(null!, context!, () => Unsubscribe(receiver));");
        sb.AppendLine("            return Task.FromResult<ISubscriptionToken>(token);");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 为每个接口方法生成智能分发方法
        foreach (var member in interfaceSymbol.GetMembers())
        {
            if (member is IMethodSymbol methodSymbol && methodSymbol.DeclaredAccessibility == Accessibility.Public)
            {
                GenerateSmartDispatchMethod(sb, methodSymbol, interfaceName);
            }
        }
    }

    private static void GenerateSmartDispatchMethod(StringBuilder sb, IMethodSymbol methodSymbol, string interfaceName)
    {
        var methodName = methodSymbol.Name;
        var returnType = methodSymbol.ReturnType.ToDisplayString();
        var isAsync = IsAsyncMethod(methodSymbol);
        var parameters = methodSymbol.Parameters;

        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// 智能分发 {methodName} 事件");
        sb.AppendLine($"        /// </summary>");
        sb.Append($"        public async Task Dispatch{methodName}Async(");

        // 生成参数列表
        for (var i = 0; i < parameters.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append($"{parameters[i].Type.ToDisplayString()} {parameters[i].Name}");
        }

        sb.AppendLine(")");
        sb.AppendLine("        {");
        sb.AppendLine("            ThrowIfDisposed();");
        sb.AppendLine($"            _metrics.RecordEventReceived(\"{methodName}\");");
        sb.AppendLine();

        sb.AppendLine("            var tasks = new List<Task>();");
        sb.AppendLine("            ");
        sb.AppendLine("            foreach (var kvp in _subscriptions)");
        sb.AppendLine("            {");
        sb.AppendLine("                var receiver = kvp.Key;");
        sb.AppendLine("                var context = kvp.Value;");
        sb.AppendLine();

        var parameterNames = string.Join(", ", parameters.Select(p => p.Name));

        if (isAsync)
        {
            sb.AppendLine("                if (context.Options.EnableBatchProcessing)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    await _batchProcessor.QueueEventAsync(\"{methodName}\", new object[] {{ {parameterNames} }}, ");
            sb.AppendLine($"                        async data => ");
            sb.AppendLine("                        {");
            sb.AppendLine("                            var args = (object[])data;");
            for (int i = 0; i < parameters.Length; i++)
            {
                sb.AppendLine($"                            var param{i} = ({parameters[i].Type.ToDisplayString()})args[{i}];");
            }
            var typedParams = string.Join(", ", Enumerable.Range(0, parameters.Length).Select(i => $"param{i}"));
            sb.AppendLine($"                            var monitoredReceiver = new MonitoredEventReceiver<{interfaceName}>(receiver, context);");
            sb.AppendLine($"                            await monitoredReceiver.InvokeMethodAsync(\"{methodName}\", r => r.{methodName}({typedParams}));");
            sb.AppendLine("                        });");
            sb.AppendLine("                }");
            sb.AppendLine("                else");
            sb.AppendLine("                {");
            sb.AppendLine($"                    var monitoredReceiver = new MonitoredEventReceiver<{interfaceName}>(receiver, context);");
            sb.AppendLine($"                    tasks.Add(monitoredReceiver.InvokeMethodAsync(\"{methodName}\", r => r.{methodName}({parameterNames})));");
            sb.AppendLine("                }");
        }
        else
        {
            sb.AppendLine($"                var monitoredReceiver = new MonitoredEventReceiver<{interfaceName}>(receiver, context);");
            sb.AppendLine($"                tasks.Add(Task.Run(async () => await monitoredReceiver.InvokeMethodAsync(\"{methodName}\", r => Task.Run(() => r.{methodName}({parameterNames})))));");
        }

        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            if (tasks.Count > 0)");
        sb.AppendLine("            {");
        sb.AppendLine("                await Task.WhenAll(tasks);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GenerateChannelIntegrationMethods(StringBuilder sb, INamedTypeSymbol interfaceSymbol)
    {
        var interfaceName = interfaceSymbol.Name;

        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// 连接到 IClientChannel 并订阅所有事件");
        sb.AppendLine($"        /// </summary>");
        sb.AppendLine($"        public async Task<ISubscriptionToken> ConnectToChannelAsync(PulseRPC.Client.IClientChannel channel)");
        sb.AppendLine("        {");
        sb.AppendLine("            ThrowIfDisposed();");
        sb.AppendLine("            var tokens = new List<ISubscriptionToken>();");
        sb.AppendLine();

        // 为每个接口方法生成通道订阅
        foreach (var member in interfaceSymbol.GetMembers())
        {
            if (member is IMethodSymbol methodSymbol && methodSymbol.DeclaredAccessibility == Accessibility.Public)
            {
                GenerateChannelEventSubscription(sb, methodSymbol, interfaceName);
            }
        }

        sb.AppendLine("            // 返回复合订阅令牌");
        sb.AppendLine("            return new CompositeSubscriptionToken(tokens);");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 为每个接口方法生成智能分发方法（用于从通道事件调用）
        foreach (var member in interfaceSymbol.GetMembers())
        {
            if (member is IMethodSymbol methodSymbol && methodSymbol.DeclaredAccessibility == Accessibility.Public)
            {
                GenerateChannelDispatchMethod(sb, methodSymbol, interfaceName);
            }
        }
    }

    private static void GenerateChannelEventSubscription(StringBuilder sb, IMethodSymbol methodSymbol, string interfaceName)
    {
        var methodName = methodSymbol.Name;
        var parameters = methodSymbol.Parameters;
        var constName = ProtocolIdGenerator.GetProtocolIdConstantName(methodSymbol);

        // 确定事件数据类型
        string eventDataType;
        if (parameters.Length == 0)
        {
            eventDataType = "object";
        }
        else if (parameters.Length == 1)
        {
            eventDataType = parameters[0].Type.ToDisplayString();
        }
        else
        {
            // 多个参数时创建一个包装类型名称 (元组)
            eventDataType = "(" + string.Join(", ", parameters.Select(p => p.Type.ToDisplayString())) + ")";
        }

        sb.AppendLine($"            // ========== 零拷贝优化路径：Server Sent Event ==========");
        sb.AppendLine($"            // 订阅 {methodName} 事件（使用协议号，零拷贝反序列化）");
        sb.AppendLine($"            // Protocol ID: {constName}");
        sb.AppendLine($"            tokens.Add(channel.RegisterEventHandler(");
        sb.AppendLine($"                protocolId: {constName},");
        sb.AppendLine($"                deserializeAndInvoke: (System.ReadOnlyMemory<byte> __rawEventData__) =>");
        sb.AppendLine($"                {{");
        sb.AppendLine($"                    // 显式反序列化（编译时已知类型）");
        sb.AppendLine($"                    var __eventData__ = MemoryPack.MemoryPackSerializer.Deserialize<{eventDataType}>(__rawEventData__.Span)!;");
        sb.AppendLine($"                    // 调用分发方法");
        sb.AppendLine($"                    _ = Dispatch{methodName}FromChannelAsync(__eventData__);");
        sb.AppendLine($"                }}));");
        sb.AppendLine();
    }

    private static void GenerateChannelDispatchMethod(StringBuilder sb, IMethodSymbol methodSymbol, string interfaceName)
    {
        var methodName = methodSymbol.Name;
        var parameters = methodSymbol.Parameters;

        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// 从通道分发 {methodName} 事件到智能处理器（零拷贝优化）");
        sb.AppendLine($"        /// </summary>");

        // 确定参数类型和处理方式
        if (parameters.Length == 0)
        {
            sb.AppendLine($"        private async Task Dispatch{methodName}FromChannelAsync(object eventData)");
            sb.AppendLine("        {");
            sb.AppendLine($"            await Dispatch{methodName}Async();");
            sb.AppendLine("        }");
        }
        else if (parameters.Length == 1)
        {
            var paramType = parameters[0].Type.ToDisplayString();
            var paramName = parameters[0].Name;
            sb.AppendLine($"        private async Task Dispatch{methodName}FromChannelAsync({paramType} {paramName})");
            sb.AppendLine("        {");
            sb.AppendLine($"            await Dispatch{methodName}Async({paramName});");
            sb.AppendLine("        }");
        }
        else
        {
            // 多个参数的情况下，使用元组解构
            var tupleType = "(" + string.Join(", ", parameters.Select(p => p.Type.ToDisplayString())) + ")";
            sb.AppendLine($"        private async Task Dispatch{methodName}FromChannelAsync({tupleType} eventData)");
            sb.AppendLine("        {");
            sb.Append($"            await Dispatch{methodName}Async(");

            // 生成参数列表（从元组解构）
            for (var i = 0; i < parameters.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append($"eventData.Item{i + 1}");
            }

            sb.AppendLine(");");
            sb.AppendLine("        }");
        }
        sb.AppendLine();
    }

    private static void GenerateMonitoringMethods(StringBuilder sb)
    {
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 获取性能监控指标");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public EventHandlerMetrics GetMetrics()");
        sb.AppendLine("        {");
        sb.AppendLine("            return _metrics.GetSnapshot();");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GenerateConfigurationMethods(StringBuilder sb, INamedTypeSymbol interfaceSymbol)
    {
        var interfaceName = interfaceSymbol.Name;

        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 获取活跃订阅数量");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public int ActiveSubscriptionCount => _subscriptions.Count;");
        sb.AppendLine();

        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 获取所有活跃的订阅者");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public IReadOnlyList<{interfaceName}> GetActiveSubscribers()");
        sb.AppendLine("        {");
        sb.AppendLine("            return _subscriptions.Keys.ToList();");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GenerateDisposeMethod(StringBuilder sb)
    {
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 释放资源");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public void Dispose()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_disposed) return;");
        sb.AppendLine("            ");
        sb.AppendLine("            _cancellationTokenSource.Cancel();");
        sb.AppendLine("            ");
        sb.AppendLine("            // 取消所有订阅");
        sb.AppendLine("            foreach (var context in _subscriptions.Values)");
        sb.AppendLine("            {");
        sb.AppendLine("                context.Dispose();");
        sb.AppendLine("            }");
        sb.AppendLine("            _subscriptions.Clear();");
        sb.AppendLine("            ");
        sb.AppendLine("            _batchProcessor.Dispose();");
        sb.AppendLine("            _cancellationTokenSource.Dispose();");
        sb.AppendLine("            _disposed = true;");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private void ThrowIfDisposed()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_disposed)");
        sb.AppendLine("                throw new ObjectDisposedException(GetType().Name);");
        sb.AppendLine("        }");
        sb.AppendLine();
    }


    // 辅助方法
    private static string GetHandlerClassName(string interfaceName)
    {
        return interfaceName.StartsWith("I")
            ? interfaceName.Substring(1) + "Handler"
            : interfaceName + "Handler";
    }

    /// <summary>
    /// 生成协议号常量
    /// </summary>
    private static void GenerateProtocolIdConstants(StringBuilder sb, INamedTypeSymbol interfaceSymbol, Dictionary<string, ushort> protocolIds)
    {
        sb.AppendLine("        // ==================== 事件协议号常量 ====================");
        sb.AppendLine("        // 使用 FNV-1a 哈希算法生成，确保客户端和服务端一致");

        foreach (var member in interfaceSymbol.GetMembers())
        {
            if (member is not IMethodSymbol methodSymbol)
                continue;

            if (methodSymbol.DeclaredAccessibility != Accessibility.Public)
                continue;

            // 使用完整键格式: {InterfaceFullName}.{MethodName}
            var methodKey = $"{methodSymbol.ContainingType.ToDisplayString()}.{methodSymbol.Name}";
            if (protocolIds.TryGetValue(methodKey, out var protocolId))
            {
                var methodSignature = ProtocolIdGenerator.BuildMethodSignature(methodSymbol);
                var constName = ProtocolIdGenerator.GetProtocolIdConstantName(methodSymbol);

                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// 协议号: {methodSymbol.Name}");
                sb.AppendLine($"        /// 方法签名: {methodSignature}");
                sb.AppendLine($"        /// </summary>");
                sb.AppendLine($"        private const ushort {constName} = 0x{protocolId:X4}; // {protocolId}");
            }
        }
    }

    private static string? GetChannelAttributeValue(ISymbol symbol)
    {
        foreach (var attribute in symbol.GetAttributes())
        {
            if (attribute.AttributeClass?.Name is "ChannelAttribute" or "Channel")
            {
                if (attribute.ConstructorArguments.Length > 0 &&
                    attribute.ConstructorArguments[0].Value is string channelName)
                {
                    return channelName;
                }
            }
        }
        return null;
    }

    private static bool IsAsyncMethod(IMethodSymbol methodSymbol)
    {
        var returnTypeName = methodSymbol.ReturnType.ToDisplayString();
        return returnTypeName.StartsWith("System.Threading.Tasks.Task") ||
               returnTypeName.StartsWith("Task") ||
               returnTypeName.StartsWith("System.Threading.Tasks.ValueTask") ||
               returnTypeName.StartsWith("ValueTask");
    }
}
