using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace PulseRPC.Generator.Generators;

/// <summary>
/// 生成 ITransportChannel 的扩展方法，支持双向 RPC
/// - GetHubAsync<T>(): 获取远程 Hub 的代理
/// - RegisterHub<T>(impl): 注册本地 Hub 供远程调用
/// </summary>
public static class TransportChannelExtensionsGenerator
{
    /// <summary>
    /// 生成 ITransportChannel 扩展方法
    /// </summary>
    /// <param name="hubTypes">Hub 类型列表</param>
    /// <param name="channelNames">配置的 Channel 名称列表（来自 MSBuild 配置）</param>
    public static string GenerateExtensions(ImmutableArray<INamedTypeSymbol> hubTypes, string[] channelNames)
    {
        var sb = new StringBuilder();

        GenerateFileHeader(sb);
        GenerateGetHubAsyncExtensions(sb, hubTypes);
        GenerateChannelSpecificGetHubAsyncExtensions(sb, hubTypes, channelNames);
        GenerateRegisterHubExtensions(sb, hubTypes);
        GenerateChannelSpecificRegisterHubExtensions(sb, hubTypes, channelNames);

        return sb.ToString();
    }

    private static void GenerateFileHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// ITransportChannel Bidirectional RPC Extensions");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using PulseRPC;");
        sb.AppendLine("using PulseRPC.Channels;");
        sb.AppendLine();
    }

    private static void GenerateGetHubAsyncExtensions(StringBuilder sb, ImmutableArray<INamedTypeSymbol> hubTypes)
    {
        sb.AppendLine("namespace PulseRPC.Channels");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// ITransportChannel 扩展方法 - 双向 RPC 支持");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static partial class TransportChannelExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        #region GetHubAsync - 获取远程 Hub 代理");
        sb.AppendLine();

        // 生成通用的 GetHubAsync<T> 方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 获取远程 Hub 代理的通用方法（类型分发）");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static Task<THub> GetHubAsync<THub>(this ITransportChannel channel)");
        sb.AppendLine("            where THub : class, IPulseHub");
        sb.AppendLine("        {");
        sb.AppendLine("            if (channel == null) throw new ArgumentNullException(nameof(channel));");
        sb.AppendLine();
        sb.AppendLine("            var hubType = typeof(THub);");
        sb.AppendLine();

        // 为每个 Hub 类型生成类型检查和代理创建逻辑
        foreach (var hubType in hubTypes)
        {
            if (hubType == null) continue;

            var interfaceName = hubType.Name;
            if (string.IsNullOrEmpty(interfaceName)) continue;

            var fullTypeName = GetFullTypeName(hubType);
            if (string.IsNullOrEmpty(fullTypeName)) continue;

            var proxyTypeName = $"{fullTypeName}Proxy";

            sb.AppendLine($"            // 检查是否请求 {interfaceName} Hub");
            sb.AppendLine($"            if (hubType == typeof({fullTypeName}))");
            sb.AppendLine("            {");
            sb.AppendLine($"                // 需要 IClientChannel 来创建代理");
            sb.AppendLine($"                if (channel is not PulseRPC.Client.IClientChannel clientChannel)");
            sb.AppendLine($"                    throw new InvalidOperationException(\"Channel must implement IClientChannel to create Hub proxies\");");
            sb.AppendLine($"                var proxy = new {proxyTypeName}(clientChannel);");
            sb.AppendLine($"                return Task.FromResult((THub)(object)proxy);");
            sb.AppendLine("            }");
            sb.AppendLine();
        }

        // 如果没有匹配的类型，抛出异常
        sb.AppendLine("            throw new ArgumentException($\"不支持的 Hub 类型: {hubType.Name}。请确保 Hub 接口已使用 [PulseClientGeneration] 特性注册。\", nameof(THub));");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        #endregion");
        sb.AppendLine();
    }

    private static void GenerateRegisterHubExtensions(StringBuilder sb, ImmutableArray<INamedTypeSymbol> hubTypes)
    {
        sb.AppendLine("        #region RegisterHub - 注册本地 Hub 实现");
        sb.AppendLine();

        // 生成通用的 RegisterHub<T> 方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 注册本地 Hub 实现的通用方法（类型分发）");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static IHubRegistrationToken RegisterHub<THub>(this ITransportChannel channel, THub implementation)");
        sb.AppendLine("            where THub : class, IPulseHub");
        sb.AppendLine("        {");
        sb.AppendLine("            if (channel == null) throw new ArgumentNullException(nameof(channel));");
        sb.AppendLine("            if (implementation == null) throw new ArgumentNullException(nameof(implementation));");
        sb.AppendLine();
        sb.AppendLine("            var hubType = typeof(THub);");
        sb.AppendLine("            var hubName = hubType.Name;");
        sb.AppendLine();

        // 为每个 Hub 类型生成类型检查和服务处理器注册逻辑
        foreach (var hubType in hubTypes)
        {
            if (hubType == null) continue;

            var interfaceName = hubType.Name;
            if (string.IsNullOrEmpty(interfaceName)) continue;

            var fullTypeName = GetFullTypeName(hubType);
            if (string.IsNullOrEmpty(fullTypeName)) continue;

            var handlerTypeName = $"{fullTypeName}ServiceHandler";

            sb.AppendLine($"            // 检查是否注册 {interfaceName} Hub");
            sb.AppendLine($"            if (hubType == typeof({fullTypeName}))");
            sb.AppendLine("            {");
            sb.AppendLine($"                var typedImpl = implementation as {fullTypeName}");
            sb.AppendLine($"                    ?? throw new ArgumentException($\"Implementation must be of type {fullTypeName}\", nameof(implementation));");
            sb.AppendLine($"                var handler = new {handlerTypeName}(typedImpl);");
            sb.AppendLine($"                var disposable = channel.RegisterServiceHandler(\"{interfaceName}\", handler);");
            sb.AppendLine($"                return new HubRegistrationToken(typeof({fullTypeName}), \"{interfaceName}\", () => disposable.Dispose());");
            sb.AppendLine("            }");
            sb.AppendLine();
        }

        // 如果没有匹配的类型，抛出异常
        sb.AppendLine("            throw new ArgumentException($\"不支持的 Hub 类型: {hubType.Name}。请确保 Hub 接口已使用 [PulseClientGeneration] 特性注册。\", nameof(THub));");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        #endregion");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    /// <summary>
    /// 生成 Channel 特定的 GetHubAsync 扩展方法
    /// 例如：Get{ChannelName}HubAsync<THub>()
    /// </summary>
    private static void GenerateChannelSpecificGetHubAsyncExtensions(StringBuilder sb, ImmutableArray<INamedTypeSymbol> hubTypes, string[] channelNames)
    {
        if (channelNames == null || channelNames.Length == 0)
            return;

        // 按 Channel 分组 Hub 类型
        var hubsByChannel = new Dictionary<string, List<INamedTypeSymbol>>();

        foreach (var hubType in hubTypes)
        {
            if (hubType == null) continue;

            var channelName = GetChannelName(hubType);
            if (!hubsByChannel.ContainsKey(channelName))
            {
                hubsByChannel[channelName] = new List<INamedTypeSymbol>();
            }
            hubsByChannel[channelName].Add(hubType);
        }

        sb.AppendLine("namespace PulseRPC.Channels");
        sb.AppendLine("{");
        sb.AppendLine("    public static partial class TransportChannelExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        #region Channel-Specific GetHubAsync Methods");
        sb.AppendLine();

        // 为每个配置的 Channel 生成特定的扩展方法
        foreach (var channelName in channelNames)
        {
            if (!hubsByChannel.TryGetValue(channelName, out var channelHubs) || channelHubs.Count == 0)
                continue;

            var methodName = $"Get{ToPascalCase(channelName)}HubAsync";

            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 获取 {channelName} Channel 的远程 Hub 代理");
            sb.AppendLine($"        /// 仅支持标记为 [Channel(\"{channelName}\")] 的 Hub 接口");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        public static Task<THub> {methodName}<THub>(this ITransportChannel channel)");
            sb.AppendLine($"            where THub : class, IPulseHub");
            sb.AppendLine("        {");
            sb.AppendLine("            if (channel == null) throw new ArgumentNullException(nameof(channel));");
            sb.AppendLine();
            sb.AppendLine("            var hubType = typeof(THub);");
            sb.AppendLine();

            // 为该 Channel 的每个 Hub 类型生成类型检查和代理创建逻辑
            foreach (var hubType in channelHubs)
            {
                var interfaceName = hubType.Name;
                if (string.IsNullOrEmpty(interfaceName)) continue;

                var fullTypeName = GetFullTypeName(hubType);
                if (string.IsNullOrEmpty(fullTypeName)) continue;

                var proxyTypeName = $"{fullTypeName}Proxy";

                sb.AppendLine($"            // {interfaceName}");
                sb.AppendLine($"            if (hubType == typeof({fullTypeName}))");
                sb.AppendLine("            {");
                sb.AppendLine($"                if (channel is not PulseRPC.Client.IClientChannel clientChannel)");
                sb.AppendLine($"                    throw new InvalidOperationException(\"Channel must implement IClientChannel to create Hub proxies\");");
                sb.AppendLine($"                var proxy = new {proxyTypeName}(clientChannel);");
                sb.AppendLine($"                return Task.FromResult((THub)(object)proxy);");
                sb.AppendLine("            }");
                sb.AppendLine();
            }

            sb.AppendLine($"            throw new ArgumentException($\"不支持的 Hub 类型: {{hubType.Name}}。此方法仅支持 {channelName} Channel 的 Hub 接口。\", nameof(THub));");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine("        #endregion");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    /// <summary>
    /// 生成 Channel 特定的 RegisterHub 扩展方法
    /// 例如：Register{ChannelName}Hub<THub>(impl)
    /// </summary>
    private static void GenerateChannelSpecificRegisterHubExtensions(StringBuilder sb, ImmutableArray<INamedTypeSymbol> hubTypes, string[] channelNames)
    {
        if (channelNames == null || channelNames.Length == 0)
            return;

        // 按 Channel 分组 Hub 类型
        var hubsByChannel = new Dictionary<string, List<INamedTypeSymbol>>();

        foreach (var hubType in hubTypes)
        {
            if (hubType == null) continue;

            var channelName = GetChannelName(hubType);
            if (!hubsByChannel.ContainsKey(channelName))
            {
                hubsByChannel[channelName] = new List<INamedTypeSymbol>();
            }
            hubsByChannel[channelName].Add(hubType);
        }

        sb.AppendLine("namespace PulseRPC.Channels");
        sb.AppendLine("{");
        sb.AppendLine("    public static partial class TransportChannelExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        #region Channel-Specific RegisterHub Methods");
        sb.AppendLine();

        // 为每个配置的 Channel 生成特定的扩展方法
        foreach (var channelName in channelNames)
        {
            if (!hubsByChannel.TryGetValue(channelName, out var channelHubs) || channelHubs.Count == 0)
                continue;

            var methodName = $"Register{ToPascalCase(channelName)}Hub";

            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 注册 {channelName} Channel 的本地 Hub 实现");
            sb.AppendLine($"        /// 仅支持标记为 [Channel(\"{channelName}\")] 的 Hub 接口");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        public static IHubRegistrationToken {methodName}<THub>(this ITransportChannel channel, THub implementation)");
            sb.AppendLine($"            where THub : class, IPulseHub");
            sb.AppendLine("        {");
            sb.AppendLine("            if (channel == null) throw new ArgumentNullException(nameof(channel));");
            sb.AppendLine("            if (implementation == null) throw new ArgumentNullException(nameof(implementation));");
            sb.AppendLine();
            sb.AppendLine("            var hubType = typeof(THub);");
            sb.AppendLine("            var hubName = hubType.Name;");
            sb.AppendLine();

            // 为该 Channel 的每个 Hub 类型生成类型检查和服务处理器注册逻辑
            foreach (var hubType in channelHubs)
            {
                var interfaceName = hubType.Name;
                if (string.IsNullOrEmpty(interfaceName)) continue;

                var fullTypeName = GetFullTypeName(hubType);
                if (string.IsNullOrEmpty(fullTypeName)) continue;

                var handlerTypeName = $"{fullTypeName}ServiceHandler";

                sb.AppendLine($"            // {interfaceName}");
                sb.AppendLine($"            if (hubType == typeof({fullTypeName}))");
                sb.AppendLine("            {");
                sb.AppendLine($"                var typedImpl = implementation as {fullTypeName}");
                sb.AppendLine($"                    ?? throw new ArgumentException($\"Implementation must be of type {fullTypeName}\", nameof(implementation));");
                sb.AppendLine($"                var handler = new {handlerTypeName}(typedImpl);");
                sb.AppendLine($"                var disposable = channel.RegisterServiceHandler(\"{interfaceName}\", handler);");
                sb.AppendLine($"                return new HubRegistrationToken(typeof({fullTypeName}), \"{interfaceName}\", () => disposable.Dispose());");
                sb.AppendLine("            }");
                sb.AppendLine();
            }

            sb.AppendLine($"            throw new ArgumentException($\"不支持的 Hub 类型: {{hubType.Name}}。此方法仅支持 {channelName} Channel 的 Hub 接口。\", nameof(THub));");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine("        #endregion");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    /// <summary>
    /// 从接口获取 Channel 名称
    /// </summary>
    private static string GetChannelName(INamedTypeSymbol interfaceSymbol)
    {
        var channelAttr = interfaceSymbol.GetAttributes()
            .FirstOrDefault(attr => attr.AttributeClass?.Name is "ChannelAttribute" or "Channel");

        if (channelAttr?.ConstructorArguments.Length > 0)
        {
            var channelName = channelAttr.ConstructorArguments[0].Value?.ToString();
            if (!string.IsNullOrWhiteSpace(channelName))
            {
                return channelName!;
            }
        }

        return "default";
    }

    /// <summary>
    /// 将字符串转换为 PascalCase（首字母大写）
    /// </summary>
    private static string ToPascalCase(string input)
    {
        if (string.IsNullOrEmpty(input))
            return input;

        // 简单实现：首字母大写，其余保持不变
        return char.ToUpperInvariant(input[0]) + input.Substring(1);
    }

    private static string GetFullTypeName(INamedTypeSymbol typeSymbol)
    {
        if (typeSymbol.ContainingNamespace.IsGlobalNamespace)
        {
            return typeSymbol.Name;
        }

        return $"{typeSymbol.ContainingNamespace.ToDisplayString()}.{typeSymbol.Name}";
    }
}
