using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace PulseRPC.Generator.Generators;

/// <summary>
/// 统一接收器注册生成器 - 生成 RegisterAllReceivers 扩展方法
/// </summary>
/// <remarks>
/// 为每个项目生成一个统一的扩展方法，可以自动注册对象实现的所有 IPulseReceiver 接口。
/// <code>
/// // 生成的代码允许一行注册所有接收器
/// var tokens = channel.RegisterAllReceivers(eventHandler);
/// </code>
/// </remarks>
public static class UnifiedReceiverRegistrationGenerator
{
    /// <summary>
    /// 生成统一注册扩展方法
    /// </summary>
    /// <param name="receiverInterfaces">项目中所有的 IPulseReceiver 接口</param>
    /// <returns>生成的代码</returns>
    public static string Generate(IEnumerable<INamedTypeSymbol> receiverInterfaces)
    {
        var interfaces = receiverInterfaces.ToList();
        if (interfaces.Count == 0)
            return string.Empty;

        var sb = new StringBuilder();

        GenerateFileHeader(sb);
        GenerateUsingStatements(sb, interfaces);

        sb.AppendLine("namespace PulseRPC.Client");
        sb.AppendLine("{");

        GenerateExtensionClass(sb, interfaces);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateFileHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This code was generated by PulseRPC.Client.SourceGenerator");
        sb.AppendLine("// Unified receiver registration extensions");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
    }

    private static void GenerateUsingStatements(StringBuilder sb, List<INamedTypeSymbol> interfaces)
    {
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using PulseRPC;");
        sb.AppendLine("using PulseRPC.Client;");
        sb.AppendLine();

        // 添加所有接口的命名空间
        var namespaces = interfaces
            .Select(i => i.ContainingNamespace.ToDisplayString())
            .Distinct()
            .OrderBy(ns => ns);

        foreach (var ns in namespaces)
        {
            sb.AppendLine($"using {ns};");
        }
        sb.AppendLine();
    }

    private static void GenerateExtensionClass(StringBuilder sb, List<INamedTypeSymbol> interfaces)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 统一接收器注册扩展方法");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <remarks>");
        sb.AppendLine("    /// <para>");
        sb.AppendLine("    /// 自动检测并注册对象实现的所有 IPulseReceiver 接口。");
        sb.AppendLine("    /// </para>");
        sb.AppendLine("    /// <code>");
        sb.AppendLine("    /// // 一行代码注册所有接收器");
        sb.AppendLine("    /// var tokens = channel.RegisterAllReceivers(eventHandler);");
        sb.AppendLine("    /// </code>");
        sb.AppendLine("    /// </remarks>");
        sb.AppendLine("    public static class UnifiedReceiverExtensions");
        sb.AppendLine("    {");

        // 生成泛型 RegisterAllReceivers<T> 方法
        GenerateGenericRegisterAllMethod(sb, interfaces);

        sb.AppendLine("    }");
    }

    private static void GenerateGenericRegisterAllMethod(StringBuilder sb, List<INamedTypeSymbol> interfaces)
    {
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 注册对象实现的所有 IPulseReceiver 接口");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <typeparam name=\"T\">实现了一个或多个 IPulseReceiver 接口的类型</typeparam>");
        sb.AppendLine("        /// <param name=\"channel\">客户端通道</param>");
        sb.AppendLine("        /// <param name=\"receiver\">接收器实现对象</param>");
        sb.AppendLine("        /// <returns>所有注册的订阅令牌列表</returns>");
        sb.AppendLine("        public static List<ISubscriptionToken> RegisterAllReceivers<T>(");
        sb.AppendLine("            this IClientChannel channel,");
        sb.AppendLine("            T receiver) where T : class, IPulseReceiver");
        sb.AppendLine("        {");
        sb.AppendLine("            var tokens = new List<ISubscriptionToken>();");
        sb.AppendLine();

        // 为每个接口生成类型检查和注册
        foreach (var iface in interfaces)
        {
            var fullName = iface.ToDisplayString();
            var shortName = iface.Name;

            sb.AppendLine($"            // 检查并注册 {shortName}");
            sb.AppendLine($"            if (receiver is {fullName} {GetVariableName(shortName)})");
            sb.AppendLine("            {");
            sb.AppendLine($"                tokens.Add(channel.RegisterReceiver({GetVariableName(shortName)}));");
            sb.AppendLine("            }");
            sb.AppendLine();
        }

        sb.AppendLine("            return tokens;");
        sb.AppendLine("        }");
    }

    private static string GetVariableName(string interfaceName)
    {
        // IPlayerReceiver -> playerReceiver
        var name = interfaceName.StartsWith("I") ? interfaceName.Substring(1) : interfaceName;
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }
}

