using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace PulseRPC.Generator.Generators;

/// <summary>
/// 统一接收器注册生成器 - 生成 RegisterAllReceivers 扩展方法
/// 允许一行代码注册对象实现的所有 IPulseReceiver 接口
/// </summary>
public static class UnifiedReceiverRegistrationGenerator
{
    /// <summary>
    /// 生成统一接收器注册扩展方法
    /// </summary>
    public static string Generate(ImmutableArray<INamedTypeSymbol> receiverTypes)
    {
        if (receiverTypes.Length == 0)
            return string.Empty;

        var sb = new StringBuilder();

        // 文件头
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This code was generated by PulseRPC.Client.SourceGenerator");
        sb.AppendLine("// Unified receiver registration extensions");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using PulseRPC;");
        sb.AppendLine("using PulseRPC.Client;");

        // 收集所有需要的命名空间
        var namespaces = receiverTypes
            .Where(t => !t.ContainingNamespace.IsGlobalNamespace)
            .Select(t => t.ContainingNamespace.ToDisplayString())
            .Distinct()
            .OrderBy(ns => ns);

        foreach (var ns in namespaces)
        {
            sb.AppendLine($"using {ns};");
        }

        sb.AppendLine();
        sb.AppendLine("namespace PulseRPC.Client");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 统一接收器注册扩展方法");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class UnifiedReceiverRegistrationExtensions");
        sb.AppendLine("    {");

        // 生成泛型的 RegisterAllReceivers 方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 注册对象实现的所有 IPulseReceiver 接口");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <typeparam name=\"T\">接收器类型</typeparam>");
        sb.AppendLine("        /// <param name=\"channel\">客户端通道</param>");
        sb.AppendLine("        /// <param name=\"receiver\">接收器实例</param>");
        sb.AppendLine("        /// <returns>所有订阅令牌的列表</returns>");
        sb.AppendLine("        public static List<ISubscriptionToken> RegisterAllReceivers<T>(");
        sb.AppendLine("            this IClientChannel channel,");
        sb.AppendLine("            T receiver) where T : class");
        sb.AppendLine("        {");
        sb.AppendLine("            if (channel == null) throw new ArgumentNullException(nameof(channel));");
        sb.AppendLine("            if (receiver == null) throw new ArgumentNullException(nameof(receiver));");
        sb.AppendLine();
        sb.AppendLine("            var tokens = new List<ISubscriptionToken>();");
        sb.AppendLine();

        // 为每个接收器类型生成类型检查和注册
        foreach (var receiverType in receiverTypes)
        {
            var fullTypeName = receiverType.ToDisplayString();
            var dispatcherClassName = GetDispatcherClassName(receiverType);
            var dispatcherFullName = GetDispatcherFullName(receiverType, dispatcherClassName);

            sb.AppendLine($"            // 检查并注册 {fullTypeName}");
            sb.AppendLine($"            if (receiver is {fullTypeName} {GetSafeVariableName(receiverType)}Impl)");
            sb.AppendLine("            {");
            sb.AppendLine($"                var dispatcher = new {dispatcherFullName}({GetSafeVariableName(receiverType)}Impl);");
            sb.AppendLine("                tokens.Add(dispatcher.RegisterTo(channel));");
            sb.AppendLine("            }");
            sb.AppendLine();
        }

        sb.AppendLine("            return tokens;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GetDispatcherClassName(INamedTypeSymbol interfaceSymbol)
    {
        var name = interfaceSymbol.Name;
        return name.StartsWith("I") && name.Length > 1 && char.IsUpper(name[1])
            ? name.Substring(1) + "Dispatcher"
            : name + "Dispatcher";
    }

    private static string GetDispatcherFullName(INamedTypeSymbol interfaceSymbol, string dispatcherClassName)
    {
        if (interfaceSymbol.ContainingNamespace.IsGlobalNamespace)
        {
            return dispatcherClassName;
        }
        return $"{interfaceSymbol.ContainingNamespace.ToDisplayString()}.{dispatcherClassName}";
    }

    private static string GetSafeVariableName(INamedTypeSymbol interfaceSymbol)
    {
        var name = interfaceSymbol.Name;
        // 去掉 I 前缀并转为小写开头
        if (name.StartsWith("I") && name.Length > 1 && char.IsUpper(name[1]))
        {
            name = name.Substring(1);
        }
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }
}
