<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../GameServer.Contracts/GameServer.Contracts.csproj" />
    <ProjectReference Include="../../../src/PulseRPC.Server/PulseRPC.Server.csproj" />
    <ProjectReference Include="../../../src/PulseRPC.Client/PulseRPC.Client.csproj" />
    <ProjectReference Include="../../../src/PulseRPC.Backplane.Redis/PulseRPC.Backplane.Redis.csproj" />
    <ProjectReference Include="../../../src/PulseRPC.Server.SourceGenerator/PulseRPC.Server.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../../src/PulseRPC.Client.SourceGenerator/PulseRPC.Client.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>
</Project>
