using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace PulseRPC.Client.SourceGenerator;

[Generator]
public class MessageRegistrationGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        // 注册语法接收器
        context.RegisterForSyntaxNotifications(() => new MessageAttributeReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        // 获取语法接收器
        if (context.SyntaxContextReceiver is not MessageAttributeReceiver receiver)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor(
                    "PRPC001",
                    "消息注册生成器初始化失败",
                    "无法获取语法接收器",
                    "PulseRPC",
                    DiagnosticSeverity.Warning,
                    true),
                Location.None));
            return;
        }

        // 输出编译单元信息
        foreach (var tree in context.Compilation.SyntaxTrees)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor(
                    "PRPC008",
                    "编译单元",
                    "正在处理编译单元: {0}",
                    "PulseRPC",
                    DiagnosticSeverity.Info,
                    true),
                Location.None,
                tree.FilePath));
        }

        // 输出引用信息
        foreach (var reference in context.Compilation.References)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor(
                    "PRPC009",
                    "程序集引用",
                    "项目引用: {0}",
                    "PulseRPC",
                    DiagnosticSeverity.Info,
                    true),
                Location.None,
                reference.Display));
        }

        if (!receiver.MessageTypes.Any())
        {
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor(
                    "PRPC002",
                    "未找到任何消息类型",
                    "在编译单元中未找到任何带有MessageAttribute的消息类型",
                    "PulseRPC",
                    DiagnosticSeverity.Warning,
                    true),
                Location.None));
        }

        // 生成注册代码
        var source = GenerateRegistrationCode(receiver.MessageTypes);
        context.AddSource("MessageRegistration.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private string GenerateRegistrationCode(IEnumerable<(INamedTypeSymbol Type, int MessageId)> messageTypes)
    {
        var builder = new StringBuilder();
        builder.AppendLine(@"// <auto-generated/>
using System.Runtime.CompilerServices;
using PulseRPC.Protocol;

namespace PulseRPC.Client;

/// <summary>
/// 自动生成的消息注册类
/// </summary>
internal static class PulseRPCMessageRegistration
{
    /// <summary>
    /// 模块初始化器，程序集加载时自动执行
    /// </summary>
    [ModuleInitializer]
    internal static void Initialize()
    {
        RegisterAllMessages();
    }

    /// <summary>
    /// 注册所有消息类型
    /// </summary>
    private static void RegisterAllMessages()
    {");

        foreach (var (type, messageId) in messageTypes)
        {
            builder.AppendLine($"        MessageRegistry.RegisterMessageType<{type.ToDisplayString()}>({messageId});");
        }

        builder.AppendLine(@"    }
}");

        return builder.ToString();
    }
}

/// <summary>
/// 消息特性接收器
/// </summary>
public class MessageAttributeReceiver : ISyntaxContextReceiver
{
    public List<(INamedTypeSymbol Type, int MessageId)> MessageTypes { get; } = [];

    public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
    {
        // 查找类声明
        if (context.Node is not ClassDeclarationSyntax classDeclaration)
        {
            return;
        }

        // 获取语义模型
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration);
        if (symbol is not INamedTypeSymbol typeSymbol)
        {
            return;
        }

        // 输出类型信息
        var diagnostic = Diagnostic.Create(
            new DiagnosticDescriptor(
                "PRPC010",
                "类型检查",
                "检查类型: {0}, 基类: {1}, 接口: {2}, 特性: {3}",
                "PulseRPC",
                DiagnosticSeverity.Info,
                true),
            Location.None,
            typeSymbol.ToDisplayString(),
            typeSymbol.BaseType?.ToDisplayString() ?? "无",
            string.Join(", ", typeSymbol.AllInterfaces.Select(i => i.ToDisplayString())),
            string.Join(", ", typeSymbol.GetAttributes().Select(a => a.AttributeClass?.ToDisplayString() ?? "未知")));

        context.ReportDiagnostic(diagnostic);

        // 检查是否实现了IMessage接口
        var hasMessageInterface = typeSymbol.AllInterfaces.Any(i =>
            i.ToDisplayString() == "PulseRPC.Protocol.IMessage");
        if (!hasMessageInterface)
        {
            return;
        }

        // 查找Message特性
        var messageAttribute = typeSymbol.GetAttributes()
            .FirstOrDefault(attr =>
            {
                var attrName = attr.AttributeClass?.ToDisplayString();
                return attrName == "PulseRPC.Protocol.Attributes.MessageAttribute" ||
                       attrName == "PulseRPC.Protocol.Attributes.Message";
            });

        if (messageAttribute == null)
        {
            // 输出特性未找到信息
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor(
                    "PRPC011",
                    "特性未找到",
                    "类型 {0} 实现了IMessage但未找到Message特性",
                    "PulseRPC",
                    DiagnosticSeverity.Info,
                    true),
                Location.None,
                typeSymbol.ToDisplayString()));
            return;
        }

        // 获取消息ID
        if (messageAttribute.ConstructorArguments.Length >= 1 &&
            messageAttribute.ConstructorArguments[0].Value is int messageId)
        {
            // 输出成功注册信息
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor(
                    "PRPC012",
                    "消息注册",
                    "成功注册消息类型: {0} (ID: {1})",
                    "PulseRPC",
                    DiagnosticSeverity.Info,
                    true),
                Location.None,
                typeSymbol.ToDisplayString(),
                messageId));
            MessageTypes.Add((typeSymbol, messageId));
        }
    }
}
