using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;

namespace PulseRPC.Client.SourceGenerator;

/// <summary>
/// 接收器实现类生成器
/// </summary>
[Generator]
public class ReceiverImplementationGenerator : IIncrementalGenerator
{
    /// <summary>
    /// 初始化
    /// </summary>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 注册语法节点提供器
        var receiverTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is InterfaceDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => GetReceiverTypeFromContext(ctx))
            .Where(static m => m is not null)!;

        // 获取所有通知处理方法
        var notificationHandlers = context.CompilationProvider
            .SelectMany((compilation, ct) => GetNotificationHandlers(compilation, ct))
            .Collect();

        // 组合接收器类型和通知处理方法
        var combinedData = receiverTypes.Combine(notificationHandlers);

        // 注册源代码输出
        context.RegisterSourceOutput(combinedData, static (spc, data) =>
        {
            if (data.Left != null)
            {
                GenerateReceiverImplementation(spc, data.Left, data.Right);
            }
        });
    }

    private static INamedTypeSymbol? GetReceiverTypeFromContext(GeneratorSyntaxContext context)
    {
        var interfaceDeclaration = (InterfaceDeclarationSyntax)context.Node;

        var symbol = context.SemanticModel.GetDeclaredSymbol(interfaceDeclaration) as INamedTypeSymbol;
        if (symbol == null) return null;

        // 检查是否有 ReceiverInterface 特性
        if (!symbol.GetAttributes().Any(attr => attr.AttributeClass?.Name == "ReceiverInterfaceAttribute"))
            return null;

        return symbol;
    }

    private static IEnumerable<IMethodSymbol> GetNotificationHandlers(Compilation compilation, CancellationToken cancellationToken)
    {
        var handlerAttribute = compilation.GetTypeByMetadataName("PulseRPC.NotificationHandlerAttribute");
        if (handlerAttribute == null) return Enumerable.Empty<IMethodSymbol>();

        // 查找所有标记了 NotificationHandlerAttribute 的方法
        var handlers = new List<IMethodSymbol>();

        foreach (var syntaxTree in compilation.SyntaxTrees)
        {
            cancellationToken.ThrowIfCancellationRequested();

            var semanticModel = compilation.GetSemanticModel(syntaxTree);
            var classSyntax = syntaxTree.GetRoot().DescendantNodes().OfType<ClassDeclarationSyntax>();

            foreach (var classNode in classSyntax)
            {
                cancellationToken.ThrowIfCancellationRequested();

                var methods = classNode.Members.OfType<MethodDeclarationSyntax>();
                foreach (var method in methods)
                {
                    var methodSymbol = semanticModel.GetDeclaredSymbol(method) as IMethodSymbol;
                    if (methodSymbol != null && methodSymbol.GetAttributes().Any(a =>
                        a.AttributeClass?.Equals(handlerAttribute, SymbolEqualityComparer.Default) == true))
                    {
                        handlers.Add(methodSymbol);
                    }
                }
            }
        }

        return handlers;
    }

    /// <summary>
    /// 生成接收器实现类
    /// </summary>
    private static void GenerateReceiverImplementation(SourceProductionContext context,
        INamedTypeSymbol receiverType, ImmutableArray<IMethodSymbol> notificationHandlers)
    {
        try
        {
            var source = GenerateImplementation(receiverType, notificationHandlers);
            context.AddSource($"{receiverType.Name}Implementation.g.cs", source);
        }
        catch (Exception ex)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor(
                    id: "PRPC701",
                    title: "接收器实现类生成出错",
                    messageFormat: "生成接收器 {0} 的实现类时出错: {1}",
                    category: "PulseRPC.Generator",
                    defaultSeverity: DiagnosticSeverity.Error,
                    isEnabledByDefault: true),
                Location.None,
                receiverType.Name,
                ex.Message));
        }
    }

    private static string GenerateImplementation(INamedTypeSymbol receiverType,
        ImmutableArray<IMethodSymbol> notificationHandlers)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// 此代码由 PulseRPC.Generators 自动生成，请勿手动修改");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();

        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using PulseRPC;");
        sb.AppendLine();

        sb.AppendLine($"namespace {receiverType.ContainingNamespace}");
        sb.AppendLine("{");

        // 生成接收器实现类
        sb.AppendLine($"    public class {receiverType.Name}Implementation : {receiverType.Name}");
        sb.AppendLine("    {");

        // 生成事件处理方法
        foreach (var method in receiverType.GetMembers().OfType<IMethodSymbol>())
        {
            if (method.IsStatic || !method.ReturnsVoid || method.Parameters.Length != 1)
                continue;

            var paramType = method.Parameters[0].Type;
            var handlers = notificationHandlers.Where(h =>
                h.Parameters.Length == 1 &&
                h.Parameters[0].Type.Equals(paramType, SymbolEqualityComparer.Default)).ToList();

            if (!handlers.Any())
                continue;

            sb.AppendLine($"        public override void {method.Name}({paramType} notification)");
            sb.AppendLine("        {");

            foreach (var handler in handlers)
            {
                sb.AppendLine($"            {handler.ContainingType.Name}.{handler.Name}(notification);");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}

/// <summary>
/// 接收器语法接收器
/// </summary>
public class ReceiverImplementationSyntaxReceiver : ISyntaxContextReceiver
{
    /// <summary>
    /// 接收器类型列表
    /// </summary>
    public List<INamedTypeSymbol> ReceiverTypes { get; } = new List<INamedTypeSymbol>();

    /// <summary>
    /// 通知处理方法列表
    /// </summary>
    public List<IMethodSymbol> NotificationHandlers { get; } = new List<IMethodSymbol>();

    /// <summary>
    /// 访问语法节点
    /// </summary>
    public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
    {
        // 查找接收器接口
        if (context.Node is InterfaceDeclarationSyntax interfaceDeclaration)
        {
            var symbol = context.SemanticModel.GetDeclaredSymbol(interfaceDeclaration) as INamedTypeSymbol;
            if (symbol != null &&
                symbol.GetAttributes().Any(attr => attr.AttributeClass?.Name == "ReceiverInterfaceAttribute"))
            {
                ReceiverTypes.Add(symbol);
            }
        }

        // 查找通知处理方法
        if (context.Node is MethodDeclarationSyntax methodDeclaration &&
            methodDeclaration.AttributeLists.Count > 0)
        {
            var symbol = context.SemanticModel.GetDeclaredSymbol(methodDeclaration) as IMethodSymbol;
            if (symbol != null &&
                symbol.GetAttributes().Any(attr => attr.AttributeClass?.Name == "NotificationHandlerAttribute"))
            {
                NotificationHandlers.Add(symbol);
            }
        }
    }
}
