using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace PulseRPC.Client.SourceGenerator;

[Generator]
public class StreamingHubClientGenerator : ISourceGenerator
{
    private const string IStreamingHubFullName = "PulseRPC.IStreamingHub";
    private const string PulseClientGenerationAttributeName = "PulseClientGenerationAttribute";

    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new StreamingHubSyntaxReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxContextReceiver is not StreamingHubSyntaxReceiver receiver || !receiver.StreamingHubs.Any())
        {
            return;
        }

        foreach (var hubType in receiver.StreamingHubs)
        {
            try
            {
                var source = GenerateStreamingHubClient(hubType);
                context.AddSource($"{hubType.Name}Client.g.cs", source);
            }
            catch (Exception ex)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "PRPC100",
                        "生成StreamingHub客户端代理失败",
                        $"生成类型 {hubType.Name} 的代理时发生错误: {ex.Message}",
                        "PulseRPC",
                        DiagnosticSeverity.Error,
                        true),
                    Location.None));
            }
        }
    }

    private string GenerateStreamingHubClient(INamedTypeSymbol hubType)
    {
        var namespaceName = hubType.ContainingNamespace.ToDisplayString();
        var hubName = hubType.Name;
        var clientClassName = $"{hubName}Client";

        var sb = new StringBuilder();

        // 添加命名空间
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// 此代码由PulseRPC.Client.SourceGenerator生成，请勿手动修改");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();

        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using PulseRPC;");
        sb.AppendLine("using PulseRPC.Client;");
        sb.AppendLine();

        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");

        // 生成客户端代理类
        sb.AppendLine($"    public class {clientClassName} : {hubType.ToDisplayString()}");
        sb.AppendLine("    {");

        // 添加字段
        sb.AppendLine("        private readonly NetworkClient _client;");
        sb.AppendLine("        private readonly CancellationToken _defaultCancellationToken;");
        sb.AppendLine("        private readonly DateTime _defaultDeadline;");
        sb.AppendLine("        private readonly string _host;");
        sb.AppendLine();

        // 添加构造函数
        sb.AppendLine($"        public {clientClassName}(NetworkClient client)");
        sb.AppendLine("        {");
        sb.AppendLine("            _client = client;");
        sb.AppendLine("            _defaultCancellationToken = CancellationToken.None;");
        sb.AppendLine("            _defaultDeadline = DateTime.MaxValue;");
        sb.AppendLine("            _host = string.Empty;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 实现接口方法
        foreach (var method in hubType.GetMembers().OfType<IMethodSymbol>())
        {
            if (method.IsStatic || method.IsAbstract || !method.IsVirtual)
                continue;

            if (method.Name == "WithDeadline" || method.Name == "WithCancellationToken" || method.Name == "WithHost")
                continue;

            var returnType = method.ReturnType.ToString();
            var parameters = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"));
            var parameterNames = string.Join(", ", method.Parameters.Select(p => p.Name));

            sb.AppendLine($"        public {returnType} {method.Name}({parameters})");
            sb.AppendLine("        {");

            if (method.Parameters.Length == 1 && method.Parameters[0].Type.GetMembers().OfType<IPropertySymbol>().Any())
            {
                // 有一个参数，直接用SendRequestAsync
                sb.AppendLine(
                    $"            return _client.SendRequestAsync<{method.Parameters[0].Type}, {method.ReturnType.ToString()?.Replace("System.Threading.Tasks.Task<", "").Replace(">", "")}>(");
                sb.AppendLine($"                {method.Parameters[0].Name}, _defaultCancellationToken);");
            }
            else if (method.Parameters.Length > 0)
            {
                // 多个参数，先创建请求对象
                var responseType = method.ReturnType.ToString()
                    ?.Replace("System.Threading.Tasks.Task<", "")
                    .Replace(">", "");
                sb.AppendLine($"            // 创建请求参数包装");
                sb.AppendLine($"            var request = new {method.ContainingType.Name}_{method.Name}_Request");
                sb.AppendLine("            {");

                foreach (var param in method.Parameters)
                {
                    sb.AppendLine($"                {param.Name.ToPascalCase()} = {param.Name},");
                }

                sb.AppendLine("            };");
                sb.AppendLine();
                sb.AppendLine(
                    $"            return _client.SendRequestAsync<{method.ContainingType.Name}_{method.Name}_Request, {responseType}>(");
                sb.AppendLine("                request, _defaultCancellationToken);");
            }
            else
            {
                // 没有参数，创建空请求
                var responseType = method.ReturnType.ToString()
                    ?.Replace("System.Threading.Tasks.Task<", "")
                    .Replace(">", "");
                sb.AppendLine($"            // 创建空请求");
                sb.AppendLine($"            var request = new {method.ContainingType.Name}_{method.Name}_Request();");
                sb.AppendLine();
                sb.AppendLine(
                    $"            return _client.SendRequestAsync<{method.ContainingType.Name}_{method.Name}_Request, {responseType}>(");
                sb.AppendLine("                request, _defaultCancellationToken);");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // 实现IStreamingHub接口方法
        sb.AppendLine($"        public {hubType.ToDisplayString()} WithDeadline(DateTime deadline)");
        sb.AppendLine("        {");
        sb.AppendLine("            return this;");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine(
            $"        public {hubType.ToDisplayString()} WithCancellationToken(CancellationToken cancellationToken)");
        sb.AppendLine("        {");
        sb.AppendLine("            return this;");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine($"        public {hubType.ToDisplayString()} WithHost(string host)");
        sb.AppendLine("        {");
        sb.AppendLine("            return this;");
        sb.AppendLine("        }");

        sb.AppendLine("    }");

        // 为每个方法生成请求类
        foreach (var method in hubType.GetMembers().OfType<IMethodSymbol>())
        {
            if (method.IsStatic || method.IsAbstract || !method.IsVirtual)
                continue;

            if (method.Name == "WithDeadline" || method.Name == "WithCancellationToken" || method.Name == "WithHost")
                continue;

            if (method.Parameters.Length > 0 && method.Parameters.Length != 1)
            {
                sb.AppendLine();
                sb.AppendLine($"    [MemoryPack.MemoryPackable]");
                sb.AppendLine($"    public partial class {method.ContainingType.Name}_{method.Name}_Request");
                sb.AppendLine("    {");

                foreach (var param in method.Parameters)
                {
                    var propertyName = param.Name.ToPascalCase();
                    sb.AppendLine($"        public {param.Type} {propertyName} {{ get; set; }}");
                }

                sb.AppendLine("    }");
            }
        }

        sb.AppendLine("}");

        return sb.ToString();
    }
}

public class StreamingHubSyntaxReceiver : ISyntaxContextReceiver
{
    public List<INamedTypeSymbol> StreamingHubs { get; } = new List<INamedTypeSymbol>();

    public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
    {
        if (context.Node is InterfaceDeclarationSyntax interfaceDeclaration)
        {
            var symbol = context.SemanticModel.GetDeclaredSymbol(interfaceDeclaration) as INamedTypeSymbol;
            if (symbol != null && IsStreamingHub(symbol))
            {
                StreamingHubs.Add(symbol);
            }
        }
    }

    private bool IsStreamingHub(INamedTypeSymbol symbol)
    {
        foreach (var intf in symbol.AllInterfaces)
        {
            if (intf.IsGenericType && intf.ConstructedFrom.ToDisplayString().StartsWith("PulseRPC.IStreamingHub<"))
            {
                return true;
            }
        }

        return false;
    }
}

public static class StringExtensions
{
    public static string ToPascalCase(this string value)
    {
        if (string.IsNullOrEmpty(value))
            return value;

        return char.ToUpperInvariant(value[0]) + value.Substring(1);
    }
}
