using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using MemoryPack;

namespace PulseRPC.Client.SourceGenerator;

[Generator]
public class StreamingHubClientGenerator : IIncrementalGenerator
{
    private const string IStreamingHubFullName = "PulseRPC.IStreamingHub";
    private const string PulseClientGenerationAttributeName = "PulseClientGenerationAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 注册语法节点提供器
        IncrementalValuesProvider<INamedTypeSymbol> serviceTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is InterfaceDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => GetServiceTypeFromContext(ctx))
            .Where(static m => m is not null)!;

        // 注册源代码输出
        context.RegisterSourceOutput(serviceTypes, static (spc, serviceType) =>
            GenerateServiceClient(spc, serviceType));
    }

    private static INamedTypeSymbol? GetServiceTypeFromContext(GeneratorSyntaxContext context)
    {
        var typeDeclaration = (TypeDeclarationSyntax)context.Node;

        // 添加更多的验证
        if (!typeDeclaration.AttributeLists.Any())
            return null;

        var symbol = context.SemanticModel.GetDeclaredSymbol(typeDeclaration);
        if (symbol is not INamedTypeSymbol typeSymbol)
            return null;

        // 验证是否实现了正确的接口
        if (!IsStreamingHub(typeSymbol))
            return null;

        return typeSymbol;
    }

    private static bool IsStreamingHub(INamedTypeSymbol symbol)
    {
        foreach (var intf in symbol.AllInterfaces)
        {
            if (intf.IsGenericType && intf.ConstructedFrom.ToDisplayString().StartsWith("PulseRPC.IStreamingHub<"))
            {
                return true;
            }
        }

        return false;
    }

    private static void GenerateServiceClient(SourceProductionContext context, INamedTypeSymbol serviceType)
    {
        try
        {
            var source = GenerateStreamingHubClient(serviceType);
            context.AddSource($"{serviceType.Name}Client.g.cs", source);
        }
        catch (Exception ex)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor(
                    "PRPC100",
                    "生成StreamingHub客户端代理失败",
                    $"生成类型 {serviceType.Name} 的代理时发生错误: {ex.Message}",
                    "PulseRPC",
                    DiagnosticSeverity.Error,
                    true),
                Location.None));
        }
    }

    private static string GenerateStreamingHubClient(INamedTypeSymbol hubType)
    {
        var namespaceName = hubType.ContainingNamespace.ToDisplayString();
        var hubName = hubType.Name;
        var clientClassName = $"{hubName}Client";

        var sb = new StringBuilder();

        // 添加命名空间
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// 此代码由PulseRPC.Client.SourceGenerator生成，请勿手动修改");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();

        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using PulseRPC;");
        sb.AppendLine("using PulseRPC.Client;");
        sb.AppendLine("using MemoryPack;");
        sb.AppendLine();

        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");

        // 生成客户端代理类
        sb.AppendLine($"    public class {clientClassName} : {hubType.ToDisplayString()}");
        sb.AppendLine("    {");

        // 添加字段
        sb.AppendLine("        private readonly NetworkClient _client;");
        sb.AppendLine("        private readonly CancellationToken _defaultCancellationToken;");
        sb.AppendLine("        private readonly DateTime _defaultDeadline;");
        sb.AppendLine("        private readonly string _host;");
        sb.AppendLine();

        // 添加构造函数
        sb.AppendLine($"        public {clientClassName}(NetworkClient client)");
        sb.AppendLine("        {");
        sb.AppendLine("            _client = client;");
        sb.AppendLine("            _defaultCancellationToken = CancellationToken.None;");
        sb.AppendLine("            _defaultDeadline = DateTime.MaxValue;");
        sb.AppendLine("            _host = string.Empty;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 为每个方法生成空请求和单参数请求类的声明
        var requestClassDefinitions = new HashSet<string>();

        // 实现接口方法
        foreach (var method in hubType.GetMembers().OfType<IMethodSymbol>())
        {
            if (method.IsStatic || method.IsAbstract || !method.IsVirtual)
                continue;

            if (method.Name == "WithDeadline" || method.Name == "WithCancellationToken" || method.Name == "WithHost")
                continue;

            var returnType = method.ReturnType.ToString();
            var parameters = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"));
            var parameterNames = string.Join(", ", method.Parameters.Select(p => p.Name));

            // 为0或1个参数的方法准备请求类名
            string requestClassName = $"{method.ContainingType.Name}_{method.Name}_Request";
            requestClassDefinitions.Add(requestClassName);

            sb.AppendLine($"        public {returnType} {method.Name}({parameters})");
            sb.AppendLine("        {");

            if (method.Parameters.Length == 1 && method.Parameters[0].Type.GetMembers().OfType<IPropertySymbol>().Any())
            {
                // 有一个参数，直接用SendRequestAsync
                sb.AppendLine(
                    $"            return _client.SendRequestAsync<{method.Parameters[0].Type}, {method.ReturnType.ToString()?.Replace("System.Threading.Tasks.Task<", "").Replace(">", "")}>(");
                sb.AppendLine($"                {method.Parameters[0].Name}, _defaultCancellationToken);");
            }
            else if (method.Parameters.Length > 0)
            {
                // 多个参数，先创建请求对象
                var responseType = method.ReturnType.ToString()
                    ?.Replace("System.Threading.Tasks.Task<", "")
                    .Replace(">", "");
                sb.AppendLine($"            // 创建请求参数包装");
                sb.AppendLine($"            var request = new {requestClassName}");
                sb.AppendLine("            {");

                foreach (var param in method.Parameters)
                {
                    sb.AppendLine($"                {param.Name.ToPascalCase()} = {param.Name},");
                }

                sb.AppendLine("            };");
                sb.AppendLine();
                sb.AppendLine(
                    $"            return _client.SendRequestAsync<{requestClassName}, {responseType}>(");
                sb.AppendLine("                request, _defaultCancellationToken);");
            }
            else
            {
                // 没有参数，创建空请求
                var responseType = method.ReturnType.ToString()
                    ?.Replace("System.Threading.Tasks.Task<", "")
                    .Replace(">", "");
                sb.AppendLine($"            // 创建空请求");
                sb.AppendLine($"            var request = new {requestClassName}();");
                sb.AppendLine();
                sb.AppendLine(
                    $"            return _client.SendRequestAsync<{requestClassName}, {responseType}>(");
                sb.AppendLine("                request, _defaultCancellationToken);");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // 实现IStreamingHub接口方法
        sb.AppendLine($"        public {hubType.ToDisplayString()} WithDeadline(DateTime deadline)");
        sb.AppendLine("        {");
        sb.AppendLine("            return this;");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine(
            $"        public {hubType.ToDisplayString()} WithCancellationToken(CancellationToken cancellationToken)");
        sb.AppendLine("        {");
        sb.AppendLine("            return this;");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine($"        public {hubType.ToDisplayString()} WithHost(string host)");
        sb.AppendLine("        {");
        sb.AppendLine("            return this;");
        sb.AppendLine("        }");

        sb.AppendLine("    }");

        // 为每个方法生成请求类
        foreach (var method in hubType.GetMembers().OfType<IMethodSymbol>())
        {
            if (method.IsStatic || method.IsAbstract || !method.IsVirtual)
                continue;

            if (method.Name == "WithDeadline" || method.Name == "WithCancellationToken" || method.Name == "WithHost")
                continue;

            var requestClassName = $"{method.ContainingType.Name}_{method.Name}_Request";

            if (method.Parameters.Length == 0)
            {
                // 生成空请求类
                sb.AppendLine();
                sb.AppendLine($"    [MemoryPackable]");
                sb.AppendLine($"    public partial class {requestClassName} : IMemoryPackable<{requestClassName}>");
                sb.AppendLine("    {");
                sb.AppendLine("        // 空请求");
                sb.AppendLine("    }");
            }
            else if (method.Parameters.Length == 1 && method.Parameters[0].Type.GetMembers().OfType<IPropertySymbol>().Any())
            {
                // 对于单参数方法，如果原始参数类型不是IMemoryPackable，生成封装类
                var paramType = method.Parameters[0].Type;
                var isMemoryPackable = false;
                
                // 检查参数类型是否实现IMemoryPackable
                foreach (var iface in paramType.AllInterfaces)
                {
                    if (iface.IsGenericType && 
                        iface.ConstructedFrom.ToDisplayString() == "MemoryPack.IMemoryPackable<T>" && 
                        iface.TypeArguments[0].Equals(paramType))
                    {
                        isMemoryPackable = true;
                        break;
                    }
                }
                
                if (!isMemoryPackable)
                {
                    // 生成包装类
                    sb.AppendLine();
                    sb.AppendLine($"    [MemoryPackable]");
                    sb.AppendLine($"    public partial class {requestClassName} : IMemoryPackable<{requestClassName}>");
                    sb.AppendLine("    {");
                    sb.AppendLine($"        public {paramType} Value {{ get; set; }}");
                    sb.AppendLine("    }");
                }
            }
            else if (method.Parameters.Length > 1)
            {
                // 多参数方法的请求类
                sb.AppendLine();
                sb.AppendLine($"    [MemoryPackable]");
                sb.AppendLine($"    public partial class {requestClassName} : IMemoryPackable<{requestClassName}>");
                sb.AppendLine("    {");

                foreach (var param in method.Parameters)
                {
                    var propertyName = param.Name.ToPascalCase();
                    sb.AppendLine($"        public {param.Type} {propertyName} {{ get; set; }}");
                }

                sb.AppendLine("    }");
            }
        }

        sb.AppendLine("}");

        return sb.ToString();
    }
}

public static class StringExtensions
{
    public static string ToPascalCase(this string value)
    {
        if (string.IsNullOrEmpty(value))
            return value;

        return char.ToUpperInvariant(value[0]) + value.Substring(1);
    }
}
