using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace PulseRPC.Client.SourceGenerator;

/// <summary>
/// StreamingHub 格式化器注册代码生成器 - 自动注册所有 StreamingHub 临时对象的格式化器
/// </summary>
[Generator]
public class StreamingHubFormatterRegistration : IIncrementalGenerator
{
    // 临时对象的命名模式
    private static readonly string[] TemporaryObjectPatterns = new[]
    {
        "_Request",
        "_Response"
    };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 收集所有StreamingHub客户端类的信息
        // 使用语法提供器来找到所有接口（包括StreamingHub）
        IncrementalValuesProvider<InterfaceDeclarationSyntax> hubInterfaces = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is InterfaceDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => ctx.Node as InterfaceDeclarationSyntax)
            .Where(static node => node != null)!;

        // 为每个接口找到生成的临时类型
        IncrementalValuesProvider<(string InterfaceName, ImmutableArray<string> TempObjects)> tempObjectsInfo =
            hubInterfaces.Select((node, ct) =>
            {
                if (node.Identifier.Text.EndsWith("StreamingHub") || node.Identifier.Text.EndsWith("Hub"))
                {
                    var interfaceName = node.Identifier.Text;
                    var methods = node.Members.OfType<MethodDeclarationSyntax>()
                        .Where(m => m.Identifier.Text != "WithDeadline" &&
                                   m.Identifier.Text != "WithCancellationToken" &&
                                   m.Identifier.Text != "WithHost")
                        .ToList();

                    var tempObjects = new List<string>();
                    foreach (var method in methods)
                    {
                        var requestClassName = $"{interfaceName}_{method.Identifier.Text}_Request";
                        var responseClassName = $"{interfaceName}_{method.Identifier.Text}_Response";
                        tempObjects.Add(requestClassName);
                        tempObjects.Add(responseClassName);
                    }

                    return (interfaceName, tempObjects.ToImmutableArray());
                }

                return (string.Empty, ImmutableArray<string>.Empty);
            })
            .Where(info => !string.IsNullOrEmpty(info.Item1));

        // 收集所有临时对象信息
        var allTempObjectsInfo = tempObjectsInfo.Collect();

        // 生成注册代码
        context.RegisterSourceOutput(allTempObjectsInfo, static (spc, tempObjectsInfo) =>
        {
            if (tempObjectsInfo.IsEmpty)
                return;

            GenerateRegistrationClass(spc, tempObjectsInfo);
        });
    }

    /// <summary>
    /// 生成统一的注册类
    /// </summary>
    private static void GenerateRegistrationClass(SourceProductionContext context, ImmutableArray<(string InterfaceName, ImmutableArray<string> TempObjects)> hubsInfo)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// 此代码由PulseRPC.Client.SourceGenerator自动生成");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using MemoryPack;");
        sb.AppendLine("using MemoryPack.Formatters;");
        sb.AppendLine();
        sb.AppendLine("namespace PulseRPC.Client");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// StreamingHub临时对象序列化器注册 - 由源代码生成器自动生成");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class StreamingHubFormatterRegistration");
        sb.AppendLine("    {");
        sb.AppendLine("        // 防止多次注册");
        sb.AppendLine("        private static bool _isRegistered = false;");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 注册所有StreamingHub临时对象序列化器");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static void RegisterAll()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_isRegistered) return;");
        sb.AppendLine("            _isRegistered = true;");
        sb.AppendLine();

        int totalObjects = 0;
        foreach (var (hubName, tempObjects) in hubsInfo)
        {
            sb.AppendLine($"            // {hubName} 相关临时对象");
            foreach (var tempObject in tempObjects.Where(name => !string.IsNullOrEmpty(name)))
            {
                sb.AppendLine($"            try {{ {tempObject}FormatterRegistration.Register(); }} catch {{ }}");
                totalObjects++;
            }
            sb.AppendLine();
        }

        sb.AppendLine($"            // 共注册 {totalObjects} 个临时对象的序列化器");

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("StreamingHubFormatterRegistration.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
