// using System;
// using System.Collections.Generic;
// using System.Collections.Immutable;
// using System.Linq;
// using System.Text;
// using Microsoft.CodeAnalysis;
// using Microsoft.CodeAnalysis.Text;
//
// namespace PulseRPC.Client.SourceGenerator;
//
// /// <summary>
// /// 临时对象注册代码生成器 - 生成统一的入口点注册所有临时对象的序列化器
// /// </summary>
// [Generator]
// public class TemporaryObjectRegistration : IIncrementalGenerator
// {
//     // 临时对象的命名模式
//     private static readonly string[] TemporaryObjectPatterns = new[]
//     {
//         "_Request",
//         "_Response"
//     };
//
//     private const string EnableMemoryPackGeneratorPropertyName = "PulseRPC_EnableMemoryPackGenerator";
//
//     public void Initialize(IncrementalGeneratorInitializationContext context)
//     {
//         // 获取编译选项，检查是否启用了生成器
//         IncrementalValueProvider<bool> isGeneratorEnabled = context.AnalyzerConfigOptionsProvider
//             .Select((provider, _) =>
//             {
//                 provider.GlobalOptions.TryGetValue($"build_property.{EnableMemoryPackGeneratorPropertyName}", out var enabledValue);
//                 return string.Equals(enabledValue, "true", StringComparison.OrdinalIgnoreCase);
//             });
//
//         // 获取所有临时对象
//         IncrementalValuesProvider<INamedTypeSymbol> temporaryObjects = context.CompilationProvider
//             .SelectMany((compilation, _) => FindTemporaryObjects(compilation));
//
//         // 合并所有临时对象
//         IncrementalValueProvider<ImmutableArray<INamedTypeSymbol>> allObjects = temporaryObjects.Collect();
//
//         // 将配置与临时对象列表结合
//         IncrementalValueProvider<(bool isEnabled, ImmutableArray<INamedTypeSymbol> objects)> filteredObjects =
//             isGeneratorEnabled.Combine(allObjects);
//
//         // 注册源代码输出
//         context.RegisterSourceOutput(
//             filteredObjects,
//             static (spc, data) =>
//             {
//                 if (!data.isEnabled || data.objects.IsEmpty)
//                     return;
//
//                 GenerateRegistrationClass(spc, data.objects);
//             });
//     }
//
//     /// <summary>
//     /// 在编译中查找所有临时对象
//     /// </summary>
//     private static IEnumerable<INamedTypeSymbol> FindTemporaryObjects(Compilation compilation)
//     {
//         var allTypes = new List<INamedTypeSymbol>();
//
//         // 递归查找所有类型
//         void CollectTypes(INamespaceSymbol ns)
//         {
//             foreach (var member in ns.GetMembers())
//             {
//                 if (member is INamespaceSymbol nestedNs)
//                 {
//                     CollectTypes(nestedNs);
//                 }
//                 else if (member is INamedTypeSymbol type)
//                 {
//                     // 检查类型名称是否符合临时对象模式
//                     if (IsTemporaryObject(type))
//                     {
//                         allTypes.Add(type);
//                     }
//
//                     // 递归查找嵌套类型
//                     foreach (var nestedType in type.GetTypeMembers())
//                     {
//                         if (IsTemporaryObject(nestedType))
//                         {
//                             allTypes.Add(nestedType);
//                         }
//                     }
//                 }
//             }
//         }
//
//         // 从全局命名空间开始查找
//         CollectTypes(compilation.GlobalNamespace);
//         return allTypes;
//     }
//
//     /// <summary>
//     /// 判断类型是否为临时对象
//     /// </summary>
//     private static bool IsTemporaryObject(INamedTypeSymbol type)
//     {
//         // 检查类型名称是否符合临时对象模式
//         bool matchesPattern = TemporaryObjectPatterns.Any(pattern => type.Name.EndsWith(pattern));
//         if (!matchesPattern)
//             return false;
//
//         // 检查是否有[MemoryPackable]特性或已经实现了IMemoryPackable接口
//         bool hasMemoryPackableAttribute = type.GetAttributes().Any(attr =>
//             attr.AttributeClass?.Name == "MemoryPackableAttribute" ||
//             attr.AttributeClass?.ToDisplayString().Contains("MemoryPack.MemoryPackableAttribute") == true);
//
//         // 检查是否实现了IMemoryPackable接口
//         bool implementsIMemoryPackable = type.AllInterfaces.Any(i =>
//             i.Name == "IMemoryPackable" ||
//             i.ToDisplayString().Contains("MemoryPack.IMemoryPackable"));
//
//         // 只处理标记了[MemoryPackable]但没有实现IMemoryPackable的临时对象
//         return hasMemoryPackableAttribute && !implementsIMemoryPackable;
//     }
//
//     /// <summary>
//     /// 生成全局注册类
//     /// </summary>
//     private static void GenerateRegistrationClass(SourceProductionContext context, ImmutableArray<INamedTypeSymbol> types)
//     {
//         var sb = new StringBuilder();
//         sb.AppendLine("// <auto-generated>");
//         sb.AppendLine("// 此代码由PulseRPC.Client.SourceGenerator自动生成");
//         sb.AppendLine("// </auto-generated>");
//         sb.AppendLine();
//         sb.AppendLine("using System;");
//         sb.AppendLine("using MemoryPack;");
//         sb.AppendLine("using MemoryPack.Formatters;");
//         sb.AppendLine();
//         sb.AppendLine("namespace PulseRPC.Serialization");
//         sb.AppendLine("{");
//         sb.AppendLine("    /// <summary>");
//         sb.AppendLine("    /// 临时对象序列化器注册 - 由源代码生成器自动生成");
//         sb.AppendLine("    /// </summary>");
//         sb.AppendLine("    public static class TemporaryObjectFormatterRegistration");
//         sb.AppendLine("    {");
//         sb.AppendLine("        // 防止多次注册");
//         sb.AppendLine("        private static bool _isRegistered = false;");
//         sb.AppendLine();
//         sb.AppendLine("        /// <summary>");
//         sb.AppendLine("        /// 注册所有临时对象序列化器");
//         sb.AppendLine("        /// </summary>");
//         sb.AppendLine("        public static void RegisterAll()");
//         sb.AppendLine("        {");
//         sb.AppendLine("            if (_isRegistered) return;");
//         sb.AppendLine("            _isRegistered = true;");
//         sb.AppendLine();
//
//         if (types.Length == 0)
//         {
//             sb.AppendLine("            // 没有需要注册的临时对象");
//         }
//         else
//         {
//             sb.AppendLine($"            // 注册 {types.Length} 个临时对象的序列化器");
//             foreach (var type in types)
//             {
//                 var typeName = type.Name;
//                 sb.AppendLine($"            MemoryPack.{typeName}FormatterRegistration.Register();");
//             }
//         }
//
//         sb.AppendLine("        }");
//         sb.AppendLine("    }");
//         sb.AppendLine("}");
//
//         context.AddSource("TemporaryObjectFormatterRegistration.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
//     }
// }
