using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.Tokens;
using PulseRPC.Server;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;

namespace DistributedGameApp.GameServer.Services;

/// <summary>
/// JWT 令牌验证服务 - 实现 PulseRPC.Server.IJwtTokenService
/// </summary>
public class JwtService : IJwtTokenService
{
    private readonly JwtOptions _options;
    private readonly ILogger<JwtService> _logger;

    public JwtService(IOptions<JwtOptions> options, ILogger<JwtService> logger)
    {
        _options = options.Value;
        _logger = logger;
    }

    /// <summary>
    /// 验证令牌并返回 Claims（IJwtTokenService 接口方法）
    /// </summary>
    public Task<IEnumerable<Claim>?> ValidateTokenAsync(string token)
    {
        try
        {
            var tokenHandler = new JwtSecurityTokenHandler();
            var key = Encoding.UTF8.GetBytes(_options.SecretKey);

            var validationParameters = new TokenValidationParameters
            {
                ValidateIssuerSigningKey = true,
                IssuerSigningKey = new SymmetricSecurityKey(key),
                ValidateIssuer = true,
                ValidIssuer = _options.Issuer,
                ValidateAudience = true,
                ValidAudience = _options.Audience,
                ValidateLifetime = true,
                ClockSkew = TimeSpan.Zero
            };

            var principal = tokenHandler.ValidateToken(token, validationParameters, out var validatedToken);

            _logger.LogInformation("JWT token validated successfully");
            return Task.FromResult<IEnumerable<Claim>?>(principal.Claims);
        }
        catch (SecurityTokenExpiredException)
        {
            _logger.LogWarning("JWT token expired");
            return Task.FromResult<IEnumerable<Claim>?>(null);
        }
        catch (SecurityTokenInvalidSignatureException)
        {
            _logger.LogWarning("JWT token has invalid signature");
            return Task.FromResult<IEnumerable<Claim>?>(null);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "JWT token validation failed");
            return Task.FromResult<IEnumerable<Claim>?>(null);
        }
    }

    /// <summary>
    /// 生成令牌（GameServer 不需要生成令牌，但需要实现接口）
    /// </summary>
    public Task<string> GenerateTokenAsync(string userId, HashSet<string> permissions, HashSet<string> roles)
    {
        throw new NotSupportedException("GameServer does not generate JWT tokens. Tokens should be generated by LoginServer.");
    }
}

/// <summary>
/// JWT 配置选项
/// </summary>
public class JwtOptions
{
    /// <summary>
    /// 配置节名称
    /// </summary>
    public const string SectionName = "Jwt";

    /// <summary>
    /// 密钥（至少32字符）
    /// </summary>
    public string SecretKey { get; set; } = string.Empty;

    /// <summary>
    /// 发行者
    /// </summary>
    public string Issuer { get; set; } = "DistributedGameApp";

    /// <summary>
    /// 受众
    /// </summary>
    public string Audience { get; set; } = "DistributedGameApp.Client";

    /// <summary>
    /// 访问令牌过期时间（分钟）
    /// </summary>
    public int AccessTokenExpirationMinutes { get; set; } = 60;

    /// <summary>
    /// 刷新令牌过期时间（天）
    /// </summary>
    public int RefreshTokenExpirationDays { get; set; } = 30;
}
