using System.Collections.Generic;
using System.Linq;
using System.Text;
using PulseRPC.Server.SourceGenerator.Models;

namespace PulseRPC.Server.SourceGenerator.Generators;

/// <summary>
/// 事件订阅管理器生成器 - 生成高性能的事件订阅管理代码
/// </summary>
public static class EventSubscriptionManagerGenerator
{
    /// <summary>
    /// 生成事件订阅管理器的源代码
    /// </summary>
    public static string GenerateSourceText(List<ServiceModel> serviceModels)
    {
        var sb = new StringBuilder();

        GenerateFileHeader(sb);
        GenerateSubscriptionManagerInterface(sb);
        GenerateSubscriptionManagerImplementation(sb, serviceModels);
        GenerateSubscriptionSupportTypes(sb);

        return sb.ToString();
    }

    private static void GenerateFileHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// PulseRPC Event Subscription Manager Generator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Collections.Concurrent;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine("using PulseRPC.Server.Transport;");
        sb.AppendLine();
    }

    private static void GenerateSubscriptionManagerInterface(StringBuilder sb)
    {
        sb.AppendLine("namespace PulseRPC.Server.Events");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 事件订阅管理器接口 - 管理客户端的事件订阅");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public interface IEventSubscriptionManager");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 客户端订阅特定事件");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        Task SubscribeAsync(string connectionId, string eventName, EventSubscriptionOptions? options = null);");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 客户端取消订阅特定事件");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        Task UnsubscribeAsync(string connectionId, string eventName);");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 获取事件的所有订阅者");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        IReadOnlyList<string> GetSubscribers(string eventName);");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 获取连接的所有订阅");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        IReadOnlyList<string> GetSubscriptions(string connectionId);");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 根据标签获取订阅者");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        IReadOnlyList<string> GetSubscribersByTags(Dictionary<string, string> tags);");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 获取订阅统计信息");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        SubscriptionStatistics GetStatistics();");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 订阅变化事件");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        event EventHandler<SubscriptionChangedEventArgs>? SubscriptionChanged;");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 清理断开连接的订阅");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        Task CleanupDisconnectedSubscriptionsAsync();");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateSubscriptionManagerImplementation(StringBuilder sb, List<ServiceModel> serviceModels)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 高性能事件订阅管理器实现");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public sealed class GeneratedEventSubscriptionManager : IEventSubscriptionManager, IDisposable");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly ConcurrentDictionary<string, ConcurrentHashSet<SubscriptionEntry>> _eventSubscriptions = new();");
        sb.AppendLine("        private readonly ConcurrentDictionary<string, ConcurrentHashSet<string>> _connectionSubscriptions = new();");
        sb.AppendLine("        private readonly ConcurrentDictionary<string, EventSubscriptionOptions> _subscriptionOptions = new();");
        sb.AppendLine("        private readonly ILogger<GeneratedEventSubscriptionManager> _logger;");
        sb.AppendLine("        private readonly Timer _cleanupTimer;");
        sb.AppendLine("        private readonly SubscriptionMetrics _metrics = new();");
        sb.AppendLine("        private bool _disposed;");
        sb.AppendLine();

        // 生成构造函数
        sb.AppendLine("        public GeneratedEventSubscriptionManager(ILogger<GeneratedEventSubscriptionManager> logger)");
        sb.AppendLine("        {");
        sb.AppendLine("            _logger = logger ?? throw new ArgumentNullException(nameof(logger));");
        sb.AppendLine("            ");
        sb.AppendLine("            // 每5分钟清理一次断开的连接");
        sb.AppendLine("            _cleanupTimer = new Timer(async _ => await CleanupDisconnectedSubscriptionsAsync(),");
        sb.AppendLine("                null, TimeSpan.FromMinutes(5), TimeSpan.FromMinutes(5));");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 生成订阅方法
        GenerateSubscribeMethod(sb);

        // 生成取消订阅方法
        GenerateUnsubscribeMethod(sb);

        // 生成查询方法
        GenerateQueryMethods(sb);

        // 生成清理方法
        GenerateCleanupMethods(sb);

        // 生成事件
        sb.AppendLine("        public event EventHandler<SubscriptionChangedEventArgs>? SubscriptionChanged;");
        sb.AppendLine();

        // 生成Dispose方法
        GenerateDisposeMethod(sb);

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateSubscribeMethod(StringBuilder sb)
    {
        sb.AppendLine("        /// <inheritdoc/>");
        sb.AppendLine("        public async Task SubscribeAsync(string connectionId, string eventName, EventSubscriptionOptions? options = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (string.IsNullOrEmpty(connectionId))");
        sb.AppendLine("                throw new ArgumentException(\"Connection ID cannot be null or empty\", nameof(connectionId));");
        sb.AppendLine("            if (string.IsNullOrEmpty(eventName))");
        sb.AppendLine("                throw new ArgumentException(\"Event name cannot be null or empty\", nameof(eventName));");
        sb.AppendLine();
        sb.AppendLine("            ThrowIfDisposed();");
        sb.AppendLine();
        sb.AppendLine("            options ??= EventSubscriptionOptions.Default;");
        sb.AppendLine("            var subscriptionKey = GetSubscriptionKey(connectionId, eventName);");
        sb.AppendLine();
        sb.AppendLine("            // 存储订阅选项");
        sb.AppendLine("            _subscriptionOptions[subscriptionKey] = options;");
        sb.AppendLine();
        sb.AppendLine("            // 添加到事件订阅表");
        sb.AppendLine("            var eventSubscriptions = _eventSubscriptions.GetOrAdd(eventName, _ => new ConcurrentHashSet<SubscriptionEntry>());");
        sb.AppendLine("            var entry = new SubscriptionEntry(connectionId, DateTime.UtcNow, options);");
        sb.AppendLine("            eventSubscriptions.Add(entry);");
        sb.AppendLine();
        sb.AppendLine("            // 添加到连接订阅表");
        sb.AppendLine("            var connectionSubscriptions = _connectionSubscriptions.GetOrAdd(connectionId, _ => new ConcurrentHashSet<string>());");
        sb.AppendLine("            connectionSubscriptions.Add(eventName);");
        sb.AppendLine();
        sb.AppendLine("            // 更新指标");
        sb.AppendLine("            _metrics.RecordSubscription(eventName);");
        sb.AppendLine();
        sb.AppendLine("            // 触发事件");
        sb.AppendLine("            SubscriptionChanged?.Invoke(this, new SubscriptionChangedEventArgs(");
        sb.AppendLine("                connectionId, eventName, SubscriptionChangeType.Added, options));");
        sb.AppendLine();
        sb.AppendLine("            _logger.LogDebug(\"Client {ConnectionId} subscribed to event {EventName}\", connectionId, eventName);");
        sb.AppendLine();
        sb.AppendLine("            await Task.CompletedTask;");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GenerateUnsubscribeMethod(StringBuilder sb)
    {
        sb.AppendLine("        /// <inheritdoc/>");
        sb.AppendLine("        public async Task UnsubscribeAsync(string connectionId, string eventName)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (string.IsNullOrEmpty(connectionId))");
        sb.AppendLine("                throw new ArgumentException(\"Connection ID cannot be null or empty\", nameof(connectionId));");
        sb.AppendLine("            if (string.IsNullOrEmpty(eventName))");
        sb.AppendLine("                throw new ArgumentException(\"Event name cannot be null or empty\", nameof(eventName));");
        sb.AppendLine();
        sb.AppendLine("            ThrowIfDisposed();");
        sb.AppendLine();
        sb.AppendLine("            var subscriptionKey = GetSubscriptionKey(connectionId, eventName);");
        sb.AppendLine("            var removed = false;");
        sb.AppendLine();
        sb.AppendLine("            // 从事件订阅表中移除");
        sb.AppendLine("            if (_eventSubscriptions.TryGetValue(eventName, out var eventSubscriptions))");
        sb.AppendLine("            {");
        sb.AppendLine("                var entryToRemove = eventSubscriptions.FirstOrDefault(e => e.ConnectionId == connectionId);");
        sb.AppendLine("                if (entryToRemove != null)");
        sb.AppendLine("                {");
        sb.AppendLine("                    eventSubscriptions.Remove(entryToRemove);");
        sb.AppendLine("                    removed = true;");
        sb.AppendLine();
        sb.AppendLine("                    // 如果没有订阅者了，移除整个事件条目");
        sb.AppendLine("                    if (eventSubscriptions.Count == 0)");
        sb.AppendLine("                    {");
        sb.AppendLine("                        _eventSubscriptions.TryRemove(eventName, out _);");
        sb.AppendLine("                    }");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            // 从连接订阅表中移除");
        sb.AppendLine("            if (_connectionSubscriptions.TryGetValue(connectionId, out var connectionSubscriptions))");
        sb.AppendLine("            {");
        sb.AppendLine("                connectionSubscriptions.Remove(eventName);");
        sb.AppendLine();
        sb.AppendLine("                // 如果连接没有订阅了，移除整个连接条目");
        sb.AppendLine("                if (connectionSubscriptions.Count == 0)");
        sb.AppendLine("                {");
        sb.AppendLine("                    _connectionSubscriptions.TryRemove(connectionId, out _);");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            // 移除订阅选项");
        sb.AppendLine("            _subscriptionOptions.TryRemove(subscriptionKey, out var options);");
        sb.AppendLine();
        sb.AppendLine("            if (removed)");
        sb.AppendLine("            {");
        sb.AppendLine("                // 更新指标");
        sb.AppendLine("                _metrics.RecordUnsubscription(eventName);");
        sb.AppendLine();
        sb.AppendLine("                // 触发事件");
        sb.AppendLine("                SubscriptionChanged?.Invoke(this, new SubscriptionChangedEventArgs(");
        sb.AppendLine("                    connectionId, eventName, SubscriptionChangeType.Removed, options));");
        sb.AppendLine();
        sb.AppendLine("                _logger.LogDebug(\"Client {ConnectionId} unsubscribed from event {EventName}\", connectionId, eventName);");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            await Task.CompletedTask;");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GenerateQueryMethods(StringBuilder sb)
    {
        sb.AppendLine("        /// <inheritdoc/>");
        sb.AppendLine("        public IReadOnlyList<string> GetSubscribers(string eventName)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (string.IsNullOrEmpty(eventName))");
        sb.AppendLine("                return Array.Empty<string>();");
        sb.AppendLine();
        sb.AppendLine("            return _eventSubscriptions.TryGetValue(eventName, out var subscribers)");
        sb.AppendLine("                ? subscribers.Select(s => s.ConnectionId).ToList()");
        sb.AppendLine("                : Array.Empty<string>();");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        /// <inheritdoc/>");
        sb.AppendLine("        public IReadOnlyList<string> GetSubscriptions(string connectionId)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (string.IsNullOrEmpty(connectionId))");
        sb.AppendLine("                return Array.Empty<string>();");
        sb.AppendLine();
        sb.AppendLine("            return _connectionSubscriptions.TryGetValue(connectionId, out var subscriptions)");
        sb.AppendLine("                ? subscriptions.ToList()");
        sb.AppendLine("                : Array.Empty<string>();");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        /// <inheritdoc/>");
        sb.AppendLine("        public IReadOnlyList<string> GetSubscribersByTags(Dictionary<string, string> tags)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (tags == null || tags.Count == 0)");
        sb.AppendLine("                return Array.Empty<string>();");
        sb.AppendLine();
        sb.AppendLine("            var result = new List<string>();");
        sb.AppendLine();
        sb.AppendLine("            foreach (var eventSubscriptions in _eventSubscriptions.Values)");
        sb.AppendLine("            {");
        sb.AppendLine("                foreach (var entry in eventSubscriptions.ToList())");
        sb.AppendLine("                {");
        sb.AppendLine("                    if (entry.Options.Tags != null && TagsMatch(entry.Options.Tags, tags))");
        sb.AppendLine("                    {");
        sb.AppendLine("                        result.Add(entry.ConnectionId);");
        sb.AppendLine("                    }");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return result.Distinct().ToList();");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        /// <inheritdoc/>");
        sb.AppendLine("        public SubscriptionStatistics GetStatistics()");
        sb.AppendLine("        {");
        sb.AppendLine("            return new SubscriptionStatistics");
        sb.AppendLine("            {");
        sb.AppendLine("                TotalEvents = _eventSubscriptions.Count,");
        sb.AppendLine("                TotalConnections = _connectionSubscriptions.Count,");
        sb.AppendLine("                TotalSubscriptions = _eventSubscriptions.Values.Sum(s => s.Count),");
        sb.AppendLine("                EventMetrics = _metrics.GetSnapshot()");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GenerateCleanupMethods(StringBuilder sb)
    {
        sb.AppendLine("        /// <inheritdoc/>");
        sb.AppendLine("        public async Task CleanupDisconnectedSubscriptionsAsync()");
        sb.AppendLine("        {");
        sb.AppendLine("            ThrowIfDisposed();");
        sb.AppendLine();
        sb.AppendLine("            var cleanupTasks = new List<Task>();");
        sb.AppendLine("            var now = DateTime.UtcNow;");
        sb.AppendLine();
        sb.AppendLine("            // 清理超时的订阅（如果有配置超时时间）");
        sb.AppendLine("            foreach (var kvp in _eventSubscriptions.ToList())");
        sb.AppendLine("            {");
        sb.AppendLine("                var eventName = kvp.Key;");
        sb.AppendLine("                var subscriptions = kvp.Value;");
        sb.AppendLine();
        sb.AppendLine("                var expiredEntries = subscriptions.Where(entry =>");
        sb.AppendLine("                    entry.Options.TimeToLive.HasValue &&");
        sb.AppendLine("                    now - entry.SubscribeTime > entry.Options.TimeToLive.Value).ToList();");
        sb.AppendLine();
        sb.AppendLine("                foreach (var expiredEntry in expiredEntries)");
        sb.AppendLine("                {");
        sb.AppendLine("                    cleanupTasks.Add(UnsubscribeAsync(expiredEntry.ConnectionId, eventName));");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            if (cleanupTasks.Count > 0)");
        sb.AppendLine("            {");
        sb.AppendLine("                await Task.WhenAll(cleanupTasks);");
        sb.AppendLine("                _logger.LogInformation(\"Cleaned up {Count} expired subscriptions\", cleanupTasks.Count);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 辅助方法
        sb.AppendLine("        private static string GetSubscriptionKey(string connectionId, string eventName)");
        sb.AppendLine("        {");
        sb.AppendLine("            return $\"{connectionId}:{eventName}\";");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private static bool TagsMatch(Dictionary<string, string> entryTags, Dictionary<string, string> queryTags)");
        sb.AppendLine("        {");
        sb.AppendLine("            return queryTags.All(queryTag =>");
        sb.AppendLine("                entryTags.TryGetValue(queryTag.Key, out var value) && value == queryTag.Value);");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private void ThrowIfDisposed()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_disposed)");
        sb.AppendLine("                throw new ObjectDisposedException(nameof(GeneratedEventSubscriptionManager));");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GenerateDisposeMethod(StringBuilder sb)
    {
        sb.AppendLine("        public void Dispose()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_disposed) return;");
        sb.AppendLine();
        sb.AppendLine("            _cleanupTimer?.Dispose();");
        sb.AppendLine("            _eventSubscriptions.Clear();");
        sb.AppendLine("            _connectionSubscriptions.Clear();");
        sb.AppendLine("            _subscriptionOptions.Clear();");
        sb.AppendLine();
        sb.AppendLine("            _disposed = true;");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GenerateSubscriptionSupportTypes(StringBuilder sb)
    {
        // EventSubscriptionOptions
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 事件订阅选项");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public sealed class EventSubscriptionOptions");
        sb.AppendLine("    {");
        sb.AppendLine("        public static EventSubscriptionOptions Default { get; } = new();");
        sb.AppendLine();
        sb.AppendLine("        public Func<object, bool>? Filter { get; set; }");
        sb.AppendLine("        public EventPriority Priority { get; set; } = EventPriority.Normal;");
        sb.AppendLine("        public Dictionary<string, string> Tags { get; set; } = new();");
        sb.AppendLine("        public TimeSpan? TimeToLive { get; set; }");
        sb.AppendLine("        public int MaxQueueSize { get; set; } = 1000;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // EventPriority
        sb.AppendLine("    public enum EventPriority");
        sb.AppendLine("    {");
        sb.AppendLine("        Low = 0,");
        sb.AppendLine("        Normal = 1,");
        sb.AppendLine("        High = 2,");
        sb.AppendLine("        Critical = 3");
        sb.AppendLine("    }");
        sb.AppendLine();

        // SubscriptionEntry
        sb.AppendLine("    internal sealed class SubscriptionEntry");
        sb.AppendLine("    {");
        sb.AppendLine("        public string ConnectionId { get; }");
        sb.AppendLine("        public DateTime SubscribeTime { get; }");
        sb.AppendLine("        public EventSubscriptionOptions Options { get; }");
        sb.AppendLine();
        sb.AppendLine("        public SubscriptionEntry(string connectionId, DateTime subscribeTime, EventSubscriptionOptions options)");
        sb.AppendLine("        {");
        sb.AppendLine("            ConnectionId = connectionId;");
        sb.AppendLine("            SubscribeTime = subscribeTime;");
        sb.AppendLine("            Options = options;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public override bool Equals(object? obj)");
        sb.AppendLine("        {");
        sb.AppendLine("            return obj is SubscriptionEntry other && ConnectionId == other.ConnectionId;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public override int GetHashCode()");
        sb.AppendLine("        {");
        sb.AppendLine("            return ConnectionId.GetHashCode();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // 其他支持类型
        GenerateAdditionalSupportTypes(sb);

        // 结束命名空间
        sb.AppendLine("}");
    }

    private static void GenerateAdditionalSupportTypes(StringBuilder sb)
    {
        // SubscriptionChangedEventArgs
        sb.AppendLine("    public sealed class SubscriptionChangedEventArgs : EventArgs");
        sb.AppendLine("    {");
        sb.AppendLine("        public string ConnectionId { get; }");
        sb.AppendLine("        public string EventName { get; }");
        sb.AppendLine("        public SubscriptionChangeType ChangeType { get; }");
        sb.AppendLine("        public EventSubscriptionOptions? Options { get; }");
        sb.AppendLine();
        sb.AppendLine("        public SubscriptionChangedEventArgs(string connectionId, string eventName,");
        sb.AppendLine("            SubscriptionChangeType changeType, EventSubscriptionOptions? options = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            ConnectionId = connectionId;");
        sb.AppendLine("            EventName = eventName;");
        sb.AppendLine("            ChangeType = changeType;");
        sb.AppendLine("            Options = options;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // SubscriptionChangeType
        sb.AppendLine("    public enum SubscriptionChangeType");
        sb.AppendLine("    {");
        sb.AppendLine("        Added,");
        sb.AppendLine("        Removed,");
        sb.AppendLine("        Modified");
        sb.AppendLine("    }");
        sb.AppendLine();

        // SubscriptionStatistics
        sb.AppendLine("    public sealed class SubscriptionStatistics");
        sb.AppendLine("    {");
        sb.AppendLine("        public int TotalEvents { get; init; }");
        sb.AppendLine("        public int TotalConnections { get; init; }");
        sb.AppendLine("        public int TotalSubscriptions { get; init; }");
        sb.AppendLine("        public Dictionary<string, long> EventMetrics { get; init; } = new();");
        sb.AppendLine("    }");
        sb.AppendLine();

        // SubscriptionMetrics
        sb.AppendLine("    internal sealed class SubscriptionMetrics");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly ConcurrentDictionary<string, long> _eventCounts = new();");
        sb.AppendLine();
        sb.AppendLine("        public void RecordSubscription(string eventName)");
        sb.AppendLine("        {");
        sb.AppendLine("            _eventCounts.AddOrUpdate(eventName, 1, (_, count) => count + 1);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public void RecordUnsubscription(string eventName)");
        sb.AppendLine("        {");
        sb.AppendLine("            _eventCounts.AddOrUpdate(eventName, 0, (_, count) => Math.Max(0, count - 1));");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public Dictionary<string, long> GetSnapshot()");
        sb.AppendLine("        {");
        sb.AppendLine("            return new Dictionary<string, long>(_eventCounts);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ConcurrentHashSet
        sb.AppendLine("    internal sealed class ConcurrentHashSet<T> : IDisposable where T : notnull");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly HashSet<T> _set = new();");
        sb.AppendLine("        private readonly ReaderWriterLockSlim _lock = new();");
        sb.AppendLine();
        sb.AppendLine("        public int Count");
        sb.AppendLine("        {");
        sb.AppendLine("            get");
        sb.AppendLine("            {");
        sb.AppendLine("                _lock.EnterReadLock();");
        sb.AppendLine("                try { return _set.Count; }");
        sb.AppendLine("                finally { _lock.ExitReadLock(); }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public bool Add(T item)");
        sb.AppendLine("        {");
        sb.AppendLine("            _lock.EnterWriteLock();");
        sb.AppendLine("            try { return _set.Add(item); }");
        sb.AppendLine("            finally { _lock.ExitWriteLock(); }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public bool Remove(T item)");
        sb.AppendLine("        {");
        sb.AppendLine("            _lock.EnterWriteLock();");
        sb.AppendLine("            try { return _set.Remove(item); }");
        sb.AppendLine("            finally { _lock.ExitWriteLock(); }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public T? FirstOrDefault(Func<T, bool> predicate)");
        sb.AppendLine("        {");
        sb.AppendLine("            _lock.EnterReadLock();");
        sb.AppendLine("            try { return _set.FirstOrDefault(predicate); }");
        sb.AppendLine("            finally { _lock.ExitReadLock(); }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public List<T> Where(Func<T, bool> predicate)");
        sb.AppendLine("        {");
        sb.AppendLine("            _lock.EnterReadLock();");
        sb.AppendLine("            try { return _set.Where(predicate).ToList(); }");
        sb.AppendLine("            finally { _lock.ExitReadLock(); }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public List<TResult> Select<TResult>(Func<T, TResult> selector)");
        sb.AppendLine("        {");
        sb.AppendLine("            _lock.EnterReadLock();");
        sb.AppendLine("            try { return _set.Select(selector).ToList(); }");
        sb.AppendLine("            finally { _lock.ExitReadLock(); }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public List<T> ToList()");
        sb.AppendLine("        {");
        sb.AppendLine("            _lock.EnterReadLock();");
        sb.AppendLine("            try { return new List<T>(_set); }");
        sb.AppendLine("            finally { _lock.ExitReadLock(); }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public void Dispose()");
        sb.AppendLine("        {");
        sb.AppendLine("            _lock?.Dispose();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }
}