using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using PulseRPC.Server.SourceGenerator.Models;

namespace PulseRPC.Server.SourceGenerator.Generators;

/// <summary>
/// 编译时消息分发器生成器 - 消除运行时反射开销
/// </summary>
public static class MessageDispatcherGenerator
{
    /// <summary>
    /// 生成编译时消息分发器代码
    /// </summary>
    public static string GenerateSourceText(List<ServiceModel> serviceModels)
    {
        var code = new StringBuilder();

        // 生成文件头
        GenerateFileHeader(code, serviceModels);

        // 生成命名空间和类开始
        GenerateClassHeader(code);

        // 生成消息类型映射
        GenerateMessageTypeMapping(code, serviceModels);

        // 生成处理器映射
        GenerateHandlerMapping(code, serviceModels);

        // 生成服务代理映射
        GenerateServiceProxyMapping(code, serviceModels);

        // 生成 Hub + Method 元数据映射
        GenerateHandlerMetadataMap(code, serviceModels);

        // 生成元数据访问辅助方法
        GenerateHandlerMetadataHelpers(code);

        // 生成注册方法
        GenerateRegistrationMethod(code, serviceModels);

        // 生成快速分发方法
        GenerateDispatchMethod(code, serviceModels);

        // 生成字节流直接分发方法
        GenerateDispatchFromBytesMethod(code, serviceModels);

        // 生成服务初始化方法
        GenerateServiceInitializationMethod(code, serviceModels);


        // 生成统计和监控方法
        GenerateStatisticsMethod(code, serviceModels);

        // 生成类结尾
        GenerateClassFooter(code);

        return code.ToString();
    }

    /// <summary>
    /// 生成文件头
    /// </summary>
    private static void GenerateFileHeader(StringBuilder code, List<ServiceModel> serviceModels)
    {
        code.AppendLine("// <auto-generated />");
        code.AppendLine("// 此文件由PulseRPC Source Generator自动生成");
        code.AppendLine("// 警告: 请勿手动修改此文件，所有更改都会在下次生成时被覆盖");
        code.AppendLine();
        code.AppendLine("#nullable enable");
        code.AppendLine("#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释");
        code.AppendLine();
        code.AppendLine("using System;");
        code.AppendLine("using System.Collections.Generic;");
        code.AppendLine("using System.Collections.Concurrent;");
        code.AppendLine("using System.Linq;");
        code.AppendLine("using System.Threading;");
        code.AppendLine("using System.Threading.Tasks;");
        code.AppendLine("using System.Runtime.CompilerServices;");
        code.AppendLine("using System.Diagnostics;");
        code.AppendLine("using Microsoft.Extensions.Logging;");
        code.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        code.AppendLine("using PulseRPC.Server.Engine;");
        code.AppendLine("using PulseRPC.Server.Abstractions;");

        // 添加服务命名空间
        var namespaces = serviceModels.Select(s => s.Namespace).Where(ns => !string.IsNullOrEmpty(ns)).Distinct().ToList();
        foreach (var ns in namespaces)
        {
            code.AppendLine($"using {ns};");
        }

        code.AppendLine();
    }

    /// <summary>
    /// 生成类头部
    /// </summary>
    private static void GenerateClassHeader(StringBuilder code)
    {
        code.AppendLine("namespace PulseRPC.Generated;");
        code.AppendLine();
        code.AppendLine("/// <summary>");
        code.AppendLine("/// 编译时生成的高性能消息分发器");
        code.AppendLine("/// 特性:");
        code.AppendLine("/// - 零反射开销");
        code.AppendLine("/// - 预编译方法查找");
        code.AppendLine("/// - 内联优化支持");
        code.AppendLine("/// - AOT编译兼容");
        code.AppendLine("/// </summary>");
        code.AppendLine("public sealed class CompiledMessageDispatcher : PulseRPC.Server.Engine.AbstractCompiledMessageDispatcher");
        code.AppendLine("{");
    }

    /// <summary>
    /// 生成消息类型映射
    /// </summary>
    private static void GenerateMessageTypeMapping(StringBuilder code, List<ServiceModel> serviceModels)
    {
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 预编译的消息类型映射 - 避免运行时Type.GetType调用");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    private static readonly Dictionary<string, Type> MessageTypeMap = new(StringComparer.Ordinal)");
        code.AppendLine("    {");

        var allMessageTypes = new HashSet<string>();
        foreach (var service in serviceModels)
        {
            foreach (var method in service.Methods)
            {
                // 参数类型作为请求类型
                if (method.IsSingleParameter && !allMessageTypes.Contains(method.FirstParameter!.TypeFullName))
                {
                    allMessageTypes.Add(method.FirstParameter!.TypeFullName);
                    code.AppendLine($"        [\"{method.FirstParameter!.TypeFullName}\"] = typeof({method.FirstParameter!.TypeFullName}),");
                }

                // 返回类型作为响应类型
                if (!string.IsNullOrEmpty(method.ReturnTypeFullName) && method.ReturnTypeFullName != "void" &&
                    method.ReturnTypeFullName != "System.Threading.Tasks.Task" &&
                    !allMessageTypes.Contains(method.ReturnTypeFullName))
                {
                    allMessageTypes.Add(method.ReturnTypeFullName);
                    code.AppendLine($"        [\"{method.ReturnTypeFullName}\"] = typeof({method.ReturnTypeFullName}),");
                }
            }
        }

        code.AppendLine("    };");
        code.AppendLine();
    }

    /// <summary>
    /// 生成服务代理映射 - 直接映射到生成的代理类，无需 IServiceProvider
    /// </summary>
    private static void GenerateServiceProxyMapping(StringBuilder code, List<ServiceModel> serviceModels)
    {
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 服务代理映射 - 运行时初始化");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    private readonly Dictionary<string, IGeneratedServiceProxy> ServiceProxyMap = new(StringComparer.Ordinal);");
        code.AppendLine();

        // 生成服务实例字段 - 通过静态初始化方法设置
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 静态服务实例 - 由运行时初始化设置");
        code.AppendLine("    /// </summary>");
        foreach (var service in serviceModels)
        {
            var serviceInstanceField = $"_{service.InterfaceName.TrimStart('I').ToLower()}Instance";
            code.AppendLine($"    private {service.InterfaceFullName}? {serviceInstanceField};");
        }
        code.AppendLine();
    }

    /// <summary>
    /// 生成 Hub + Method 元数据映射，用于高性能反序列化
    /// </summary>
    private static void GenerateHandlerMetadataMap(StringBuilder code, List<ServiceModel> serviceModels)
    {
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 编译时生成的 Hub + Method 元数据映射 - 支持零反射反序列化");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    private static readonly Dictionary<string, Dictionary<string, HandlerMetadata>> HandlerMetadataMap = new(StringComparer.Ordinal)");
        code.AppendLine("    {");

        foreach (var service in serviceModels)
        {
            var methodItems = service.Methods;
            var keys = new List<string> { service.InterfaceFullName };
            if (!string.IsNullOrEmpty(service.ServiceName) && !keys.Contains(service.ServiceName!))
            {
                keys.Add(service.ServiceName!);
            }

            foreach (var key in keys)
            {
                code.AppendLine($"        [\"{key}\"] = new Dictionary<string, HandlerMetadata>(StringComparer.Ordinal)");
                code.AppendLine("        {");

                foreach (var method in methodItems)
                {
                    var metadataInitializer = BuildHandlerMetadataInitializer(service, method, key);
                    code.Append(metadataInitializer);
                }

                code.AppendLine("        },");
            }
        }

        code.AppendLine("    };");
        code.AppendLine();
    }

    /// <summary>
    /// 生成元数据访问方法
    /// 注意：HandlerMetadata 类型定义在运行时 PulseRPC.Server.Engine 命名空间
    /// </summary>
    private static void GenerateHandlerMetadataHelpers(StringBuilder code)
    {
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 尝试获取指定 Hub 与方法的预编译元数据");
        code.AppendLine("    /// 实现 AbstractCompiledMessageDispatcher.TryGetHandlerMetadata");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    public override bool TryGetHandlerMetadata(string serviceName, string methodName, [System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out HandlerMetadata? metadata)");
        code.AppendLine("    {");
        code.AppendLine("        if (HandlerMetadataMap.TryGetValue(serviceName, out var methods) && methods.TryGetValue(methodName, out metadata))");
        code.AppendLine("        {");
        code.AppendLine("            return true;");
        code.AppendLine("        }");
        code.AppendLine("        metadata = null;");
        code.AppendLine("        return false;");
        code.AppendLine("    }");
        code.AppendLine();
    }

    private static string BuildHandlerMetadataInitializer(ServiceModel service, MethodModel method, string serviceKey)
    {
        var indent = "            ";
        var builder = new StringBuilder();

        // 使用运行时 HandlerMetadata 构造函数
        builder.Append($"{indent}[\"{method.MethodName}\"] = new HandlerMetadata(");
        builder.AppendLine();
        builder.AppendLine($"{indent}    serviceName: \"{service.InterfaceFullName}\",");
        builder.AppendLine($"{indent}    methodName: \"{method.MethodName}\",");
        builder.AppendLine($"{indent}    requestType: {GetRequestTypeExpression(method)},");
        builder.AppendLine($"{indent}    responseType: {GetResponseTypeExpression(method)},");
        builder.AppendLine($"{indent}    requestIsMemoryPackable: {GetRequestIsMemoryPackable(method)},");
        builder.AppendLine($"{indent}    responseIsMemoryPackable: {GetResponseIsMemoryPackable(method)},");
        builder.AppendLine($"{indent}    isOneWay: {IsOneWayMethod(method)},");
        builder.AppendLine($"{indent}    signature: \"{service.InterfaceFullName}.{method.MethodName}\"),");

        return builder.ToString();
    }

    private static string GetRequestTypeExpression(MethodModel method)
    {
        if (method.FirstParameter == null)
        {
            return "null";
        }

        return $"typeof({method.FirstParameter.TypeFullName})";
    }

    private static string GetResponseTypeExpression(MethodModel method)
    {
        if (string.IsNullOrEmpty(method.ReturnTypeFullName) || method.ReturnTypeFullName == "void" || method.ReturnTypeFullName == "System.Void")
        {
            return "null";
        }

        if (IsTaskTypeWithoutResult(method.ReturnTypeFullName))
        {
            return "null";
        }

        if (method.ReturnTypeFullName.StartsWith("System.Threading.Tasks.Task<", StringComparison.Ordinal))
        {
            var payloadType = ExtractGenericType(method.ReturnTypeFullName);
            return payloadType != null ? $"typeof({payloadType})" : "null";
        }

        if (method.ReturnTypeFullName.StartsWith("System.Threading.Tasks.ValueTask<", StringComparison.Ordinal))
        {
            var payloadType = ExtractGenericType(method.ReturnTypeFullName);
            return payloadType != null ? $"typeof({payloadType})" : "null";
        }

        return $"typeof({method.ReturnTypeFullName})";
    }

    private static string GetReturnTypeExpression(MethodModel method)
    {
        if (string.IsNullOrEmpty(method.ReturnTypeFullName) || method.ReturnTypeFullName == "void" || method.ReturnTypeFullName == "System.Void")
        {
            return "null";
        }

        return $"typeof({method.ReturnTypeFullName})";
    }

    private static string GetRequestTypeFullName(MethodModel method)
    {
        if (method.FirstParameter == null)
        {
            return "null";
        }

        return $"\"{method.FirstParameter.TypeFullName}\"";
    }

    private static string GetResponseTypeFullName(MethodModel method)
    {
        if (string.IsNullOrEmpty(method.ReturnTypeFullName) || method.ReturnTypeFullName == "void" || method.ReturnTypeFullName == "System.Void")
        {
            return "null";
        }

        var payloadType = GetResponsePayloadType(method.ReturnTypeFullName);
        return payloadType != null ? $"\"{payloadType}\"" : "null";
    }

    private static string GetReturnTypeFullName(MethodModel method)
    {
        if (string.IsNullOrEmpty(method.ReturnTypeFullName) || method.ReturnTypeFullName == "void" || method.ReturnTypeFullName == "System.Void")
        {
            return "null";
        }

        return $"\"{method.ReturnTypeFullName}\"";
    }

    private static string GetRequestIsMemoryPackable(MethodModel method)
    {
        return method.FirstParameter?.IsMemoryPackable == true ? "true" : "false";
    }

    private static string GetResponseIsMemoryPackable(MethodModel method)
    {
        var payloadType = GetResponsePayloadType(method.ReturnTypeFullName);
        if (payloadType == null)
        {
            return "false";
        }

        // TODO: 增强 MemoryPackable 检测（当前生成器尚未标记响应类型）
        return "false";
    }

    private static string IsValueTask(MethodModel method)
    {
        if (string.IsNullOrEmpty(method.ReturnTypeFullName))
        {
            return "false";
        }

        return method.ReturnTypeFullName.StartsWith("System.Threading.Tasks.ValueTask", StringComparison.Ordinal)
            ? "true"
            : "false";
    }

    private static bool IsTaskTypeWithoutResult(string? typeFullName)
    {
        if (string.IsNullOrEmpty(typeFullName))
        {
            return false;
        }

        return string.Equals(typeFullName, "System.Threading.Tasks.Task", StringComparison.Ordinal) ||
               string.Equals(typeFullName, "System.Threading.Tasks.ValueTask", StringComparison.Ordinal);
    }

    private static string? GetResponsePayloadType(string? returnTypeFullName)
    {
        if (string.IsNullOrEmpty(returnTypeFullName))
        {
            return null;
        }

        if (returnTypeFullName!.StartsWith("System.Threading.Tasks.Task<", StringComparison.Ordinal) ||
            returnTypeFullName.StartsWith("System.Threading.Tasks.ValueTask<", StringComparison.Ordinal))
        {
            return ExtractGenericType(returnTypeFullName);
        }

        if (returnTypeFullName == "void" || returnTypeFullName == "System.Void")
        {
            return null;
        }

        return returnTypeFullName;
    }

    private static string? ExtractGenericType(string typeFullName)
    {
        var start = typeFullName.IndexOf('<');
        var end = typeFullName.LastIndexOf('>');

        if (start < 0 || end <= start + 1)
        {
            return null;
        }

        return typeFullName.Substring(start + 1, end - start - 1);
    }

    private static string IsOneWayMethod(MethodModel method)
    {
        // 单向方法：返回类型为 void、Task 或 ValueTask（无结果）
        bool isOneWay = string.IsNullOrEmpty(method.ReturnTypeFullName) ||
                        method.ReturnTypeFullName == "void" ||
                        method.ReturnTypeFullName == "System.Void" ||
                        method.ReturnTypeFullName == "System.Threading.Tasks.Task" ||
                        method.ReturnTypeFullName == "System.Threading.Tasks.ValueTask";
        return isOneWay.ToString().ToLowerInvariant();
    }

    /// <summary>
    /// 生成处理器映射
    /// </summary>
    private static void GenerateHandlerMapping(StringBuilder code, List<ServiceModel> serviceModels)
    {
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 预编译的消息处理器映射 - 直接方法调用，无反射开销");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    private readonly Dictionary<Type, MessageHandlerInfo> HandlerMap;");
        code.AppendLine();
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 构造函数 - 初始化处理器映射");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    public CompiledMessageDispatcher()");
        code.AppendLine("    {");
        code.AppendLine("        HandlerMap = new Dictionary<Type, MessageHandlerInfo>");
        code.AppendLine("        {");

        foreach (var service in serviceModels)
        {
            foreach (var method in service.Methods)
            {
                if (method.IsSingleParameter)
                {
                    var handlerName = $"Handle{service.InterfaceName.TrimStart('I')}{method.MethodName}";
                    var isAsync = method.IsAsync;
                    var serviceName = service.InterfaceName;

                    code.AppendLine($"        [typeof({method.FirstParameter!.TypeFullName})] = new MessageHandlerInfo");
                    code.AppendLine("        {");
                    code.AppendLine($"            ServiceType = typeof({serviceName}),");
                    code.AppendLine($"            MethodName = \"{method.MethodName}\",");
                    code.AppendLine($"            IsAsync = {isAsync.ToString().ToLower()},");
                    code.AppendLine($"            Handler = (message, cancellationToken) => this.{handlerName}(message, cancellationToken),");
                    code.AppendLine($"            Priority = MessagePriority.{GetMessagePriority(method)},");
                    code.AppendLine($"            EstimatedLatencyMs = {GetEstimatedLatency(method)},");
                    code.AppendLine("        },");
                }
            }
        }

        code.AppendLine("        };");
        code.AppendLine("    }");
        code.AppendLine();
    }

    /// <summary>
    /// 生成注册方法 - 让运行时分发器可以注册编译时生成的处理器
    /// </summary>
    private static void GenerateRegistrationMethod(StringBuilder code, List<ServiceModel> serviceModels)
    {
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 将编译时生成的处理器注册到运行时分发器");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    public override void RegisterHandlers(IStaticMessageDispatcher dispatcher)");
        code.AppendLine("    {");
        code.AppendLine("        if (dispatcher == null)");
        code.AppendLine("            throw new ArgumentNullException(nameof(dispatcher));");
        code.AppendLine();

        foreach (var service in serviceModels)
        {
            foreach (var method in service.Methods)
            {
                if (method.IsSingleParameter)
                {
                    var handlerName = $"Handle{service.InterfaceName.TrimStart('I')}{method.MethodName}";
                    var requestType = method.FirstParameter!.TypeFullName;

                    code.AppendLine($"        // 注册 {service.InterfaceName}.{method.MethodName}");
                    code.AppendLine($"        dispatcher.RegisterHandler<{requestType}>(this.{handlerName});");
                }
            }
        }

        code.AppendLine("    }");
        code.AppendLine();

    }

    /// <summary>
    /// 生成快速分发方法
    /// </summary>
    private static void GenerateDispatchMethod(StringBuilder code, List<ServiceModel> serviceModels)
    {
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 高性能消息分发 - 编译时优化的快速路径");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        code.AppendLine("    public override async ValueTask<object?> DispatchAsync(");
        code.AppendLine("        object message, ");
        code.AppendLine("        CancellationToken cancellationToken = default)");
        code.AppendLine("    {");
        code.AppendLine("        var messageType = message.GetType();");
        code.AppendLine("        ");
        code.AppendLine("        // 快速路径：预编译的类型检查和分发");
        code.AppendLine("        if (HandlerMap.TryGetValue(messageType, out var handlerInfo))");
        code.AppendLine("        {");
        code.AppendLine("            var startTime = Stopwatch.GetTimestamp();");
        code.AppendLine("            ");
        code.AppendLine("            try");
        code.AppendLine("            {");
        code.AppendLine("                var result = await handlerInfo.Handler(message, cancellationToken);");
        code.AppendLine("                ");
        code.AppendLine("                // 记录成功指标");
        code.AppendLine("                var elapsedMs = (Stopwatch.GetTimestamp() - startTime) * 1000.0 / Stopwatch.Frequency;");
        code.AppendLine("                Metrics.RecordDispatchSuccess(messageType.Name, elapsedMs);");
        code.AppendLine("                ");
        code.AppendLine("                return result;");
        code.AppendLine("            }");
        code.AppendLine("            catch (Exception ex)");
        code.AppendLine("            {");
        code.AppendLine("                // 记录错误指标");
        code.AppendLine("                var elapsedMs = (Stopwatch.GetTimestamp() - startTime) * 1000.0 / Stopwatch.Frequency;");
        code.AppendLine("                Metrics.RecordDispatchError(messageType.Name, elapsedMs, ex);");
        code.AppendLine("                throw;");
        code.AppendLine("            }");
        code.AppendLine("        }");
        code.AppendLine("        ");
        code.AppendLine("        // 慢速路径：未识别的消息类型");
        code.AppendLine("        Metrics.RecordUnknownMessageType(messageType.Name);");
        code.AppendLine("        throw new InvalidOperationException($\"未找到消息类型 '{messageType.Name}' 的处理器\");");
        code.AppendLine("    }");
        code.AppendLine();
    }

    /// <summary>
    /// 生成字节流直接分发方法 - 零反射，高性能路径
    /// </summary>
    private static void GenerateDispatchFromBytesMethod(StringBuilder code, List<ServiceModel> serviceModels)
    {
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 直接从字节流分发到服务代理 - 无需反序列化为中间对象");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        code.AppendLine("    public override async ValueTask<object?> DispatchFromBytesAsync(");
        code.AppendLine("        string serviceName,");
        code.AppendLine("        string methodName,");
        code.AppendLine("        ReadOnlyMemory<byte> payloadData,");
        code.AppendLine("        CancellationToken cancellationToken = default)");
        code.AppendLine("    {");
        code.AppendLine("        // 快速路径：直接查找服务代理");
        code.AppendLine("        if (ServiceProxyMap.TryGetValue(serviceName, out var proxy))");
        code.AppendLine("        {");
        code.AppendLine("            var startTime = Stopwatch.GetTimestamp();");
        code.AppendLine("            ");
        code.AppendLine("            try");
        code.AppendLine("            {");
        code.AppendLine("                // 直接调用生成的代理方法");
        code.AppendLine("                var result = await proxy.InvokeAsync(methodName, payloadData, cancellationToken);");
        code.AppendLine("                ");
        code.AppendLine("                // 记录成功指标");
        code.AppendLine("                var elapsedMs = (Stopwatch.GetTimestamp() - startTime) * 1000.0 / Stopwatch.Frequency;");
        code.AppendLine("                Metrics.RecordDispatchSuccess($\"{serviceName}.{methodName}\", elapsedMs);");
        code.AppendLine("                ");
        code.AppendLine("                return result;");
        code.AppendLine("            }");
        code.AppendLine("            catch (Exception ex)");
        code.AppendLine("            {");
        code.AppendLine("                // 记录错误指标");
        code.AppendLine("                var elapsedMs = (Stopwatch.GetTimestamp() - startTime) * 1000.0 / Stopwatch.Frequency;");
        code.AppendLine("                Metrics.RecordDispatchError($\"{serviceName}.{methodName}\", elapsedMs, ex);");
        code.AppendLine("                throw;");
        code.AppendLine("            }");
        code.AppendLine("        }");
        code.AppendLine("        ");
        code.AppendLine("        // 慢速路径：未找到服务");
        code.AppendLine("        Metrics.RecordUnknownMessageType($\"{serviceName}.{methodName}\");");
        code.AppendLine("        throw new ServiceNotFoundException($\"服务 '{serviceName}' 未找到或未注册\");");
        code.AppendLine("    }");
        code.AppendLine();
    }

    /// <summary>
    /// 生成服务初始化方法
    /// </summary>
    private static void GenerateServiceInitializationMethod(StringBuilder code, List<ServiceModel> serviceModels)
    {
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 初始化服务实例 - 由运行时调用");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    public override void InitializeServices(IServiceProvider serviceProvider)");
        code.AppendLine("    {");
        code.AppendLine("        if (serviceProvider == null)");
        code.AppendLine("            throw new ArgumentNullException(nameof(serviceProvider));");
        code.AppendLine("        ");

        foreach (var service in serviceModels)
        {
            var serviceInstanceField = $"_{service.InterfaceName.TrimStart('I').ToLower()}Instance";
            code.AppendLine($"        {serviceInstanceField} = serviceProvider.GetRequiredService<{service.InterfaceFullName}>();");
        }

        code.AppendLine("        ");
        code.AppendLine("        // 注册服务代理");
        foreach (var service in serviceModels)
        {
            var serviceInstanceField = $"_{service.InterfaceName.TrimStart('I').ToLower()}Instance";
            var proxyClassName = $"{service.InterfaceName.TrimStart('I')}Proxy";
            code.AppendLine($"        ServiceProxyMap[\"{service.InterfaceFullName}\"] = new {service.Namespace}.Generated.{proxyClassName}({serviceInstanceField}!);");
        }

        code.AppendLine("        ");
        code.AppendLine("        // 标记为已初始化");
        code.AppendLine("        _isInitialized = true;");
        code.AppendLine("    }");
        code.AppendLine();
    }


    /// <summary>
    /// 生成具体的处理器方法
    /// </summary>
    private static void GenerateHandlerMethods(StringBuilder code, List<ServiceModel> serviceModels)
    {
        foreach (var service in serviceModels)
        {
            foreach (var method in service.Methods)
            {
                if (method.IsSingleParameter)
                {
                    var handlerName = $"Handle{service.InterfaceName.TrimStart('I')}{method.MethodName}";
                    var serviceName = service.InterfaceName;
                    var requestType = method.FirstParameter!.TypeFullName;
                    var responseType = method.ReturnTypeFullName ?? "object";
                    var isAsync = method.IsAsync;

                    code.AppendLine($"    /// <summary>");
                    code.AppendLine($"    /// 生成的处理器：{serviceName}.{method.MethodName}");
                    code.AppendLine($"    /// </summary>");
                    code.AppendLine($"    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                    code.AppendLine($"    private async ValueTask<object?> {handlerName}(");
                    code.AppendLine($"        object message, ");
                    code.AppendLine($"        CancellationToken cancellationToken)");
                    code.AppendLine($"    {{");
                    code.AppendLine($"        var typedMessage = ({requestType})message;");
                    var serviceInstanceField = $"_{service.InterfaceName.TrimStart('I').ToLower()}Instance";
                    code.AppendLine($"        var service = {serviceInstanceField} ?? throw new InvalidOperationException(\"Service {serviceName} not initialized. Call InitializeServices first.\");");
                    code.AppendLine($"        ");

                    if (isAsync)
                    {
                        if (responseType == "void" || responseType == "System.Threading.Tasks.Task" || responseType == "System.Threading.Tasks.ValueTask")
                        {
                            code.AppendLine($"        await service.{method.MethodName}(typedMessage).ConfigureAwait(false);");
                            code.AppendLine($"        return null;");
                        }
                        else
                        {
                            code.AppendLine($"        var result = await service.{method.MethodName}(typedMessage).ConfigureAwait(false);");
                            code.AppendLine($"        return result;");
                        }
                    }
                    else
                    {
                        if (responseType == "void")
                        {
                            code.AppendLine($"        service.{method.MethodName}(typedMessage);");
                            code.AppendLine($"        return null;");
                        }
                        else
                        {
                            code.AppendLine($"        var result = service.{method.MethodName}(typedMessage);");
                            code.AppendLine($"        return result;");
                        }
                    }

                    code.AppendLine($"    }}");
                    code.AppendLine();
                }
            }
        }
    }

    /// <summary>
    /// 生成统计和监控方法
    /// </summary>
    private static void GenerateStatisticsMethod(StringBuilder code, List<ServiceModel> serviceModels)
    {
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 获取分发器统计信息");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    public override object GetStatistics()");
        code.AppendLine("    {");
        code.AppendLine("        return new DispatcherStatistics");
        code.AppendLine("        {");
        code.AppendLine($"            TotalHandlers = {GetTotalHandlerCount(serviceModels)},");
        code.AppendLine($"            TotalServices = {serviceModels.Count},");
        code.AppendLine("            Metrics = Metrics.GetSnapshot(),");
        code.AppendLine($"            GeneratedAt = DateTime.UtcNow,");
        code.AppendLine("            HandlerMap = HandlerMap.ToDictionary(");
        code.AppendLine("                kvp => kvp.Key.Name, ");
        code.AppendLine("                kvp => kvp.Value)");
        code.AppendLine("        };");
        code.AppendLine("    }");
        code.AppendLine();

        // 生成 IsInitialized 属性
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 检查是否已正确初始化");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    public override bool IsInitialized => _isInitialized;");
        code.AppendLine();
        code.AppendLine("    private bool _isInitialized;");
        code.AppendLine();

        // 生成性能指标类
        GenerateMetricsClass(code);

        // 生成统计数据类
        GenerateStatisticsDataClasses(code);

        // 生成具体的处理器方法
        GenerateHandlerMethods(code, serviceModels);
    }

    /// <summary>
    /// 生成性能指标类
    /// </summary>
    private static void GenerateMetricsClass(StringBuilder code)
    {
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 分发器性能指标");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    public static class Metrics");
        code.AppendLine("    {");
        code.AppendLine("        private static readonly ConcurrentDictionary<string, long> SuccessCount = new();");
        code.AppendLine("        private static readonly ConcurrentDictionary<string, long> ErrorCount = new();");
        code.AppendLine("        private static readonly ConcurrentDictionary<string, double> TotalLatency = new();");
        code.AppendLine("        private static readonly ConcurrentDictionary<string, long> UnknownTypes = new();");
        code.AppendLine("        ");
        code.AppendLine("        public static void RecordDispatchSuccess(string messageType, double latencyMs)");
        code.AppendLine("        {");
        code.AppendLine("            SuccessCount.AddOrUpdate(messageType, 1, (_, count) => count + 1);");
        code.AppendLine("            TotalLatency.AddOrUpdate(messageType, latencyMs, (_, total) => total + latencyMs);");
        code.AppendLine("        }");
        code.AppendLine("        ");
        code.AppendLine("        public static void RecordDispatchError(string messageType, double latencyMs, Exception ex)");
        code.AppendLine("        {");
        code.AppendLine("            ErrorCount.AddOrUpdate(messageType, 1, (_, count) => count + 1);");
        code.AppendLine("            TotalLatency.AddOrUpdate(messageType, latencyMs, (_, total) => total + latencyMs);");
        code.AppendLine("        }");
        code.AppendLine("        ");
        code.AppendLine("        public static void RecordUnknownMessageType(string messageType)");
        code.AppendLine("        {");
        code.AppendLine("            UnknownTypes.AddOrUpdate(messageType, 1, (_, count) => count + 1);");
        code.AppendLine("        }");
        code.AppendLine("        ");
        code.AppendLine("        public static MetricsSnapshot GetSnapshot()");
        code.AppendLine("        {");
        code.AppendLine("            return new MetricsSnapshot");
        code.AppendLine("            {");
        code.AppendLine("                SuccessCount = new Dictionary<string, long>(SuccessCount),");
        code.AppendLine("                ErrorCount = new Dictionary<string, long>(ErrorCount),");
        code.AppendLine("                TotalLatency = new Dictionary<string, double>(TotalLatency),");
        code.AppendLine("                UnknownTypes = new Dictionary<string, long>(UnknownTypes)");
        code.AppendLine("            };");
        code.AppendLine("        }");
        code.AppendLine("    }");
        code.AppendLine();
    }

    /// <summary>
    /// 生成统计数据类
    /// </summary>
    private static void GenerateStatisticsDataClasses(StringBuilder code)
    {
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 消息处理器信息");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    public class MessageHandlerInfo");
        code.AppendLine("    {");
        code.AppendLine("        public Type ServiceType { get; set; } = null!;");
        code.AppendLine("        public string MethodName { get; set; } = null!;");
        code.AppendLine("        public bool IsAsync { get; set; }");
        code.AppendLine("        public Func<object, CancellationToken, ValueTask<object?>> Handler { get; set; } = null!;");
        code.AppendLine("        public MessagePriority Priority { get; set; }");
        code.AppendLine("        public double EstimatedLatencyMs { get; set; }");
        code.AppendLine("    }");
        code.AppendLine();

        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 分发器统计信息");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    public class DispatcherStatistics");
        code.AppendLine("    {");
        code.AppendLine("        public int TotalHandlers { get; set; }");
        code.AppendLine("        public int TotalServices { get; set; }");
        code.AppendLine("        public MetricsSnapshot Metrics { get; set; } = null!;");
        code.AppendLine("        public DateTime GeneratedAt { get; set; }");
        code.AppendLine("        public Dictionary<string, MessageHandlerInfo> HandlerMap { get; set; } = null!;");
        code.AppendLine("    }");
        code.AppendLine();

        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 性能指标快照");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    public class MetricsSnapshot");
        code.AppendLine("    {");
        code.AppendLine("        public Dictionary<string, long> SuccessCount { get; set; } = null!;");
        code.AppendLine("        public Dictionary<string, long> ErrorCount { get; set; } = null!;");
        code.AppendLine("        public Dictionary<string, double> TotalLatency { get; set; } = null!;");
        code.AppendLine("        public Dictionary<string, long> UnknownTypes { get; set; } = null!;");
        code.AppendLine("    }");
        code.AppendLine();

        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 消息优先级");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    public enum MessagePriority");
        code.AppendLine("    {");
        code.AppendLine("        Low = 0,");
        code.AppendLine("        Normal = 1,");
        code.AppendLine("        High = 2,");
        code.AppendLine("        Critical = 3");
        code.AppendLine("    }");
        code.AppendLine();
    }

    /// <summary>
    /// 生成类结尾
    /// </summary>
    private static void GenerateClassFooter(StringBuilder code)
    {
        code.AppendLine("}");
        code.AppendLine();
        code.AppendLine("#pragma warning restore CS1591");
    }

    /// <summary>
    /// 获取消息优先级
    /// </summary>
    private static string GetMessagePriority(MethodModel method)
    {
        // 根据方法特性推断优先级
        if (method.MethodName.Contains("Critical") || method.MethodName.Contains("Emergency"))
            return "Critical";
        if (method.MethodName.Contains("High") || method.MethodName.Contains("Priority"))
            return "High";
        if (method.MethodName.Contains("Low") || method.MethodName.Contains("Background"))
            return "Low";
        return "Normal";
    }

    /// <summary>
    /// 获取预估延迟
    /// </summary>
    private static double GetEstimatedLatency(MethodModel method)
    {
        // 根据方法复杂度预估延迟
        if (method.IsAsync)
            return 2.0; // 异步方法通常更快
        if (method.MethodName.Contains("Query") || method.MethodName.Contains("Get"))
            return 1.0; // 查询操作较快
        if (method.MethodName.Contains("Create") || method.MethodName.Contains("Update"))
            return 5.0; // 写入操作较慢
        return 3.0; // 默认延迟
    }

    /// <summary>
    /// 获取总处理器数量
    /// </summary>
    private static int GetTotalHandlerCount(List<ServiceModel> serviceModels)
    {
        return serviceModels.Sum(s => s.Methods.Count(m => m.IsSingleParameter));
    }
}
