using System.Collections.Generic;
using System.Linq;
using System.Text;
using PulseRPC.Server.SourceGenerator.Models;

namespace PulseRPC.Server.SourceGenerator.Generators;

/// <summary>
/// 性能优化代码生成器 - 生成高性能的事件处理和发布代码
/// </summary>
public static class PerformanceOptimizationGenerator
{
    /// <summary>
    /// 生成性能优化代码
    /// </summary>
    public static string GenerateSourceText(List<ServiceModel> serviceModels)
    {
        var sb = new StringBuilder();

        GenerateFileHeader(sb);
        GenerateHighPerformanceEventPublisher(sb, serviceModels);
        GenerateBatchEventProcessor(sb);
        GenerateMemoryPooledSerializer(sb);
        GenerateHotPathOptimizations(sb);
        GeneratePerformanceMetrics(sb);

        return sb.ToString();
    }

    private static void GenerateFileHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// PulseRPC Performance Optimization Generator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Buffers;");
        sb.AppendLine("using System.Collections.Concurrent;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.IO.Pipelines;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Channels;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine("using Microsoft.Extensions.ObjectPool;");
        sb.AppendLine("using PulseRPC.Server.Transport;");
        sb.AppendLine("using PulseRPC.Server.Events;");
        sb.AppendLine();
    }

    private static void GenerateHighPerformanceEventPublisher(StringBuilder sb, List<ServiceModel> serviceModels)
    {
        sb.AppendLine("namespace PulseRPC.Server.Events");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 高性能事件发布器 - 零拷贝、内存池化、批量处理");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public sealed class HighPerformanceEventPublisher : IEventPublisher, IDisposable");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly IServerChannelManager _channelManager;");
        sb.AppendLine("        private readonly IEventSubscriptionManager _subscriptionManager;");
        sb.AppendLine("        private readonly ISmartEventRouter _eventRouter;");
        sb.AppendLine("        private readonly ILogger<HighPerformanceEventPublisher> _logger;");
        sb.AppendLine("        private readonly PooledEventSerializer _serializer;");
        sb.AppendLine("        private readonly BatchEventProcessor _batchProcessor;");
        sb.AppendLine("        private readonly PerformanceMetricsCollector _metrics;");
        sb.AppendLine("        private readonly ArrayPool<byte> _arrayPool = ArrayPool<byte>.Shared;");
        sb.AppendLine("        private readonly ConcurrentQueue<PendingEvent> _hotPathQueue = new();");
        sb.AppendLine("        private readonly Timer _hotPathProcessor;");
        sb.AppendLine("        private bool _disposed;");
        sb.AppendLine();

        // 构造函数
        sb.AppendLine("        public HighPerformanceEventPublisher(");
        sb.AppendLine("            IServerChannelManager channelManager,");
        sb.AppendLine("            IEventSubscriptionManager subscriptionManager,");
        sb.AppendLine("            ISmartEventRouter eventRouter,");
        sb.AppendLine("            ILogger<HighPerformanceEventPublisher> logger)");
        sb.AppendLine("        {");
        sb.AppendLine("            _channelManager = channelManager ?? throw new ArgumentNullException(nameof(channelManager));");
        sb.AppendLine("            _subscriptionManager = subscriptionManager ?? throw new ArgumentNullException(nameof(subscriptionManager));");
        sb.AppendLine("            _eventRouter = eventRouter ?? throw new ArgumentNullException(nameof(eventRouter));");
        sb.AppendLine("            _logger = logger ?? throw new ArgumentNullException(nameof(logger));");
        sb.AppendLine("            _serializer = new PooledEventSerializer();");
        sb.AppendLine("            _batchProcessor = new BatchEventProcessor(_metrics = new PerformanceMetricsCollector());");
        sb.AppendLine("            ");
        sb.AppendLine("            // 热路径处理器：每1ms处理一次");
        sb.AppendLine("            _hotPathProcessor = new Timer(ProcessHotPathEvents, null,");
        sb.AppendLine("                TimeSpan.FromMilliseconds(1), TimeSpan.FromMilliseconds(1));");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 生成主要发布方法
        GeneratePublishMethods(sb);

        // 生成热路径优化方法
        GenerateHotPathMethods(sb);

        // 生成性能监控方法
        GeneratePerformanceMonitoringMethods(sb);

        // 生成Dispose方法
        GeneratePublisherDisposeMethod(sb);

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GeneratePublishMethods(StringBuilder sb)
    {
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 高性能事件发布 - 零拷贝、智能路由");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        public async Task PublishEventAsync<T>(string eventName, T eventData)");
        sb.AppendLine("        {");
        sb.AppendLine("            ThrowIfDisposed();");
        sb.AppendLine("            ");
        sb.AppendLine("            using var activity = _metrics.StartEventPublishing(eventName);");
        sb.AppendLine("            ");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                // 对于高频事件，使用热路径优化");
        sb.AppendLine("                if (IsHotPathEvent(eventName))");
        sb.AppendLine("                {");
        sb.AppendLine("                    await PublishHotPathEventAsync(eventName, eventData);");
        sb.AppendLine("                    return;");
        sb.AppendLine("                }");
        sb.AppendLine("                ");
        sb.AppendLine("                // 智能路由");
        sb.AppendLine("                var context = CreateRoutingContext();");
        sb.AppendLine("                var publishedCount = await _eventRouter.RouteAndPublishAsync(eventName, eventData, context);");
        sb.AppendLine("                ");
        sb.AppendLine("                _metrics.RecordEventPublished(eventName, publishedCount);");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine("                _metrics.RecordEventError(eventName, ex);");
        sb.AppendLine("                _logger.LogError(ex, \"Failed to publish event {EventName}\", eventName);");
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 批量事件发布 - 优化多事件发布性能");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public async Task PublishBatchEventsAsync<T>(IEnumerable<(string EventName, T EventData)> events)");
        sb.AppendLine("        {");
        sb.AppendLine("            ThrowIfDisposed();");
        sb.AppendLine("            ");
        sb.AppendLine("            var eventList = events.ToList();");
        sb.AppendLine("            if (eventList.Count == 0) return;");
        sb.AppendLine("            ");
        sb.AppendLine("            using var activity = _metrics.StartBatchPublishing(eventList.Count);");
        sb.AppendLine("            ");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                await _batchProcessor.ProcessBatchAsync(eventList);");
        sb.AppendLine("                _metrics.RecordBatchPublished(eventList.Count);");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine("                _metrics.RecordBatchError(ex);");
        sb.AppendLine("                _logger.LogError(ex, \"Failed to publish batch of {Count} events\", eventList.Count);");
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 零拷贝事件发布 - 直接使用预序列化数据");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public async Task PublishPreSerializedEventAsync(string eventName, ReadOnlyMemory<byte> serializedData)");
        sb.AppendLine("        {");
        sb.AppendLine("            ThrowIfDisposed();");
        sb.AppendLine("            ");
        sb.AppendLine("            var subscribers = _subscriptionManager.GetSubscribers(eventName);");
        sb.AppendLine("            if (!subscribers.Any()) return;");
        sb.AppendLine("            ");
        sb.AppendLine("            var channels = _channelManager.GetAuthenticatedChannels()");
        sb.AppendLine("                .Where(c => subscribers.Contains(c.ConnectionId))");
        sb.AppendLine("                .ToList();");
        sb.AppendLine("            ");
        sb.AppendLine("            await SendToChannelsZeroCopyAsync(channels, serializedData);");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GenerateHotPathMethods(StringBuilder sb)
    {
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 热路径事件发布 - 极致性能优化");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        private async ValueTask PublishHotPathEventAsync<T>(string eventName, T eventData)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 使用无锁队列进行预处理");
        sb.AppendLine("            var pendingEvent = new PendingEvent(eventName, eventData!, typeof(T));");
        sb.AppendLine("            _hotPathQueue.Enqueue(pendingEvent);");
        sb.AppendLine("            ");
        sb.AppendLine("            // 如果队列过长，立即处理");
        sb.AppendLine("            if (_hotPathQueue.Count > 100)");
        sb.AppendLine("            {");
        sb.AppendLine("                ProcessHotPathEvents(null);");
        sb.AppendLine("            }");
        sb.AppendLine("            ");
        sb.AppendLine("            await ValueTask.CompletedTask;");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private void ProcessHotPathEvents(object? state)");
        sb.AppendLine("        {");
        sb.AppendLine("            var events = new List<PendingEvent>();");
        sb.AppendLine("            ");
        sb.AppendLine("            // 批量出队");
        sb.AppendLine("            while (events.Count < 50 && _hotPathQueue.TryDequeue(out var evt))");
        sb.AppendLine("            {");
        sb.AppendLine("                events.Add(evt);");
        sb.AppendLine("            }");
        sb.AppendLine("            ");
        sb.AppendLine("            if (events.Count == 0) return;");
        sb.AppendLine("            ");
        sb.AppendLine("            // 异步处理，避免阻塞定时器");
        sb.AppendLine("            _ = Task.Run(async () =>");
        sb.AppendLine("            {");
        sb.AppendLine("                try");
        sb.AppendLine("                {");
        sb.AppendLine("                    await ProcessHotPathEventsBatchAsync(events);");
        sb.AppendLine("                }");
        sb.AppendLine("                catch (Exception ex)");
        sb.AppendLine("                {");
        sb.AppendLine("                    _logger.LogError(ex, \"Error processing hot path events batch\");");
        sb.AppendLine("                }");
        sb.AppendLine("            });");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private async Task ProcessHotPathEventsBatchAsync(List<PendingEvent> events)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 按事件名分组");
        sb.AppendLine("            var groupedEvents = events.GroupBy(e => e.EventName);");
        sb.AppendLine("            ");
        sb.AppendLine("            var tasks = groupedEvents.Select(async group =>");
        sb.AppendLine("            {");
        sb.AppendLine("                var eventName = group.Key;");
        sb.AppendLine("                var subscribers = _subscriptionManager.GetSubscribers(eventName);");
        sb.AppendLine("                ");
        sb.AppendLine("                if (!subscribers.Any()) return;");
        sb.AppendLine("                ");
        sb.AppendLine("                var channels = _channelManager.GetAuthenticatedChannels()");
        sb.AppendLine("                    .Where(c => subscribers.Contains(c.ConnectionId))");
        sb.AppendLine("                    .ToList();");
        sb.AppendLine("                ");
        sb.AppendLine("                // 批量序列化和发送");
        sb.AppendLine("                foreach (var evt in group)");
        sb.AppendLine("                {");
        sb.AppendLine("                    var serializedData = _serializer.SerializeFast(evt.EventData, evt.EventType);");
        sb.AppendLine("                    await SendToChannelsZeroCopyAsync(channels, serializedData);");
        sb.AppendLine("                }");
        sb.AppendLine("            });");
        sb.AppendLine("            ");
        sb.AppendLine("            await Task.WhenAll(tasks);");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GeneratePerformanceMonitoringMethods(StringBuilder sb)
    {
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 获取性能指标");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public PerformanceMetrics GetPerformanceMetrics()");
        sb.AppendLine("        {");
        sb.AppendLine("            return _metrics.GetSnapshot();");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 辅助方法
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        private static bool IsHotPathEvent(string eventName)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 高频事件模式匹配");
        sb.AppendLine("            return eventName.Contains(\"Realtime\") || ");
        sb.AppendLine("                   eventName.Contains(\"Position\") || ");
        sb.AppendLine("                   eventName.Contains(\"Heartbeat\") ||");
        sb.AppendLine("                   eventName.EndsWith(\"Update\");");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private static EventRoutingContext CreateRoutingContext()");
        sb.AppendLine("        {");
        sb.AppendLine("            return new EventRoutingContext");
        sb.AppendLine("            {");
        sb.AppendLine("                Timestamp = DateTime.UtcNow");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        private static async ValueTask SendToChannelsZeroCopyAsync(");
        sb.AppendLine("            IEnumerable<IServerChannel> channels, ReadOnlyMemory<byte> data)");
        sb.AppendLine("        {");
        sb.AppendLine("            var tasks = channels.Select(async channel =>");
        sb.AppendLine("            {");
        sb.AppendLine("                try");
        sb.AppendLine("                {");
        sb.AppendLine("                    await channel.SendAsync(data, CancellationToken.None);");
        sb.AppendLine("                }");
        sb.AppendLine("                catch");
        sb.AppendLine("                {");
        sb.AppendLine("                    // 忽略发送失败，避免影响其他通道");
        sb.AppendLine("                }");
        sb.AppendLine("            });");
        sb.AppendLine("            ");
        sb.AppendLine("            await Task.WhenAll(tasks);");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private void ThrowIfDisposed()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_disposed)");
        sb.AppendLine("                throw new ObjectDisposedException(nameof(HighPerformanceEventPublisher));");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GeneratePublisherDisposeMethod(StringBuilder sb)
    {
        sb.AppendLine("        public void Dispose()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_disposed) return;");
        sb.AppendLine("            ");
        sb.AppendLine("            _hotPathProcessor?.Dispose();");
        sb.AppendLine("            _batchProcessor?.Dispose();");
        sb.AppendLine("            _serializer?.Dispose();");
        sb.AppendLine("            ");
        sb.AppendLine("            // 清空队列");
        sb.AppendLine("            while (_hotPathQueue.TryDequeue(out _)) { }");
        sb.AppendLine("            ");
        sb.AppendLine("            _disposed = true;");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GenerateBatchEventProcessor(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 批量事件处理器 - 优化批量事件处理性能");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal sealed class BatchEventProcessor : IDisposable");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly PerformanceMetricsCollector _metrics;");
        sb.AppendLine("        private readonly SemaphoreSlim _processingLock = new(1, 1);");
        sb.AppendLine();

        sb.AppendLine("        public BatchEventProcessor(PerformanceMetricsCollector metrics)");
        sb.AppendLine("        {");
        sb.AppendLine("            _metrics = metrics;");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        public async Task ProcessBatchAsync<T>(IList<(string EventName, T EventData)> events)");
        sb.AppendLine("        {");
        sb.AppendLine("            await _processingLock.WaitAsync();");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                // 分组处理相同类型的事件");
        sb.AppendLine("                var groupedEvents = events.GroupBy(e => e.EventName);");
        sb.AppendLine("                ");
        sb.AppendLine("                var tasks = groupedEvents.Select(ProcessEventGroupAsync);");
        sb.AppendLine("                await Task.WhenAll(tasks);");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                _processingLock.Release();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private static async Task ProcessEventGroupAsync<T>(IGrouping<string, (string EventName, T EventData)> group)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 这里可以进一步优化相同事件类型的批量处理");
        sb.AppendLine("            await Task.Delay(1); // 占位符");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        public void Dispose()");
        sb.AppendLine("        {");
        sb.AppendLine("            _processingLock?.Dispose();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateMemoryPooledSerializer(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 内存池化序列化器 - 减少GC压力");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal sealed class PooledEventSerializer : IDisposable");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly ArrayPool<byte> _arrayPool = ArrayPool<byte>.Shared;");
        sb.AppendLine("        private readonly ConcurrentQueue<byte[]> _bufferCache = new();");
        sb.AppendLine();

        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        public ReadOnlyMemory<byte> SerializeFast<T>(T data, Type? dataType = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 获取缓存的缓冲区");
        sb.AppendLine("            var buffer = GetBuffer();");
        sb.AppendLine("            ");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                // 这里应该使用实际的序列化器（如MemoryPack）");
        sb.AppendLine("                // 目前返回空数据作为占位符");
        sb.AppendLine("                return ReadOnlyMemory<byte>.Empty;");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                ReturnBuffer(buffer);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private byte[] GetBuffer()");
        sb.AppendLine("        {");
        sb.AppendLine("            return _bufferCache.TryDequeue(out var buffer) ? buffer : _arrayPool.Rent(4096);");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private void ReturnBuffer(byte[] buffer)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_bufferCache.Count < 100) // 限制缓存大小");
        sb.AppendLine("            {");
        sb.AppendLine("                _bufferCache.Enqueue(buffer);");
        sb.AppendLine("            }");
        sb.AppendLine("            else");
        sb.AppendLine("            {");
        sb.AppendLine("                _arrayPool.Return(buffer);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        public void Dispose()");
        sb.AppendLine("        {");
        sb.AppendLine("            // 归还所有缓存的缓冲区");
        sb.AppendLine("            while (_bufferCache.TryDequeue(out var buffer))");
        sb.AppendLine("            {");
        sb.AppendLine("                _arrayPool.Return(buffer);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateHotPathOptimizations(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 待处理事件（热路径优化）");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal readonly struct PendingEvent");
        sb.AppendLine("    {");
        sb.AppendLine("        public string EventName { get; }");
        sb.AppendLine("        public object EventData { get; }");
        sb.AppendLine("        public Type EventType { get; }");
        sb.AppendLine("        public DateTime Timestamp { get; }");
        sb.AppendLine();

        sb.AppendLine("        public PendingEvent(string eventName, object eventData, Type eventType)");
        sb.AppendLine("        {");
        sb.AppendLine("            EventName = eventName;");
        sb.AppendLine("            EventData = eventData;");
        sb.AppendLine("            EventType = eventType;");
        sb.AppendLine("            Timestamp = DateTime.UtcNow;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GeneratePerformanceMetrics(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 性能指标收集器");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal sealed class PerformanceMetricsCollector");
        sb.AppendLine("    {");
        sb.AppendLine("        private long _eventsPublished;");
        sb.AppendLine("        private long _batchesProcessed;");
        sb.AppendLine("        private long _errors;");
        sb.AppendLine("        private readonly ConcurrentDictionary<string, PerformanceMetric> _eventMetrics = new();");
        sb.AppendLine();

        sb.AppendLine("        public IDisposable StartEventPublishing(string eventName)");
        sb.AppendLine("        {");
        sb.AppendLine("            return new EventPublishingActivity(eventName, this);");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        public IDisposable StartBatchPublishing(int eventCount)");
        sb.AppendLine("        {");
        sb.AppendLine("            return new BatchPublishingActivity(eventCount, this);");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        public void RecordEventPublished(string eventName, int subscriberCount)");
        sb.AppendLine("        {");
        sb.AppendLine("            Interlocked.Increment(ref _eventsPublished);");
        sb.AppendLine("            ");
        sb.AppendLine("            var metric = _eventMetrics.GetOrAdd(eventName, _ => new PerformanceMetric());");
        sb.AppendLine("            Interlocked.Increment(ref metric.Count);");
        sb.AppendLine("            Interlocked.Add(ref metric.TotalSubscribers, subscriberCount);");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        public void RecordEventError(string eventName, Exception exception)");
        sb.AppendLine("        {");
        sb.AppendLine("            Interlocked.Increment(ref _errors);");
        sb.AppendLine("            ");
        sb.AppendLine("            var metric = _eventMetrics.GetOrAdd(eventName, _ => new PerformanceMetric());");
        sb.AppendLine("            Interlocked.Increment(ref metric.Errors);");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        public void RecordBatchPublished(int eventCount)");
        sb.AppendLine("        {");
        sb.AppendLine("            Interlocked.Increment(ref _batchesProcessed);");
        sb.AppendLine("            Interlocked.Add(ref _eventsPublished, eventCount);");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        public void RecordBatchError(Exception exception)");
        sb.AppendLine("        {");
        sb.AppendLine("            Interlocked.Increment(ref _errors);");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        public PerformanceMetrics GetSnapshot()");
        sb.AppendLine("        {");
        sb.AppendLine("            return new PerformanceMetrics");
        sb.AppendLine("            {");
        sb.AppendLine("                TotalEventsPublished = _eventsPublished,");
        sb.AppendLine("                TotalBatchesProcessed = _batchesProcessed,");
        sb.AppendLine("                TotalErrors = _errors,");
        sb.AppendLine("                EventMetrics = new Dictionary<string, PerformanceMetric>(_eventMetrics)");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 生成内部活动类
        sb.AppendLine("        private sealed class EventPublishingActivity : IDisposable");
        sb.AppendLine("        {");
        sb.AppendLine("            private readonly string _eventName;");
        sb.AppendLine("            private readonly PerformanceMetricsCollector _collector;");
        sb.AppendLine("            private readonly System.Diagnostics.Stopwatch _stopwatch;");
        sb.AppendLine();

        sb.AppendLine("            public EventPublishingActivity(string eventName, PerformanceMetricsCollector collector)");
        sb.AppendLine("            {");
        sb.AppendLine("                _eventName = eventName;");
        sb.AppendLine("                _collector = collector;");
        sb.AppendLine("                _stopwatch = System.Diagnostics.Stopwatch.StartNew();");
        sb.AppendLine("            }");
        sb.AppendLine();

        sb.AppendLine("            public void Dispose()");
        sb.AppendLine("            {");
        sb.AppendLine("                _stopwatch.Stop();");
        sb.AppendLine("                // 记录耗时等其他指标");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private sealed class BatchPublishingActivity : IDisposable");
        sb.AppendLine("        {");
        sb.AppendLine("            private readonly int _eventCount;");
        sb.AppendLine("            private readonly PerformanceMetricsCollector _collector;");
        sb.AppendLine("            private readonly System.Diagnostics.Stopwatch _stopwatch;");
        sb.AppendLine();

        sb.AppendLine("            public BatchPublishingActivity(int eventCount, PerformanceMetricsCollector collector)");
        sb.AppendLine("            {");
        sb.AppendLine("                _eventCount = eventCount;");
        sb.AppendLine("                _collector = collector;");
        sb.AppendLine("                _stopwatch = System.Diagnostics.Stopwatch.StartNew();");
        sb.AppendLine("            }");
        sb.AppendLine();

        sb.AppendLine("            public void Dispose()");
        sb.AppendLine("            {");
        sb.AppendLine("                _stopwatch.Stop();");
        sb.AppendLine("                // 记录批量处理指标");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // 生成指标数据结构
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 性能指标");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public sealed class PerformanceMetrics");
        sb.AppendLine("    {");
        sb.AppendLine("        public long TotalEventsPublished { get; init; }");
        sb.AppendLine("        public long TotalBatchesProcessed { get; init; }");
        sb.AppendLine("        public long TotalErrors { get; init; }");
        sb.AppendLine("        public Dictionary<string, PerformanceMetric> EventMetrics { get; init; } = new();");
        sb.AppendLine();
        sb.AppendLine("        public double ErrorRate => TotalEventsPublished > 0 ? (double)TotalErrors / TotalEventsPublished : 0;");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 单个事件的性能指标");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public sealed class PerformanceMetric");
        sb.AppendLine("    {");
        sb.AppendLine("        public long Count;");
        sb.AppendLine("        public long TotalSubscribers;");
        sb.AppendLine("        public long Errors;");
        sb.AppendLine();
        sb.AppendLine("        public double AverageSubscribers => Count > 0 ? (double)TotalSubscribers / Count : 0;");
        sb.AppendLine("        public double ErrorRate => Count > 0 ? (double)Errors / Count : 0;");
        sb.AppendLine("    }");

        // 结束命名空间
        sb.AppendLine("}");
    }
}