using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using PulseRPC.Server.SourceGenerator.Models;

namespace PulseRPC.Server.SourceGenerator.Generators;

/// <summary>
/// 接收器代理生成器 - 为 IPulseReceiver 接口生成服务端推送代码
/// </summary>
/// <remarks>
/// 生成内容：
/// - XxxReceiverProxy: 实现接收器接口，处理序列化和发送
/// - XxxReceiverHubContext: 实现 IHubContext&lt;TReceiver&gt;
/// - XxxReceiverHubClients: 实现 IHubClients&lt;TReceiver&gt;
/// - DI 扩展方法
/// </remarks>
public static class ReceiverProxyGenerator
{
    /// <summary>
    /// 生成接收器代理代码
    /// </summary>
    public static string GenerateReceiverProxy(ReceiverModel receiver)
    {
        var sb = new StringBuilder();

        GenerateFileHeader(sb, receiver);
        GenerateUsingStatements(sb);

        sb.AppendLine($"namespace {receiver.Namespace}.Generated;");
        sb.AppendLine();

        // 生成代理类（实现接收器接口）
        GenerateProxyClass(sb, receiver);

        // 生成 HubClients 实现
        GenerateHubClientsClass(sb, receiver);

        // 生成 HubContext 实现
        GenerateHubContextClass(sb, receiver);

        // 生成 DI 扩展方法
        GenerateDIExtensions(sb, receiver);

        return sb.ToString();
    }

    /// <summary>
    /// 生成 SourceText
    /// </summary>
    public static SourceText GenerateSourceText(ReceiverModel receiver)
    {
        var code = GenerateReceiverProxy(receiver);
        return SourceText.From(code, Encoding.UTF8);
    }

    private static void GenerateFileHeader(StringBuilder sb, ReceiverModel receiver)
    {
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This code was generated by PulseRPC.Server.SourceGenerator");
        sb.AppendLine($"// Receiver proxy for {receiver.InterfaceFullName}");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
    }

    private static void GenerateUsingStatements(StringBuilder sb)
    {
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Buffers;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using MemoryPack;");
        sb.AppendLine("using PulseRPC;");
        sb.AppendLine("using PulseRPC.Server;");
        sb.AppendLine("using PulseRPC.Server.Transport;");
        sb.AppendLine("using PulseRPC.Messaging;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
    }

    /// <summary>
    /// 生成代理类 - 实现接收器接口
    /// </summary>
    private static void GenerateProxyClass(StringBuilder sb, ReceiverModel receiver)
    {
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// {receiver.InterfaceName} 的服务端代理");
        sb.AppendLine($"/// 处理序列化和消息发送");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public sealed class {receiver.ProxyClassName} : {receiver.InterfaceFullName}");
        sb.AppendLine("{");

        // 字段
        sb.AppendLine("    private readonly IEnumerable<IServerChannel> _targets;");
        sb.AppendLine();

        // 协议号常量
        GenerateProtocolIdConstants(sb, receiver);

        // 构造函数
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// 创建代理实例");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public {receiver.ProxyClassName}(IEnumerable<IServerChannel> targets)");
        sb.AppendLine("    {");
        sb.AppendLine("        _targets = targets ?? throw new ArgumentNullException(nameof(targets));");
        sb.AppendLine("    }");
        sb.AppendLine();

        // 单连接构造函数
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// 创建单连接代理实例");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public {receiver.ProxyClassName}(IServerChannel? target)");
        sb.AppendLine("    {");
        sb.AppendLine("        _targets = target != null ? new[] { target } : Array.Empty<IServerChannel>();");
        sb.AppendLine("    }");
        sb.AppendLine();

        // 生成每个方法的实现
        foreach (var method in receiver.Methods)
        {
            GenerateMethodImplementation(sb, receiver, method);
        }

        // 辅助方法
        GenerateHelperMethods(sb);

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void GenerateProtocolIdConstants(StringBuilder sb, ReceiverModel receiver)
    {
        sb.AppendLine("    // ==================== 协议号常量 ====================");
        sb.AppendLine("    // 使用 FNV-1a 哈希算法生成，确保客户端和服务端一致");
        sb.AppendLine();

        foreach (var method in receiver.Methods)
        {
            var constName = $"Protocol_{method.MethodName}";
            sb.AppendLine($"    private const ushort {constName} = 0x{method.ProtocolId:X4};");
        }
        sb.AppendLine();
    }

    private static void GenerateMethodImplementation(StringBuilder sb, ReceiverModel receiver, ReceiverMethodModel method)
    {
        var constName = $"Protocol_{method.MethodName}";

        // 生成方法签名
        sb.AppendLine($"    /// <inheritdoc/>");
        sb.Append($"    public async Task {method.MethodName}(");

        for (var i = 0; i < method.Parameters.Count; i++)
        {
            if (i > 0) sb.Append(", ");
            var param = method.Parameters[i];
            sb.Append($"{param.TypeFullName} {param.Name}");
        }

        sb.AppendLine(")");
        sb.AppendLine("    {");

        // 如果没有目标，直接返回
        sb.AppendLine("        var targetList = _targets.ToList();");
        sb.AppendLine("        if (targetList.Count == 0) return;");
        sb.AppendLine();

        // 序列化参数
        if (method.Parameters.Count == 0)
        {
            sb.AppendLine("        // 无参数方法");
            sb.AppendLine("        var payload = Array.Empty<byte>();");
        }
        else if (method.Parameters.Count == 1)
        {
            var param = method.Parameters[0];
            sb.AppendLine($"        // 序列化单个参数");
            sb.AppendLine($"        var payload = MemoryPackSerializer.Serialize({param.Name});");
        }
        else
        {
            // 多参数使用元组
            var tupleParams = string.Join(", ", method.Parameters.Select(p => p.Name));
            sb.AppendLine($"        // 序列化多个参数为元组");
            sb.AppendLine($"        var payload = MemoryPackSerializer.Serialize(({tupleParams}));");
        }
        sb.AppendLine();

        // 构造消息包
        sb.AppendLine($"        // 构造消息包（使用协议号）");
        sb.AppendLine($"        var packet = BuildEventPacket({constName}, payload);");
        sb.AppendLine();

        // 发送到所有目标
        sb.AppendLine("        // 并行发送到所有目标");
        sb.AppendLine("        var tasks = targetList.Select(async target =>");
        sb.AppendLine("        {");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                await target.SendAsync(packet, CancellationToken.None);");
        sb.AppendLine("            }");
        sb.AppendLine("            catch");
        sb.AppendLine("            {");
        sb.AppendLine("                // 忽略发送失败（连接可能已断开）");
        sb.AppendLine("            }");
        sb.AppendLine("        });");
        sb.AppendLine();
        sb.AppendLine("        await Task.WhenAll(tasks);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateHelperMethods(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 构建事件消息包");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    private static byte[] BuildEventPacket(ushort protocolId, byte[] payload)");
        sb.AppendLine("    {");
        sb.AppendLine("        var header = new MessageHeader(MessageType.Event, string.Empty, string.Empty)");
        sb.AppendLine("        {");
        sb.AppendLine("            MessageId = Guid.NewGuid(),");
        sb.AppendLine("            ProtocolId = protocolId,");
        sb.AppendLine("            Flags = MessageFlags.None,");
        sb.AppendLine("            Timestamp = DateTimeOffset.UtcNow.Ticks");
        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        var packet = new MessagePacket(header, payload);");
        sb.AppendLine("        var estimatedSize = packet.EstimateSize();");
        sb.AppendLine("        var buffer = ArrayPool<byte>.Shared.Rent(estimatedSize);");
        sb.AppendLine();
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            var bytesWritten = packet.WriteTo(buffer);");
        sb.AppendLine("            var result = new byte[bytesWritten];");
        sb.AppendLine("            Array.Copy(buffer, result, bytesWritten);");
        sb.AppendLine("            return result;");
        sb.AppendLine("        }");
        sb.AppendLine("        finally");
        sb.AppendLine("        {");
        sb.AppendLine("            ArrayPool<byte>.Shared.Return(buffer);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    /// <summary>
    /// 生成 HubClients 实现（MagicOnion 风格 API）
    /// </summary>
    private static void GenerateHubClientsClass(StringBuilder sb, ReceiverModel receiver)
    {
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// {receiver.InterfaceName} 的客户端选择器实现（MagicOnion 风格）");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public sealed class {receiver.HubClientsClassName} : IHubClients<{receiver.InterfaceFullName}>");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly IServerChannelManager _channelManager;");
        sb.AppendLine("    private readonly IUserConnectionMapping _userMapping;");
        sb.AppendLine("    private readonly IGroupManager _groupManager;");
        sb.AppendLine();

        // 构造函数
        sb.AppendLine($"    public {receiver.HubClientsClassName}(");
        sb.AppendLine("        IServerChannelManager channelManager,");
        sb.AppendLine("        IUserConnectionMapping userMapping,");
        sb.AppendLine("        IGroupManager groupManager)");
        sb.AppendLine("    {");
        sb.AppendLine("        _channelManager = channelManager;");
        sb.AppendLine("        _userMapping = userMapping;");
        sb.AppendLine("        _groupManager = groupManager;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // All 属性
        sb.AppendLine($"    /// <inheritdoc/>");
        sb.AppendLine($"    public {receiver.InterfaceFullName} All =>");
        sb.AppendLine($"        new {receiver.ProxyClassName}(_channelManager.GetAuthenticatedChannels());");
        sb.AppendLine();

        // ==================== MagicOnion 风格 API ====================

        // Single 方法（MagicOnion 风格）
        sb.AppendLine($"    /// <inheritdoc/>");
        sb.AppendLine($"    public {receiver.InterfaceFullName} Single(string connectionId) =>");
        sb.AppendLine($"        new {receiver.ProxyClassName}(_channelManager.GetChannel(connectionId));");
        sb.AppendLine();

        // Only 方法（MagicOnion 风格）
        sb.AppendLine($"    /// <inheritdoc/>");
        sb.AppendLine($"    public {receiver.InterfaceFullName} Only(IReadOnlyList<string> connectionIds)");
        sb.AppendLine("    {");
        sb.AppendLine("        var channels = connectionIds");
        sb.AppendLine("            .Select(id => _channelManager.GetChannel(id))");
        sb.AppendLine("            .Where(c => c != null)!;");
        sb.AppendLine($"        return new {receiver.ProxyClassName}(channels);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Except(string) 方法（MagicOnion 风格 - 单个排除）
        sb.AppendLine($"    /// <inheritdoc/>");
        sb.AppendLine($"    public {receiver.InterfaceFullName} Except(string connectionId)");
        sb.AppendLine("    {");
        sb.AppendLine("        var channels = _channelManager.GetAuthenticatedChannels()");
        sb.AppendLine("            .Where(c => c.ConnectionId != connectionId);");
        sb.AppendLine($"        return new {receiver.ProxyClassName}(channels);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Except(IReadOnlyList<string>) 方法（MagicOnion 风格 - 多个排除）
        sb.AppendLine($"    /// <inheritdoc/>");
        sb.AppendLine($"    public {receiver.InterfaceFullName} Except(IReadOnlyList<string> connectionIds)");
        sb.AppendLine("    {");
        sb.AppendLine("        var excluded = new HashSet<string>(connectionIds);");
        sb.AppendLine("        var channels = _channelManager.GetAuthenticatedChannels()");
        sb.AppendLine("            .Where(c => !excluded.Contains(c.ConnectionId));");
        sb.AppendLine($"        return new {receiver.ProxyClassName}(channels);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ==================== 用户和组 API ====================

        // User 方法
        sb.AppendLine($"    /// <inheritdoc/>");
        sb.AppendLine($"    public {receiver.InterfaceFullName} User(string userId)");
        sb.AppendLine("    {");
        sb.AppendLine("        var connectionIds = _userMapping.GetConnections(userId);");
        sb.AppendLine("        return Only(connectionIds.ToArray());");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Users 方法
        sb.AppendLine($"    /// <inheritdoc/>");
        sb.AppendLine($"    public {receiver.InterfaceFullName} Users(IReadOnlyList<string> userIds)");
        sb.AppendLine("    {");
        sb.AppendLine("        var connectionIds = _userMapping.GetConnections(userIds);");
        sb.AppendLine("        return Only(connectionIds.ToArray());");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Group 方法
        sb.AppendLine($"    /// <inheritdoc/>");
        sb.AppendLine($"    public {receiver.InterfaceFullName} Group(string groupName)");
        sb.AppendLine("    {");
        sb.AppendLine("        var connectionIds = _groupManager.GetGroupConnections(groupName);");
        sb.AppendLine("        return Only(connectionIds.ToArray());");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Groups 方法
        sb.AppendLine($"    /// <inheritdoc/>");
        sb.AppendLine($"    public {receiver.InterfaceFullName} Groups(IReadOnlyList<string> groupNames)");
        sb.AppendLine("    {");
        sb.AppendLine("        var connectionIds = _groupManager.GetGroupConnections(groupNames);");
        sb.AppendLine("        return Only(connectionIds.ToArray());");
        sb.AppendLine("    }");
        sb.AppendLine();

        // GroupExcept(string, string) 方法（MagicOnion 风格 - 单个排除）
        sb.AppendLine($"    /// <inheritdoc/>");
        sb.AppendLine($"    public {receiver.InterfaceFullName} GroupExcept(string groupName, string excludedConnectionId)");
        sb.AppendLine("    {");
        sb.AppendLine("        var connectionIds = _groupManager.GetGroupConnections(groupName)");
        sb.AppendLine("            .Where(id => id != excludedConnectionId)");
        sb.AppendLine("            .ToArray();");
        sb.AppendLine("        return Only(connectionIds);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // GroupExcept(string, IReadOnlyList<string>) 方法（MagicOnion 风格 - 多个排除）
        sb.AppendLine($"    /// <inheritdoc/>");
        sb.AppendLine($"    public {receiver.InterfaceFullName} GroupExcept(string groupName, IReadOnlyList<string> excludedConnectionIds)");
        sb.AppendLine("    {");
        sb.AppendLine("        var excluded = new HashSet<string>(excludedConnectionIds);");
        sb.AppendLine("        var connectionIds = _groupManager.GetGroupConnections(groupName)");
        sb.AppendLine("            .Where(id => !excluded.Contains(id))");
        sb.AppendLine("            .ToArray();");
        sb.AppendLine("        return Only(connectionIds);");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        sb.AppendLine();
    }

    /// <summary>
    /// 生成 HubContext 实现
    /// </summary>
    private static void GenerateHubContextClass(StringBuilder sb, ReceiverModel receiver)
    {
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// {receiver.InterfaceName} 的 HubContext 实现");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public sealed class {receiver.HubContextClassName} : IHubContext<{receiver.InterfaceFullName}>");
        sb.AppendLine("{");

        // 字段和属性
        sb.AppendLine($"    /// <inheritdoc/>");
        sb.AppendLine($"    public IHubClients<{receiver.InterfaceFullName}> Clients {{ get; }}");
        sb.AppendLine();
        sb.AppendLine($"    /// <inheritdoc/>");
        sb.AppendLine($"    public IGroupManager Groups {{ get; }}");
        sb.AppendLine();

        // 构造函数
        sb.AppendLine($"    public {receiver.HubContextClassName}(");
        sb.AppendLine("        IServerChannelManager channelManager,");
        sb.AppendLine("        IUserConnectionMapping userMapping,");
        sb.AppendLine("        IGroupManager groupManager)");
        sb.AppendLine("    {");
        sb.AppendLine($"        Clients = new {receiver.HubClientsClassName}(channelManager, userMapping, groupManager);");
        sb.AppendLine("        Groups = groupManager;");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        sb.AppendLine();
    }

    /// <summary>
    /// 生成 DI 扩展方法
    /// </summary>
    private static void GenerateDIExtensions(StringBuilder sb, ReceiverModel receiver)
    {
        var extensionClassName = receiver.InterfaceName.StartsWith("I")
            ? receiver.InterfaceName.Substring(1) + "Extensions"
            : receiver.InterfaceName + "Extensions";

        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// {receiver.InterfaceName} 的 DI 扩展方法");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public static class {extensionClassName}");
        sb.AppendLine("{");

        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// 注册 {receiver.InterfaceName} 的 HubContext");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public static IServiceCollection AddPulseReceiverContext<TReceiver>(this IServiceCollection services)");
        sb.AppendLine($"        where TReceiver : class, IPulseReceiver");
        sb.AppendLine("    {");
        sb.AppendLine($"        // 检查是否为 {receiver.InterfaceName}");
        sb.AppendLine($"        if (typeof(TReceiver) == typeof({receiver.InterfaceFullName}))");
        sb.AppendLine("        {");
        sb.AppendLine($"            services.AddSingleton<IHubContext<{receiver.InterfaceFullName}>, {receiver.HubContextClassName}>();");
        sb.AppendLine("        }");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // 非泛型版本
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// 注册 {receiver.InterfaceName} 的 HubContext（非泛型版本）");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public static IServiceCollection Add{receiver.InterfaceName.TrimStart('I')}HubContext(this IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine($"        services.AddSingleton<IHubContext<{receiver.InterfaceFullName}>, {receiver.HubContextClassName}>();");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");

        sb.AppendLine("}");
    }

    /// <summary>
    /// 生成所有接收器的统一 DI 扩展方法
    /// </summary>
    public static string GenerateUnifiedDIExtensions(List<ReceiverModel> receivers)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This code was generated by PulseRPC.Server.SourceGenerator");
        sb.AppendLine("// Unified DI extensions for all IPulseReceiver implementations");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using PulseRPC;");
        sb.AppendLine("using PulseRPC.Server;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();

        // 添加生成的命名空间 using（去重）
        var generatedNamespaces = receivers
            .Select(r => r.Namespace)
            .Where(ns => !string.IsNullOrWhiteSpace(ns))
            .Distinct()
            .OrderBy(ns => ns);

        foreach (var ns in generatedNamespaces)
        {
            sb.AppendLine($"using {ns}.Generated;");
        }
        sb.AppendLine();

        sb.AppendLine("namespace PulseRPC.Server.Extensions;");
        sb.AppendLine();

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// PulseReceiver 统一 DI 扩展方法");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class PulseReceiverServiceExtensions");
        sb.AppendLine("{");

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 注册所有 IPulseReceiver 的 HubContext");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IServiceCollection AddAllPulseReceiverContexts(this IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var receiver in receivers)
        {
            sb.AppendLine($"        // {receiver.InterfaceName}");
            sb.AppendLine($"        services.AddSingleton<IHubContext<{receiver.InterfaceFullName}>, {receiver.Namespace}.Generated.{receiver.HubContextClassName}>();");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// 生成协议号映射表（接收器专用）
    /// </summary>
    public static string GenerateReceiverProtocolIdMapping(List<ReceiverModel> receivers)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This code was generated by PulseRPC.Server.SourceGenerator");
        sb.AppendLine("// Protocol ID constants for IPulseReceiver interfaces");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace PulseRPC.Generated;");
        sb.AppendLine();

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// IPulseReceiver 协议号常量");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static partial class ProtocolIdMapping");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Receiver 协议号常量");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static partial class ReceiverProtocolIds");
        sb.AppendLine("    {");

        foreach (var receiver in receivers)
        {
            var shortName = receiver.InterfaceName.TrimStart('I');
            sb.AppendLine($"        // {receiver.InterfaceFullName}");

            foreach (var method in receiver.Methods)
            {
                var constName = $"{shortName}_{method.MethodName}";
                sb.AppendLine($"        public const ushort {constName} = 0x{method.ProtocolId:X4};");
            }
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}

