using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using PulseRPC.Server.SourceGenerator.Models;

namespace PulseRPC.Server.SourceGenerator.Generators;

/// <summary>
/// 接收器代理生成器 - 为 [Channel("CLIENT")] : IPulseHub 推送接收器接口生成服务端推送代码
/// </summary>
/// <remarks>
/// 生成内容：
/// - XxxReceiverProxy: 实现接收器接口，处理序列化和发送
/// - XxxReceiverHubContext: 实现 IHubContext&lt;TReceiver&gt;
/// - XxxReceiverHubClients: 实现 IHubClients&lt;TReceiver&gt;
/// - DI 扩展方法
/// </remarks>
public static class ReceiverProxyGenerator
{
    /// <summary>
    /// 生成接收器代理代码
    /// </summary>
    public static string GenerateReceiverProxy(ReceiverModel receiver)
    {
        var sb = new StringBuilder();

        GenerateFileHeader(sb, receiver);
        GenerateUsingStatements(sb);

        sb.AppendLine($"namespace {receiver.Namespace}.Generated;");
        sb.AppendLine();

        // 生成代理类（实现接收器接口）
        GenerateProxyClass(sb, receiver);

        // 生成 HubClients 实现
        GenerateHubClientsClass(sb, receiver);

        // 生成 HubContext 实现
        GenerateHubContextClass(sb, receiver);

        // 生成 DI 扩展方法
        GenerateDIExtensions(sb, receiver);

        return sb.ToString();
    }

    /// <summary>
    /// 生成 SourceText
    /// </summary>
    public static SourceText GenerateSourceText(ReceiverModel receiver)
    {
        var code = GenerateReceiverProxy(receiver);
        return SourceText.From(code, Encoding.UTF8);
    }

    private static void GenerateFileHeader(StringBuilder sb, ReceiverModel receiver)
    {
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This code was generated by PulseRPC.Server.SourceGenerator");
        sb.AppendLine($"// Receiver proxy for {receiver.InterfaceFullName}");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
    }

    private static void GenerateUsingStatements(StringBuilder sb)
    {
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using MemoryPack;");
        sb.AppendLine("using PulseRPC;");
        sb.AppendLine("using PulseRPC.Server;");
        sb.AppendLine("using PulseRPC.Server.Extensions;");
        sb.AppendLine("using PulseRPC.Server.Transport;");
        sb.AppendLine("using PulseRPC.Routing;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
    }

    /// <summary>
    /// 生成代理类 - 实现接收器接口
    /// </summary>
    private static void GenerateProxyClass(StringBuilder sb, ReceiverModel receiver)
    {
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// {receiver.InterfaceName} 的服务端代理");
        sb.AppendLine($"/// 序列化参数后经 <see cref=\"IPulseRouter\"/> 投递（§P3 fanout-via-router），");
        sb.AppendLine($"/// 单节点默认由 LocalPulseRouter 直投本地连接/组/用户，行为与此前直接遍历 IServerChannel 等价。");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public sealed class {receiver.ProxyClassName} : {receiver.InterfaceFullName}");
        sb.AppendLine("{");

        // 字段
        sb.AppendLine("    private readonly IPulseRouter _router;");
        sb.AppendLine("    private readonly IReadOnlyList<PulseAddress> _addresses;");
        sb.AppendLine();

        // 协议号常量
        GenerateProtocolIdConstants(sb, receiver);

        // 构造函数（多地址：All/Only/Users/Groups/Except(list)/GroupExcept 等 Fan-out 场景）
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// 创建代理实例（多目标地址）");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public {receiver.ProxyClassName}(IPulseRouter router, IEnumerable<PulseAddress> addresses)");
        sb.AppendLine("    {");
        sb.AppendLine("        _router = router ?? throw new ArgumentNullException(nameof(router));");
        sb.AppendLine("        if (addresses == null) throw new ArgumentNullException(nameof(addresses));");
        sb.AppendLine("        // 优化：如果已经是 IReadOnlyList 则直接使用，避免分配");
        sb.AppendLine("        _addresses = addresses as IReadOnlyList<PulseAddress> ?? addresses.ToArray();");
        sb.AppendLine("    }");
        sb.AppendLine();

        // 单地址构造函数（All/Single/Group/User/Except(single) 等可直接映射为单一 PulseAddress 的场景）
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// 创建代理实例（单一目标地址）");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public {receiver.ProxyClassName}(IPulseRouter router, PulseAddress address)");
        sb.AppendLine("    {");
        sb.AppendLine("        _router = router ?? throw new ArgumentNullException(nameof(router));");
        sb.AppendLine("        _addresses = new[] { address };");
        sb.AppendLine("    }");
        sb.AppendLine();

        // 生成每个方法的实现
        foreach (var method in receiver.Methods)
        {
            GenerateMethodImplementation(sb, receiver, method);
        }

        // 辅助方法
        GenerateHelperMethods(sb);

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void GenerateProtocolIdConstants(StringBuilder sb, ReceiverModel receiver)
    {
        sb.AppendLine("    // ==================== 协议号常量 ====================");
        sb.AppendLine("    // 使用 FNV-1a 哈希算法生成，确保客户端和服务端一致");
        sb.AppendLine();

        foreach (var method in receiver.Methods)
        {
            var constName = $"Protocol_{method.MethodName}";
            sb.AppendLine($"    private const ushort {constName} = 0x{method.ProtocolId:X4};");
        }
        sb.AppendLine();
    }

    private static void GenerateMethodImplementation(StringBuilder sb, ReceiverModel receiver, ReceiverMethodModel method)
    {
        // [P-4] 返回 Task<T>/ValueTask<T> 的方法 => 反向 Ask（等待客户端应答）
        if (method.IsRequestResponse)
        {
            GenerateReverseAskMethod(sb, receiver, method);
            return;
        }

        var constName = $"Protocol_{method.MethodName}";

        // 生成方法签名 - 仅支持 Task/ValueTask 返回类型
        sb.AppendLine($"    /// <inheritdoc/>");

        if (method.ReturnsTask || method.ReturnsValueTask)
        {
            // 返回 Task/ValueTask 的方法
            sb.Append($"    public async {method.ReturnTypeName} {method.MethodName}(");
        }
        else
        {
            // 其他返回类型，默认使用 Task
            sb.Append($"    public async Task {method.MethodName}(");
        }

        for (var i = 0; i < method.Parameters.Count; i++)
        {
            if (i > 0) sb.Append(", ");
            var param = method.Parameters[i];
            sb.Append($"{param.TypeFullName} {param.Name}");
        }

        sb.AppendLine(")");
        sb.AppendLine("    {");

        // 快速路径：如果没有目标，直接返回（无分配）
        sb.AppendLine("        // 快速路径检查：避免无意义的序列化和发送");
        sb.AppendLine("        var count = _addresses.Count;");
        sb.AppendLine("        if (count == 0) return;");
        sb.AppendLine();

        // 序列化参数
        GenerateSerializationCode(sb, method);
        sb.AppendLine();

        // 经 IPulseRouter 投递：单地址走快速路径，多地址并行投递
        sb.AppendLine($"        // 经 IPulseRouter 投递（§P3 fanout-via-router）");
        sb.AppendLine("        if (count == 1)");
        sb.AppendLine("        {");
        sb.AppendLine($"            await _router.SendAsync(_addresses[0], {constName}, payload, cancellationToken: CancellationToken.None);");
        sb.AppendLine("        }");
        sb.AppendLine("        else");
        sb.AppendLine("        {");
        sb.AppendLine("            var tasks = new Task[count];");
        sb.AppendLine("            for (var i = 0; i < count; i++)");
        sb.AppendLine("            {");
        sb.AppendLine($"                tasks[i] = SendToAddressAsync(_addresses[i], {constName}, payload);");
        sb.AppendLine("            }");
        sb.AppendLine("            await Task.WhenAll(tasks);");
        sb.AppendLine("        }");

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// [P-4] 生成反向 Ask 方法实现（Task&lt;T&gt;/ValueTask&lt;T&gt;）：
    /// 序列化参数 -> 通过唯一目标连接发起需应答请求 -> 反序列化客户端应答为 T。
    /// </summary>
    private static void GenerateReverseAskMethod(StringBuilder sb, ReceiverModel receiver, ReceiverMethodModel method)
    {
        var constName = $"Protocol_{method.MethodName}";

        sb.AppendLine($"    /// <inheritdoc/>");
        sb.Append($"    public async {method.ReturnTypeName} {method.MethodName}(");

        for (var i = 0; i < method.Parameters.Count; i++)
        {
            if (i > 0) sb.Append(", ");
            var param = method.Parameters[i];
            sb.Append($"{param.TypeFullName} {param.Name}");
        }

        sb.AppendLine(")");
        sb.AppendLine("    {");

        // 反向 Ask 要求恰好 1 个目标地址（多目标语义不明确，禁止）
        sb.AppendLine("        // [P-4] 反向 Ask：要求恰好 1 个目标地址");
        sb.AppendLine("        var count = _addresses.Count;");
        sb.AppendLine("        if (count != 1)");
        sb.AppendLine("        {");
        sb.AppendLine($"            throw new InvalidOperationException(\"反向 Ask 方法 '{method.MethodName}' 需要恰好 1 个目标连接，当前为 \" + count + \" 个。请使用 Single/Client 指定单一连接。\");");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 序列化参数（复用 push 路径的序列化逻辑，产出 payload）
        GenerateSerializationCode(sb, method);
        sb.AppendLine();

        // 经 IPulseRouter.AskAsync 发起反向请求并等待应答（单节点由 LocalPulseRouter 经目标连接的
        // InvokeClientAsync 完成；超时/失败由实现抛出 TimeoutException/PulseReverseCallException）
        sb.AppendLine($"        var __responseBytes__ = await _router.AskAsync(_addresses[0], {constName}, payload, CancellationToken.None);");
        sb.AppendLine($"        return MemoryPackSerializer.Deserialize<{method.ResponseTypeName}>(__responseBytes__.Span)!;");

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// 生成序列化代码
    /// </summary>
    private static void GenerateSerializationCode(StringBuilder sb, ReceiverMethodModel method)
    {
        if (method.Parameters.Count == 0)
        {
            sb.AppendLine("        // 无参数方法");
            sb.AppendLine("        var payload = Array.Empty<byte>();");
        }
        else if (method.Parameters.Count == 1)
        {
            var param = method.Parameters[0];
            sb.AppendLine($"        // 序列化单个参数");
            sb.AppendLine($"        var payload = MemoryPackSerializer.Serialize({param.Name});");
        }
        else
        {
            // 多参数使用元组
            var tupleParams = string.Join(", ", method.Parameters.Select(p => p.Name));
            sb.AppendLine($"        // 序列化多个参数为元组");
            sb.AppendLine($"        var payload = MemoryPackSerializer.Serialize(({tupleParams}));");
        }
    }

    private static void GenerateHelperMethods(StringBuilder sb)
    {
        // 经 IPulseRouter 投递到单个地址（异常安全：与此前直接遍历 IServerChannel 时对单个失败目标的容错语义一致）
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 经 IPulseRouter 投递到单个地址（异常安全）");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    private async Task SendToAddressAsync(PulseAddress address, ushort protocolId, byte[] payload)");
        sb.AppendLine("    {");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            await _router.SendAsync(address, protocolId, payload, cancellationToken: CancellationToken.None);");
        sb.AppendLine("        }");
        sb.AppendLine("        catch");
        sb.AppendLine("        {");
        sb.AppendLine("            // 忽略单个目标发送失败（连接可能已断开）");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    /// <summary>
    /// 生成 HubClients 实现（MagicOnion 风格 API）
    /// </summary>
    private static void GenerateHubClientsClass(StringBuilder sb, ReceiverModel receiver)
    {
        var hub = receiver.InterfaceName.TrimStart('I');

        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// {receiver.InterfaceName} 的客户端选择器实现（MagicOnion 风格）。");
        sb.AppendLine($"/// 单一目标场景（All/Single/Group/User/Except(单个)）直接映射为一个 PulseAddress，");
        sb.AppendLine($"/// 交给 IPulseRouter 在投递时解析目标（§P3 fanout-via-router）；");
        sb.AppendLine($"/// 多目标场景（Only/Users/Groups/GroupExcept/Except(多个)）在此处一次性解析为具体连接 ID 列表，");
        sb.AppendLine($"/// 因为 PulseAddress 尚不支持任意连接 ID 集合的寻址。");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public sealed class {receiver.HubClientsClassName} : IHubClients<{receiver.InterfaceFullName}>");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly IPulseRouter _router;");
        sb.AppendLine("    private readonly IServerChannelManager _channelManager;");
        sb.AppendLine("    private readonly IUserConnectionMapping _userMapping;");
        sb.AppendLine("    private readonly IGroupManager _groupManager;");
        sb.AppendLine();

        // 构造函数
        sb.AppendLine($"    public {receiver.HubClientsClassName}(");
        sb.AppendLine("        IPulseRouter router,");
        sb.AppendLine("        IServerChannelManager channelManager,");
        sb.AppendLine("        IUserConnectionMapping userMapping,");
        sb.AppendLine("        IGroupManager groupManager)");
        sb.AppendLine("    {");
        sb.AppendLine("        _router = router;");
        sb.AppendLine("        _channelManager = channelManager;");
        sb.AppendLine("        _userMapping = userMapping;");
        sb.AppendLine("        _groupManager = groupManager;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // All 属性
        sb.AppendLine($"    /// <inheritdoc/>");
        sb.AppendLine($"    public {receiver.InterfaceFullName} All =>");
        sb.AppendLine($"        new {receiver.ProxyClassName}(_router, PulseAddress.AllClients(\"{hub}\"));");
        sb.AppendLine();

        // ==================== MagicOnion 风格 API ====================

        // Single 方法（MagicOnion 风格）
        sb.AppendLine($"    /// <inheritdoc/>");
        sb.AppendLine($"    public {receiver.InterfaceFullName} Single(string connectionId) =>");
        sb.AppendLine($"        new {receiver.ProxyClassName}(_router, PulseAddress.Connection(\"{hub}\", connectionId));");
        sb.AppendLine();

        // Only 方法（MagicOnion 风格）
        sb.AppendLine($"    /// <inheritdoc/>");
        sb.AppendLine($"    public {receiver.InterfaceFullName} Only(IReadOnlyList<string> connectionIds)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var addresses = connectionIds.Select(id => PulseAddress.Connection(\"{hub}\", id));");
        sb.AppendLine($"        return new {receiver.ProxyClassName}(_router, addresses);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Except(string) 方法（MagicOnion 风格 - 单个排除）
        sb.AppendLine($"    /// <inheritdoc/>");
        sb.AppendLine($"    public {receiver.InterfaceFullName} Except(string connectionId) =>");
        sb.AppendLine($"        new {receiver.ProxyClassName}(_router, PulseAddress.Except(\"{hub}\", connectionId));");
        sb.AppendLine();

        // Except(IReadOnlyList<string>) 方法（MagicOnion 风格 - 多个排除）
        // PulseAddress.Except 仅支持排除单个连接；多重排除没有对应的单一地址，需要在此一次性
        // 枚举当前已认证连接集合并过滤，再映射为逐连接的 PulseAddress.Connection 列表。
        sb.AppendLine($"    /// <inheritdoc/>");
        sb.AppendLine($"    public {receiver.InterfaceFullName} Except(IReadOnlyList<string> connectionIds)");
        sb.AppendLine("    {");
        sb.AppendLine("        var excluded = new HashSet<string>(connectionIds);");
        sb.AppendLine("        var addresses = _channelManager.GetAuthenticatedChannels()");
        sb.AppendLine("            .Where(c => !excluded.Contains(c.ConnectionId))");
        sb.AppendLine($"            .Select(c => PulseAddress.Connection(\"{hub}\", c.ConnectionId));");
        sb.AppendLine($"        return new {receiver.ProxyClassName}(_router, addresses);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ==================== 用户和组 API ====================

        // User 方法
        sb.AppendLine($"    /// <inheritdoc/>");
        sb.AppendLine($"    public {receiver.InterfaceFullName} User(string userId) =>");
        sb.AppendLine($"        new {receiver.ProxyClassName}(_router, PulseAddress.User(\"{hub}\", userId));");
        sb.AppendLine();

        // Users 方法（多用户：无对应单一地址，一次性解析为连接 ID 列表）
        sb.AppendLine($"    /// <inheritdoc/>");
        sb.AppendLine($"    public {receiver.InterfaceFullName} Users(IReadOnlyList<string> userIds)");
        sb.AppendLine("    {");
        sb.AppendLine("        var connectionIds = _userMapping.GetConnections(userIds);");
        sb.AppendLine("        return Only(connectionIds.ToArray());");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Group 方法
        sb.AppendLine($"    /// <inheritdoc/>");
        sb.AppendLine($"    public {receiver.InterfaceFullName} Group(string groupName) =>");
        sb.AppendLine($"        new {receiver.ProxyClassName}(_router, PulseAddress.Group(\"{hub}\", groupName));");
        sb.AppendLine();

        // Groups 方法（多组：无对应单一地址，一次性解析为连接 ID 列表）
        sb.AppendLine($"    /// <inheritdoc/>");
        sb.AppendLine($"    public {receiver.InterfaceFullName} Groups(IReadOnlyList<string> groupNames)");
        sb.AppendLine("    {");
        sb.AppendLine("        var connectionIds = _groupManager.GetGroupConnections(groupNames);");
        sb.AppendLine("        return Only(connectionIds.ToArray());");
        sb.AppendLine("    }");
        sb.AppendLine();

        // GroupExcept(string, string) 方法（组+单个排除：无对应单一地址，一次性解析为连接 ID 列表）
        sb.AppendLine($"    /// <inheritdoc/>");
        sb.AppendLine($"    public {receiver.InterfaceFullName} GroupExcept(string groupName, string excludedConnectionId)");
        sb.AppendLine("    {");
        sb.AppendLine("        var connectionIds = _groupManager.GetGroupConnections(groupName)");
        sb.AppendLine("            .Where(id => id != excludedConnectionId)");
        sb.AppendLine("            .ToArray();");
        sb.AppendLine("        return Only(connectionIds);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // GroupExcept(string, IReadOnlyList<string>) 方法（组+多个排除）
        sb.AppendLine($"    /// <inheritdoc/>");
        sb.AppendLine($"    public {receiver.InterfaceFullName} GroupExcept(string groupName, IReadOnlyList<string> excludedConnectionIds)");
        sb.AppendLine("    {");
        sb.AppendLine("        var excluded = new HashSet<string>(excludedConnectionIds);");
        sb.AppendLine("        var connectionIds = _groupManager.GetGroupConnections(groupName)");
        sb.AppendLine("            .Where(id => !excluded.Contains(id))");
        sb.AppendLine("            .ToArray();");
        sb.AppendLine("        return Only(connectionIds);");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        sb.AppendLine();
    }

    /// <summary>
    /// 生成 HubContext 实现
    /// </summary>
    private static void GenerateHubContextClass(StringBuilder sb, ReceiverModel receiver)
    {
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// {receiver.InterfaceName} 的 HubContext 实现");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public sealed class {receiver.HubContextClassName} : IHubContext<{receiver.InterfaceFullName}>");
        sb.AppendLine("{");

        // 字段和属性
        sb.AppendLine($"    /// <inheritdoc/>");
        sb.AppendLine($"    public IHubClients<{receiver.InterfaceFullName}> Clients {{ get; }}");
        sb.AppendLine();
        sb.AppendLine($"    /// <inheritdoc/>");
        sb.AppendLine($"    public IGroupManager Groups {{ get; }}");
        sb.AppendLine();

        // 构造函数
        sb.AppendLine($"    public {receiver.HubContextClassName}(");
        sb.AppendLine("        IPulseRouter router,");
        sb.AppendLine("        IServerChannelManager channelManager,");
        sb.AppendLine("        IUserConnectionMapping userMapping,");
        sb.AppendLine("        IGroupManager groupManager)");
        sb.AppendLine("    {");
        sb.AppendLine($"        Clients = new {receiver.HubClientsClassName}(router, channelManager, userMapping, groupManager);");
        sb.AppendLine("        Groups = groupManager;");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        sb.AppendLine();
    }

    /// <summary>
    /// 生成 DI 扩展方法
    /// </summary>
    private static void GenerateDIExtensions(StringBuilder sb, ReceiverModel receiver)
    {
        var extensionClassName = receiver.InterfaceName.StartsWith("I")
            ? receiver.InterfaceName.Substring(1) + "Extensions"
            : receiver.InterfaceName + "Extensions";

        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// {receiver.InterfaceName} 的 DI 扩展方法");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public static class {extensionClassName}");
        sb.AppendLine("{");

        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// 注册 {receiver.InterfaceName} 的 HubContext");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public static IServiceCollection AddPulseReceiverContext<TReceiver>(this IServiceCollection services)");
        sb.AppendLine($"        where TReceiver : class, IPulseHub");
        sb.AppendLine("    {");
        sb.AppendLine($"        // 检查是否为 {receiver.InterfaceName}");
        sb.AppendLine($"        if (typeof(TReceiver) == typeof({receiver.InterfaceFullName}))");
        sb.AppendLine("        {");
        sb.AppendLine("            // 确保 IPulseRouter（Fan-out 投递依赖，§P3）已注册，与注册顺序无关（幂等）");
        sb.AppendLine("            services.AddPulseRouting();");
        sb.AppendLine($"            services.AddSingleton<IHubContext<{receiver.InterfaceFullName}>, {receiver.HubContextClassName}>();");
        sb.AppendLine("        }");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // 非泛型版本
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// 注册 {receiver.InterfaceName} 的 HubContext（非泛型版本）");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public static IServiceCollection Add{receiver.InterfaceName.TrimStart('I')}HubContext(this IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine("        // 确保 IPulseRouter（Fan-out 投递依赖，§P3）已注册，与注册顺序无关（幂等）");
        sb.AppendLine("        services.AddPulseRouting();");
        sb.AppendLine($"        services.AddSingleton<IHubContext<{receiver.InterfaceFullName}>, {receiver.HubContextClassName}>();");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");

        sb.AppendLine("}");
    }

    /// <summary>
    /// 生成所有接收器的统一 DI 扩展方法
    /// </summary>
    public static string GenerateDIExtensions(List<ReceiverModel> receivers)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This code was generated by PulseRPC.Server.SourceGenerator");
        sb.AppendLine("// Unified DI extensions for all [Channel(\"CLIENT\")] : IPulseHub receiver implementations");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using PulseRPC;");
        sb.AppendLine("using PulseRPC.Server;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();

        // 添加生成的命名空间 using（去重）
        // 注：本文件已位于 PulseRPC.Server.Extensions 命名空间内，AddPulseRouting 无需额外 using。
        var generatedNamespaces = receivers
            .Select(r => r.Namespace)
            .Where(ns => !string.IsNullOrWhiteSpace(ns))
            .Distinct()
            .OrderBy(ns => ns);

        foreach (var ns in generatedNamespaces)
        {
            sb.AppendLine($"using {ns}.Generated;");
        }
        sb.AppendLine();

        sb.AppendLine("namespace PulseRPC.Server.Extensions;");
        sb.AppendLine();

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// PulseReceiver 统一 DI 扩展方法");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class PulseReceiverServiceExtensions");
        sb.AppendLine("{");

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 注册所有推送接收器（[Channel(\"CLIENT\")] : IPulseHub）的 HubContext");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IServiceCollection AddAllPulseReceiverContexts(this IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine("        // 确保 IPulseRouter（Fan-out 投递依赖，§P3）已注册，与注册顺序无关（幂等）");
        sb.AppendLine("        services.AddPulseRouting();");
        sb.AppendLine();

        foreach (var receiver in receivers)
        {
            sb.AppendLine($"        // {receiver.InterfaceName}");
            sb.AppendLine($"        services.AddSingleton<IHubContext<{receiver.InterfaceFullName}>, {receiver.Namespace}.Generated.{receiver.HubContextClassName}>();");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// 生成协议号映射表（接收器专用）
    /// </summary>
    public static string GenerateReceiverProtocolIdMapping(List<ReceiverModel> receivers)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This code was generated by PulseRPC.Server.SourceGenerator");
        sb.AppendLine("// Protocol ID constants for [Channel(\"CLIENT\")] : IPulseHub receiver interfaces");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace PulseRPC.Generated;");
        sb.AppendLine();

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// 推送接收器（[Channel(\"CLIENT\")] : IPulseHub）协议号常量");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static partial class ProtocolIdMapping");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Receiver 协议号常量");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static partial class ReceiverProtocolIds");
        sb.AppendLine("    {");

        foreach (var receiver in receivers)
        {
            var shortName = receiver.InterfaceName.TrimStart('I');
            sb.AppendLine($"        // {receiver.InterfaceFullName}");

            foreach (var method in receiver.Methods)
            {
                var constName = $"{shortName}_{method.MethodName}";
                sb.AppendLine($"        public const ushort {constName} = 0x{method.ProtocolId:X4};");
            }
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}

