using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis.Text;
using PulseRPC.Server.SourceGenerator.Models;

namespace PulseRPC.Server.SourceGenerator.Generators;

/// <summary>
/// 生成响应序列化器注册表及各方法的零拷贝序列化实现。
/// </summary>
public static class ResponseSerializerGenerator
{
    public static SourceText GenerateSourceText(List<ServiceModel> services)
    {
        var code = GenerateCode(services);
        return SourceText.From(code, Encoding.UTF8);
    }

    private static string GenerateCode(List<ServiceModel> services)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by PulseRPC.Server.SourceGenerator");
        sb.AppendLine("// Response serialization registry - maps service methods to zero-copy serializers");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0168");
        sb.AppendLine("#pragma warning disable CS0219");
        sb.AppendLine("#pragma warning disable CS8602");
        sb.AppendLine();

        GenerateUsings(sb, services);
        GenerateNamespace(sb, services);

        return sb.ToString();
    }

    private static void GenerateUsings(StringBuilder sb, List<ServiceModel> services)
    {
        // 只保留必要的系统命名空间，不使用自定义类型的命名空间
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Buffers;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using MemoryPack;");
        sb.AppendLine("using PulseRPC.Serialization;");
        // 不再收集和添加自定义类型的命名空间
        sb.AppendLine();
    }

    private static void GenerateNamespace(StringBuilder sb, List<ServiceModel> services)
    {
        sb.AppendLine("namespace PulseRPC.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// 自动生成的响应序列化器注册表");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static partial class ResponseSerializers");
        sb.AppendLine("{");

        GenerateRegistry(sb, services);
        sb.AppendLine();
        GenerateSerializerContainer(sb, services);

        GenerateModuleInitializer(sb);

        sb.AppendLine("}");
    }

    private static void GenerateRegistry(StringBuilder sb, List<ServiceModel> services)
    {
        var serializerInfos = CollectSerializerInfos(services);

        sb.AppendLine("    private sealed class RegistryImpl : IResponseSerializerRegistry");
        sb.AppendLine("    {");
        sb.AppendLine("        private static readonly IResponseSerializer[] s_serializers = new IResponseSerializer[]");
        sb.AppendLine("        {");

        for (var i = 0; i < serializerInfos.Count; i++)
        {
            var info = serializerInfos[i];
            var comma = i == serializerInfos.Count - 1 ? string.Empty : ",";
            sb.AppendLine($"            Serializers.{info.ClassName}.Instance{comma}");
        }

        sb.AppendLine("        };");
        sb.AppendLine();

        // P3 优化：使用数组索引替代字典查找
        // 计算协议号范围以优化数组大小
        if (serializerInfos.Count > 0)
        {
            var minProtocolId = serializerInfos.Min(s => s.ProtocolId);
            var maxProtocolId = serializerInfos.Max(s => s.ProtocolId);
            var arraySize = maxProtocolId - minProtocolId + 1;

            // 如果范围较小（< 4096），使用偏移数组；否则使用全范围数组
            var useOffset = arraySize <= 4096 && minProtocolId > 0;

            if (useOffset)
            {
                sb.AppendLine($"        // 使用偏移数组索引 (范围: 0x{minProtocolId:X4} - 0x{maxProtocolId:X4}, 大小: {arraySize})");
                sb.AppendLine($"        private const ushort ProtocolIdOffset = 0x{minProtocolId:X4};");
                sb.AppendLine($"        private static readonly IResponseSerializer?[] s_protocolArray = new IResponseSerializer?[{arraySize}];");
            }
            else
            {
                sb.AppendLine($"        // 使用直接数组索引 (协议号数量: {serializerInfos.Count})");
                sb.AppendLine("        private static readonly IResponseSerializer?[] s_protocolArray = new IResponseSerializer?[65536];");
            }
            sb.AppendLine();

            // 生成静态构造函数初始化数组
            sb.AppendLine("        static RegistryImpl()");
            sb.AppendLine("        {");
            foreach (var info in serializerInfos)
            {
                if (useOffset)
                {
                    sb.AppendLine($"            s_protocolArray[0x{info.ProtocolId:X4} - ProtocolIdOffset] = Serializers.{info.ClassName}.Instance;");
                }
                else
                {
                    sb.AppendLine($"            s_protocolArray[0x{info.ProtocolId:X4}] = Serializers.{info.ClassName}.Instance;");
                }
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            // 生成优化的 TryGetSerializer 方法
            sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine("        public bool TryGetSerializer(ushort protocolId, [NotNullWhen(true)] out IResponseSerializer? serializer)");
            sb.AppendLine("        {");
            if (useOffset)
            {
                sb.AppendLine($"            var index = protocolId - ProtocolIdOffset;");
                sb.AppendLine($"            if ((uint)index < (uint)s_protocolArray.Length)");
                sb.AppendLine("            {");
                sb.AppendLine("                serializer = s_protocolArray[index];");
                sb.AppendLine("                return serializer != null;");
                sb.AppendLine("            }");
                sb.AppendLine("            serializer = null;");
                sb.AppendLine("            return false;");
            }
            else
            {
                sb.AppendLine("            serializer = s_protocolArray[protocolId];");
                sb.AppendLine("            return serializer != null;");
            }
            sb.AppendLine("        }");
        }
        else
        {
            // 没有序列化器的情况
            sb.AppendLine("        public bool TryGetSerializer(ushort protocolId, [NotNullWhen(true)] out IResponseSerializer? serializer)");
            sb.AppendLine("        {");
            sb.AppendLine("            serializer = null;");
            sb.AppendLine("            return false;");
            sb.AppendLine("        }");
        }
        sb.AppendLine();

        sb.AppendLine("        public ReadOnlySpan<IResponseSerializer> EnumerateSerializers() => s_serializers;");
        sb.AppendLine("    }");
    }

    private static void GenerateSerializerContainer(StringBuilder sb, List<ServiceModel> services)
    {
        var serializerInfos1 = CollectSerializerInfos(services);
        if (serializerInfos1.Count == 0)
        {
            return;
        }

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 自动生成的响应序列化器实现。");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class Serializers");
        sb.AppendLine("    {");

        foreach (var info in serializerInfos1)
        {
            GenerateSerializerClass(sb, info);
            sb.AppendLine();
        }

        sb.AppendLine("    }");
    }

    private static void GenerateSerializerClass(StringBuilder sb, ResponseSerializerInfo info)
    {
        var serializerInterface = info.IsNullable
            ? "INullResponseSerializer"
            : "IResponseSerializer";
        sb.AppendLine($"        public sealed class {info.ClassName} : {serializerInterface}");
        sb.AppendLine("        {");
        sb.AppendLine($"            public static {info.ClassName} Instance {{ get; }} = new();");
        sb.AppendLine();
        sb.AppendLine($"            private {info.ClassName}() {{ }}");
        sb.AppendLine();
            sb.AppendLine($"            public ushort ProtocolId => 0x{info.ProtocolId:X4}; // {info.ProtocolId}");
            sb.AppendLine();

        sb.AppendLine($"            // A {info.ResponseTypeName}");

        if (! string.IsNullOrWhiteSpace(info.ResponseTypeName))
        {
            sb.AppendLine("            public void Serialize(object response, IBufferWriter<byte> writer)");
            sb.AppendLine("            {");
            sb.AppendLine("                if (response is null)");
            sb.AppendLine("                {");

            var responseTypeName = info.ResponseTypeName!;
            var runtimeTypeName = info.RuntimeTypeName!;

            if (info.IsNullable)
            {
                sb.AppendLine($"                    {responseTypeName} typedNull = default;");
                sb.AppendLine("                    MemoryPackSerializer.Serialize(writer, typedNull);");
                sb.AppendLine("                    return;");
            }
            else
            {
                sb.AppendLine("                    throw new ArgumentNullException(nameof(response));");
            }
            sb.AppendLine("                }");
            sb.AppendLine();

            // 检测是否为元组类型，元组类型不能使用模式匹配
            if (IsTupleType(runtimeTypeName))
            {
                // 对于元组类型，使用类型检查和转换
                sb.AppendLine($"                if (response.GetType() == typeof({runtimeTypeName}))");
                sb.AppendLine("                {");
                sb.AppendLine($"                    var typed = ({runtimeTypeName})response;");
                sb.AppendLine($"                    {responseTypeName} typedResponse = typed;");
                sb.AppendLine("                    MemoryPackSerializer.Serialize(writer, typedResponse);");
                sb.AppendLine("                    return;");
                sb.AppendLine("                }");
            }
            else
            {
                // 对于非元组类型，使用模式匹配
                sb.AppendLine($"                if (response is {runtimeTypeName} typed)");
                sb.AppendLine("                {");
                sb.AppendLine($"                    {responseTypeName} typedResponse = typed;");
                sb.AppendLine("                    MemoryPackSerializer.Serialize(writer, typedResponse);");
                sb.AppendLine("                    return;");
                sb.AppendLine("                }");
            }

            sb.AppendLine();
            sb.AppendLine($"                throw new InvalidCastException($\"期待类型 {{typeof({runtimeTypeName})}} 但接收到 {{response.GetType()}}\");");
            sb.AppendLine("            }");
            sb.AppendLine();

            sb.AppendLine("            public ValueTask SerializeAsync(object response, IBufferWriter<byte> writer, CancellationToken cancellationToken = default)");
            sb.AppendLine("            {");
            sb.AppendLine("                Serialize(response, writer);");
            sb.AppendLine("                return ValueTask.CompletedTask;");
            sb.AppendLine("            }");
            sb.AppendLine();

            sb.AppendLine("            public bool TryGetTypedSerializer<T>(out Action<T, IBufferWriter<byte>> serializer)");
            sb.AppendLine("            {");
            if (!info.IsNullable)
            {
                sb.AppendLine($"                if (typeof(T) == typeof({responseTypeName}))");
                sb.AppendLine("                {");
                sb.AppendLine("                    serializer = static (value, bufferWriter) =>");
                sb.AppendLine("                    {");
                sb.AppendLine($"                        MemoryPackSerializer.Serialize(bufferWriter, Unsafe.As<T, {responseTypeName}>(ref value));");
                sb.AppendLine("                    };");
                sb.AppendLine("                    return true;");
                sb.AppendLine("                }");
                sb.AppendLine();
            }
            sb.AppendLine("                serializer = null!;");
            sb.AppendLine("                return false;");
            sb.AppendLine("            }");
        }
        else
        {
            sb.AppendLine("            public void Serialize(object response, IBufferWriter<byte> writer)");
            sb.AppendLine("            {");
            sb.AppendLine("                if (response is null || response is EmptyResponse)");
            sb.AppendLine("                {");
            sb.AppendLine("                    return;");
            sb.AppendLine("                }");
            sb.AppendLine();
            sb.AppendLine($"                throw new InvalidOperationException(\"协议号 0x{info.ProtocolId:X4} 不期望返回值\");");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            public ValueTask SerializeAsync(object response, IBufferWriter<byte> writer, CancellationToken cancellationToken = default)");
            sb.AppendLine("            {");
            sb.AppendLine("                Serialize(response, writer);");
            sb.AppendLine("                return ValueTask.CompletedTask;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            public bool TryGetTypedSerializer<T>(out Action<T, IBufferWriter<byte>> serializer)");
            sb.AppendLine("            {");
            sb.AppendLine("                serializer = null!;");
            sb.AppendLine("                return false;");
            sb.AppendLine("            }");
        }

        sb.AppendLine("        }");
    }

    private static IReadOnlyList<ResponseSerializerInfo> CollectSerializerInfos(List<ServiceModel> services)
    {
        var list = new List<ResponseSerializerInfo>();

        foreach (var service in services)
        {
            foreach (var method in service.Methods)
            {
                if (!string.IsNullOrWhiteSpace(method.ResponseTypeFullName) && !method.IsResponseMemoryPackable)
                {
                    throw new InvalidOperationException(
                        $"Response type '{method.ResponseTypeFullName}' for {service.InterfaceName}.{method.MethodName} is not MemoryPack serializable.");
                }

                var serviceIdentifier = service.CodeIdentifier == service.InterfaceName.TrimStart('I')
                    ? service.ServiceName ?? service.InterfaceName
                    : service.CodeIdentifier;
                var className = $"{GetSafeIdentifier(serviceIdentifier)}_{GetSafeIdentifier(method.GeneratedIdentifier)}_ResponseSerializer";

                // responseType 为 null 表示 void 返回，否则为 MemoryPackable 类型
                var responseType = string.IsNullOrWhiteSpace(method.ResponseTypeFullName) ? null : method.ResponseTypeFullName;
                string? runtimeType = null;
                var isNullable = false;

                if (responseType != null && responseType.Length > 0)
                {
                    var normalizedResponseType = responseType;

                    // 保留声明类型的可空标记用于 MemoryPack wire 格式，同时使用去掉外层 ? 的类型做运行时匹配。
                    isNullable = normalizedResponseType.EndsWith("?", StringComparison.Ordinal);
                    if (isNullable)
                    {
                        runtimeType = normalizedResponseType.Substring(0, normalizedResponseType.Length - 1);
                    }
                    else
                    {
                        runtimeType = normalizedResponseType;
                    }

                    // 对于元组类型，移除元素名称（如 guild, member 等）
                    // 例如：(GuildEntity? guild, GuildMember? member) -> (GuildEntity?, GuildMember?)
                    if (IsTupleType(runtimeType))
                    {
                        runtimeType = StripTupleElementNames(runtimeType);
                        normalizedResponseType = isNullable ? runtimeType + "?" : runtimeType;
                    }

                    responseType = normalizedResponseType;
                }

                list.Add(new ResponseSerializerInfo(
                    className,
                    method.ProtocolId,
                    responseType,
                    runtimeType,
                    isNullable));
            }
        }

        return list;
    }

    private static IEnumerable<string> CollectNamespaces(List<ServiceModel> services)
    {
        var set = new HashSet<string>();

        foreach (var service in services)
        {
            if (!string.IsNullOrWhiteSpace(service.Namespace) && IsValidNamespace(service.Namespace))
            {
                set.Add(service.Namespace);
            }

            foreach (var method in service.Methods)
            {
                if (!string.IsNullOrWhiteSpace(method.ResponseTypeFullName))
                {
                    ExtractNamespacesFromType(method.ResponseTypeFullName!, set);
                }
            }
        }

        // Filter out any invalid namespaces and return sorted
        return set.Where(IsValidNamespace).OrderBy(n => n);
    }

    /// <summary>
    /// Validates that a namespace string is a valid C# namespace identifier
    /// </summary>
    private static bool IsValidNamespace(string ns)
    {
        if (string.IsNullOrWhiteSpace(ns))
            return false;

        // Namespace should not contain generic markers, special chars, or be a keyword
        if (ns.Contains('<') || ns.Contains('>') || ns.Contains('?') ||
            ns.Contains('[') || ns.Contains(']') || ns.Contains(' ') ||
            ns.Contains('@') || ns.Contains('`'))
            return false;

        // Each part of the namespace should be a valid identifier
        var parts = ns.Split(new[] { '.' });
        foreach (var part in parts)
        {
            if (string.IsNullOrEmpty(part))
                return false;

            // First character must be letter or underscore
            if (!char.IsLetter(part[0]) && part[0] != '_')
                return false;

            // Remaining characters must be letters, digits, or underscores
            for (var i = 1; i < part.Length; i++)
            {
                if (!char.IsLetterOrDigit(part[i]) && part[i] != '_')
                    return false;
            }
        }

        return true;
    }

    /// <summary>
    /// 从类型全名中提取所有命名空间（包括泛型参数和元组元素）
    /// </summary>
    private static void ExtractNamespacesFromType(string typeFullName, HashSet<string> namespaces)
    {
        if (string.IsNullOrWhiteSpace(typeFullName))
            return;

        var trimmed = typeFullName.Trim();

        // 移除可能的可空标记
        if (trimmed.EndsWith("?", StringComparison.Ordinal))
        {
            trimmed = trimmed.Substring(0, trimmed.Length - 1).Trim();
        }

        // 移除参数名（如果类型名包含参数名，如 "Guild? guild" -> "Guild?"）
        // 查找最后一个空格，如果后面跟着有效的标识符，则可能是参数名
        // 但要注意：空格可能也在类型名内部（如泛型参数中的空格），所以需要更智能的判断
        trimmed = RemoveParameterName(trimmed);

        // 检查是否是元组类型
        if (trimmed.StartsWith("(", StringComparison.Ordinal) && trimmed.EndsWith(")", StringComparison.Ordinal))
        {
            // 提取元组元素（移除外层的括号）
            var tupleContent = trimmed.Substring(1, trimmed.Length - 2).Trim();
            var elements = SplitTupleElements(tupleContent);
            foreach (var element in elements)
            {
                var elementTrimmed = element.Trim();
                if (!string.IsNullOrWhiteSpace(elementTrimmed))
                {
                    // 递归处理每个元组元素
                    ExtractNamespacesFromType(elementTrimmed, namespaces);
                }
            }
            return;
        }

        // 检查是否是泛型类型
        var genericStart = trimmed.IndexOf('<');
        if (genericStart > 0)
        {
            // 提取泛型定义的命名空间（如 System.Collections.Generic.List<T> 中的 System.Collections.Generic）
            var genericDefinition = trimmed.Substring(0, genericStart);
            var lastDot = genericDefinition.LastIndexOf('.');
            if (lastDot > 0)
            {
                var ns = genericDefinition.Substring(0, lastDot);
                if (!string.IsNullOrWhiteSpace(ns) && IsValidNamespace(ns))
                {
                    namespaces.Add(ns);
                }
            }

            // 提取泛型参数的命名空间
            var genericEnd = trimmed.LastIndexOf('>');
            if (genericEnd > genericStart)
            {
                var genericArgs = trimmed.Substring(genericStart + 1, genericEnd - genericStart - 1);

                // 处理多个泛型参数（用逗号分隔）
                var args = SplitGenericArguments(genericArgs);
                foreach (var arg in args)
                {
                    var trimmedArg = arg.Trim();
                    if (!string.IsNullOrWhiteSpace(trimmedArg))
                    {
                        // 递归处理嵌套泛型
                        ExtractNamespacesFromType(trimmedArg, namespaces);
                    }
                }
            }
        }
        else
        {
            // 非泛型类型，直接提取命名空间
            var lastDot = trimmed.LastIndexOf('.');
            if (lastDot > 0)
            {
                var ns = trimmed.Substring(0, lastDot);
                if (!string.IsNullOrWhiteSpace(ns) && IsValidNamespace(ns))
                {
                    namespaces.Add(ns);
                }
            }
        }
    }

    /// <summary>
    /// 移除类型名中的参数名
    /// 例如："Libra.Modules.GuildSystem.Guild? guild" -> "Libra.Modules.GuildSystem.Guild?"
    /// 例如："int count" -> "int"
    /// </summary>
    private static string RemoveParameterName(string typeName)
    {
        if (string.IsNullOrWhiteSpace(typeName))
            return typeName;

        var trimmed = typeName.Trim();

        // 如果类型名包含泛型或元组，参数名应该在最后（在 > 或 ) 之后）
        // 例如："List<int> items" -> "List<int>"
        var genericEnd = trimmed.LastIndexOf('>');
        var tupleEnd = trimmed.LastIndexOf(')');
        var lastBracket = Math.Max(genericEnd, tupleEnd);

        if (lastBracket >= 0)
        {
            // 有泛型或元组，参数名应该在括号之后
            var afterBracket = trimmed.Substring(lastBracket + 1).Trim();
            if (!string.IsNullOrWhiteSpace(afterBracket))
            {
                // 检查括号后是否有空格和标识符（参数名）
                var spaceIndex = afterBracket.IndexOf(' ');
                if (spaceIndex > 0 && spaceIndex < afterBracket.Length - 1)
                {
                    var afterSpace = afterBracket.Substring(spaceIndex + 1).Trim();
                    if (IsValidIdentifier(afterSpace))
                    {
                        // 移除参数名
                        return trimmed.Substring(0, lastBracket + 1 + spaceIndex).Trim();
                    }
                }
            }
        }
        else
        {
            // 没有泛型或元组，查找最后一个空格
            var lastSpace = trimmed.LastIndexOf(' ');
            if (lastSpace > 0 && lastSpace < trimmed.Length - 1)
            {
                var afterSpace = trimmed.Substring(lastSpace + 1).Trim();
                // 如果空格后是有效的 C# 标识符（可能是参数名），则移除它
                if (IsValidIdentifier(afterSpace))
                {
                    // 但需要确保这不是类型名的一部分（如 "System.Collections.Generic"）
                    // 检查空格前的部分是否以点结尾，如果是，则可能是命名空间的一部分
                    var beforeSpace = trimmed.Substring(0, lastSpace).Trim();
                    if (!beforeSpace.EndsWith(".", StringComparison.Ordinal))
                    {
                        return beforeSpace;
                    }
                }
            }
        }

        return trimmed;
    }

    /// <summary>
    /// 分割泛型参数，正确处理嵌套泛型
    /// 例如：Dictionary&lt;string, List&lt;int&gt;&gt; 应该分割为 ["string", "List&lt;int&gt;"]
    /// </summary>
    private static List<string> SplitGenericArguments(string genericArgs)
    {
        var result = new List<string>();
        var current = new StringBuilder();
        var depth = 0;

        foreach (var ch in genericArgs)
        {
            if (ch == '<')
            {
                depth++;
                current.Append(ch);
            }
            else if (ch == '>')
            {
                depth--;
                current.Append(ch);
            }
            else if (ch == ',' && depth == 0)
            {
                // 顶层逗号，分隔参数
                result.Add(current.ToString());
                current.Clear();
            }
            else
            {
                current.Append(ch);
            }
        }

        if (current.Length > 0)
        {
            result.Add(current.ToString());
        }

        return result;
    }

    /// <summary>
    /// 分割元组元素，正确处理嵌套元组
    /// 例如：(string, int) 应该分割为 ["string", "int"]
    /// 例如：((string, int), bool) 应该分割为 ["(string, int)", "bool"]
    /// </summary>
    private static List<string> SplitTupleElements(string tupleContent)
    {
        var result = new List<string>();
        var current = new StringBuilder();
        var depth = 0;

        foreach (var ch in tupleContent)
        {
            if (ch == '(')
            {
                depth++;
                current.Append(ch);
            }
            else if (ch == ')')
            {
                depth--;
                current.Append(ch);
            }
            else if (ch == ',' && depth == 0)
            {
                // 顶层逗号，分隔元素
                result.Add(current.ToString());
                current.Clear();
            }
            else
            {
                current.Append(ch);
            }
        }

        if (current.Length > 0)
        {
            result.Add(current.ToString());
        }

        return result;
    }

    /// <summary>
    /// 检查字符串是否是有效的 C# 标识符（用于检测参数名）
    /// </summary>
    private static bool IsValidIdentifier(string text)
    {
        if (string.IsNullOrWhiteSpace(text))
            return false;

        var trimmed = text.Trim();
        if (trimmed.Length == 0)
            return false;

        // 第一个字符必须是字母、下划线或 @
        if (!char.IsLetter(trimmed[0]) && trimmed[0] != '_' && trimmed[0] != '@')
            return false;

        // 其余字符必须是字母、数字或下划线
        for (int i = 1; i < trimmed.Length; i++)
        {
            if (!char.IsLetterOrDigit(trimmed[i]) && trimmed[i] != '_')
                return false;
        }

        return true;
    }

    /// <summary>
    /// 生成模块初始化器 - 自动注册 ResponseSerializer
    /// </summary>
    private static void GenerateModuleInitializer(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Module initializer - automatically registers ResponseSerializer when assembly loads");
        sb.AppendLine("    /// This method is called automatically by the runtime before any other code in the assembly");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");
        sb.AppendLine("        // 自动注册ResponseSerializer实例到全局注册中心");
        sb.AppendLine("        PulseRPC.Server.Processing.Pipeline.ResponseSerializerRegistry.Register(new RegistryImpl());");
        sb.AppendLine("        System.Diagnostics.Debug.WriteLine(\"[PulseRPC] ResponseSerializer registered to global registry\");");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// 检测类型名是否为元组类型
    /// </summary>
    private static bool IsTupleType(string typeName)
    {
        if (string.IsNullOrWhiteSpace(typeName))
            return false;

        // 元组类型通常以 '(' 开头并以 ')' 结尾
        var trimmed = typeName.Trim();
        return trimmed.StartsWith("(", StringComparison.Ordinal) && trimmed.EndsWith(")", StringComparison.Ordinal);
    }

    /// <summary>
    /// 移除元组类型中的元素名称
    /// 例如：(Libra.GuildEntity? guild, Libra.GuildMember? member) -> (Libra.GuildEntity?, Libra.GuildMember?)
    /// </summary>
    private static string StripTupleElementNames(string typeName)
    {
        if (string.IsNullOrWhiteSpace(typeName))
            return typeName;

        var trimmed = typeName.Trim();

        // 如果不是元组类型，直接返回
        if (!trimmed.StartsWith("(", StringComparison.Ordinal) || !trimmed.EndsWith(")", StringComparison.Ordinal))
            return trimmed;

        // 提取元组内容（移除外层括号）
        var tupleContent = trimmed.Substring(1, trimmed.Length - 2);
        var elements = SplitTupleElements(tupleContent);
        var cleanedElements = new List<string>();

        foreach (var element in elements)
        {
            var cleanedElement = StripSingleElementName(element.Trim());
            cleanedElements.Add(cleanedElement);
        }

        return $"({string.Join(", ", cleanedElements)})";
    }

    /// <summary>
    /// 移除单个元组元素中的名称
    /// 例如：Libra.GuildEntity? guild -> Libra.GuildEntity?
    /// </summary>
    private static string StripSingleElementName(string element)
    {
        if (string.IsNullOrWhiteSpace(element))
            return element;

        var trimmed = element.Trim();

        // 如果是嵌套元组，递归处理
        if (trimmed.StartsWith("(", StringComparison.Ordinal) && trimmed.EndsWith(")", StringComparison.Ordinal))
        {
            return StripTupleElementNames(trimmed);
        }

        // 如果是泛型类型，需要特殊处理
        var genericEnd = trimmed.LastIndexOf('>');
        if (genericEnd >= 0)
        {
            // 泛型类型后可能有元素名称
            // 例如: List<int> items
            var afterGeneric = trimmed.Substring(genericEnd + 1).Trim();
            if (!string.IsNullOrWhiteSpace(afterGeneric) && IsValidIdentifier(afterGeneric))
            {
                return trimmed.Substring(0, genericEnd + 1);
            }
            return trimmed;
        }

        // 非泛型类型：查找最后一个空格
        // 例如：Libra.GuildEntity? guild
        var lastSpace = trimmed.LastIndexOf(' ');
        if (lastSpace > 0 && lastSpace < trimmed.Length - 1)
        {
            var beforeSpace = trimmed.Substring(0, lastSpace).Trim();
            var afterSpace = trimmed.Substring(lastSpace + 1).Trim();

            // 如果空格后是有效标识符（元素名），移除它
            // 但要确保 beforeSpace 不以点结尾（不是命名空间的一部分）
            if (IsValidIdentifier(afterSpace) && !beforeSpace.EndsWith(".", StringComparison.Ordinal))
            {
                return beforeSpace;
            }
        }

        return trimmed;
    }

    private static string GetSafeIdentifier(string value)
    {
        var sb = new StringBuilder(value.Length);
        foreach (var ch in value)
        {
            sb.Append(char.IsLetterOrDigit(ch) ? ch : '_');
        }
        return sb.ToString();
    }

    private sealed class ResponseSerializerInfo
    {
        public string ClassName { get; }
        public ushort ProtocolId { get; }
        public string? ResponseTypeName { get; }
        public string? RuntimeTypeName { get; }
        public bool IsNullable { get; }

        public ResponseSerializerInfo(
            string className,
            ushort protocolId,
            string? responseTypeName,
            string? runtimeTypeName,
            bool isNullable)
        {
            ClassName = className;
            ProtocolId = protocolId;
            ResponseTypeName = responseTypeName;
            RuntimeTypeName = runtimeTypeName;
            IsNullable = isNullable;
        }
    }
}
