using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using PulseRPC.Server.SourceGenerator.Models;

namespace PulseRPC.Server.SourceGenerator.Generators;

/// <summary>
/// 路由表生成器 - 生成高性能的静态路由分发表
/// </summary>
public static class RoutingTableGenerator
{
    /// <summary>
    /// 为所有服务生成统一的路由表
    /// </summary>
    public static string GenerateRoutingTable(List<ServiceModel> services)
    {
        var sb = new StringBuilder();

        // 文件头部
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This code was generated by PulseRPC.Server.SourceGenerator");
        sb.AppendLine("// High-performance static routing table for all PulseRPC services");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();

        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS8019");
        sb.AppendLine();

        // Using statements
        GenerateUsingStatements(sb, services);

        // 生成全局路由表
        GenerateGlobalRoutingTable(sb, services);

        return sb.ToString();
    }

    /// <summary>
    /// 生成using语句
    /// </summary>
    private static void GenerateUsingStatements(StringBuilder sb, List<ServiceModel> services)
    {
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Buffers;");
        sb.AppendLine("using PulseRPC.Server;");
        sb.AppendLine("using PulseRPC.Server.Abstractions;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");

        // 添加服务命名空间
        var namespaces = services.Select(s => s.Namespace).Where(ns => !string.IsNullOrEmpty(ns)).Distinct().ToList();
        foreach (var ns in namespaces)
        {
            sb.AppendLine($"using {ns};");
        }

        sb.AppendLine();
    }

    /// <summary>
    /// 生成全局路由表类
    /// </summary>
    private static void GenerateGlobalRoutingTable(StringBuilder sb, List<ServiceModel> services)
    {
        sb.AppendLine("namespace PulseRPC.Generated;");
        sb.AppendLine();

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// High-performance static routing table for all PulseRPC services");
        sb.AppendLine("/// Provides compile-time optimized service dispatch");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public sealed class ServiceRoutingTable : IServiceRoutingTable");
        sb.AppendLine("{");
        sb.AppendLine("    // 单例实例");
        sb.AppendLine("    private static readonly ServiceRoutingTable _instance = new();");
        sb.AppendLine("    ");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 获取路由表单例实例");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static ServiceRoutingTable Instance => _instance;");
        sb.AppendLine("    ");
        sb.AppendLine("    // 私有构造函数，确保单例");
        sb.AppendLine("    private ServiceRoutingTable() { }");
        sb.AppendLine();

        // 生成路由方法
        GenerateRouteMethod(sb, services);

        // 生成每个服务的专用路由器
        GenerateServiceRouters(sb, services);

        // 生成统计信息
        GenerateStatistics(sb, services);

        // 生成辅助方法
        GenerateHelperMethods(sb, services);

        sb.AppendLine("}");
    }


    /// <summary>
    /// 生成主路由方法（仅 Protocol ID 版本）
    /// </summary>
    private static void GenerateRouteMethod(StringBuilder sb, List<ServiceModel> services)
    {
        // 生成基于协议号的路由方法
        GenerateProtocolIdBasedRouting(sb, services);
    }

    /// <summary>
    /// 生成基于协议号的路由（最快路径）
    /// </summary>
    private static void GenerateProtocolIdBasedRouting(StringBuilder sb, List<ServiceModel> services)
    {
        sb.AppendLine("    #region Protocol ID Based Routing (Recommended - Zero Allocation)");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// [推荐] 基于协议号的超快速路由 - 零字符串分配");
        sb.AppendLine("    /// 通过编译时生成的协议号直接定位到方法处理器");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    public ValueTask<object?> RouteByProtocolIdAsync(IServiceProvider serviceProvider, ushort protocolId, ReadOnlyMemory<byte> data, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        return protocolId switch");
        sb.AppendLine("        {");

        // 为所有服务的所有方法生成协议号路由
        foreach (var service in services)
        {
            foreach (var method in service.Methods)
            {
                var protocolIdConstantName = $"ProtocolIds.{GetProtocolIdConstantName(service.InterfaceName, method)}";
                var routerMethodName = GetProtocolIdRouterMethodName(service.InterfaceName, method.MethodName);
                sb.AppendLine($"            {protocolIdConstantName} => {routerMethodName}(serviceProvider, data, cancellationToken),");
            }
        }

        sb.AppendLine("            _ => ThrowProtocolIdNotFoundException(protocolId)");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();

        // 生成协议号常量
        GenerateProtocolIdConstants(sb, services);

        sb.AppendLine("    #endregion");
        sb.AppendLine();
    }

    /// <summary>
    /// 生成协议号常量
    /// </summary>
    private static void GenerateProtocolIdConstants(StringBuilder sb, List<ServiceModel> services)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Protocol ID constants for all methods");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class ProtocolIds");
        sb.AppendLine("    {");

        foreach (var service in services)
        {
            sb.AppendLine($"        // {service.InterfaceName}");
            foreach (var method in service.Methods)
            {
                var constantName = GetProtocolIdConstantName(service.InterfaceName, method);
                sb.AppendLine($"        public const ushort {constantName} = 0x{method.ProtocolId:X4};  // {service.InterfaceName}.{method.MethodName}");
            }
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }


    /// <summary>
    /// 为每个方法生成专用的 Protocol ID 路由器，并生成代理获取方法
    /// </summary>
    private static void GenerateServiceRouters(StringBuilder sb, List<ServiceModel> services)
    {
        // 生成基于协议号的方法路由器
        GenerateProtocolIdMethodRouters(sb, services);

        // 为每个服务生成代理获取方法
        sb.AppendLine("    #region Proxy Getters");
        sb.AppendLine();
        foreach (var service in services)
        {
            GenerateProxyGetter(sb, service);
        }
        sb.AppendLine("    #endregion");
        sb.AppendLine();
    }

    /// <summary>
    /// 为每个方法生成专用的协议号路由器
    /// </summary>
    private static void GenerateProtocolIdMethodRouters(StringBuilder sb, List<ServiceModel> services)
    {
        sb.AppendLine("    #region Protocol ID Method Routers");
        sb.AppendLine();

        foreach (var service in services)
        {
            foreach (var method in service.Methods)
            {
                GenerateProtocolIdMethodRouter(sb, service, method);
            }
        }

        sb.AppendLine("    #endregion");
        sb.AppendLine();
    }

    /// <summary>
    /// 生成单个方法的协议号路由器
    /// </summary>
    private static void GenerateProtocolIdMethodRouter(StringBuilder sb, ServiceModel service, MethodModel method)
    {
        var routerMethodName = GetProtocolIdRouterMethodName(service.InterfaceName, method.MethodName);
        var proxyClassName = $"{service.InterfaceName.TrimStart('I')}Proxy";

        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Protocol ID router for {service.InterfaceName}.{method.MethodName} (0x{method.ProtocolId:X4})");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"    private ValueTask<object?> {routerMethodName}(IServiceProvider serviceProvider, ReadOnlyMemory<byte> data, CancellationToken cancellationToken)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var proxy = GetOrCreate{service.InterfaceName.TrimStart('I')}Proxy(serviceProvider);");
        sb.AppendLine($"        return proxy.Invoke_{method.MethodName}_Async(data, cancellationToken);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }


    /// <summary>
    /// 生成代理实例获取方法
    /// </summary>
    private static void GenerateProxyGetter(StringBuilder sb, ServiceModel service)
    {
        var proxyClassName = $"{service.InterfaceName.TrimStart('I')}Proxy";

        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Get or create proxy for {service.InterfaceName} from ServiceProvider");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"    private {service.Namespace}.Generated.{proxyClassName} GetOrCreate{service.InterfaceName.TrimStart('I')}Proxy(IServiceProvider serviceProvider)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var implementation = ({service.InterfaceFullName}?)serviceProvider?.GetService(typeof({service.InterfaceFullName}));");
        sb.AppendLine("        if (implementation is null)");
        sb.AppendLine($"            throw new InvalidOperationException($\"Service implementation for {service.InterfaceName} not registered in DI container\");");
        sb.AppendLine($"        return new {service.Namespace}.Generated.{proxyClassName}(implementation);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// 生成统计信息
    /// </summary>
    private static void GenerateStatistics(StringBuilder sb, List<ServiceModel> services)
    {
        sb.AppendLine("    #region Statistics and Metadata");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Routing table statistics and metadata");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class Statistics");
        sb.AppendLine("    {");
        sb.AppendLine($"        public const int TotalServices = {services.Count};");
        sb.AppendLine($"        public const int TotalMethods = {services.Sum(s => s.Methods.Count)};");

        sb.AppendLine("        public static readonly Dictionary<string, int> MethodCountByService = new()");
        sb.AppendLine("        {");
        foreach (var service in services)
        {
            sb.AppendLine($"            [\"{service.InterfaceFullName}\"] = {service.Methods.Count},");
        }
        sb.AppendLine("        };");

        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    #endregion");
        sb.AppendLine();
    }

    /// <summary>
    /// 生成辅助方法
    /// </summary>
    private static void GenerateHelperMethods(StringBuilder sb, List<ServiceModel> services)
    {
        sb.AppendLine("    #region Helper Methods");
        sb.AppendLine();

        // 异常抛出方法（仅 Protocol ID 版本）
        sb.AppendLine("    [MethodImpl(MethodImplOptions.NoInlining)]");
        sb.AppendLine("    private static ValueTask<object?> ThrowProtocolIdNotFoundException(ushort protocolId)");
        sb.AppendLine("    {");
        sb.AppendLine("        throw new ProtocolIdNotFoundException($\"Method with protocol ID '0x{protocolId:X4}' ({protocolId}) not found. Total methods: {Statistics.TotalMethods}\");");
        sb.AppendLine("    }");
        sb.AppendLine();

        // 服务提供者访问
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Service provider access (must be set during application startup)");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IServiceProvider? ServiceProvider { get; set; }");
        sb.AppendLine();

        // 生成 ModuleInitializer
        GenerateModuleInitializer(sb);

        sb.AppendLine("    #endregion");
    }

    /// <summary>
    /// 生成模块初始化器 - 自动注册 ServiceRoutingTable
    /// </summary>
    private static void GenerateModuleInitializer(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Module initializer - automatically registers ServiceRoutingTable when assembly loads");
        sb.AppendLine("    /// This method is called automatically by the runtime before any other code in the assembly");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");
        sb.AppendLine("        // 自动注册路由表实例到全局注册中心");
        sb.AppendLine("        PulseRPC.Server.ServiceRoutingTableRegistry.Register(Instance);");
        sb.AppendLine("        System.Diagnostics.Debug.WriteLine(\"[PulseRPC] ServiceRoutingTable registered to global registry\");");
        sb.AppendLine("    }");
        sb.AppendLine();
    }


    /// <summary>
    /// 获取协议号常量名（旧版本 - 向后兼容）
    /// </summary>
    [Obsolete("Use GetProtocolIdConstantName(string, MethodModel) instead to support method overloading")]
    private static string GetProtocolIdConstantName(string interfaceName, string methodName)
    {
        var serviceName = interfaceName.TrimStart('I').ToUpperInvariant();
        var method = methodName.ToUpperInvariant();
        return $"{serviceName}_{method}";
    }

    /// <summary>
    /// 获取协议号常量名（支持方法重载）
    /// </summary>
    private static string GetProtocolIdConstantName(string interfaceName, MethodModel method)
    {
        var serviceName = interfaceName.TrimStart('I').ToUpperInvariant();
        var methodName = method.MethodName.ToUpperInvariant();
        var baseName = $"{serviceName}_{methodName}";

        // 如果方法没有参数，直接返回基础名称
        if (method.Parameters.Count == 0)
        {
            return baseName;
        }

        // 构建参数类型的简短描述
        var paramParts = method.Parameters.Select(p => GetSimpleTypeNameServer(p.TypeName)).ToArray();
        var paramSuffix = string.Join("_", paramParts);

        return $"{baseName}_{paramSuffix}";
    }

    /// <summary>
    /// 获取类型的简化名称（服务端版本）
    /// </summary>
    private static string GetSimpleTypeNameServer(string typeName)
    {
        // 移除命名空间
        var lastDotIndex = typeName.LastIndexOf('.');
        var simpleName = lastDotIndex >= 0 ? typeName.Substring(lastDotIndex + 1) : typeName;

        // 处理数组类型
        if (simpleName.EndsWith("[]"))
        {
            return simpleName.Replace("[]", "Array");
        }

        // 处理泛型类型（简化表示）
        if (simpleName.Contains('<'))
        {
            // 例如: List<int> -> ListOfInt
            simpleName = simpleName
                .Replace("<", "Of")
                .Replace(">", "")
                .Replace(",", "And")
                .Replace(" ", "");
        }

        // 移除常见的后缀以缩短名称
        simpleName = simpleName
            .Replace("Event", "Evt")
            .Replace("Message", "Msg")
            .Replace("Request", "Req")
            .Replace("Response", "Rsp")
            .Replace("Data", "")
            .Replace("Info", "");

        return simpleName.ToUpperInvariant();
    }

    /// <summary>
    /// 获取基于协议号的路由器方法名
    /// </summary>
    private static string GetProtocolIdRouterMethodName(string interfaceName, string methodName)
    {
        return $"RouteById_{interfaceName.TrimStart('I')}_{methodName}";
    }

    /// <summary>
    /// 生成SourceText用于编译器集成
    /// </summary>
    public static SourceText GenerateSourceText(List<ServiceModel> services)
    {
        var code = GenerateRoutingTable(services);
        return SourceText.From(code, Encoding.UTF8);
    }
}
