using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using PulseRPC.Server.SourceGenerator.Models;

namespace PulseRPC.Server.SourceGenerator.Generators;

/// <summary>
/// 为服务端主动调用 Hub/Actor 的场景生成基于 <c>IPulseRouter</c> 的强类型代理。
/// </summary>
public static class RouterProxyGenerator
{
    public static SourceText GenerateSourceText(ServiceModel serviceModel)
        => SourceText.From(Generate(serviceModel), Encoding.UTF8);

    public static string Generate(ServiceModel serviceModel)
    {
        var sb = new StringBuilder();
        var canonicalHub = serviceModel.InterfaceName.TrimStart('I');
        var proxyName = canonicalHub + "RouterProxy";

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Typed IPulseRouter proxy generated by PulseRPC.Server.SourceGenerator");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using MemoryPack;");
        sb.AppendLine("using PulseRPC;");
        sb.AppendLine("using PulseRPC.Routing;");
        sb.AppendLine();
        sb.AppendLine($"namespace {serviceModel.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// 强类型 {serviceModel.InterfaceName} 出站代理；直接使用 IPulseRouter，不注册服务端路由表或全局 registry。");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed class {proxyName} : {serviceModel.InterfaceFullName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public const string HubName = \"{EscapeString(canonicalHub)}\";");
        sb.AppendLine();
        sb.AppendLine("    private readonly IPulseRouter _router;");
        sb.AppendLine("    private readonly PulseAddress _address;");
        sb.AppendLine();

        foreach (var method in serviceModel.Methods)
        {
            sb.AppendLine($"    private const ushort Protocol_{method.GeneratedIdentifier} = 0x{method.ProtocolId:X4};");
        }
        sb.AppendLine();

        sb.AppendLine($"    public {proxyName}(IPulseRouter router, PulseAddress address)");
        sb.AppendLine("    {");
        sb.AppendLine("        _router = router ?? throw new ArgumentNullException(nameof(router));");
        sb.AppendLine("        if (!string.Equals(address.Hub, HubName, StringComparison.Ordinal))");
        sb.AppendLine("        {");
        sb.AppendLine("            throw new ArgumentException($\"Address Hub '{address.Hub}' does not match typed proxy Hub '{HubName}'.\", nameof(address));");
        sb.AppendLine("        }");
        sb.AppendLine("        _address = address;");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    public static {proxyName} ForActor(IPulseRouter router, string key, string? nodeId = null) =>");
        sb.AppendLine($"        new {proxyName}(router, PulseAddress.Actor(\"{EscapeString(canonicalHub)}\", key, nodeId));");
        sb.AppendLine();

        foreach (var method in serviceModel.Methods)
        {
            GenerateMethod(sb, method);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void GenerateMethod(StringBuilder sb, MethodModel method)
    {
        var returnType = method.ReturnTypeFullName;
        var cancellationToken = method.Parameters.FirstOrDefault(parameter => parameter.IsCancellationToken);
        var cancellationExpression = cancellationToken is null
            ? "CancellationToken.None"
            : EscapeIdentifier(cancellationToken.Name);

        sb.AppendLine("    /// <inheritdoc/>");
        sb.Append($"    public async {returnType} {EscapeIdentifier(method.MethodName)}(");
        for (var i = 0; i < method.Parameters.Count; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            var parameter = method.Parameters[i];
            sb.Append(GetRefPrefix(parameter.RefKind));
            sb.Append(parameter.TypeFullName);
            sb.Append(' ');
            sb.Append(EscapeIdentifier(parameter.Name));
            if (parameter.IsCancellationToken)
            {
                sb.Append(" = default");
            }
        }
        sb.AppendLine(")");
        sb.AppendLine("    {");

        GenerateSerialization(sb, method);
        sb.AppendLine();

        var protocolConstant = "Protocol_" + method.GeneratedIdentifier;
        if (method.ResponseTypeFullName is null)
        {
            sb.AppendLine($"        await _router.SendAsync(_address, {protocolConstant}, payload, cancellationToken: {cancellationExpression});");
        }
        else
        {
            sb.AppendLine($"        var response = await _router.AskAsync(_address, {protocolConstant}, payload, {cancellationExpression});");
            sb.AppendLine($"        return MemoryPackSerializer.Deserialize<{method.ResponseTypeFullName}>(response.Span)!;");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateSerialization(StringBuilder sb, MethodModel method)
    {
        var wireParameters = method.Parameters.Where(parameter => !parameter.IsCancellationToken).ToArray();
        if (wireParameters.Length == 0)
        {
            sb.AppendLine("        var payload = MemoryPackSerializer.Serialize(PulseRPC.EmptyResponse.Instance);");
            return;
        }

        if (wireParameters.Length == 1)
        {
            sb.AppendLine($"        var payload = MemoryPackSerializer.Serialize({EscapeIdentifier(wireParameters[0].Name)});");
            return;
        }

        sb.AppendLine($"        var payload = MemoryPackSerializer.Serialize(({string.Join(", ", wireParameters.Select(parameter => EscapeIdentifier(parameter.Name)))}));");
    }

    private static string GetRefPrefix(RefKind refKind)
    {
        return refKind switch
        {
            RefKind.Ref => "ref ",
            RefKind.Out => "out ",
            RefKind.In => "in ",
            _ => string.Empty,
        };
    }

    private static string EscapeIdentifier(string identifier)
        => IsCSharpKeyword(identifier) ? "@" + identifier : identifier;

    private static bool IsCSharpKeyword(string identifier)
    {
        return identifier is
            "abstract" or "as" or "base" or "bool" or "break" or "byte" or "case" or "catch" or
            "char" or "checked" or "class" or "const" or "continue" or "decimal" or "default" or
            "delegate" or "do" or "double" or "else" or "enum" or "event" or "explicit" or "extern" or
            "false" or "finally" or "fixed" or "float" or "for" or "foreach" or "goto" or "if" or
            "implicit" or "in" or "int" or "interface" or "internal" or "is" or "lock" or "long" or
            "namespace" or "new" or "null" or "object" or "operator" or "out" or "override" or
            "params" or "private" or "protected" or "public" or "readonly" or "ref" or "return" or
            "sbyte" or "sealed" or "short" or "sizeof" or "stackalloc" or "static" or "string" or
            "struct" or "switch" or "this" or "throw" or "true" or "try" or "typeof" or "uint" or
            "ulong" or "unchecked" or "unsafe" or "ushort" or "using" or "virtual" or "void" or
            "volatile" or "while";
    }

    private static string EscapeString(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
