using System.Collections.Generic;
using System.Linq;
using System.Text;
using PulseRPC.Server.SourceGenerator.Models;

namespace PulseRPC.Server.SourceGenerator.Generators;

/// <summary>
/// 智能事件路由器生成器 - 生成基于上下文的智能事件路由代码
/// </summary>
public static class SmartEventRouterGenerator
{
    /// <summary>
    /// 生成智能事件路由器的源代码
    /// </summary>
    public static string GenerateSourceText(List<ServiceModel> serviceModels)
    {
        var sb = new StringBuilder();

        GenerateFileHeader(sb);
        GenerateEventRouterInterface(sb);
        GenerateSmartEventRouterImplementation(sb, serviceModels);
        GenerateRoutingSupportTypes(sb);

        return sb.ToString();
    }

    private static void GenerateFileHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// PulseRPC Smart Event Router Generator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Collections.Concurrent;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine("using PulseRPC.Server.Transport;");
        sb.AppendLine("using PulseRPC.Server.Events;");
        sb.AppendLine();
    }

    private static void GenerateEventRouterInterface(StringBuilder sb)
    {
        sb.AppendLine("namespace PulseRPC.Server.Events");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 智能事件路由器接口 - 基于上下文智能路由事件");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public interface ISmartEventRouter");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 注册路由规则");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        void RegisterRoute(EventRoute route);");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 注册条件路由规则");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        void RegisterConditionalRoute<T>(string eventName, Func<T, EventRoutingContext, IEnumerable<string>> selector);");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 路由事件到目标连接");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        Task<IReadOnlyList<string>> RouteEventAsync(string eventName, object eventData, EventRoutingContext context);");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 路由并发布事件");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        Task<int> RouteAndPublishAsync<T>(string eventName, T eventData, EventRoutingContext context);");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 获取路由统计信息");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        EventRoutingStatistics GetStatistics();");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 清除所有路由规则");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        void ClearRoutes();");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateSmartEventRouterImplementation(StringBuilder sb, List<ServiceModel> serviceModels)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 智能事件路由器实现 - 高性能、可扩展的事件路由");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public sealed class GeneratedSmartEventRouter : ISmartEventRouter, IDisposable");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly ConcurrentDictionary<string, List<EventRoute>> _routes = new();");
        sb.AppendLine("        private readonly ConcurrentDictionary<string, object> _conditionalRoutes = new();");
        sb.AppendLine("        private readonly IServerChannelManager _channelManager;");
        sb.AppendLine("        private readonly IEventSubscriptionManager _subscriptionManager;");
        sb.AppendLine("        private readonly ILogger<GeneratedSmartEventRouter> _logger;");
        sb.AppendLine("        private readonly EventRoutingMetrics _metrics = new();");
        sb.AppendLine("        private readonly ReaderWriterLockSlim _routesLock = new();");
        sb.AppendLine("        private bool _disposed;");
        sb.AppendLine();

        // 生成预定义路由
        GeneratePreDefinedRoutes(sb, serviceModels);

        // 生成构造函数
        sb.AppendLine("        public GeneratedSmartEventRouter(");
        sb.AppendLine("            IServerChannelManager channelManager,");
        sb.AppendLine("            IEventSubscriptionManager subscriptionManager,");
        sb.AppendLine("            ILogger<GeneratedSmartEventRouter> logger)");
        sb.AppendLine("        {");
        sb.AppendLine("            _channelManager = channelManager ?? throw new ArgumentNullException(nameof(channelManager));");
        sb.AppendLine("            _subscriptionManager = subscriptionManager ?? throw new ArgumentNullException(nameof(subscriptionManager));");
        sb.AppendLine("            _logger = logger ?? throw new ArgumentNullException(nameof(logger));");
        sb.AppendLine();
        sb.AppendLine("            // 注册预定义路由");
        sb.AppendLine("            RegisterPredefinedRoutes();");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 生成路由注册方法
        GenerateRouteRegistrationMethods(sb);

        // 生成路由执行方法
        GenerateRouteExecutionMethods(sb, serviceModels);

        // 生成统计和管理方法
        GenerateManagementMethods(sb);

        // 生成Dispose方法
        GenerateDisposeMethod(sb);

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GeneratePreDefinedRoutes(StringBuilder sb, List<ServiceModel> serviceModels)
    {
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 注册预定义的路由规则");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        private void RegisterPredefinedRoutes()");
        sb.AppendLine("        {");

        // 为每个服务模型生成路由规则
        foreach (var service in serviceModels)
        {
            var serviceName = service.InterfaceName;

            sb.AppendLine($"            // {serviceName} 服务的路由规则");
            sb.AppendLine($"            RegisterRoute(new EventRoute");
            sb.AppendLine("            {");
            sb.AppendLine($"                Id = \"{serviceName}.Room\",");
            sb.AppendLine($"                EventNamePattern = \"{serviceName}.*\",");
            sb.AppendLine("                TargetSelector = (data, context) =>");
            sb.AppendLine("                {");
            sb.AppendLine("                    // 房间路由：发送给同房间的用户");
            sb.AppendLine("                    if (!string.IsNullOrEmpty(context.RoomId))");
            sb.AppendLine("                    {");
            sb.AppendLine("                        return _subscriptionManager.GetSubscribersByTags(");
            sb.AppendLine("                            new Dictionary<string, string> { [\"room_id\"] = context.RoomId });");
            sb.AppendLine("                    }");
            sb.AppendLine("                    return Array.Empty<string>();");
            sb.AppendLine("                },");
            sb.AppendLine("                Priority = 1,");
            sb.AppendLine("                Enabled = true");
            sb.AppendLine("            });");
            sb.AppendLine();

            sb.AppendLine($"            RegisterRoute(new EventRoute");
            sb.AppendLine("            {");
            sb.AppendLine($"                Id = \"{serviceName}.User\",");
            sb.AppendLine($"                EventNamePattern = \"{serviceName}.*\",");
            sb.AppendLine("                TargetSelector = (data, context) =>");
            sb.AppendLine("                {");
            sb.AppendLine("                    // 用户路由：发送给特定用户");
            sb.AppendLine("                    if (!string.IsNullOrEmpty(context.UserId))");
            sb.AppendLine("                    {");
            sb.AppendLine("                        return _subscriptionManager.GetSubscribersByTags(");
            sb.AppendLine("                            new Dictionary<string, string> { [\"user_id\"] = context.UserId });");
            sb.AppendLine("                    }");
            sb.AppendLine("                    return Array.Empty<string>();");
            sb.AppendLine("                },");
            sb.AppendLine("                Priority = 2,");
            sb.AppendLine("                Enabled = true");
            sb.AppendLine("            });");
            sb.AppendLine();
        }

        // 通用路由规则
        sb.AppendLine("            // 通用广播路由（最低优先级）");
        sb.AppendLine("            RegisterRoute(new EventRoute");
        sb.AppendLine("            {");
        sb.AppendLine("                Id = \"Broadcast\",");
        sb.AppendLine("                EventNamePattern = \"*\",");
        sb.AppendLine("                TargetSelector = (data, context) =>");
        sb.AppendLine("                {");
        sb.AppendLine("                    // 广播到所有已认证连接");
        sb.AppendLine("                    return _channelManager.GetAuthenticatedChannels()");
        sb.AppendLine("                        .Select(c => c.ConnectionId).ToList();");
        sb.AppendLine("                },");
        sb.AppendLine("                Priority = 0,");
        sb.AppendLine("                Enabled = true");
        sb.AppendLine("            });");

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GenerateRouteRegistrationMethods(StringBuilder sb)
    {
        sb.AppendLine("        /// <inheritdoc/>");
        sb.AppendLine("        public void RegisterRoute(EventRoute route)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (route == null) throw new ArgumentNullException(nameof(route));");
        sb.AppendLine("            ");
        sb.AppendLine("            _routesLock.EnterWriteLock();");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var routeList = _routes.GetOrAdd(route.EventNamePattern, _ => new List<EventRoute>());");
        sb.AppendLine("                ");
        sb.AppendLine("                // 移除相同ID的旧路由");
        sb.AppendLine("                routeList.RemoveAll(r => r.Id == route.Id);");
        sb.AppendLine("                ");
        sb.AppendLine("                // 按优先级插入");
        sb.AppendLine("                var insertIndex = routeList.FindIndex(r => r.Priority < route.Priority);");
        sb.AppendLine("                if (insertIndex >= 0)");
        sb.AppendLine("                    routeList.Insert(insertIndex, route);");
        sb.AppendLine("                else");
        sb.AppendLine("                    routeList.Add(route);");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                _routesLock.ExitWriteLock();");
        sb.AppendLine("            }");
        sb.AppendLine("            ");
        sb.AppendLine("            _logger.LogDebug(\"Registered route {RouteId} for pattern {Pattern} with priority {Priority}\",");
        sb.AppendLine("                route.Id, route.EventNamePattern, route.Priority);");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        /// <inheritdoc/>");
        sb.AppendLine("        public void RegisterConditionalRoute<T>(string eventName, Func<T, EventRoutingContext, IEnumerable<string>> selector)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (string.IsNullOrEmpty(eventName)) throw new ArgumentException(\"Event name cannot be null or empty\", nameof(eventName));");
        sb.AppendLine("            if (selector == null) throw new ArgumentNullException(nameof(selector));");
        sb.AppendLine("            ");
        sb.AppendLine("            _conditionalRoutes[eventName] = selector;");
        sb.AppendLine("            ");
        sb.AppendLine("            _logger.LogDebug(\"Registered conditional route for event {EventName}\", eventName);");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GenerateRouteExecutionMethods(StringBuilder sb, List<ServiceModel> serviceModels)
    {
        sb.AppendLine("        /// <inheritdoc/>");
        sb.AppendLine("        public async Task<IReadOnlyList<string>> RouteEventAsync(string eventName, object eventData, EventRoutingContext context)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (string.IsNullOrEmpty(eventName)) throw new ArgumentException(\"Event name cannot be null or empty\", nameof(eventName));");
        sb.AppendLine("            ");
        sb.AppendLine("            ThrowIfDisposed();");
        sb.AppendLine("            ");
        sb.AppendLine("            var stopwatch = System.Diagnostics.Stopwatch.StartNew();");
        sb.AppendLine("            ");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                // 首先尝试条件路由");
        sb.AppendLine("                if (_conditionalRoutes.TryGetValue(eventName, out var conditionalRoute))");
        sb.AppendLine("                {");
        sb.AppendLine("                    var targets = InvokeConditionalRoute(conditionalRoute, eventData, context);");
        sb.AppendLine("                    if (targets.Any())");
        sb.AppendLine("                    {");
        sb.AppendLine("                        _metrics.RecordRouting(eventName, targets.Count(), stopwatch.Elapsed);");
        sb.AppendLine("                        return targets.ToList();");
        sb.AppendLine("                    }");
        sb.AppendLine("                }");
        sb.AppendLine("                ");
        sb.AppendLine("                // 然后尝试模式路由");
        sb.AppendLine("                var matchingRoutes = FindMatchingRoutes(eventName);");
        sb.AppendLine("                ");
        sb.AppendLine("                foreach (var route in matchingRoutes.Where(r => r.Enabled).OrderByDescending(r => r.Priority))");
        sb.AppendLine("                {");
        sb.AppendLine("                    try");
        sb.AppendLine("                    {");
        sb.AppendLine("                        var targets = route.TargetSelector(eventData, context);");
        sb.AppendLine("                        if (targets.Any())");
        sb.AppendLine("                        {");
        sb.AppendLine("                            var targetList = targets.ToList();");
        sb.AppendLine("                            _metrics.RecordRouting(eventName, targetList.Count, stopwatch.Elapsed);");
        sb.AppendLine("                            return targetList;");
        sb.AppendLine("                        }");
        sb.AppendLine("                    }");
        sb.AppendLine("                    catch (Exception ex)");
        sb.AppendLine("                    {");
        sb.AppendLine("                        _logger.LogWarning(ex, \"Route {RouteId} failed for event {EventName}\", route.Id, eventName);");
        sb.AppendLine("                        _metrics.RecordRoutingError(eventName, ex);");
        sb.AppendLine("                    }");
        sb.AppendLine("                }");
        sb.AppendLine("                ");
        sb.AppendLine("                // 如果没有匹配的路由，返回空列表");
        sb.AppendLine("                _metrics.RecordRouting(eventName, 0, stopwatch.Elapsed);");
        sb.AppendLine("                return Array.Empty<string>();");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine("                _metrics.RecordRoutingError(eventName, ex);");
        sb.AppendLine("                _logger.LogError(ex, \"Error routing event {EventName}\", eventName);");
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        /// <inheritdoc/>");
        sb.AppendLine("        public async Task<int> RouteAndPublishAsync<T>(string eventName, T eventData, EventRoutingContext context)");
        sb.AppendLine("        {");
        sb.AppendLine("            var targets = await RouteEventAsync(eventName, eventData!, context);");
        sb.AppendLine("            ");
        sb.AppendLine("            if (!targets.Any())");
        sb.AppendLine("            {");
        sb.AppendLine("                _logger.LogDebug(\"No targets found for event {EventName}\", eventName);");
        sb.AppendLine("                return 0;");
        sb.AppendLine("            }");
        sb.AppendLine("            ");
        sb.AppendLine("            // 获取目标通道");
        sb.AppendLine("            var channels = _channelManager.GetAuthenticatedChannels()");
        sb.AppendLine("                .Where(c => targets.Contains(c.ConnectionId))");
        sb.AppendLine("                .ToList();");
        sb.AppendLine("            ");
        sb.AppendLine("            if (!channels.Any())");
        sb.AppendLine("            {");
        sb.AppendLine("                _logger.LogDebug(\"No active channels found for targets of event {EventName}\", eventName);");
        sb.AppendLine("                return 0;");
        sb.AppendLine("            }");
        sb.AppendLine("            ");
        sb.AppendLine("            // 序列化事件数据");
        sb.AppendLine("            var serializedData = SerializeEventData(eventData);");
        sb.AppendLine("            ");
        sb.AppendLine("            // 并行发送到所有目标通道");
        sb.AppendLine("            var tasks = channels.Select(async channel =>");
        sb.AppendLine("            {");
        sb.AppendLine("                try");
        sb.AppendLine("                {");
        sb.AppendLine("                    await channel.SendAsync(serializedData, CancellationToken.None);");
        sb.AppendLine("                    return true;");
        sb.AppendLine("                }");
        sb.AppendLine("                catch (Exception ex)");
        sb.AppendLine("                {");
        sb.AppendLine("                    _logger.LogWarning(ex, \"Failed to send event {EventName} to channel {ConnectionId}\",");
        sb.AppendLine("                        eventName, channel.ConnectionId);");
        sb.AppendLine("                    return false;");
        sb.AppendLine("                }");
        sb.AppendLine("            });");
        sb.AppendLine("            ");
        sb.AppendLine("            var results = await Task.WhenAll(tasks);");
        sb.AppendLine("            var successCount = results.Count(r => r);");
        sb.AppendLine("            ");
        sb.AppendLine("            _logger.LogDebug(\"Published event {EventName} to {SuccessCount}/{TotalCount} channels\",");
        sb.AppendLine("                eventName, successCount, channels.Count);");
        sb.AppendLine("            ");
        sb.AppendLine("            return successCount;");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GenerateManagementMethods(StringBuilder sb)
    {
        sb.AppendLine("        /// <inheritdoc/>");
        sb.AppendLine("        public EventRoutingStatistics GetStatistics()");
        sb.AppendLine("        {");
        sb.AppendLine("            return new EventRoutingStatistics");
        sb.AppendLine("            {");
        sb.AppendLine("                TotalRoutes = _routes.Values.Sum(list => list.Count),");
        sb.AppendLine("                TotalConditionalRoutes = _conditionalRoutes.Count,");
        sb.AppendLine("                RoutingMetrics = _metrics.GetSnapshot()");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        /// <inheritdoc/>");
        sb.AppendLine("        public void ClearRoutes()");
        sb.AppendLine("        {");
        sb.AppendLine("            _routesLock.EnterWriteLock();");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                _routes.Clear();");
        sb.AppendLine("                _conditionalRoutes.Clear();");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                _routesLock.ExitWriteLock();");
        sb.AppendLine("            }");
        sb.AppendLine("            ");
        sb.AppendLine("            _logger.LogInformation(\"All routes have been cleared\");");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 辅助方法
        GenerateHelperMethods(sb);
    }

    private static void GenerateHelperMethods(StringBuilder sb)
    {
        sb.AppendLine("        private List<EventRoute> FindMatchingRoutes(string eventName)");
        sb.AppendLine("        {");
        sb.AppendLine("            var matchingRoutes = new List<EventRoute>();");
        sb.AppendLine("            ");
        sb.AppendLine("            _routesLock.EnterReadLock();");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                foreach (var kvp in _routes)");
        sb.AppendLine("                {");
        sb.AppendLine("                    var pattern = kvp.Key;");
        sb.AppendLine("                    if (pattern == \"*\" || eventName.StartsWith(pattern.TrimEnd('*')))");
        sb.AppendLine("                    {");
        sb.AppendLine("                        matchingRoutes.AddRange(kvp.Value);");
        sb.AppendLine("                    }");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                _routesLock.ExitReadLock();");
        sb.AppendLine("            }");
        sb.AppendLine("            ");
        sb.AppendLine("            return matchingRoutes;");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private static IEnumerable<string> InvokeConditionalRoute(object routeDelegate, object eventData, EventRoutingContext context)");
        sb.AppendLine("        {");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                // 使用反射调用泛型委托");
        sb.AppendLine("                var method = routeDelegate.GetType().GetMethod(\"Invoke\");");
        sb.AppendLine("                if (method != null)");
        sb.AppendLine("                {");
        sb.AppendLine("                    var result = method.Invoke(routeDelegate, new[] { eventData, context });");
        sb.AppendLine("                    return (IEnumerable<string>)result!;");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception)");
        sb.AppendLine("            {");
        sb.AppendLine("                // 忽略反射错误");
        sb.AppendLine("            }");
        sb.AppendLine("            ");
        sb.AppendLine("            return Array.Empty<string>();");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private static ReadOnlyMemory<byte> SerializeEventData<T>(T eventData)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 这里应该使用实际的序列化器");
        sb.AppendLine("            // 暂时返回空数据");
        sb.AppendLine("            return ReadOnlyMemory<byte>.Empty;");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private void ThrowIfDisposed()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_disposed)");
        sb.AppendLine("                throw new ObjectDisposedException(nameof(GeneratedSmartEventRouter));");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GenerateDisposeMethod(StringBuilder sb)
    {
        sb.AppendLine("        public void Dispose()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_disposed) return;");
        sb.AppendLine("            ");
        sb.AppendLine("            _routesLock?.Dispose();");
        sb.AppendLine("            _routes.Clear();");
        sb.AppendLine("            _conditionalRoutes.Clear();");
        sb.AppendLine("            ");
        sb.AppendLine("            _disposed = true;");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GenerateRoutingSupportTypes(StringBuilder sb)
    {
        // EventRoute
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 事件路由规则");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public sealed class EventRoute");
        sb.AppendLine("    {");
        sb.AppendLine("        public string Id { get; set; } = string.Empty;");
        sb.AppendLine("        public string EventNamePattern { get; set; } = string.Empty;");
        sb.AppendLine("        public Func<object, EventRoutingContext, IEnumerable<string>> TargetSelector { get; set; } = null!;");
        sb.AppendLine("        public int Priority { get; set; } = 0;");
        sb.AppendLine("        public bool Enabled { get; set; } = true;");
        sb.AppendLine("        public string Description { get; set; } = string.Empty;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // EventRoutingContext
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 事件路由上下文");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public sealed class EventRoutingContext");
        sb.AppendLine("    {");
        sb.AppendLine("        public string? UserId { get; set; }");
        sb.AppendLine("        public string? RoomId { get; set; }");
        sb.AppendLine("        public string? Region { get; set; }");
        sb.AppendLine("        public Dictionary<string, string> Tags { get; set; } = new();");
        sb.AppendLine("        public Dictionary<string, object> Properties { get; set; } = new();");
        sb.AppendLine("        public DateTime Timestamp { get; set; } = DateTime.UtcNow;");
        sb.AppendLine("        public string? SourceConnectionId { get; set; }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // EventRoutingStatistics
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 事件路由统计信息");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public sealed class EventRoutingStatistics");
        sb.AppendLine("    {");
        sb.AppendLine("        public int TotalRoutes { get; init; }");
        sb.AppendLine("        public int TotalConditionalRoutes { get; init; }");
        sb.AppendLine("        public Dictionary<string, EventRoutingMetric> RoutingMetrics { get; init; } = new();");
        sb.AppendLine("    }");
        sb.AppendLine();

        // EventRoutingMetrics
        sb.AppendLine("    internal sealed class EventRoutingMetrics");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly ConcurrentDictionary<string, EventRoutingMetric> _metrics = new();");
        sb.AppendLine();
        sb.AppendLine("        public void RecordRouting(string eventName, int targetCount, TimeSpan duration)");
        sb.AppendLine("        {");
        sb.AppendLine("            var metric = _metrics.GetOrAdd(eventName, _ => new EventRoutingMetric());");
        sb.AppendLine("            lock (metric)");
        sb.AppendLine("            {");
        sb.AppendLine("                metric.TotalRoutes++;");
        sb.AppendLine("                metric.TotalTargets += targetCount;");
        sb.AppendLine("                metric.TotalDuration += duration.TotalMilliseconds;");
        sb.AppendLine("                metric.MaxDuration = Math.Max(metric.MaxDuration, duration.TotalMilliseconds);");
        sb.AppendLine("                metric.MinDuration = metric.MinDuration == 0 ? duration.TotalMilliseconds : Math.Min(metric.MinDuration, duration.TotalMilliseconds);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public void RecordRoutingError(string eventName, Exception exception)");
        sb.AppendLine("        {");
        sb.AppendLine("            var metric = _metrics.GetOrAdd(eventName, _ => new EventRoutingMetric());");
        sb.AppendLine("            lock (metric)");
        sb.AppendLine("            {");
        sb.AppendLine("                metric.ErrorCount++;");
        sb.AppendLine("                metric.LastError = exception;");
        sb.AppendLine("                metric.LastErrorTime = DateTime.UtcNow;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public Dictionary<string, EventRoutingMetric> GetSnapshot()");
        sb.AppendLine("        {");
        sb.AppendLine("            var snapshot = new Dictionary<string, EventRoutingMetric>();");
        sb.AppendLine("            foreach (var kvp in _metrics)");
        sb.AppendLine("            {");
        sb.AppendLine("                lock (kvp.Value)");
        sb.AppendLine("                {");
        sb.AppendLine("                    snapshot[kvp.Key] = new EventRoutingMetric");
        sb.AppendLine("                    {");
        sb.AppendLine("                        TotalRoutes = kvp.Value.TotalRoutes,");
        sb.AppendLine("                        TotalTargets = kvp.Value.TotalTargets,");
        sb.AppendLine("                        ErrorCount = kvp.Value.ErrorCount,");
        sb.AppendLine("                        TotalDuration = kvp.Value.TotalDuration,");
        sb.AppendLine("                        MaxDuration = kvp.Value.MaxDuration,");
        sb.AppendLine("                        MinDuration = kvp.Value.MinDuration,");
        sb.AppendLine("                        LastError = kvp.Value.LastError,");
        sb.AppendLine("                        LastErrorTime = kvp.Value.LastErrorTime");
        sb.AppendLine("                    };");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("            return snapshot;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // EventRoutingMetric
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 单个事件的路由指标");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public sealed class EventRoutingMetric");
        sb.AppendLine("    {");
        sb.AppendLine("        public long TotalRoutes { get; set; }");
        sb.AppendLine("        public long TotalTargets { get; set; }");
        sb.AppendLine("        public long ErrorCount { get; set; }");
        sb.AppendLine("        public double TotalDuration { get; set; }");
        sb.AppendLine("        public double MaxDuration { get; set; }");
        sb.AppendLine("        public double MinDuration { get; set; }");
        sb.AppendLine("        public Exception? LastError { get; set; }");
        sb.AppendLine("        public DateTime LastErrorTime { get; set; }");
        sb.AppendLine();
        sb.AppendLine("        public double AverageDuration => TotalRoutes > 0 ? TotalDuration / TotalRoutes : 0;");
        sb.AppendLine("        public double AverageTargets => TotalRoutes > 0 ? (double)TotalTargets / TotalRoutes : 0;");
        sb.AppendLine("        public double ErrorRate => TotalRoutes > 0 ? (double)ErrorCount / TotalRoutes : 0;");
        sb.AppendLine("    }");

        // 结束命名空间
        sb.AppendLine("}");
    }
}