using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using PulseRPC.SourceGenerator.Models;

namespace PulseRPC.SourceGenerator.Generators;

/// <summary>
/// 编译时消息分发器生成器 - 消除运行时反射开销
/// </summary>
public static class MessageDispatcherGenerator
{
    /// <summary>
    /// 生成编译时消息分发器代码
    /// </summary>
    public static string GenerateSourceText(List<ServiceModel> serviceModels)
    {
        var code = new StringBuilder();
        
        // 生成文件头
        GenerateFileHeader(code);
        
        // 生成命名空间和类开始
        GenerateClassHeader(code);
        
        // 生成消息类型映射
        GenerateMessageTypeMapping(code, serviceModels);
        
        // 生成处理器映射
        GenerateHandlerMapping(code, serviceModels);
        
        // 生成快速分发方法
        GenerateDispatchMethod(code, serviceModels);
        
        // 生成批量分发方法
        GenerateBatchDispatchMethod(code, serviceModels);
        
        // 生成统计和监控方法
        GenerateStatisticsMethod(code, serviceModels);
        
        // 生成类结尾
        GenerateClassFooter(code);
        
        return code.ToString();
    }
    
    /// <summary>
    /// 生成文件头
    /// </summary>
    private static void GenerateFileHeader(StringBuilder code)
    {
        code.AppendLine("// <auto-generated />");
        code.AppendLine("// 此文件由PulseRPC Source Generator自动生成");
        code.AppendLine($"// 生成时间: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        code.AppendLine("// 警告: 请勿手动修改此文件，所有更改都会在下次生成时被覆盖");
        code.AppendLine();
        code.AppendLine("#nullable enable");
        code.AppendLine("#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释");
        code.AppendLine();
        code.AppendLine("using System;");
        code.AppendLine("using System.Collections.Generic;");
        code.AppendLine("using System.Collections.Concurrent;");
        code.AppendLine("using System.Threading;");
        code.AppendLine("using System.Threading.Tasks;");
        code.AppendLine("using System.Runtime.CompilerServices;");
        code.AppendLine("using System.Diagnostics;");
        code.AppendLine("using Microsoft.Extensions.Logging;");
        code.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        code.AppendLine();
    }
    
    /// <summary>
    /// 生成类头部
    /// </summary>
    private static void GenerateClassHeader(StringBuilder code)
    {
        code.AppendLine("namespace PulseRPC.Generated;");
        code.AppendLine();
        code.AppendLine("/// <summary>");
        code.AppendLine("/// 编译时生成的高性能消息分发器");
        code.AppendLine("/// 特性:");
        code.AppendLine("/// - 零反射开销");
        code.AppendLine("/// - 预编译方法查找");
        code.AppendLine("/// - 内联优化支持");
        code.AppendLine("/// - AOT编译兼容");
        code.AppendLine("/// </summary>");
        code.AppendLine("public static partial class CompiledMessageDispatcher");
        code.AppendLine("{");
    }
    
    /// <summary>
    /// 生成消息类型映射
    /// </summary>
    private static void GenerateMessageTypeMapping(StringBuilder code, List<ServiceModel> serviceModels)
    {
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 预编译的消息类型映射 - 避免运行时Type.GetType调用");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    private static readonly Dictionary<string, Type> MessageTypeMap = new(StringComparer.Ordinal)");
        code.AppendLine("    {");
        
        var allMessageTypes = new HashSet<string>();
        foreach (var service in serviceModels)
        {
            foreach (var method in service.Methods)
            {
                // 参数类型作为请求类型
                if (method.IsSingleParameter && !allMessageTypes.Contains(method.FirstParameter!.TypeFullName))
                {
                    allMessageTypes.Add(method.FirstParameter!.TypeFullName);
                    code.AppendLine($"        [\"{method.FirstParameter!.TypeFullName}\"] = typeof({method.FirstParameter!.TypeFullName}),");
                }
                
                // 返回类型作为响应类型
                if (!string.IsNullOrEmpty(method.ReturnTypeFullName) && method.ReturnTypeFullName != "void" && 
                    method.ReturnTypeFullName != "System.Threading.Tasks.Task" && 
                    !allMessageTypes.Contains(method.ReturnTypeFullName))
                {
                    allMessageTypes.Add(method.ReturnTypeFullName);
                    code.AppendLine($"        [\"{method.ReturnTypeFullName}\"] = typeof({method.ReturnTypeFullName}),");
                }
            }
        }
        
        code.AppendLine("    };");
        code.AppendLine();
    }
    
    /// <summary>
    /// 生成处理器映射
    /// </summary>
    private static void GenerateHandlerMapping(StringBuilder code, List<ServiceModel> serviceModels)
    {
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 预编译的消息处理器映射 - 直接方法调用，无反射开销");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    private static readonly Dictionary<Type, MessageHandlerInfo> HandlerMap = new()");
        code.AppendLine("    {");
        
        foreach (var service in serviceModels)
        {
            foreach (var method in service.Methods)
            {
                if (method.IsSingleParameter)
                {
                    var handlerName = $"Handle{service.InterfaceName.TrimStart('I')}{method.MethodName}";
                    var isAsync = method.IsAsync;
                    var serviceName = service.InterfaceName;
                    
                    code.AppendLine($"        [typeof({method.FirstParameter!.TypeFullName})] = new MessageHandlerInfo");
                    code.AppendLine("        {");
                    code.AppendLine($"            ServiceType = typeof({serviceName}),");
                    code.AppendLine($"            MethodName = \"{method.MethodName}\",");
                    code.AppendLine($"            IsAsync = {isAsync.ToString().ToLower()},");
                    code.AppendLine($"            Handler = {handlerName},");
                    code.AppendLine($"            Priority = MessagePriority.{GetMessagePriority(method)},");
                    code.AppendLine($"            EstimatedLatencyMs = {GetEstimatedLatency(method)},");
                    code.AppendLine("        },");
                }
            }
        }
        
        code.AppendLine("    };");
        code.AppendLine();
    }
    
    /// <summary>
    /// 生成快速分发方法
    /// </summary>
    private static void GenerateDispatchMethod(StringBuilder code, List<ServiceModel> serviceModels)
    {
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 高性能消息分发 - 编译时优化的快速路径");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        code.AppendLine("    public static async ValueTask<object?> DispatchAsync(");
        code.AppendLine("        object message, ");
        code.AppendLine("        IServiceProvider serviceProvider, ");
        code.AppendLine("        CancellationToken cancellationToken = default)");
        code.AppendLine("    {");
        code.AppendLine("        var messageType = message.GetType();");
        code.AppendLine("        ");
        code.AppendLine("        // 快速路径：预编译的类型检查和分发");
        code.AppendLine("        if (HandlerMap.TryGetValue(messageType, out var handlerInfo))");
        code.AppendLine("        {");
        code.AppendLine("            var startTime = Stopwatch.GetTimestamp();");
        code.AppendLine("            ");
        code.AppendLine("            try");
        code.AppendLine("            {");
        code.AppendLine("                var result = await handlerInfo.Handler(message, serviceProvider, cancellationToken);");
        code.AppendLine("                ");
        code.AppendLine("                // 记录成功指标");
        code.AppendLine("                var elapsedMs = (Stopwatch.GetTimestamp() - startTime) * 1000.0 / Stopwatch.Frequency;");
        code.AppendLine("                Metrics.RecordDispatchSuccess(messageType.Name, elapsedMs);");
        code.AppendLine("                ");
        code.AppendLine("                return result;");
        code.AppendLine("            }");
        code.AppendLine("            catch (Exception ex)");
        code.AppendLine("            {");
        code.AppendLine("                // 记录错误指标");
        code.AppendLine("                var elapsedMs = (Stopwatch.GetTimestamp() - startTime) * 1000.0 / Stopwatch.Frequency;");
        code.AppendLine("                Metrics.RecordDispatchError(messageType.Name, elapsedMs, ex);");
        code.AppendLine("                throw;");
        code.AppendLine("            }");
        code.AppendLine("        }");
        code.AppendLine("        ");
        code.AppendLine("        // 慢速路径：未识别的消息类型");
        code.AppendLine("        Metrics.RecordUnknownMessageType(messageType.Name);");
        code.AppendLine("        throw new InvalidOperationException($\"未找到消息类型 '{messageType.Name}' 的处理器\");");
        code.AppendLine("    }");
        code.AppendLine();
    }
    
    /// <summary>
    /// 生成批量分发方法
    /// </summary>
    private static void GenerateBatchDispatchMethod(StringBuilder code, List<ServiceModel> serviceModels)
    {
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 批量消息分发 - 优化的批处理路径");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    public static async ValueTask<object?[]> DispatchBatchAsync(");
        code.AppendLine("        ReadOnlyMemory<object> messages, ");
        code.AppendLine("        IServiceProvider serviceProvider, ");
        code.AppendLine("        CancellationToken cancellationToken = default)");
        code.AppendLine("    {");
        code.AppendLine("        var results = new object?[messages.Length];");
        code.AppendLine("        var tasks = new ValueTask<object?>[messages.Length];");
        code.AppendLine("        ");
        code.AppendLine("        // 并行分发所有消息");
        code.AppendLine("        var messageSpan = messages.Span;");
        code.AppendLine("        for (int i = 0; i < messageSpan.Length; i++)");
        code.AppendLine("        {");
        code.AppendLine("            tasks[i] = DispatchAsync(messageSpan[i], serviceProvider, cancellationToken);");
        code.AppendLine("        }");
        code.AppendLine("        ");
        code.AppendLine("        // 等待所有任务完成");
        code.AppendLine("        for (int i = 0; i < tasks.Length; i++)");
        code.AppendLine("        {");
        code.AppendLine("            results[i] = await tasks[i];");
        code.AppendLine("        }");
        code.AppendLine("        ");
        code.AppendLine("        return results;");
        code.AppendLine("    }");
        code.AppendLine();
    }
    
    /// <summary>
    /// 生成具体的处理器方法
    /// </summary>
    private static void GenerateHandlerMethods(StringBuilder code, List<ServiceModel> serviceModels)
    {
        foreach (var service in serviceModels)
        {
            foreach (var method in service.Methods)
            {
                if (method.IsSingleParameter)
                {
                    var handlerName = $"Handle{service.InterfaceName.TrimStart('I')}{method.MethodName}";
                    var serviceName = service.InterfaceName;
                    var requestType = method.FirstParameter!.TypeFullName;
                    var responseType = method.ReturnTypeFullName ?? "object";
                    var isAsync = method.IsAsync;
                    
                    code.AppendLine($"    /// <summary>");
                    code.AppendLine($"    /// 生成的处理器：{serviceName}.{method.MethodName}");
                    code.AppendLine($"    /// </summary>");
                    code.AppendLine($"    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                    code.AppendLine($"    private static async ValueTask<object?> {handlerName}(");
                    code.AppendLine($"        object message, ");
                    code.AppendLine($"        IServiceProvider serviceProvider, ");
                    code.AppendLine($"        CancellationToken cancellationToken)");
                    code.AppendLine($"    {{");
                    code.AppendLine($"        var typedMessage = ({requestType})message;");
                    code.AppendLine($"        var service = serviceProvider.GetRequiredService<{serviceName}>();");
                    code.AppendLine($"        ");
                    
                    if (isAsync)
                    {
                        if (responseType == "void" || responseType == "System.Threading.Tasks.Task")
                        {
                            code.AppendLine($"        await service.{method.MethodName}(typedMessage, cancellationToken).ConfigureAwait(false);");
                            code.AppendLine($"        return null;");
                        }
                        else
                        {
                            code.AppendLine($"        var result = await service.{method.MethodName}(typedMessage, cancellationToken).ConfigureAwait(false);");
                            code.AppendLine($"        return result;");
                        }
                    }
                    else
                    {
                        if (responseType == "void")
                        {
                            code.AppendLine($"        service.{method.MethodName}(typedMessage);");
                            code.AppendLine($"        return null;");
                        }
                        else
                        {
                            code.AppendLine($"        var result = service.{method.MethodName}(typedMessage);");
                            code.AppendLine($"        return result;");
                        }
                    }
                    
                    code.AppendLine($"    }}");
                    code.AppendLine();
                }
            }
        }
    }
    
    /// <summary>
    /// 生成统计和监控方法
    /// </summary>
    private static void GenerateStatisticsMethod(StringBuilder code, List<ServiceModel> serviceModels)
    {
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 获取分发器统计信息");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    public static DispatcherStatistics GetStatistics()");
        code.AppendLine("    {");
        code.AppendLine("        return new DispatcherStatistics");
        code.AppendLine("        {");
        code.AppendLine($"            TotalHandlers = {GetTotalHandlerCount(serviceModels)},");
        code.AppendLine($"            TotalServices = {serviceModels.Count},");
        code.AppendLine("            Metrics = Metrics.GetSnapshot(),");
        code.AppendLine($"            GeneratedAt = DateTime.UtcNow,");
        code.AppendLine("            HandlerMap = HandlerMap.ToDictionary(");
        code.AppendLine("                kvp => kvp.Key.Name, ");
        code.AppendLine("                kvp => kvp.Value)");
        code.AppendLine("        };");
        code.AppendLine("    }");
        code.AppendLine();
        
        // 生成性能指标类
        GenerateMetricsClass(code);
        
        // 生成统计数据类
        GenerateStatisticsDataClasses(code);
        
        // 生成具体的处理器方法
        GenerateHandlerMethods(code, serviceModels);
    }
    
    /// <summary>
    /// 生成性能指标类
    /// </summary>
    private static void GenerateMetricsClass(StringBuilder code)
    {
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 分发器性能指标");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    public static class Metrics");
        code.AppendLine("    {");
        code.AppendLine("        private static readonly ConcurrentDictionary<string, long> SuccessCount = new();");
        code.AppendLine("        private static readonly ConcurrentDictionary<string, long> ErrorCount = new();");
        code.AppendLine("        private static readonly ConcurrentDictionary<string, double> TotalLatency = new();");
        code.AppendLine("        private static readonly ConcurrentDictionary<string, long> UnknownTypes = new();");
        code.AppendLine("        ");
        code.AppendLine("        public static void RecordDispatchSuccess(string messageType, double latencyMs)");
        code.AppendLine("        {");
        code.AppendLine("            SuccessCount.AddOrUpdate(messageType, 1, (_, count) => count + 1);");
        code.AppendLine("            TotalLatency.AddOrUpdate(messageType, latencyMs, (_, total) => total + latencyMs);");
        code.AppendLine("        }");
        code.AppendLine("        ");
        code.AppendLine("        public static void RecordDispatchError(string messageType, double latencyMs, Exception ex)");
        code.AppendLine("        {");
        code.AppendLine("            ErrorCount.AddOrUpdate(messageType, 1, (_, count) => count + 1);");
        code.AppendLine("            TotalLatency.AddOrUpdate(messageType, latencyMs, (_, total) => total + latencyMs);");
        code.AppendLine("        }");
        code.AppendLine("        ");
        code.AppendLine("        public static void RecordUnknownMessageType(string messageType)");
        code.AppendLine("        {");
        code.AppendLine("            UnknownTypes.AddOrUpdate(messageType, 1, (_, count) => count + 1);");
        code.AppendLine("        }");
        code.AppendLine("        ");
        code.AppendLine("        public static MetricsSnapshot GetSnapshot()");
        code.AppendLine("        {");
        code.AppendLine("            return new MetricsSnapshot");
        code.AppendLine("            {");
        code.AppendLine("                SuccessCount = new Dictionary<string, long>(SuccessCount),");
        code.AppendLine("                ErrorCount = new Dictionary<string, long>(ErrorCount),");
        code.AppendLine("                TotalLatency = new Dictionary<string, double>(TotalLatency),");
        code.AppendLine("                UnknownTypes = new Dictionary<string, long>(UnknownTypes)");
        code.AppendLine("            };");
        code.AppendLine("        }");
        code.AppendLine("    }");
        code.AppendLine();
    }
    
    /// <summary>
    /// 生成统计数据类
    /// </summary>
    private static void GenerateStatisticsDataClasses(StringBuilder code)
    {
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 消息处理器信息");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    public class MessageHandlerInfo");
        code.AppendLine("    {");
        code.AppendLine("        public required Type ServiceType { get; set; }");
        code.AppendLine("        public required string MethodName { get; set; }");
        code.AppendLine("        public bool IsAsync { get; set; }");
        code.AppendLine("        public required Func<object, IServiceProvider, CancellationToken, ValueTask<object?>> Handler { get; set; }");
        code.AppendLine("        public MessagePriority Priority { get; set; }");
        code.AppendLine("        public double EstimatedLatencyMs { get; set; }");
        code.AppendLine("    }");
        code.AppendLine();
        
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 分发器统计信息");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    public class DispatcherStatistics");
        code.AppendLine("    {");
        code.AppendLine("        public int TotalHandlers { get; set; }");
        code.AppendLine("        public int TotalServices { get; set; }");
        code.AppendLine("        public required MetricsSnapshot Metrics { get; set; }");
        code.AppendLine("        public DateTime GeneratedAt { get; set; }");
        code.AppendLine("        public required Dictionary<string, MessageHandlerInfo> HandlerMap { get; set; }");
        code.AppendLine("    }");
        code.AppendLine();
        
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 性能指标快照");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    public class MetricsSnapshot");
        code.AppendLine("    {");
        code.AppendLine("        public required Dictionary<string, long> SuccessCount { get; set; }");
        code.AppendLine("        public required Dictionary<string, long> ErrorCount { get; set; }");
        code.AppendLine("        public required Dictionary<string, double> TotalLatency { get; set; }");
        code.AppendLine("        public required Dictionary<string, long> UnknownTypes { get; set; }");
        code.AppendLine("    }");
        code.AppendLine();
        
        code.AppendLine("    /// <summary>");
        code.AppendLine("    /// 消息优先级");
        code.AppendLine("    /// </summary>");
        code.AppendLine("    public enum MessagePriority");
        code.AppendLine("    {");
        code.AppendLine("        Low = 0,");
        code.AppendLine("        Normal = 1,");
        code.AppendLine("        High = 2,");
        code.AppendLine("        Critical = 3");
        code.AppendLine("    }");
        code.AppendLine();
    }
    
    /// <summary>
    /// 生成类结尾
    /// </summary>
    private static void GenerateClassFooter(StringBuilder code)
    {
        code.AppendLine("}");
        code.AppendLine();
        code.AppendLine("#pragma warning restore CS1591");
    }
    
    /// <summary>
    /// 获取消息优先级
    /// </summary>
    private static string GetMessagePriority(MethodModel method)
    {
        // 根据方法特性推断优先级
        if (method.MethodName.Contains("Critical") || method.MethodName.Contains("Emergency"))
            return "Critical";
        if (method.MethodName.Contains("High") || method.MethodName.Contains("Priority"))
            return "High";
        if (method.MethodName.Contains("Low") || method.MethodName.Contains("Background"))
            return "Low";
        return "Normal";
    }
    
    /// <summary>
    /// 获取预估延迟
    /// </summary>
    private static double GetEstimatedLatency(MethodModel method)
    {
        // 根据方法复杂度预估延迟
        if (method.IsAsync)
            return 2.0; // 异步方法通常更快
        if (method.MethodName.Contains("Query") || method.MethodName.Contains("Get"))
            return 1.0; // 查询操作较快
        if (method.MethodName.Contains("Create") || method.MethodName.Contains("Update"))
            return 5.0; // 写入操作较慢
        return 3.0; // 默认延迟
    }
    
    /// <summary>
    /// 获取总处理器数量
    /// </summary>
    private static int GetTotalHandlerCount(List<ServiceModel> serviceModels)
    {
        return serviceModels.Sum(s => s.Methods.Count(m => m.IsSingleParameter));
    }
}