using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using PulseRPC.SourceGenerator.Models;

namespace PulseRPC.SourceGenerator.Generators;

/// <summary>
/// 服务代理生成器 - 生成高性能的服务调用代理
/// </summary>
public static class ServiceProxyGenerator
{
    /// <summary>
    /// 为服务模型生成代理类代码
    /// </summary>
    public static string GenerateServiceProxy(ServiceModel serviceModel)
    {
        var sb = new StringBuilder();

        // 文件头部
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This code was generated by PulseRPC.SourceGenerator");
        sb.AppendLine("// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();

        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS8019 // Unnecessary using directive");
        sb.AppendLine();

        // Using statements
        GenerateUsingStatements(sb);

        // Namespace
        sb.AppendLine($"namespace {serviceModel.Namespace}.Generated;");
        sb.AppendLine();

        // 生成代理类
        GenerateProxyClass(sb, serviceModel);

        return sb.ToString();
    }

    /// <summary>
    /// 生成using语句
    /// </summary>
    private static void GenerateUsingStatements(StringBuilder sb)
    {
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using MemoryPack;");
        sb.AppendLine("using PulseRPC.Abstractions;");
        sb.AppendLine();
    }

    /// <summary>
    /// 生成代理类
    /// </summary>
    private static void GenerateProxyClass(StringBuilder sb, ServiceModel serviceModel)
    {
        var proxyClassName = $"{serviceModel.InterfaceName.TrimStart('I')}Proxy";

        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Generated high-performance proxy for {serviceModel.InterfaceName}");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public sealed partial class {proxyClassName} : IGeneratedServiceProxy");
        sb.AppendLine("{");

        // 服务实现字段
        GenerateFields(sb, serviceModel);

        // 构造函数
        GenerateConstructor(sb, serviceModel, proxyClassName);

        // 主要调用方法
        GenerateInvokeAsync(sb, serviceModel);

        // 为每个方法生成专用调用方法
        GenerateMethodInvokers(sb, serviceModel);

        // 辅助方法
        GenerateHelperMethods(sb, serviceModel);

        sb.AppendLine("}");
    }

    /// <summary>
    /// 生成字段
    /// </summary>
    private static void GenerateFields(StringBuilder sb, ServiceModel serviceModel)
    {
        sb.AppendLine($"    private readonly {serviceModel.InterfaceFullName} _implementation;");
        sb.AppendLine($"    private static readonly string ServiceName = \"{serviceModel.InterfaceFullName}\";");
        sb.AppendLine();
    }

    /// <summary>
    /// 生成构造函数
    /// </summary>
    private static void GenerateConstructor(StringBuilder sb, ServiceModel serviceModel, string proxyClassName)
    {
        sb.AppendLine($"    public {proxyClassName}({serviceModel.InterfaceFullName} implementation)");
        sb.AppendLine("    {");
        sb.AppendLine("        _implementation = implementation ?? throw new ArgumentNullException(nameof(implementation));");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// 生成主要的InvokeAsync方法
    /// </summary>
    private static void GenerateInvokeAsync(StringBuilder sb, ServiceModel serviceModel)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// High-performance method dispatcher with compile-time optimization");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    public ValueTask<object?> InvokeAsync(string methodName, ReadOnlyMemory<byte> data, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");

        // 使用switch表达式进行快速方法分发
        sb.AppendLine("        return methodName switch");
        sb.AppendLine("        {");

        foreach (var method in serviceModel.Methods)
        {
            sb.AppendLine($"            \"{method.MethodName}\" => Invoke{method.MethodName}Async(data, cancellationToken),");
        }

        sb.AppendLine($"            _ => throw new MethodNotFoundException($\"Method {{methodName}} not found in service {serviceModel.InterfaceName}\")");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// 为每个方法生成专用调用器
    /// </summary>
    private static void GenerateMethodInvokers(StringBuilder sb, ServiceModel serviceModel)
    {
        foreach (var method in serviceModel.Methods)
        {
            GenerateMethodInvoker(sb, method, serviceModel.InterfaceName);
        }
    }

    /// <summary>
    /// 生成单个方法的调用器
    /// </summary>
    private static void GenerateMethodInvoker(StringBuilder sb, MethodModel method, string serviceName)
    {
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Optimized invoker for {method.MethodName}");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"    private async ValueTask<object?> Invoke{method.MethodName}Async(ReadOnlyMemory<byte> data, CancellationToken cancellationToken)");
        sb.AppendLine("    {");

        // 反序列化参数
        GenerateParameterDeserialization(sb, method);

        // 调用服务方法
        GenerateServiceMethodCall(sb, method);

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// 生成参数反序列化代码
    /// </summary>
    private static void GenerateParameterDeserialization(StringBuilder sb, MethodModel method)
    {
        if (!method.HasParameters)
        {
            sb.AppendLine("        // Method has no parameters");
            return;
        }

        if (method.IsSingleParameter)
        {
            var param = method.FirstParameter!;
            sb.AppendLine($"        // Deserialize single parameter: {param.TypeName}");
            
            if (param.IsMemoryPackable)
            {
                sb.AppendLine($"        var {param.Name} = MemoryPackSerializer.Deserialize<{param.TypeFullName}>(data.Span);");
            }
            else
            {
                sb.AppendLine($"        // Warning: Parameter type {param.TypeName} is not MemoryPackable");
                sb.AppendLine($"        var {param.Name} = MemoryPackSerializer.Deserialize<{param.TypeFullName}>(data.Span);");
            }
        }
        else
        {
            // 多参数处理（需要参数包装类）
            sb.AppendLine("        // Multi-parameter deserialization");
            sb.AppendLine("        var parameters = DeserializeMultipleParameters(data);");
            
            for (int i = 0; i < method.Parameters.Count; i++)
            {
                var param = method.Parameters[i];
                sb.AppendLine($"        var {param.Name} = ({param.TypeFullName})parameters[{i}];");
            }
        }

        sb.AppendLine();
    }

    /// <summary>
    /// 生成服务方法调用代码
    /// </summary>
    private static void GenerateServiceMethodCall(StringBuilder sb, MethodModel method)
    {
        var paramList = method.HasParameters ? 
            string.Join(", ", method.Parameters.Select(p => p.Name)) : 
            "";

        if (method.IsAsync)
        {
            if (method.IsGenericTask)
            {
                // ValueTask<T> 或 Task<T>
                sb.AppendLine($"        var result = await _implementation.{method.MethodName}({paramList});");
                sb.AppendLine("        return result;");
            }
            else
            {
                // ValueTask 或 Task (void)
                sb.AppendLine($"        await _implementation.{method.MethodName}({paramList});");
                sb.AppendLine("        return null;");
            }
        }
        else
        {
            // 同步方法
            if (method.ReturnTypeName == "void")
            {
                sb.AppendLine($"        _implementation.{method.MethodName}({paramList});");
                sb.AppendLine("        return null;");
            }
            else
            {
                sb.AppendLine($"        var result = _implementation.{method.MethodName}({paramList});");
                sb.AppendLine("        return result;");
            }
        }
    }

    /// <summary>
    /// 生成辅助方法
    /// </summary>
    private static void GenerateHelperMethods(StringBuilder sb, ServiceModel serviceModel)
    {
        // 多参数反序列化辅助方法
        GenerateMultiParameterDeserializer(sb, serviceModel);

        // 服务信息属性
        GenerateServiceInfo(sb, serviceModel);
    }

    /// <summary>
    /// 生成多参数反序列化方法
    /// </summary>
    private static void GenerateMultiParameterDeserializer(StringBuilder sb, ServiceModel serviceModel)
    {
        var hasMultiParamMethods = serviceModel.Methods.Any(m => m.Parameters.Count > 1);
        if (!hasMultiParamMethods) return;

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Deserialize multiple parameters (fallback for complex scenarios)");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    private static object[] DeserializeMultipleParameters(ReadOnlyMemory<byte> data)");
        sb.AppendLine("    {");
        sb.AppendLine("        // TODO: Implement multi-parameter deserialization");
        sb.AppendLine("        // This requires a parameter wrapper class or tuple serialization");
        sb.AppendLine("        throw new NotImplementedException(\"Multi-parameter deserialization not yet implemented\");");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// 生成服务信息
    /// </summary>
    private static void GenerateServiceInfo(StringBuilder sb, ServiceModel serviceModel)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Service metadata for debugging and introspection");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class ServiceInfo");
        sb.AppendLine("    {");
        sb.AppendLine($"        public const string Name = \"{serviceModel.InterfaceFullName}\";");
        sb.AppendLine($"        public const string ShortName = \"{serviceModel.InterfaceName}\";");
        sb.AppendLine($"        public const string Channel = \"{serviceModel.ChannelName}\";");
        sb.AppendLine($"        public const int MethodCount = {serviceModel.Methods.Count};");
        
        sb.AppendLine("        public static readonly string[] Methods = new[]");
        sb.AppendLine("        {");
        foreach (var method in serviceModel.Methods)
        {
            sb.AppendLine($"            \"{method.MethodName}\",");
        }
        sb.AppendLine("        };");
        
        sb.AppendLine("    }");
    }

    /// <summary>
    /// 生成SourceText用于编译器集成
    /// </summary>
    public static SourceText GenerateSourceText(ServiceModel serviceModel)
    {
        var code = GenerateServiceProxy(serviceModel);
        return SourceText.From(code, Encoding.UTF8);
    }
}