name: Release

# ADD PERMISSIONS HERE (WORKFLOW-LEVEL):
permissions:
  actions: read
  contents: read

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag: git tag you want create. (sample 1.0.0)"
        required: true
      dry-run:
        description: "dry-run: true will never create relase/nuget."
        required: true
        default: false
        type: boolean

jobs:
  update-packagejson:
    permissions:
      actions: read   # 为了调用可复用工作流
      contents: write  # 为了允许推送更改到仓库
    uses: ChronosGames/Actions/.github/workflows/update-packagejson.yaml@main
    with:
      file-path: |
        ./src/PulseRPC.Client.Unity/Assets/Scripts/PulseRPC.Client.Unity/package.json
        ./src/PulseRPC.Client/package.json
        ./Directory.Build.props
      tag: ${{ inputs.tag }}
      dry-run: ${{ inputs.dry-run }}
      push-tag: false
      ref: ${{ github.ref }}

  build-dotnet:
    needs: [update-packagejson]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: echo ${{ needs.update-packagejson.outputs.sha }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.update-packagejson.outputs.sha }}
          lfs: true
      - uses: ChronosGames/Actions/.github/actions/setup-dotnet@main
      # pack nuget
      - run: dotnet build -c Release ./PulseRPC.sln
      - run: dotnet pack -c Release ./PulseRPC.Packaging.slnf --no-build -o ./publish
      - uses: ChronosGames/Actions/.github/actions/upload-artifact@main
        with:
          name: nuget
          path: ./publish/
          retention-days: 1

  build-unity:
    needs: [update-packagejson]
    strategy:
      matrix:
        unity: ["2022.3.39f1"]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - run: echo ${{ needs.update-packagejson.outputs.sha }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.update-packagejson.outputs.sha }}
          lfs: true

      # Setup .NET and build PulseRPC.Client for Unity dependency
      - uses: ChronosGames/Actions/.github/actions/setup-dotnet@main
      - run: dotnet build -c Debug ./src/PulseRPC.Client/PulseRPC.Client.csproj -f netstandard2.1

      # Execute scripts: Export Package
      # /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -executeMethod PackageExporter.Export
      - name: Build Unity (.unitypackage)
        uses: ChronosGames/Actions/.github/actions/unity-builder@main
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_PACKAGE_VERSION: ${{ inputs.tag }}
        with:
          projectPath: src/PulseRPC.Client.Unity
          unityVersion: ${{ matrix.unity }}
          targetPlatform: StandaloneLinux64
          buildMethod: PackageExporter.Export

      # check meta files
      - uses: ChronosGames/Actions/.github/actions/check-metas@main
        with:
          directory: src/PulseRPC.Client.Unity

      # Store artifacts.
      - uses: ChronosGames/Actions/.github/actions/upload-artifact@main
        with:
          name: PulseRPC.Client.Unity.${{ inputs.tag }}.unitypackage
          path: ./src/PulseRPC.Client.Unity/PulseRPC.Client.Unity.${{ inputs.tag }}.unitypackage
          retention-days: 1

  # release
  create-release:
    permissions:
      actions: read   # 为了调用可复用工作流
      contents: write  # 为了允许推送更改到仓库
    needs: [update-packagejson, build-dotnet, build-unity]
    uses: ChronosGames/Actions/.github/workflows/create-release.yaml@main
    with:
      commit-id: ${{ needs.update-packagejson.outputs.sha }}
      dry-run: ${{ inputs.dry-run }}
      tag: ${{ inputs.tag }}
      nuget-push: true
      release-format: '{0}'
      release-upload: true
      release-asset-path: ./PulseRPC.Client.Unity.${{ inputs.tag }}.unitypackage/PulseRPC.Client.Unity.${{ inputs.tag }}.unitypackage
    secrets: inherit

  cleanup:
    if: ${{ needs.update-packagejson.outputs.is-branch-created == 'true' }}
    needs: [build-dotnet, build-unity, update-packagejson]
    uses: ChronosGames/Actions/.github/workflows/clean-packagejson-branch.yaml@main
    with:
      branch: ${{ needs.update-packagejson.outputs.branch-name }}
